### ISSUE TITLE
3 build errors! 

### ISSUE THREAD

**Issue by suneet101** [artsy/eigen#10]
3 build errors on iPhone 6 simulator. Please Fix it and then share it, as I don't fix someone's else code! thanks.

**Comment by ashfurrow** [comment]
Can you provide text or a screenshot showing the three errors?

**Comment by suneet101** [comment]
![build errors](https://cloud.githubusercontent.com/assets/10668346/5872992/9b6f2502-a317-11e4-9731-d7184bde82a8.png)
here you go! thanks.

**Comment by suneet101** [comment]
Sure hold onSent from Yahoo Mail for iPhoneAt 23-Jan-2015 3:41:31 pm, Ash Furrow wrote:Can you provide text or a screenshot showing the three errors?

**Comment by ashfurrow** [comment]
Hmm. Looks like it needs `pod install` to be run on CocoaPods 0.36 Beta 1. Like in #11, that will fail, but we're [working on it](https://github.com/artsy/eigen/pull/8).

**Comment by suneet101** [comment]
Ok thank you. All of us appreciate what you are doing here! God bless.
