### ISSUE TITLE
Component: Page Title

### ISSUE THREAD

**Issue by orta** [artsy/eigen#1011]
### Inputs:
* Has a short text title attribute.
* Has a long text title attribute.
* Offers a callback for a button press

### Sizing
In small screen mode:
<img width="357" alt="screen shot 2016-01-06 at 17 22 35" src="https://cloud.githubusercontent.com/assets/49038/12149172/28cfed0c-b49a-11e5-8fd7-fc02d83f160d.png">
Uses the small text title attribute, with a left aligned single line uilabel touching a UIButton that's right aligned.

In large screen mode:
<img width="764" alt="screen shot 2016-01-06 at 17 23 24" src="https://cloud.githubusercontent.com/assets/49038/12149188/3a91580a-b49a-11e5-8feb-16ed0ca2bc3d.png">
Uses the long text title attribute, with a centered single line uilabel touching a UIButton that's right aligned. Note that the label is entered regardless of the button's position, so it will need to have a max width of the full width - the button width + margin x 2.

Full context:
<img src="https://cloud.githubusercontent.com/assets/6482926/11717962/9257b4aa-9f21-11e5-8c27-dcac9cd7a003.png">

### Notes

I got nothing.

**Comment by ashfurrow** [comment]
Looks solid :100:

**Comment by alloy** [comment]
I assume you meant that in large screen mode the large text title attribute will be used?

* Does the large title attribute default to the text of the small one?
* Is it the idea that the text in the large screen mode may differ from the small one?

**Comment by orta** [comment]
Yeah, sorry, C&P typo, should use longer text in the longer text thing.
