### ISSUE TITLE
[Hero] Text gets clipped incorrectly

### ISSUE THREAD

**Issue by alloy** [artsy/eigen#1026]
I’m not sure what the solution here is, ideally there would be no clipping at all, I imagine.

* Shrink font size?
* Show preview in CMS and/or otherwise ‘fix’ this issue in CMS?

![img_7470](https://cloud.githubusercontent.com/assets/2320/12295158/84349692-b9ff-11e5-8ee1-d5cb50af5df0.PNG)

**Comment by orta** [comment]
I wonder if we should just say "max of two lines" on either the title or the subheading.

**Comment by alloy** [comment]
Hmm, wait, I think there might simply be an issue with the placement of the hero units, as this image is actually taller:

![](https://d32dm0rphc51dk.cloudfront.net/tLNoRIN7bmh-RO-vdAzRKw/untouched-jpg.jpg)

**Comment by orta** [comment]
nah, we need a consistent height for all hero units, the edges are used for the parallax.

artsy works by having naturally smaller fonts

![slack for ios upload png](https://cloud.githubusercontent.com/assets/49038/12295232/a77adf6a-b9f7-11e5-93ef-3005f66357d4.jpeg)

**Comment by alloy** [comment]
@orta and I agree that we should simply decrease the font size to match artsy’s behaviour.

**Comment by orta** [comment]
The font size is the same, it looks like martsy consistently has a taller hero unit 

![screen shot 2016-02-11 at 12 40 20](https://cloud.githubusercontent.com/assets/49038/12976560/e4d6e1e8-d0bc-11e5-92ef-9720a942cf68.png)

**Comment by katarinabatina** [comment]
Given we'll be moving away from this current banner system I want to make sure we don't invest too much time into fixing this if it's time consuming.

**Comment by orta** [comment]
already fixed :+1:

**Comment by katarinabatina** [comment]
:+1: rockin
