### ISSUE TITLE
Issue with Copying Fonts from AWS S3 to Local Environment

### ISSUE THREAD

**Issue by liangkuku** [artsy/eigen#10266]
Description:
I encountered an error while attempting to execute yarn setup:oss to copy fonts from AWS S3 to my local environment. I have configured my AWS credentials using aws configure, as demonstrated in the [link](https://docs.aws.amazon.com/zh_cn/cli/latest/userguide/welcome-examples.html). However, when attempting to copy the fonts, I encountered the following error, as depicted in the attached screenshot.

<img width="693" alt="image" src="https://github.com/artsy/eigen/assets/62460957/f2f9be8b-0344-4482-b0cb-9c254be2c789">

Would appreciate any insights or assistance on resolving this issue. Thank you!

**Comment by brainbicycle** [comment]
hmm the bucket should be open another user had this issue and logged out of aws cli and back in and it started working: 
https://github.com/artsy/eigen/issues/7747#issuecomment-1520065061 let me know if that doesn't solve it for you, another thing might be to set your aws region to us-east

**Comment by brainbicycle** [comment]
let me know if you continue to have issues, otherwise will close!
