### ISSUE TITLE
Error installing Mapbox-iOS-SDK during yarn install:all

### ISSUE THREAD

**Issue by liangkuku** [artsy/eigen#10263]
Description
I encountered an error while running yarn install:all. I have configured the MAPBOX_DOWNLOAD_TOKEN correctly in .env.shared. To verify, I wrote a demo using the same token, and it successfully loaded the map, which indicates the token is correct. However, the error "Error installing Mapbox-iOS-SDK" still occurs.

Environment
OS: macOS M1
Node.js version: v20.8.0
Yarn version: v1.22.19
CocoaPods version:  v1.12.0

Steps to Reproduce
As [getting_started.md](https://github.com/artsy/eigen/blob/main/docs/getting_started.md)
Configure the MAPBOX_DOWNLOAD_TOKEN in .env.shared.
Run yarn install:all.

Expected Behavior
The command should complete successfully, installing all dependencies including the Mapbox iOS SDK.

Actual Behavior
The installation fails with the error "Error installing Mapbox-iOS-SDK".

Error Info
<img width="843" alt="image" src="https://github.com/artsy/eigen/assets/62460957/b832e390-5555-48cc-a922-8dafa29f2476">

Additional Information
Demo Verification:
I verified the token by writing a demo, and it successfully loaded the map.
<img width="710" alt="image" src="https://github.com/artsy/eigen/assets/62460957/1e44e445-da96-45c0-9f27-5665a556136a">

Running yarn doctor:
<img width="844" alt="image" src="https://github.com/artsy/eigen/assets/62460957/7d9197ef-0b54-4d41-8042-c787eb8fa519">

**Comment by brainbicycle** [comment]
👋 hey the mapbox auth to download the sdk is a little weird, it uses a .netrc file with the mapbox download token contents,  but this should be created for you automatically when running `yarn install:all` so something must be going wrong for you. 

A few things to check to troubleshoot:
- the env var is set in your .env.shared correctly eg.: MAPBOX_DOWNLOAD_TOKEN=<YOUR_TOKEN>
- the token has the Download:Reads scope as described here: https://docs.mapbox.com/ios/maps/guides/install/

If that all looks okay would check the .netrc file is being created properly when you run `yarn install:all` 
here are a couple lightly modified versions of the functions that check and create this file: 
```
def check_for_existing_netrc_file
  mapbox_token = ENV['MAPBOX_DOWNLOAD_TOKEN']
  if !mapbox_token || mapbox_token.length <= 1
    raise "You need a MAPBOX_DOWNLOAD_TOKEN in your .env.shared file.\nIf you work at artsy, check 1password.\nOtherwise create your own in the mapbox dashboard. https://docs.mapbox.com/ios/maps/guides/install"
  end

  $netrc_path = File.expand_path('~/.netrc')
  user_already_had_a_netrc_file = File.exists?($netrc_path)
  if user_already_had_a_netrc_file
    system("touch .i-had-a-netrc-file")
    puts "Existing .netrc file found at #{$netrc_path}"
  else
    system("rm -rf .i-had-a-netrc-file")
    puts "No existing .netrc file found. Will create a new one."
  end
end

def add_mapbox_creds
  puts "Adding mapbox credentials to #{$netrc_path}"
  File.open($netrc_path, 'a+', 0600) { |f|
    f.write("""machine api.mapbox.com
login mapbox
password #{ENV['MAPBOX_DOWNLOAD_TOKEN']}
""")
  }
  puts "Credentials added. Verifying file existence and content..."
  if File.exists?($netrc_path)
    puts ".netrc file exists. Here are the contents:"
    system("cat #{$netrc_path}")
  else
    puts "Error: .netrc file does not exist after attempting to write."
  end
end
```
Replace the current methods in our `Podfile` with these and run `bundle exec pod install` in the ios directory, you should see output along the lines:
```
 $ bundle exec pod install 
No existing .netrc file found. Will create a new one.
Adding mapbox credentials to /Users/<you-user>/.netrc
Credentials added. Verifying file existence and content...
.netrc file exists. Here are the contents:
machine api.mapbox.com
login mapbox
password <your-token>
```

if you see something different let me know and I can try to further troubleshoot.

**Comment by liangkuku** [comment]
I followed your instructions, and here are the results.
<img width="887" alt="image" src="https://github.com/artsy/eigen/assets/62460957/6a20d7b4-c054-486a-bc6e-825ed9abb384">
<img width="879" alt="image" src="https://github.com/artsy/eigen/assets/62460957/e95e221e-6c94-4afa-831e-d31b4e651adb">

**Comment by liangkuku** [comment]
I deleted /Users/<you-user>/.netrc file and execute "bundle exec pod install" again.
<img width="869" alt="image" src="https://github.com/artsy/eigen/assets/62460957/cf709cc1-1d85-4b50-a853-2d05348481e8">
<img width="878" alt="image" src="https://github.com/artsy/eigen/assets/62460957/b9ba5862-ab3e-4a2b-8ab8-7d4e4e4ddbd9">

**Comment by brainbicycle** [comment]
hello there, just a warning your token is viewable in your screenshot, this is your public access token. in order to download the sdk you will need your secret access token with the `Downloads:Read` scope as described here: https://docs.mapbox.com/ios/maps/guides/install/ let me know if it doesn't work but it should

**Comment by brainbicycle** [comment]
let me know if you are continuing to have issues, otherwise will close!
