### ISSUE TITLE
Page loading progress indicator does not spin.

### ISSUE THREAD

**Issue by alloy** [artsy/eigen#1027]
(This is tested on my 5S device.)
1. Load Home VC
2. Scroll to next page and observer spinner spinning
3. Load an artwork and navigate back
4. Scroll to next page and observer spinner no longer spinning

![spinner does not spin anymore after viewing artwork](https://cloud.githubusercontent.com/assets/2320/12295626/7b1e802e-ba02-11e5-8a9c-06b4aa922d1f.gif)

**Comment by orta** [comment]
intersting, mine isn't doing that on device

**Comment by alloy** [comment]
Indeed, it was a bit more elaborate. Figured out the steps to reproduce and updated the ticket.

**Comment by orta** [comment]
Re-pro'd too :+1:

**Comment by orta** [comment]
Could be a good one for @sarahscott

**Comment by katarinabatina** [comment]
no longer relevant with new react view
