### ISSUE TITLE
[Shows] Doesn’t show a banner image

### ISSUE THREAD

**Issue by alloy** [artsy/eigen#1028]
Appears to be a martsy issue: https://github.com/artsy/microgravity/issues/1207

<img width="1335" alt="screen shot 2016-01-13 at 14 36 09" src="https://cloud.githubusercontent.com/assets/2320/12295699/0df982b8-ba03-11e5-8751-03ea5bbc18e1.png">

**Comment by katarinabatina** [comment]
Closing
