### ISSUE TITLE
[Fairs] Overview page gets extra status bar margin

### ISSUE THREAD

**Issue by alloy** [artsy/eigen#1029]
![fairs overview gets extra status bar margin](https://cloud.githubusercontent.com/assets/2320/12296281/0ce6f5d2-ba07-11e5-8638-8f28cbd399ac.gif)

**Comment by orta** [comment]
can you confirm the black bar comes from the UIWindow? can you scroll up over the gap but then behind the usual bar?

**Comment by alloy** [comment]
Aye

**Comment by katarinabatina** [comment]
new explore view and subview will make this issue obsolete I think it's fine to close
