### ISSUE TITLE
Fix crash in - [ARArtworkView setUpCallbacks]

### ISSUE THREAD

**Issue by artsyit** [artsy/eigen#103]
### Stacktrace ###

<pre>ARArtworkView;setUpCallbacks;;
Artwork;onFairUpdate:failure:;;
KSPromise;resolveWithValue:;;
KSDeferred;resolveWithValue:;;
Artwork;updateFair;;
ArtsyAPI;getFairsForArtwork:success:failure:;;
Sale;.cxx_destruct;;</pre>

### Link to HockeyApp ###

* [https://rink.hockeyapp.net/manage/apps/37029/crash_reasons/27576047](https://rink.hockeyapp.net/manage/apps/37029/crash_reasons/27576047)

**Comment by orta** [comment]
I took a stab at this in the last release, https://github.com/artsy/eigen/pull/79 but didn't succeed obviously.

**Comment by alloy** [comment]
For an explanation of the attempt at a fix, please see https://github.com/artsy/eigen/pull/203.
