### ISSUE TITLE
bug reporting flow

### ISSUE THREAD

**Issue by katarinabatina** [artsy/eigen#1033]
![image](https://cloud.githubusercontent.com/assets/6482926/12306624/b0ca7e52-ba08-11e5-9fee-ca0e2b4defd4.png)

Would be cool if they just dumped in slack, we can quickly evaluate if we've logged it already or not

**Comment by alloy** [comment]
I love this idea!

I wonder if posting to github isn't better, though. Slack might be a bit to ephemeral for this and closing tickets isn't a very expensive thing to do.

**Comment by katarinabatina** [comment]
Sure, straight to hit is fine by me!

**Comment by alloy** [comment]
The only thing I worry about is that it means we’ll need to embed keys into the beta app and that’s the same build nowadays that gets shipped off to the App Store.

**Comment by alloy** [comment]
It appears we can generate access tokens that have no permissions, I wonder if that might mean that creating comments is possible. If that’s the case, then we can just do that, as the key is pretty much invaluable compared to any user account that can already create comments on our repo.

**Comment by orta** [comment]
We can't easily upload images that way though, which is tricky
