### ISSUE TITLE
New Auction Countdown Timer

### ISSUE THREAD

**Issue by katarinabatina** [artsy/eigen#1034]
![image](https://cloud.githubusercontent.com/assets/6482926/12309845/ddeae70c-ba1a-11e5-99f0-a9bce36add7d.png)

asset exported at 2x so you can see everything 0.0

**Comment by ashfurrow** [comment]
Lookin' sharp :ok_hand:

**Comment by ashfurrow** [comment]
*Estimate*: 0.5 days

**Comment by ashfurrow** [comment]
Oh, forgot to say: this took a bit over 0.5 days, like 0.75. So I was close :sweat_smile:
