### ISSUE TITLE
Crash upon launch? 

### ISSUE THREAD

**Issue by mennenia** [artsy/eigen#1048]
Heya!

So I was trying to use Artsy on my iPad (latest version, the update from a few days ago "Fresh"), and it seems to crash about one second in. It does load up, and displays the home screen, but then terminates. I can't even send the crash log (you see the dialogue flash before it closes). 

Steps I took:

Originally:
- Opened Folio
- Noticed it had a button that could open Eigen
- Clicked that
- Switched to Eigen
- Eigen started launching
- Crashed

Further:
- Tried opening it from home screen etc
- Keeps crashing

Attached the stack trace and crash logs that I managed to pull from the device. I'm running 8.3 I think, and it's the first iPad mini retina. 

Hope this helps? 

[Artsy  21-01-2016, 08-39.crash.zip](https://github.com/artsy/eigen/files/98957/Artsy.21-01-2016.08-39.crash.zip)

**Comment by orta** [comment]
Looks like https://rink.hockeyapp.net/manage/apps/37029/app_versions/49/crash_reasons/103631948?scope=os_versions&type=statistics which only happens on iOS 8 devices, WKWebViewConfiguration must have had a different API for setting the HTML5 video thing.

**Comment by orta** [comment]
Might be worth considering dropping iOS8 support, we have beta testers using iOS8

All Sessions
<img width="553" alt="screen shot 2016-01-21 at 09 54 04" src="https://cloud.githubusercontent.com/assets/49038/12477016/f056ac7c-c024-11e5-8b82-ff0a7d2b7967.png">

All Inquiries
<img width="519" alt="screen shot 2016-01-21 at 09 55 10" src="https://cloud.githubusercontent.com/assets/49038/12477040/1a23d8cc-c025-11e5-8b53-16015e2b97d4.png">

All iOS8 support comes to roughly ~5% of our user base

**Comment by mennenia** [comment]
I'd say that makes total sense. I'm still on iOS8 because I'm too lazy to update my iPad and I use it more as an ebook reader :P.

**Comment by alloy** [comment]
I’d say, let’s wait until we have a few more important features that we can’t support on iOS 8 without having to write a bunch of iOS 8 specific code. iOS 9 is really slow for some people’s older devices, which is why they might be putting upgrading off.
