### ISSUE TITLE
HOW to pod？

### ISSUE THREAD

**Issue by wy19901227** [artsy/eigen#105]
why pod install have a mistoken， Invalid `Podfile` file: undefined method `plugin' for #<Pod::Podfile:0x007f9ca423a5f8>. Updating CocoaPods might fix the issue.

**Comment by alloy** [comment]
@wy19901227 I suspect that you did not use `bundle exec` when running `pod install`. I that the case?

As the [README](https://github.com/artsy/eigen/blob/master/README.md#oss-quick-start) points out, you are supposed to run `bundle exec pod install`.
