### ISSUE TITLE
RFC: New dependency react-native-document-picker

### ISSUE THREAD

**Issue by MounirDhahri** [artsy/eigen#10538]
**Description**

As part of the new submission flow, we would like to allow users to upload valid documents from their device. We currently have no package that allows doing that for documents (we have one for photos)

**Why RNDocumentPicker?**
`react-native-document-picker` presents itself as one of the most mature, maintained and used packages out there. It also works for both android and iOS and uses native APIs.

**Alternatives**
https://github.com/react-native-documents/document-picker
It's basically the same, just a new rewrite from the save developer

No other alternatives jump to my mind. Example of usage here https://github.com/artsy/eigen/pull/10493

**Comment by araujobarret** [comment]
It looks like a nice lib, but did we consider the [expo candidate](https://github.com/expo/expo/tree/main/packages/expo-document-picker)?

Asking bc Expo modules usually receive more long-run love than the individual packages 😂

**Comment by MounirDhahri** [comment]
Good suggestion. So far, the package that I chose has been maintained for longer than the expo one and has 4 times more users with a recent release from the maintainers. It also has less issues than the expo similar one. None of the above means it's a better suggestion but it leads me to believe it's a fine one to go with

**Comment by araujobarret** [comment]
If it has better maintenance than the Expo's even better, my opinion: 👍 ✅

**Comment by MounirDhahri** [comment]
Perfect - let's go with it then
