### ISSUE TITLE
Convert ARCountdownView string interpolation to use @(thing) 

### ISSUE THREAD

**Issue by orta** [artsy/eigen#1062]
```
    self.daysValueLabel.text = [NSString stringWithFormat:@"%02ld", days];
    self.hoursValueLabel.text = [NSString stringWithFormat:@"%02ld", hours];
    self.minutesValueLabel.text = [NSString stringWithFormat:@"%02ld", minutes];
    self.secondsValueLabel.text = [NSString stringWithFormat:@"%02ld", seconds];
```
->

```
    self.daysValueLabel.text = [NSString stringWithFormat:@"%@", @(days)];
```

if you want to be 100% on the dp, use `round(days)` I guess.

Current implementation causes warnings:
<img width="1154" alt="screen shot 2016-01-24 at 17 13 43" src="https://cloud.githubusercontent.com/assets/49038/12537719/e8ed5e68-c2bd-11e5-86d4-72b9b11c8aca.png">

**Comment by ashfurrow** [comment]
RIGHT, thanks.

**Comment by ashfurrow** [comment]
OK, so the issue with this is that we want two digits even if the first is zero. I'll look into it – maybe a number formatter.

**Comment by orta** [comment]
Legit :+1:
