### ISSUE TITLE
Sale Information Modal

### ISSUE THREAD

**Issue by katarinabatina** [artsy/eigen#1070]
Part of #1035 

- [x] UI #1154 
- [x] Networking #1156

----

Coming from an Auction Sale View or from the Live Bidding UI a user needs to access the core information about the sale 

coming from 
![image](https://cloud.githubusercontent.com/assets/6482926/12599304/d6dc0cb8-c45e-11e5-9d42-47a289eaed27.png) 

huge oversight on my part omiting this from my initial breakdown of issues for native auction sale views, my apologies
![image](https://cloud.githubusercontent.com/assets/6482926/12598901/33f9d2c6-c45b-11e5-928b-167487a94b02.png)

for a reference as to how the sticky labels are supposed to operate on the FAQ please reference this example http://cl.ly/1F263X2q461r

**Comment by ashfurrow** [comment]
Ah, forgot about this view. Tomorrow I want to talk to you and @devangt to make sure we have the upcoming live views properly scoped with estimates – I have a sense of our timeline from the Shiproom deck but it'd be good to double-check specifics.

**Comment by katarinabatina** [comment]
@ashfurrow I think that's what we're planning for on Monday (as I have yet to redline all the comps)

**Comment by ashfurrow** [comment]
Cool cool, that's fine then.

--

[A.]           Ash Furrow

Artsy <https://www.artsy.net/>

                *ash@artsy.net <ash@artsy.net>*

                (347)-592-4474 <//(347)-592-4474> (Mobile)
                @ashfurrow <http://twitter.com/ashfurrow>

**Comment by ashfurrow** [comment]
Since this feature is largely standalone, it would be a great one for @alloy to pick up if he has availability.

**Comment by alloy** [comment]
:+1:

**Comment by ashfurrow** [comment]
Thanks champ!

**Comment by katarinabatina** [comment]
sale description shown underneath the title of the sale, data managed in ohm (auctions admin) https://www.artsy.net/auction/watermill-summer-benefit-and-auction-2015

auction FAQ found at the bottom of this page, data managed in general artsy admin https://www.artsy.net/how-auctions-work

**Comment by orta** [comment]
Cool, looks like it needs a custom UINavigationController, and native views for these:

![screen shot 2016-01-28 at 16 51 25](https://cloud.githubusercontent.com/assets/49038/12651675/6c1f5bc8-c5df-11e5-98b0-7f1613ee1948.png)

![screen shot 2016-01-28 at 16 51 39](https://cloud.githubusercontent.com/assets/49038/12651678/6d4fa322-c5df-11e5-9a19-2b28f09f3784.png)

and the FAQ should be the Martsy how-auctions-work

**Comment by orta** [comment]
We don't have an equivalent for contacting Artsy in Eigen, we could potentially re-use the artwork inquire panel, then figure out what we need to send something that's not an artwork as an inquiry?

**Comment by katarinabatina** [comment]
@orta we do, we used to call it "ask a specialist" I'd prefer we actual made the FAQ a native component if we can

**Comment by orta** [comment]
We do yeah - but it's build for sending Artworks, it'll need both visual changes, and API changes to support sending a generic message.

**Comment by katarinabatina** [comment]
@orta @ashfurrow perhaps for v1 then we just go straight to email

**Comment by ashfurrow** [comment]
@katarinabatina what does "straight to email" mean?

**Comment by ashfurrow** [comment]
Oh, straight to the email-sending dialogue?

**Comment by ashfurrow** [comment]
We discussed this this morning, @alloy is currently working on it (when not distracted by push notifications, I think :wink: ). 

For posterity: our estimate was 2 days.

**Comment by alloy** [comment]
@katarinabatina I’d like some clarification about the ‘contact’ portion:

* For now you’d want it to open Mail.app, right? If so, what recipient address and default subject line should be used?
* Just for reference; in the future would we have the static text as found in the design above or an interactive contact flow similar to the existing artwork inquiry flow?

**Comment by katarinabatina** [comment]
@alloy 

For starters yes, open in the mail app, to: inquiries@artsy.net, subject line: Questions about "Sale X"

In the future we'd want to support showing both contact information for the auction house (as illustrated above) or contacting artsy. I still think this would be done through email. Perhaps in the future, future it'd be integrated but we still have not decided how we want to integrate the auction house to participate in our support process.

**Comment by alloy** [comment]
Gotcha. Thanks :ok_hand:

**Comment by alloy** [comment]
Of these two examples, I assume you want the first that has the text scroll bar all the way to the side, yeah?

![simulator screen shot 08 feb 2016 16 19 13](https://cloud.githubusercontent.com/assets/2320/12889584/e69c0a4c-ce7f-11e5-8167-7ee7bce7ab0d.png)

![simulator screen shot 08 feb 2016 16 19 41](https://cloud.githubusercontent.com/assets/2320/12889585/e6baeb42-ce7f-11e5-8314-7fd6edab484a.png)

**Comment by katarinabatina** [comment]
@alloy yup!

**Comment by bhoggard** [comment]
From `/api/v1/sale/:id`

* buyers_premium
* shipping / conditions of sale - not separate fields now -- maybe in description?
* sale logo - from sale => profile

I don't know what email/alerts means.

**Comment by orta** [comment]
:+1:

**Comment by alloy** [comment]
Those FAQ items are all ‘pages’, see #1156.

**Comment by ashfurrow** [comment]
As #1170 should be finished, this ought to be closed too.

**Comment by orta** [comment]
This is good.
