### ISSUE TITLE
OSS fonts prevent compilation on first time setup

### ISSUE THREAD

**Issue by ctbeiser** [artsy/eigen#1071]
After following the instructions from the README for initial open source setup—
`git clone https://github.com/artsy/eigen.git`
`cd eigen`
`bundle install`
`make oss`
`bundle exec pod install`
`open Artsy.xcworkspace`
Artsy fails to compile with the errors `No known class method for selector ‘serifFontWithSize:’` and `No known class method for selector ‘sansSerifFontWithSize:’`

(see also: #845)

**Comment by orta** [comment]
Interesting, those imports look like they should be doing the right  thing

**Comment by lycaste** [comment]
@orta  i meet the same problem

**Comment by DamianSheldon** [comment]
I workaround by modify ARFonts.h's content as follow:

// To avoid problem with non-clang compilers not having this macro.
#if defined(__has_include)

    #if __has_include(<Artsy_UIFonts/UIFont+ArtsyFonts.h>)
    #import <Artsy_UIFonts/UIFont+ArtsyFonts.h>
    #endif

    #if __has_include(<Artsy_UIFonts/UIFont+OSSArtsyFonts.h>)
    #import <Artsy_UIFonts/UIFont+OSSArtsyFonts.h>
    #endif

#else

    #import <Artsy_UIFonts/UIFont+OSSArtsyFonts.h>

#endif

**Comment by orta** [comment]
I'm confused as to how you're compiling this without a compiler that has `__has_include` - we're using Swift/Obj-C with generics so it should require the latest build of Xcode + LLVM.

**Comment by DamianSheldon** [comment]
This is really strange. It obvious cannot find header file, so I make this modify and it works.

**Comment by jschmid** [comment]
I can confirm that @DamianSheldon's change allows me to compile and run the app.

**Comment by alloy** [comment]
@DamianSheldon My fix doesn’t necessarily do anything for non-clang compilers, but it definitely fixes the original issue.
