### ISSUE TITLE
Place Bid Modal

### ISSUE THREAD

**Issue by katarinabatina** [artsy/eigen#1081]
This modal will replace the current flow of using a microgravity view to place bids. 
![image](https://cloud.githubusercontent.com/assets/6482926/12704406/7697a70e-c828-11e5-85ac-1be875d91944.png)

**Comment by ashfurrow** [comment]
I've opened https://github.com/artsy/eigen/issues/1101 to deal with this flow for online-only auctions, thus reducing the scope of this ticket to live integration _only_.

**Comment by ashfurrow** [comment]
Also: reminder that the success/failure results for actually placing a bid are reusable views from the updated registration flow: https://github.com/artsy/eigen/issues/997

**Comment by ashfurrow** [comment]
Closing this in favour of https://github.com/artsy/eigen/issues/1102
