### ISSUE TITLE
Artwork Area

### ISSUE THREAD

**Issue by katarinabatina** [artsy/eigen#1085]
![image](https://cloud.githubusercontent.com/assets/6482926/12704435/1e90cf76-c829-11e5-85e5-57354cd96a1e.png)

- [x] Fancy layout
- [ ] Small screen support
- [ ] iPad support

**Comment by ashfurrow** [comment]
### Implementation Idea

A collection view for both iPhone/iPad, but it's non-interactive on the iPad. This simplifies the controller and creates only one code path, which is great :+1: 

The collection view will need a custom layout. I initially thought we'd find something open source to use, but I'm afraid there's a dearth of collection view layouts to accomplish this. Luckily, I [wrote the book](http://amzn.to/1SHnIgd) on collection views, so it shouldn't be a problem.

### Estimate

2 Days

**Comment by orta** [comment]
[PBDCarouselCollectionViewLayout](https://cocoapods.org/pods/PBDCarouselCollectionViewLayout] from @eldudi will do this, just had  play around with it. We can then use an `ARAspectRatioImageView` inside that in order to get the image's aspect ratio to work as expected.

**Comment by orta** [comment]
![screen shot 2016-05-18 at 5 45 16 pm](https://cloud.githubusercontent.com/assets/49038/15375975/517ec086-1d20-11e6-9416-cf977e1aefd2.png)

**Comment by ashfurrow** [comment]
The jump to live lot bar now displays the incorrect image until the user scrolls. Should be an easy fix.
