### ISSUE TITLE
Top Navigation Area

### ISSUE THREAD

**Issue by katarinabatina** [artsy/eigen#1086]
![image](https://cloud.githubusercontent.com/assets/6482926/12704443/3bac04cc-c829-11e5-86ef-0d30f94ee6e4.png)

**Comment by katarinabatina** [comment]
assets:

lots
1x http://cl.ly/1M2L3O1Y2B0V
2x http://cl.ly/1g1y2m1z2h1s

info
1x http://cl.ly/2K423N1U211M
2x http://cl.ly/3k3Y0w3t3L3h

chat
1x http://cl.ly/0p2T3t270d3t
2x http://cl.ly/450t033Y3c0S

**Comment by ashfurrow** [comment]
Estimate: 0.5ish days

**Comment by ashfurrow** [comment]
Need to follow-up regarding flow: do we need polymorphic view controllers? /cc @orta.

**Comment by katarinabatina** [comment]
@ashfurrow where the partner name is speced...If we've got the black partner logo I think it'd be preferable. Assuming we get the data we want from the backend would it be ok to amend the design here?

**Comment by ashfurrow** [comment]
Should be able to, yup.

My comment was about how a user gets here. There are two different possibilities:

- User taps any link to the auction and is _immediately_ launched into this live auction view.
- User taps a link to the auction and gets the standard auction overview page, _then_ taps a button to enter this view (this is preferable for us, from a dev effort perspective).

**Comment by katarinabatina** [comment]
@ashfurrow I think the clarity the direct link provides for the user is a big win. Meaning coming from an auction banner or any mention should open this modal while the auction is live.

**Comment by ashfurrow** [comment]
Gotcha. Orta and I discussed this this morning, and he's going go take this this sprint and include "how to get here" as part of this issue's scope.

**Comment by orta** [comment]
No polymorphic VCs we needed, routing is fine without this. Starting to look at this issue now.

**Comment by orta** [comment]
@katarinabatina did you end up with answers WRT partner profile images with a long aspect ratio?

![screen shot 2016-02-24 at 5 54 05 pm](https://cloud.githubusercontent.com/assets/49038/13303873/b12f0c4a-db1f-11e5-979f-06c58f669e7f.png)

This ^ isn't feasible with the current square
