### ISSUE TITLE
horizontal distribution of tab items on ipad are uneven

### ISSUE THREAD

**Issue by katarinabatina** [artsy/eigen#109]
I am sure you have better logic set up to determine spacing but right now i've got 340px on each side then even distribution between tab items 

![image](https://cloud.githubusercontent.com/assets/6482926/6084231/342abf96-adfd-11e4-80fe-83f235a76a2d.png)

**Comment by katarinabatina** [comment]
I think the unselected tabs are too dim looking at them more closely, I think right now they are 50% white, increase to 70% so that they are more legible

**Comment by 1aurabrown** [comment]
can this be a separate issue just so that we are clear on what has and
hasn't been completed?

On Fri, Feb 6, 2015 at 12:41 PM, Katarina Batina <notifications@github.com>
wrote:

> I think the unselected tabs are too dim looking at them more closely, I
> think right now they are 50% white, increase to 70% so that they are more
> legible
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/artsy/eigen/issues/109#issuecomment-73280094>.
>



-- 

[A.]


Laura Brown

Artsy <http://artsy.net/>

laura@artsy.net <caroline@artsy.net>

**Comment by katarinabatina** [comment]
totally, I assumed these two things were conceptually "near" one another so I lumped them together
