### ISSUE TITLE
Create a custom UINavigationController for modals

### ISSUE THREAD

**Issue by orta** [artsy/eigen#1090]
![screen shot 2016-02-01 at 13 15 23](https://cloud.githubusercontent.com/assets/49038/12718331/df0d95f6-c8e5-11e5-9036-675fee9f0a5b.png)

![screen shot 2016-02-01 at 13 16 01](https://cloud.githubusercontent.com/assets/49038/12718368/22cfe596-c8e6-11e5-92a2-15e059592480.png)

I wonder if it's possible for the view controller to be able to define its presentation context so that we can have all this be the same between the Registration function #997 and Sale information #1070

**Comment by orta** [comment]
This does share behaviour with the InquireViewController, but that has a lot more work to do ( animations, text behind the view controller )

**Comment by ashfurrow** [comment]
Great idea, would've been helpful for the Refine view :smile: I'm going to add the "Live Bidding" label, feel free to remote if inappropriate.

**Comment by ashfurrow** [comment]
@orta when you get a chance, would you mind adding an estimate to this?

**Comment by orta** [comment]
It's probably a half-day :+1:
