### ISSUE TITLE
[Register Flow] Create a Register View Controller

### ISSUE THREAD

**Issue by orta** [artsy/eigen#1091]
#997 

https://cocoapods.org/pods/CardIO seems to be the go-to here. 

![screen shot 2016-02-01 at 13 33 58](https://cloud.githubusercontent.com/assets/49038/12718738/76dd8718-c8e8-11e5-8e7d-9acb5d85e08c.png)

![screen shot 2016-02-01 at 13 34 18](https://cloud.githubusercontent.com/assets/49038/12718749/846460aa-c8e8-11e5-8255-b7e52da5a7ac.png)

**Comment by ashfurrow** [comment]
Estimation: 1 day

**Comment by ashfurrow** [comment]
Issue moved to [artsy/auctions #195](https://github.com/artsy/auctions/issues/195) via [**ZenHub**](https://www.zenhub.com/)
