### ISSUE TITLE
bundle exec pod install -> Access Denied

### ISSUE THREAD

**Issue by arnorhaux** [artsy/eigen#11]
Hi

when I run 'bundle exec pod install', I get Error saying that I don't have access to pod 'Artsy+UIFonts'. Could that mean that particular git repo is private undir Artsy ?

**Comment by ashfurrow** [comment]
Yup, that's correct – we're working on that problem here: https://github.com/artsy/eigen/pull/8

**Comment by orta** [comment]
Done :+1:
