### ISSUE TITLE
Leave Max Bid

### ISSUE THREAD

**Issue by ashfurrow** [artsy/eigen#1102]
I believe @katarinabatina has mocks for these. We need to:

- [x] Determine the API mechanism for leaving a max bid
- [x] Show button for leaving max bid or for opening auction (if it's open)

**Comment by katarinabatina** [comment]
@ashfurrow so discussed this with @devangt and it looks like we have a minor snag. For Live, the bid increments will need to be predetermined which means an open form field will not be plausible for users wanting to enter a max bid. Instead they should be able to "Select a max bid" from pre-determined increments (working on a sketch to reflect this now)
![image](https://cloud.githubusercontent.com/assets/6482926/12791637/111bd508-ca76-11e5-8e02-374fea9b44dd.png)

These increments should be fed from whatever API determines our increments today for online only auctions

**Comment by orta** [comment]
If there's a small number of values, maybe a stepper works better? like we did for the watch. Easier to navigate.

```
[ - ]  $45,000 [ + ]
```

**Comment by katarinabatina** [comment]
@orta :+1:

**Comment by ashfurrow** [comment]
@katarinabatina I think this is specific to the https://github.com/artsy/eigen/issues/1081 – I opened this issue for the "auction hasn't opened but I want to leave a max bid" flow.

**Comment by katarinabatina** [comment]
@ashfurrow this applies to any lot in a live auction that has yet to go live.

**Comment by katarinabatina** [comment]
@ashfurrow a video that shows 1. bidding on a lot on the block, 2. bidding on an upcoming lot, 3. bidding on an upcoming lot and getting outbid http://cl.ly/3q1u330c3O0z

**Comment by katarinabatina** [comment]
full flow here

![image](https://cloud.githubusercontent.com/assets/6482926/12831643/5950397a-cb63-11e5-9c97-6bd5fb695579.png)

**Comment by katarinabatina** [comment]
think this guy could work for the loading state https://cocoapods.org/pods/CPLoadingView

**Comment by orta** [comment]
This is multiple view controllers, and a bunch of tricky networking things that I've seen in Eidolon. A conservative estimate puts it at 4 days.

**Comment by katarinabatina** [comment]
And we've come full circle in this issue, back we go to the scrolly picker! 
![image](https://cloud.githubusercontent.com/assets/6482926/15595429/0a9f1d28-238d-11e6-85f4-3fc99db4965d.png)

**Comment by katarinabatina** [comment]
![image](https://cloud.githubusercontent.com/assets/6482926/15609578/d4c9a5bc-23ee-11e6-8325-396218fa91e2.png)

**Comment by orta** [comment]
#1614
