### ISSUE TITLE
Experiment with SocketRocket against Prediction

### ISSUE THREAD

**Issue by ashfurrow** [artsy/eigen#1103]
We need to experiment with [SocketRocket](https://github.com/square/SocketRocket) to verify we can use it for iOS Live Integration and estimate the work required to use it and efficiently distribute events throughout the Live UI.

**Comment by ashfurrow** [comment]
Estimate: 1 Day.

**Comment by ashfurrow** [comment]
Looks like we're going with a more Swift-based solution: https://github.com/daltoniam/Starscream

I like this library (as opposed to https://github.com/tidwall/SwiftWebSocket ) because while it's idiomatic Swift, it follows the delegation pattern used throughout eigen already, and familiar to any Cocoa dev.

**Comment by alloy** [comment]
Good call :+1:

**Comment by ashfurrow** [comment]
Went with https://github.com/socketio/socket.io-client-swift since it's made by the same developers who wrote the server library prediction is using.
