### ISSUE TITLE
Bid history table view / Bid button

### ISSUE THREAD

**Issue by ashfurrow** [artsy/eigen#1117]
This is implementing the table view that shows the bid history as well as the button to place a bid. Note this does not cover how to see more of the bid history, for the purposes of this issue, we're sticking to a table view that's just really really short

### Implementation Idea

Standard table view stuff, but there are a lot of different designs. Luckily it's congruent within compact/regular environments. 

## Estimate

1 Day

**Comment by orta** [comment]
![https://cloud.githubusercontent.com/assets/6482926/12704417/b7775bf2-c828-11e5-939e-3d42f18f7971.png](https://cloud.githubusercontent.com/assets/6482926/12704417/b7775bf2-c828-11e5-939e-3d42f18f7971.png)



![image 2016-03-07 at 9 10 48 am](https://cloud.githubusercontent.com/assets/49038/13574871/109dafaa-e454-11e5-9637-18d393428668.png)

**Comment by orta** [comment]
@katarinabatina should we show the Live Lot button if on closed lots?

**Comment by katarinabatina** [comment]
@orta yes
