### ISSUE TITLE
Make bid history scrollable

### ISSUE THREAD

**Issue by ashfurrow** [artsy/eigen#1118]
The bid history from #1117 is really short, which isn't going to work well for viewing lots of bid history. 

![image 2016-02-03 at 1 45 25 pm](https://cloud.githubusercontent.com/assets/498212/12794431/01b778d0-ca83-11e5-9b51-bfb1b6b62a09.png)

### Implementation Idea

None yet, need to do.

### Estimate

None yet.

**Comment by orta** [comment]
Do we have mockups WRT iPhone 4 for all the scroll stuff? it's gonna be super tight somewhere in there

**Comment by ashfurrow** [comment]
I asked that same question! We're going to decrease the height of the artwork area. @katarinabatina when you have a moment, could you come up with appropriate sizes and add them to https://github.com/artsy/eigen/issues/1085 ?

**Comment by ashfurrow** [comment]
I honestly don't have any ideas to implement this that aren't terrible. Input would be helpful :+1:

**Comment by orta** [comment]
Think the only reasonably option is to have the entire thing scroll above the artwork

**Comment by katarinabatina** [comment]
@orta 
![image](https://cloud.githubusercontent.com/assets/6482926/12889074/34d06a4e-ce4b-11e5-8420-bbeee1a96afa.png)

**Comment by orta** [comment]
did some chatting with @katarinabatina and it's looking like the metaphors you used in this issue at the top is gonna work for all devices :+1:

**Comment by katarinabatina** [comment]
@orta @ashfurrow kind of a functional example from Pinterest? http://cl.ly/1W271a3h413h

**Comment by orta** [comment]
This is in

**Comment by katarinabatina** [comment]
looking great
