### ISSUE TITLE
[Analytics] Separate Segment account for Apple Store

### ISSUE THREAD

**Issue by anipetrov** [artsy/eigen#1121]
Per Orta's recommendation, we could address the problem of receiving strangely behaving events when we release a version that is used by the Apple Store (eg v 2.3.0) by creating a separate Segment account for Apple Store analytics.

**Comment by alexanderfabry** [comment]
What would be the difference between this and the "eigen-production" Segment project?

**Comment by orta** [comment]
Apple Store vs App Store ( physically in the shops vs downloadable for anyone )

**Comment by alloy** [comment]
What’s the approach here, do we just wait till we hear details about the new account?

(And just to be sure, do we care about analytics from those devices?)

**Comment by orta** [comment]
We care, ish. It's more that the analytics from those devices has different pattens that throw off existing analytics.
It's mainly adding another segment bucket, then a new key to cocoapods-keys and making it check the `IS_DEMO`.

**Comment by alloy** [comment]
What’s unclear to me is how we are going to funnel the stats from the existing deployed 2.3.0 apps into a new bucket. I can only imagine regular Eigen to switch to a new bucket, which sounds a bit more complex.

What was the strategy you had in mind?

**Comment by orta** [comment]
I think we "deal with it" for the old builds, and on the next Apple Store release, we ensure they're on a different bucket

**Comment by alloy** [comment]
Right, ok, that makes sense then :+1:
