### ISSUE TITLE
[Analytics] Push notifications follow ups

### ISSUE THREAD

**Issue by anipetrov** [artsy/eigen#1122]
work in progress:

- [x] Add a `batch_id` property to `gravity_production.works_for_you` and `eigen_production`'s `notification received` and `notification tapped`

  - [x] the server includes an `event_id` (which groups batches) in its delivery analytics data
  - [x] the server includes the `batch_id` in its delivery analytics data
  - [x] the server includes the `batch_id` in the push notification payload
  - [x] eigen includes the `batch_id` in its notification received/tapped analytics data

- [x] Add a `scheduled_at` property to the analytics data that Gravity submits. (Which can just be the batch’s `created_at`.)

- [x] Add a `tapped bell icon` event to fire when users tap bell from main nav

- [x] Add a screen view for Bell ([Eigen Bell screenviews](https://artsy.looker.com/x/fqBQkZQ) seems like they dropped off with v 2.3.3. For comparison, microgravity pageviews coming from eigen for the same screen [here](https://artsy.looker.com/x/xPyrg9Q)); update: Orta is working on this here: https://github.com/artsy/eigen/pull/1124

cc @alloy @katarinabatina

**Comment by alloy** [comment]
>  Add a `batch_id` property to `gravity_production.works_for_you` and `eigen_production`'s `notification received` and `notification tapped`

We need to sort out some nomenclature here, currently I use the name ‘batch’ in Gravity to group notifications into batches of notifications that will be send at the same time. This means that notifications in that batch:

* Belong to the same event
* Are delivered to users in the same timezone (or multiple timezones with the same current UTC offset)

However, it does *not* equal an event. i.e. a single event may have many batches.

So based on that, do you want:

* an ID that associates the notification to an event? And, if so, do you have a preference for what that ID looks like (as in, some format from which you can inflect e.g. the date/time)?
* or an ID that associates the notification to ‘batch’ as it is currently used as described above?

**Comment by alloy** [comment]
> - [ ] Add a `tapped bell icon` event to fire when users tap bell from main nav
>
> - [ ] Add a screen view for Bell […] Orta is working on this here: https://github.com/artsy/eigen/pull/1124

I understand the difference between the two, but in practice these are functionally the same in Eigen. When you open the bell view via e.g. tapping a push notification Eigen switches the active tab to be the Bell tab.

Do you still want these to be counted differently? I.e. switch to Bell tab _by tapping the Bell icon_ vs switching to Bell tab _by other means_?

@orta Are these already both properly being counted differently after your fix?

**Comment by orta** [comment]
Yeah, I was just thinking of that difference. No, it will only handle it the way we used to, which is when presenting  the tab.

**Comment by alloy** [comment]
@orta Thanks :ok_hand:

**Comment by orta** [comment]
#1126 does the tap

**Comment by anipetrov** [comment]
@alloy thanks for the context! Could we add a `batch_id`? I assume then we could also create a separate table of `event_id` and `batch_id` pairs, so we could eventually track down all batches that belong to a single event and be able sort notifications by event, too, if needed?

**Comment by alloy** [comment]
@anipetrov Sure, we can do that. And so the event ID can be anything, as long as it’s unique?

**Comment by anipetrov** [comment]
Yep, I think so! Could we add a tstamp for the event?

**Comment by alloy** [comment]
@anipetrov What would the timestamp reflect, the time of scheduling? It can’t be time of delivery, because e.g. in the case of works-for-you it’s delivered at different times around the globe.

**Comment by anipetrov** [comment]
Yeah I was imagining the time of scheduling so that we have a rough idea of how events are dispersed in time but you are right that the meaningful information is the batch timestamp which we can get from any notification that belongs to a certain batch -- so that should be fine.

**Comment by alloy** [comment]
Cool. Will get to this all today.

**Comment by alloy** [comment]
@anipetrov I updated your TODO list with the individual steps to take that we discussed, of which the first 3 are address by: https://github.com/artsy/gravity/pull/9698. Can you verify that I’m not missing anything?

**Comment by anipetrov** [comment]
Yes, that's perfect! Thank you, @alloy!

**Comment by orta** [comment]
OK, I've just gone through eigen - this is all in. We send _all_ data from the notification up to analytics, so when batch_id is added, it gets passed through. This is true of anything we choose to send from gravity in the future.

**Comment by anipetrov** [comment]
:clap: :clap: :clap:

**Comment by anipetrov** [comment]
hi @alloy, @katarinabatina and I chatted today while looking through data and thought that a `created_at` timestamp for the scheduling events in gravity would be useful after all. is it a big hassle to add?

**Comment by alloy** [comment]
@anipetrov @katarinabatina Sure. To avoid confusion, shall we call it `scheduled_at` ?

**Comment by anipetrov** [comment]
Yes, perfect!

**Comment by alloy** [comment]
@anipetrov Just to be sure, you want `scheduled_at` included only in the analytics that Gravity sends on delivery, not what Eigen receives, right?

**Comment by anipetrov** [comment]
Yes! Makes it much much easier to distinguish between events when looking
at the "sent" numbers.

On Friday, February 12, 2016, Eloy Durán <notifications@github.com> wrote:

> @anipetrov <https://github.com/anipetrov> Just to be sure, you want
> scheduled_at included only in the analytics that Gravity sends on
> delivery, not what Eigen receives, right?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/artsy/eigen/issues/1122#issuecomment-183288039>.
>


-- 
[A.]      Ani Petrov

           Artsy <https://artsy.net/>
           ani@artsy.net
           +1 609 216 4575
