### ISSUE TITLE
Create an Analytics visual mode

### ISSUE THREAD

**Issue by orta** [artsy/eigen#1127]
This will visually show all the analytics events sent form eigen.

Steps:
- [ ] Create an Admin toggle for turning off/on the analytics mode, reset when it's changed.
- [ ] Create an ARAnalyticsProvider subclass that uses `ARNotificationView` to present the analytics event
- [ ] On app launch check if we are in beta && analytics mode is on, if so, add the provider

/cc @anipetrov

**Comment by anipetrov** [comment]
:clap: :clap: :clap:

**Comment by orta** [comment]
Optional: tapping the notification shows all the analytics properties etc

**Comment by alloy** [comment]
This has been done in #1215.
