### ISSUE TITLE
What to show on artwork view

### ISSUE THREAD

**Issue by katarinabatina** [artsy/eigen#113]

**Comment by katarinabatina** [comment]
Artwork in a Show
After artwork meta data show:
1. Other works in the show
2. Other works by the artist
3. Related Artworks

Artwork in an Auction
1. Other works in the auction

Artwork in a fair
1. Other works in the show/booth
2. Related artworks from the fair

Example: Artwork in a Show
![image](https://cloud.githubusercontent.com/assets/6482926/6232902/2f73c058-b69d-11e4-88d0-31be9f40f66b.png)

**Comment by alloy** [comment]
* Should the section headings contain the name of the show/fair? (Might be even more relevant for the ‘other works in show’ sections, because apparently an artwork can be in multiple shows, which would result in multiple such sections.)

* Regarding 2 & 3 of “Artwork in a Show”, are these outside the context of the show? So:
  2. Other works by the artist _in any/no show_
  3. Related Artworks _in any/no show_

**Comment by orta** [comment]
> Related Artworks in any/no show

This API doesn't exist, so there's one case you can remove

**Comment by katarinabatina** [comment]
Hi Alloy, 

Although I think having the title of specific show would be helpful, show names can be very, very long therefore I think we should stick with Other Works in Show, these works should be only those within the same show.

2 & 3 are indeed outside the context of the show, therefore, other artworks by the artist can be any artwork by that artist NOT included in the current show (if apart of a show). I'm pretty sure there is a Related Artworks API that was built a few months ago but if I am wrong we can fall back to the "Suggested Artworks" that is currently used in eigen.

**Comment by alloy** [comment]
@orta :+1:

![](http://i.imgur.com/dVTJZFO.gif)

**Comment by alloy** [comment]
@katarinabatina

> show names can be very, very long therefore I think we should stick with Other Works in Show

Yeah, totally. Good point :+1: 

> 2 & 3 are indeed outside the context of the show

Purrfect, will do.

> I'm pretty sure there is a Related Artworks API that was built a few months ago

Yeah I’ve seen references to that, so should be good.
