### ISSUE TITLE
Guide: Artist page redesign

### ISSUE THREAD

**Issue by briansw** [artsy/eigen#1131]
The image below identifies each module that make up the feature set for the redesigned artist page. All issues related to a particular module are identified by their module names in the title of the issue. Use this issue as a reference/guide as you work on the artist page redesign.

Note 1: The height of the content areas in the spec are taller than the device to show content that’s below the fold. Landscape views work just like portrait except the columns are wider.

Note 2: The exterior left and right margins should be 40px as implemented elsewhere in the app. 

![guide](https://cloud.githubusercontent.com/assets/1022172/13050521/ec0a11e4-d3c1-11e5-94f3-4528ced849bc.png)

**Comment by alloy** [comment]
Can you also provide an overview for iPad in both portrait and landscape orientation?

**Comment by briansw** [comment]
See updated issue (note + img) for clarification.

**Comment by alloy** [comment]
Perfect, thanks :+1:

**Comment by katarinabatina** [comment]
@briansw given the change in scope for the Artist Metadata project, could you provide an updated design that reflects what this section might look like with the data that we'll have 
![image](https://cloud.githubusercontent.com/assets/6482926/14159923/f076c3dc-f6a6-11e5-97c8-7f36435453e1.png)

@alloy for context, we expected to have all this new data around a particular artists provided by galleries, that project quickly grew in scope and therefore we won't have information like "collection highlights".

**Comment by briansw** [comment]
@katarinabatina @alloy I've updated the two issues related to these changes (https://github.com/artsy/eigen/issues/1134, https://github.com/artsy/eigen/issues/1133). @alloy let me know if you have any questions.

**Comment by alloy** [comment]
There are a few items that still need to be done, such as the metadata accordion, but in principle this work is 👌
