### ISSUE TITLE
AccordionModuleMetadata

### ISSUE THREAD

**Issue by briansw** [artsy/eigen#1134]
Link referenced in img: https://github.com/artsy/force/issues/4674#issuecomment-205931981

![accordion-module-metadata](https://cloud.githubusercontent.com/assets/1022172/14364907/0672cfb8-fcd9-11e5-9710-069da8383e21.png)

**Comment by alloy** [comment]
[Question for myself] Is there an API endpoint for this yet?

**Comment by alloy** [comment]
This is deferred until we have any of this data at all.

**Comment by alloy** [comment]
@mzikherman What of this data do we have nowadays?
