### ISSUE TITLE
RailModuleArticles

### ISSUE THREAD

**Issue by briansw** [artsy/eigen#1135]
![rail-module-articles](https://cloud.githubusercontent.com/assets/1022172/12961220/4bb7dbca-d00d-11e5-9f0a-ac853de6e7a6.png)

**Comment by sarahscott** [comment]
@briansw in the iPhone view, what is the absolute width?

**Comment by briansw** [comment]
@sarahscott the note for iphone is unclear, sorry about that. For iphone the width should be set to 1 column in the two column grid + 60px. See screenshot below:

![screen shot 2016-05-04 at 11 52 47 am](https://cloud.githubusercontent.com/assets/1022172/15020166/dfc420d0-11ee-11e6-8467-af3bbd88f507.png)

**Comment by sarahscott** [comment]
I see. Thanks!

**Comment by alloy** [comment]
This is done in v1 of Emission.
