### ISSUE TITLE
RelatedArtistsModule

### ISSUE THREAD

**Issue by briansw** [artsy/eigen#1136]
![related-artists-module](https://cloud.githubusercontent.com/assets/1022172/12961242/6699e83e-d00d-11e5-92b5-aa006aaafe96.png)

**Comment by alloy** [comment]
* Do we ever only show a max of 4 artists on iPhone and 6 on iPad?
* If not, is there a limit? And how are these shown?

**Comment by briansw** [comment]
From what I can tell it looks like the max set to 16—let's keep it at 16 for now.

**Comment by alloy** [comment]
Ok.

**Comment by sarahscott** [comment]
@alloy eyeing this component: https://github.com/lucholaf/react-native-grid-view after reading this discussion: https://github.com/facebook/react-native/issues/638

**Comment by alloy** [comment]
Sounds good. Skim through the code of the lib to see if it's not massively complex and it all makes sense to you, then go for it!

**Comment by alloy** [comment]
@sarahscott I think that you can do these grids with just flexbox btw, no grid view needed.

The reason for a more fancy grid view is to optimise when you have large, potentially infinite lists. Like `ListView` it removes cells from the hierarchy when they’re offscreen and recycles view objects. But in our case it’s just 16.

**Comment by alloy** [comment]
This is done v1 of Emission.
