### ISSUE TITLE
WorksModule

### ISSUE THREAD

**Issue by briansw** [artsy/eigen#1137]
![works-module](https://cloud.githubusercontent.com/assets/1022172/12961296/a1d16c9c-d00d-11e5-960e-74e49d7d75be.png)

**Comment by alloy** [comment]
I’m not sure I understand the iPad landscape design, it appears to be in portrait? Or is this because I’m missing an overview of the iPad design? (https://github.com/artsy/eigen/issues/1131#issuecomment-184155010)

**Comment by briansw** [comment]
The height of the content areas in the spec are taller than the device to show content that’s below the fold. Landscape views work just like portrait except the columns are wider.

**Comment by alloy** [comment]
This is done in v1 of Emission.
