### ISSUE TITLE
ShowsModule

### ISSUE THREAD

**Issue by briansw** [artsy/eigen#1138]
![shows-module](https://cloud.githubusercontent.com/assets/1022172/12961340/f6b79a24-d00d-11e5-8ef8-93ceefb9d0d2.png)

**Comment by alloy** [comment]
I’m not sure I understand the iPad landscape design, it appears to be in portrait? Or is this because I’m missing an overview of the iPad design? (https://github.com/artsy/eigen/issues/1131#issuecomment-184155010)

**Comment by briansw** [comment]
The height of the content areas in the spec are taller than the device to show content that’s below the fold. Landscape views work just like portrait except the columns are wider.

**Comment by alloy** [comment]
Gotcha.

**Comment by sarahscott** [comment]
Should there be a limit to the number of Current and Past Shows in each list?

**Comment by alloy** [comment]
And which images do we use? If I look at what metaphysics currently offers, I see `meta_image` and `cover_image`. I’m not sure what the difference is, but in any case those may contain portrait images, which doesn’t appear to line-up with the design.

**Comment by briansw** [comment]
We should display all shows in each bucket. For more prolific artists, there can be a lot of past shows. Could we ajax those in as the user continues to scroll down to avoid long load times?

We should use the `cover_image`, though you'll need to ensure eigen can grab the fallback images, see https://github.com/artsy/microgravity/issues/1367.

And here's an example show that doesn't have a cover_image, install shots, and works aren't sharable: https://www.artsy.net/show/museum-boijmans-van-beuningen-ugo-rondinone. Matt

**Comment by alloy** [comment]
> We should display all shows in each bucket. For more prolific artists, there can be a lot of past shows. Could we ajax those in as the user continues to scroll down to avoid long load times?

Ok. Yeah, paginating makes a lot of sense 👍 

> We should use the `cover_image`, though you'll need to ensure eigen can grab the fallback images, see https://github.com/artsy/microgravity/issues/1367.

Based on reading the linked ticket, that means we need to use `meta_image` which means that metaphysics performs the fallback for us.

**Comment by briansw** [comment]
Ah ok, I must have misread Matt's comment, thanks for catching.

**Comment by alloy** [comment]
Regarding the open/close messages (in your examples the ‘Opening Today’ and ‘Closing in 2 days’ messages):

* When do the open messages show-up? Only if a show opens today, or also in a few days and, if so, from how many days?
* When do the close messages show-up? If it’s from e.g. 2 days before closing and a show’s only open for 2 days, do we show the close message rather than the ‘Opening Today’ one?

**Comment by briansw** [comment]
I don't know the exact logic here, but we should keep the existing functionality. I'm not sure if this has been done on eigen before, but we currently do it on force. Matt or Damon might be able to point you to the logic.

**Comment by alloy** [comment]
There are shows where artists are said to be represented, but we don’t have any artworks in that show (yet?), which means that it currently shows-up in the list with ‘0 WORKS’. Should we just leave that whole part off in these cases, or do something else?

![simulator screen shot 08 may 2016 20 59 14](https://cloud.githubusercontent.com/assets/2320/15099792/da8dc02a-155f-11e6-95f5-e2923b19a421.png)

_(See top and bottom entries)_

**Comment by briansw** [comment]
Sorry, let's actually ditch the artwork counts since they're typically lower than anticipated due to galleries and institutions only uploading a few representative works for a given show.

Let's still list the show even when works aren't present, but I'm curious how this is possible. From what I understand an artist can only be associated with a show via an uploaded artwork.

Last note: It looks like we're writing "Fair show" right now, but it should be "Fair booth"

**Comment by alloy** [comment]
> Sorry, let's actually ditch the artwork counts since they're typically lower than anticipated due to galleries and institutions only uploading a few representative works for a given show.

I have to say that I think that:

* As a user, I find it very helpful to know which shows have e.g. 1 work vs over a dozen, because if I’m specifically looking for multiple works by this artist, that tells me where to go.
* Showing these numbers might motivate galleries/institutions to upload more works.

> Let's still list the show even when works aren't present

👍 

> but I'm curious how this is possible. From what I understand an artist can only be associated with a show via an uploaded artwork.

Maybe there are unpublished works? @mzikherman do you know how that works?

> Last note: It looks like we're writing "Fair show" right now, but it should be "Fair booth"

Good catch, will do.

**Comment by alloy** [comment]
This is done v1 of Emission.
