### ISSUE TITLE
No network connection warning not showing up

### ISSUE THREAD

**Issue by briansw** [artsy/eigen#1147]
I get "failed to save work" messages when trying to favorite works/follow artists, but when going to different pages I'm sent to the page without any content loaded with the spinner running indefinitely.

![img_5927_720](https://cloud.githubusercontent.com/assets/1022172/12986163/d68afc58-d0c3-11e5-84e0-8380cd21b6a7.png)

**Comment by alloy** [comment]
We have to debug this when someone runs into it. Right now it would take too much time for me to try to think of all the ways in which this could happen.

**Comment by briansw** [comment]
It happens pretty consistently for me by doing the following: 
1. turn on airplane mode 
2. go to shows tab

Let me know if I can help in any other way

**Comment by alloy** [comment]
Ooohhh, now I see the airplane mode being enabled in your screenshot. Thanks for the update.
