### ISSUE TITLE
Test multiple device configs at once

### ISSUE THREAD

**Issue by ashfurrow** [artsy/eigen#1152]
Objective-C/Specta tests have `itHasSnapshotsForDevicesWithName`, and we need something similar for Swift/Quick. Something to stub the horizontal size class, the device, then take a snapshot. See discussion in #1151.

**Comment by alloy** [comment]
I’d prefer us to move to running the full test suite multiple times against different devices, instead of trying to fake it.

**Comment by ashfurrow** [comment]
Agreed. Though we'll need something more sophisticated than just running the tests twice, since new view controllers should be written independently of the device (and rely on size classes instead). Maybe running the tests twice with two sets of arguments that influence how the whole suite gets run? We could mock `UIDevice` for existing tests that depend on the device, and otherwise stub view controllers with specific size classes / size based on those arguments. We should consider splitting into two test targets, since some of our tests don't depend on UI at all.

**Comment by alloy** [comment]
I don’t think we should mock anything for this. We can just run on an iPhone and on a iPad to set the right size classes, no? (That does not mean that our code should_check_ for the device.)

**Comment by ashfurrow** [comment]
No, unfortunately the the view controllers' size classes are only defined once they're within a view controller hierarchy that itself has defined size classes. At some point, we need to explicitly give some view controller a specific size class, which is where mocking came in.

It's completely possible that I'm missing something. I asked on Twitter a few weeks ago about this and didn't hear back anything encouraging. This definitely warrants more investigation/exploration :smiley_cat:

**Comment by alloy** [comment]
Mkay, I have no clue :dancer: 

Let me put it like this, we shouldn’t need to do anything that you normally wouldn’t need to do in an app. So no mocking of `UIDevice`, etc.

**Comment by ashfurrow** [comment]
Sounds like a plan 👍
