### ISSUE TITLE
Guide: Artwork Page

### ISSUE THREAD

**Issue by katarinabatina** [artsy/eigen#1159]
The image below identifies each module that make up the feature set for the redesigned artwork page. All issues related to a particular module are identified by their module names in the title of the issue. Use this issue as a reference/guide as you work on the artwork page.

![image](https://cloud.githubusercontent.com/assets/6482926/13064653/be04ad7a-d422-11e5-986f-5bc652ad2dd5.png)

![image](https://cloud.githubusercontent.com/assets/6482926/13064656/c493a4d4-d422-11e5-881a-83bf5760aee9.png)

![image](https://cloud.githubusercontent.com/assets/6482926/13064657/cb3854ce-d422-11e5-8bc2-bac6ca92a8ab.png)

**Comment by alloy** [comment]
@katarinabatina Should we close this for now?

**Comment by katarinabatina** [comment]
hmmm @alloy I say we keep it open for now

**Comment by alloy** [comment]
Okeydokey, captain 👌
