### ISSUE TITLE
AccordionModule

### ISSUE THREAD

**Issue by katarinabatina** [artsy/eigen#1163]
![image](https://cloud.githubusercontent.com/assets/6482926/13064813/1e5622fc-d424-11e5-9c1c-1c6117dc15a1.png)

**Comment by katarinabatina** [comment]
reference https://github.com/artsy/eigen/issues/1173 for supporting two width types

**Comment by orta** [comment]
done in #1170

**Comment by orta** [comment]
unclosing, this is specific to artworks
