### ISSUE TITLE
Wrap up the Auction Information Modal

### ISSUE THREAD

**Issue by orta** [artsy/eigen#1170]
re: #1154

- [x] Add networking for downloading the data
- [x] Remove headers from the markdown?
- [x] Remove `ARThemedFactory` from swift 
- [x] Convert the logo to be an image, make square
- [x] Bug someone about the contact API
- [x] Remove TODOs in `/Auction/AuctionInformationViewController.swift`
- [x] Remove `!` in `Artsy/Views/Auction/AuctionTitleView.swift`
- [x] remove the status bar on the modal
- [x] Support tapping links in the FAQs
- [x] Send a user to the registration url
- [x] Design QA #1172 
- [ ] ~~#1173~~
- [x] https://github.com/artsy/eigen/issues/1163
- [x] #1172

**Comment by alloy** [comment]
:+1:

**Comment by orta** [comment]
OK, I think that's all the pieces, adding tests now

**Comment by ashfurrow** [comment]
All wrapped up on this?

**Comment by orta** [comment]
Yes.
