### ISSUE TITLE
QA: Auction Information Modal Views

### ISSUE THREAD

**Issue by katarinabatina** [artsy/eigen#1172]
- [x] Add black downward arrow to module items (This component will be reused with different line widths here https://github.com/artsy/eigen/issues/1163) 
- [x] Implement https://github.com/artsy/eigen/issues/1173 so that differences list buttons are eliminated
- [x] header should be 60px not 80 px 
- [x] replace current x with this component http://cl.ly/33150g3V1t0E
![image](https://cloud.githubusercontent.com/assets/6482926/13084364/2ee7ff0e-d4a7-11e5-9c16-8b7841edcbed.png)

**Comment by orta** [comment]
done in #1170
