### ISSUE TITLE
“Failed to save artwork. Network connection error”

### ISSUE THREAD

**Issue by alloy** [artsy/eigen#1182]
From a customer review https://launchkit.io/reviews/FNdM2oeAHH4:

> "Failed to save artwork. Network connection error" non-stop. All else on my iPhone connects as expected, period.

Apparently the app works for the user, up to the moment they try to fave an artwork, at which time it shows the failure message. This is the opposite of #1147.

Not sure if this is a wide-spread problem and unfortunately the error message doesn’t tell us what’s really going on, could be any type of problem, we just say it’s a network one.

**Comment by alloy** [comment]
@katarinabatina I’d like to ask you to give adding a small ‘more info’ button to the network error banner another thought. For these cases where there’s a persistent problem, it would help to be able to ask a user for the raw underlying error message.

**Comment by katarinabatina** [comment]
@alloy could we make the whole banner tappable? I do think users jump to do this as a knee jerk reaction to seeing the error pop up

**Comment by alloy** [comment]
Sure sure, can do that :+1:

**Comment by katarinabatina** [comment]
while we're add it lets remove the ( ! ) icon as it seems to break and run into the messaging quite often.
