### ISSUE TITLE
Spotlight search for artists may not work with our new React Native artist view.

### ISSUE THREAD

**Issue by orta** [artsy/eigen#1187]
I couldn't get it to show with @devangt today.

**Comment by orta** [comment]
Just worked fine for me when testing #1192

**Comment by devangt** [comment]
Oh wow. I'll try to reinstall and repro

-devang




On Wed, Feb 24, 2016 at 3:14 PM -0800, "Orta" <notifications@github.com> wrote:












Just worked fine for me when testing #1192

**Comment by alloy** [comment]
Spotlight indexes may get removed by the system after which it will tell the app to re-index, which we haven’t implemented yet https://developer.apple.com/library/ios/documentation/CoreSpotlight/Reference/CSSearchableIndexDelegate_Protocol/index.html#//apple_ref/occ/intf/CSSearchableIndexDelegate

For favourites this would be a matter of refetching all the data, but for those you have visited we’d need to keep track of our own history. Not sure how that’s _supposed_ to work, probably needs more investigation.

**Comment by katarinabatina** [comment]
Any conclusions here? I'm thinking to close since this isn't anything we're actively pursuing (or will pursue in the near future) @orta your call

**Comment by orta** [comment]
Close, we're throwing artists over the wall to apple whether and how they catch it is ambiguous for us alas.

**Comment by orta** [comment]
Well, actually, debate on the close - I don't know if this is supported on our new react native artist views. It's probably pretty simple to move the code over.

**Comment by alloy** [comment]
Good point 👍

**Comment by alloy** [comment]
Closing this in favour of https://github.com/artsy/collector-experience/issues/810
