### ISSUE TITLE
[Universal Links] Not everybody gets pulled into app from e.g. a Google search

### ISSUE THREAD

**Issue by alloy** [artsy/eigen#1192]
Steps from @alexanderfabry:
1. Open Safari.app
2. Google for Andy Warhol
3. Tap the artsy.net search result
4. Stays in Safari.app and opens martsy

**Comment by alloy** [comment]
@alexanderfabry Can you confirm that:

* Following an artsy.net link from e.g. Messages.app, Mail.app, or Notes.app _does_ open Artsy.app?
* Did you really go to the google search results web page, or did you select a result from the suggestions that Safari.app shows you when you type search terms in Safari’s address bar?

**Comment by orta** [comment]
may be connected #1187

**Comment by orta** [comment]
( FWIW, I just tried this and couldn't re-produce )

**Comment by katarinabatina** [comment]
neither could I

**Comment by katarinabatina** [comment]
closing in favor of reviewing our "deep linking strategy" in the nearish future
