### ISSUE TITLE
[Fair] Map link overwrites a featured link

### ISSUE THREAD

**Issue by alloy** [artsy/eigen#1201]
If a fair has a map, [it takes the place of the second featured link](https://github.com/artsy/eigen/blob/adaa5d857c16df7b411db268d7af9a7d53dc3774/Artsy/View_Controllers/Fair/ARFairViewController.m#L195) and that link is lost. It was introduced in this commit: https://github.com/artsy/eigen-private/commit/41d03579c6167f65fe2b28e4e272714e3d3961e4. The current workaround is to add a dummy link as the second featured link.

@ashfurrow Do you remember why this was implemented like this?

**Comment by orta** [comment]
I wonder if the logic should be changed to look for an existing one with the lowercase'd name "map" and replace that.

**Comment by ashfurrow** [comment]
@alloy I imagine this was a mistake on my part, making the assumption there would be zero or one existing feature links. That'd be my guess.

**Comment by katarinabatina** [comment]
the work around is sufficient and something fair admins are aware of, closing for now
