### ISSUE TITLE
Fix crash in static ext.Artsy.__ObjC.SaleArtwork.((includedInRefineSettings in _576E142F1F9C30C16F243CC7693AB1F5) (__ObjC.SaleArtwork.Type) -> (Artsy.AuctionRefineSettings) -> (__ObjC.SaleArtwork) -> Swift.Bool).(closure #1), line 0

### ISSUE THREAD

**Issue by artsyit** [artsy/eigen#1204]
### Stacktrace ###

<pre>-;static ext.Artsy.__ObjC.SaleArtwork.((includedInRefineSettings in _576E142F1F9C30C16F243CC7693AB1F5) (__ObjC.SaleArtwork.Type) -> (Artsy.AuctionRefineSettings) -> (__ObjC.SaleArtwork) -> Swift.Bool).(closure #1);SaleViewModel.swift;0
-;Artsy.SaleViewModel.refinedSaleArtworks (Artsy.SaleViewModel)(Artsy.AuctionRefineSettings) -> [Artsy.SaleArtworkViewModel];SaleViewModel.swift;53
-;Artsy.AuctionViewController.displayCurrentItems (Artsy.AuctionViewController)() -> ();AuctionViewController.swift;168
-;@objc Artsy.AuctionViewController.displayCurrentItems (Artsy.AuctionViewController)() -> ();AuctionViewController.swift;0
-;function signature specialization <Arg[0] = Owned To Guaranteed> of Artsy.AuctionViewController.setupForSale (Artsy.AuctionViewController)(Artsy.SaleViewModel) -> ();AuctionViewController.swift;138
-;Artsy.AuctionViewController.(viewWillAppear (Artsy.AuctionViewController) -> (Swift.Bool) -> ()).(closure #1);AuctionViewController.swift;70
-;Interstellar.Signal.(next <A> (Interstellar.Signal<A>) -> ((A) -> ()) -> Interstellar.Signal<A>).(closure #1);Signal.swift;148
-;Interstellar.Signal.(update <A> (Interstellar.Signal<A>) -> (Interstellar.Result<A>) -> ()).(closure #1);Signal.swift;209
-;ext.Swift.Swift.SequenceType<A where A: Swift.SequenceType>.forEach <A where A: Swift.SequenceType> (A)((A.Generator.Element) throws -> ()) throws -> ();Signal.swift;0
-;Interstellar.Signal.update <A> (Interstellar.Signal<A>)(Interstellar.Result<A>) -> ();Signal.swift;209
-;partial apply forwarder for Interstellar.Signal.update <A> (Interstellar.Signal<A>)(Interstellar.Result<A>) -> ();Signal.swift;0
-;Interstellar.Signal.(update <A> (Interstellar.Signal<A>) -> (Interstellar.Result<A>) -> ()).(closure #1);Signal.swift;209
-;ext.Swift.Swift.SequenceType<A where A: Swift.SequenceType>.forEach <A where A: Swift.SequenceType> (A)((A.Generator.Element) throws -> ()) throws -> ();Signal.swift;0
-;Interstellar.Signal.update <A> (Interstellar.Signal<A>)(Interstellar.Result<A>) -> ();Signal.swift;209
-;Interstellar.Signal.(map <A><B> (Interstellar.Signal<A>) -> ((A) -> B) -> Interstellar.Signal<B>).(closure #1);Signal.swift;63
-;Interstellar.Signal.(update <A> (Interstellar.Signal<A>) -> (Interstellar.Result<A>) -> ()).(closure #1);Signal.swift;209
-;ext.Swift.Swift.SequenceType<A where A: Swift.SequenceType>.forEach <A where A: Swift.SequenceType> (A)((A.Generator.Element) throws -> ()) throws -> ();Signal.swift;0
-;Interstellar.Signal.update <A> (Interstellar.Signal<A>)(Interstellar.Result<A>) -> ();Signal.swift;209
-;Interstellar.Signal.(merge <A><B> (Interstellar.Signal<A>) -> (Interstellar.Signal<B>) -> Interstellar.Signal<(A, B)>).(closure #2);Signal.swift;187
-;Interstellar.Signal.(next <A> (Interstellar.Signal<A>) -> ((A) -> ()) -> Interstellar.Signal<A>).(closure #1);Signal.swift;148
-;Interstellar.Signal.(update <A> (Interstellar.Signal<A>) -> (Interstellar.Result<A>) -> ()).(closure #1);Signal.swift;209
-;ext.Swift.Swift.SequenceType<A where A: Swift.SequenceType>.forEach <A where A: Swift.SequenceType> (A)((A.Generator.Element) throws -> ()) throws -> ();Signal.swift;0
-;Interstellar.Signal.update <A> (Interstellar.Signal<A>)(Interstellar.Result<A>) -> ();Signal.swift;209
-;partial apply forwarder for Interstellar.Signal.update <A> (Interstellar.Signal<A>)(Interstellar.Result<A>) -> ();Signal.swift;0
-;Artsy.AuctionSaleArtworksNetworkModel.(fetchSaleArtworks (Artsy.AuctionSaleArtworksNetworkModel) -> (Swift.String, callback : (Interstellar.Result<[__ObjC.SaleArtwork]>) -> ()) -> ()).(closure #1);AuctionSaleArtworksNetworkModel.swift;21
-;Artsy.((fetchPage in _A2CC32B3077A45794C7542EE6485D1A5) (Swift.Int, forSaleID : Swift.String, alreadyFetched : [__ObjC.SaleArtwork], callback : (Interstellar.Result<[__ObjC.SaleArtwork]>) -> ()) -> ()).(closure #1);AuctionSaleArtworksNetworkModel.swift;43</pre>

### Link to HockeyApp ###

* [https://rink.hockeyapp.net/manage/apps/37020/crash_reasons/112566863](https://rink.hockeyapp.net/manage/apps/37020/crash_reasons/112566863)

**Comment by alloy** [comment]
Triggered by just tapping the 'refine' button.

**Comment by orta** [comment]
#1194 fixes this.

**Comment by alloy** [comment]
#1194 is merged
