### ISSUE TITLE
Add word lot in front of lot number, make color hex #666666, increase line spacing

### ISSUE THREAD

**Issue by katarinabatina** [artsy/eigen#1205]
current
![image](https://cloud.githubusercontent.com/assets/6482926/13380184/24467842-de0b-11e5-8525-a642ef38b6e0.png)
current color looks quite light, want to make sure its #666666, current line spacing seems squished
![image](https://cloud.githubusercontent.com/assets/6482926/13380191/4b1500ba-de0b-11e5-86c0-144d8909e794.png)

update
![image](https://cloud.githubusercontent.com/assets/6482926/13380187/2b48aa8e-de0b-11e5-96ca-440519de71c7.png)
![image](https://cloud.githubusercontent.com/assets/6482926/13380193/51b7c40c-de0b-11e5-9cba-5a267879de18.png)

**Comment by orta** [comment]
This one is really interesting, we are actually using `#666666` here - but something ( perhaps colour profiles ) is turning it into a lighter grey.

**Comment by katarinabatina** [comment]
@orta how do we fix this color profile issue, any ideas?

**Comment by orta** [comment]
I fixed it, for this case, we have to think about it at a global level to really see what's going on here
