### ISSUE TITLE
fix refine button UI, tapping refine button leads you to the artwork that is underneath the button

### ISSUE THREAD

**Issue by katarinabatina** [artsy/eigen#1206]
current
![image](https://cloud.githubusercontent.com/assets/6482926/13380200/75c6693e-de0b-11e5-8bba-fa841f32ccde.png)

update
![image](https://cloud.githubusercontent.com/assets/6482926/13380221/c7f55bc0-de0b-11e5-99cf-4226a54618a6.png)

**Comment by ashfurrow** [comment]
Issue moved to [artsy/auctions #193](https://github.com/artsy/auctions/issues/193) via [**ZenHub**](https://www.zenhub.com/)
