### ISSUE TITLE
auction preview state 

### ISSUE THREAD

**Issue by katarinabatina** [artsy/eigen#1208]
current
![image](https://cloud.githubusercontent.com/assets/6482926/13380245/22cbb4d6-de0c-11e5-9b0c-98a875d13397.png)

update
![image](https://cloud.githubusercontent.com/assets/6482926/13380246/2a0f438e-de0c-11e5-80e0-6d335ad364c6.png)

**Comment by orta** [comment]
ohh, hrm, interesting - makes sense.
