### ISSUE TITLE
[bell] artwork name and year lack space.

### ISSUE THREAD

**Issue by dblock** [artsy/eigen#1210]
![2016-02-28 17 24 38](https://cloud.githubusercontent.com/assets/542335/13382353/8bf6fa5e-de40-11e5-8c2a-b8f523a7efc4.png)

**Comment by alloy** [comment]
This is a microgravity view and bug: https://github.com/artsy/microgravity/issues/1292

**Comment by katarinabatina** [comment]
closing as we now have a native view :)
