### ISSUE TITLE
Works For You VC QA

### ISSUE THREAD

**Issue by katarinabatina** [artsy/eigen#1230]
- [x] increase touch area for tapping on the artist name and going to their artist page
- [x] zero state is not showing up, only a blank page with the title works by artists you follow
- [x] change color of chevron from grey -> black
- [x] make masonry grid 3 columns for landscape iPad
- [x] center-align title label to search button
- [x] increase padding between vertically-adjacent artwork cells

----

(@alloy) Moved these to #1264:
- [ ] ~~tapping the bell while on the view should take you to the top of the page~~
- [ ] ~~tap to top does not work (I know this is an ongoing problem but wondered if we might be able to fix it here)~~

Moved this to #1271:
- [ ] ~~we should only be showing for sale works in this feed might be related to https://github.com/artsy/gravity/issues/9752 (**update:** waiting on some answers from gravity)~~

**Comment by sarahscott** [comment]
:+1: danke!

**Comment by sarahscott** [comment]
@katarinabatina I could filter the works based on their for-sale status, but then they might become out-of-sync with the notifications count in the bell (unless I also filter that count). Probably better to wait on the gravity fix so everything stays consistent.

**Comment by sarahscott** [comment]
Make masonry grid 3 columns for landscape iPad

**Comment by sarahscott** [comment]
Center-align title to search button

**Comment by sarahscott** [comment]
Increase padding between vertically-adjacent artwork cells

**Comment by alloy** [comment]
> change color of chevron from grey -> black

Assuming this uses the Artsy-UIButtons pod, @orta made this change, I think.

**Comment by katarinabatina** [comment]
@sarahscott one thing to add to the QA list: I'm not seeing the zero state for when a user has zero follows

**Comment by alloy** [comment]
New count badge remains while scrolling. Also when scrolling past the number of new works and when changing away from the bell tab.

![asset png](https://cloud.githubusercontent.com/assets/2320/13708814/d8ab4336-e7b0-11e5-912c-0b6ed3d1638d.jpeg)

**Comment by alloy** [comment]
Title label (but might be all labels?) does not wrap text.

![image_0](https://cloud.githubusercontent.com/assets/2320/13708841/fdb39ade-e7b0-11e5-9d90-0a58747b9b88.jpg)

**Comment by alloy** [comment]
Maybe remove the view title on a blank state?

![image_0-2](https://cloud.githubusercontent.com/assets/2320/13708860/191ec19a-e7b1-11e5-9aa6-3c878c9e7268.jpg)

**Comment by alloy** [comment]
Seeing a few entries being repeated. Maybe it’s something that happens at page boundaries or something, e.g. a off by 1 error?

![works-for-you repitition](https://cloud.githubusercontent.com/assets/2320/13708978/c4033622-e7b1-11e5-82d8-80f2cb01a053.gif)

**Comment by katarinabatina** [comment]
@alloy on work titles wrapping: can we use elipses like we do on the web? for example "Untitled work 19..."

**Comment by alloy** [comment]
Sure.

**Comment by alloy** [comment]
With regards to the sale works, Gravity will change the way they generate _bundles_ (only with for-sale works), but as this VC does not use that endpoint, we should simply add the for-sale only query parameter.

**Comment by alloy** [comment]
Made #1271 to track the for-sale only works so this one can be closed.
