### ISSUE TITLE
Scrolling is really missed up (will investigate more)

### ISSUE THREAD

**Issue by katarinabatina** [artsy/eigen#1231]

**Comment by alloy** [comment]
Messed up in what way?

**Comment by orta** [comment]
I was sitting next to Katarina, on the latest build she would regularly see scrolling lag at a roughly similar timeframe, it didn't matter what view controller she was on. The lag was pretty severe.

I wondered if it's JSON parsing, or non-background thread stuff for Spotlight?

**Comment by katarinabatina** [comment]
nothing conclusive here, this was definitely on much older builds of the app I'm going to close for now
