### ISSUE TITLE
[Checkout] Country select leads to view zooming in.

### ISSUE THREAD

**Issue by dylanfareed** [artsy/eigen#1235]
# problem

If you find yourself on the ecommerce check out view in eigen (martsy redirects to eigen) clicking on the select menu to select country will zoom in a surprising fashion

Steps to reproduce:
- Search for 'Emma Abad'
- Click on artwork called 'Monsieur Grizou & Hector' (ie https://www.artsy.net/artwork/emma-abad-monsieur-grizou-and-hector)
- Click "buy"
- click on select menu for country
### Before:

![image](https://cloud.githubusercontent.com/assets/197336/13542615/e4bb357a-e231-11e5-8a11-657646614eaf.png)
### During:

![image](https://cloud.githubusercontent.com/assets/197336/13542649/2f3edf20-e232-11e5-861c-ccbce8f60cc1.png)
### After:

![image](https://cloud.githubusercontent.com/assets/197336/13542612/dd06a54e-e231-11e5-8b1c-6fc61fe9321d.png)

**Comment by dylanfareed** [comment]
Likely also or separately a microgravity bug but adding here because of the force redirect to eigen i can only repro in the appzor

**Comment by alloy** [comment]
I tested this on martsy (by removing the app from my phone first) and verified that it is a martsy issue. Filed the following 2 tickets:

- https://github.com/artsy/microgravity/issues/1298
- https://github.com/artsy/microgravity/issues/1299
