### ISSUE TITLE
view in room sizing issue

### ISSUE THREAD

**Issue by katarinabatina** [artsy/eigen#1237]
brought up in the past, but Sebastian noticed that this work 
![image](https://cloud.githubusercontent.com/assets/6482926/13557338/90aa5baa-e3bc-11e5-91f9-4667344e4036.png)

doesn't scale properly 
![image](https://cloud.githubusercontent.com/assets/6482926/13557343/a1c8de8e-e3bc-11e5-9e29-8686c0da034c.png)

**Comment by orta** [comment]
Likely a cm -> inches problem

**Comment by sarahscott** [comment]
It looks like eigen is already handling the metric field: https://github.com/artsy/eigen/blob/master/Artsy/Models/API_Models/Partner_Metadata/Artwork.m#L596, so it's not the issue I encountered in Folio. Could be some parameter tweaking?

**Comment by alloy** [comment]
I wonder, is it actually correct [on web](https://www.artsy.net/artwork/james-rosenquist-elbow-lake)? This seems the same relative to the bench:

![screen shot 2016-04-12 at 21 22 35](https://cloud.githubusercontent.com/assets/2320/14472740/da04c7d6-00f4-11e6-8639-739232dbc973.png)

**Comment by sarahscott** [comment]
Yeah I agree.... neither of them look 6 ft wide.

**Comment by sarahscott** [comment]
I suppose I should get used to describing things in meters, so 1.85m

**Comment by orta** [comment]
The metadata is weird here: https://api.artsy.net/api/v1/artwork/james-rosenquist-elbow-lake

<img width="353" alt="screen shot 2016-04-12 at 20 29 25" src="https://cloud.githubusercontent.com/assets/49038/14472892/43dd8db2-00ed-11e6-9b2d-3fc5fe02af85.png">

Could we not be handling this to `Floats` well? Which seems very reasonable

**Comment by alloy** [comment]
@sarahscott Can you set a breakpoint in that method you linked to and inspect the value?

**Comment by sarahscott** [comment]
On it

**Comment by sarahscott** [comment]
Oh... lol... the width and height on this particular artwork are switched.

**Comment by alloy** [comment]
Doh! But that fractional format is fine, then? Did you check the value in that method?

**Comment by sarahscott** [comment]
Yeah in the method it looks fine - 
![screen shot 2016-04-12 at 3 43 47 pm](https://cloud.githubusercontent.com/assets/2712962/14473308/5f8dfc40-00c5-11e6-95df-4a89a294556a.png)

**Comment by alloy** [comment]
Well, not completely, the width in inches should have been `36.25` right?

So besides switching the values in the DB, this also requires a checking with CMS/Gravity to see if they need to improve their data validation.

**Comment by sarahscott** [comment]
Aren't we changing it to 36 from 36 1/4?
https://github.com/artsy/eigen/blob/master/Artsy/Models/API_Models/Partner_Metadata/Artwork.m#L594

**Comment by sarahscott** [comment]
```artwork.width``` is 36 1/4, but ```artwork.widthInches``` returns 36.

**Comment by alloy** [comment]
The data that @orta showed is from the API, so that’s authoritative and it’s what our `Artwork` model returns as `width`.

I also spotted another issue, which is that our `Artwork` model _says_ that `width` is a `NSNumber`, but it clearly is a `NSString` https://github.com/artsy/eigen/blob/75dd8c86fdcfcf6e12101869d4dc1b6b8001fd57/Artsy/Models/API_Models/Partner_Metadata/Artwork.h#L36

**Comment by orta** [comment]
I think this is an API change, we do this in folio too, worth a look at the datatype on gravity

**Comment by sarahscott** [comment]
Garren updated the artwork metadata, so I'll close this and make a new one for the NSNumber/NSString issue.
