### ISSUE TITLE
Safari Shared Keychain Triggers App Session Ended in Analytics

### ISSUE THREAD

**Issue by orta** [artsy/eigen#1239]
![screen shot 2016-03-07 at 6 01 20 pm](https://cloud.githubusercontent.com/assets/49038/13586397/b13dc992-e48e-11e5-9cc8-a6e9df3e290c.png)

Looks like this triggers our app to "close" when the alert is being shown, probably a side-effect of some XPC buziness.

![screen shot 2016-03-07 at 6 02 12 pm](https://cloud.githubusercontent.com/assets/49038/13586401/bc3896b0-e48e-11e5-9a37-6405f1dfa9fe.png)

**Comment by alloy** [comment]
Hah, nice find!

**Comment by alloy** [comment]
Only thing I can think of right now is to check the notification dictionary to see if it includes a hint about this?

**Comment by orta** [comment]
Yeah, that was my thoughts

**Comment by alloy** [comment]
Fixed by #1307.
