### ISSUE TITLE
[Analytics] Events around onboarding

### ISSUE THREAD

**Issue by anipetrov** [artsy/eigen#1247]
## New tracks to be added

- [ ] **Initial splash slideshow**: fired when we show the initial sign up slash slideshow
- [ ] **Signup splash**: fired when we show the `sign up for a free account` splash; sign up splash can be shows if a user taps sign up on the initial splash slideshow; if the user chooses to try without account, they could later trigger the sign up splash when trying to follow an artist, favorite an artwork, tap YOU or BELL on the main nav
  * properties: {signup_context: [initial, follow artist, follow category, follow partner, favorite, you, bell]}
- [ ] **Dismiss signup splash**: fired then user taps on the top right X on the sign up splash triggered from an active trial user (trying to follow/favorite, you, bell, inquiry) AND when user clicks on back arrow from on the sign up splash triggered from initial slideshow
  * properties: {signup_context: [initial, follow artist, follow category, follow partner, favorite, you, bell]}
- [ ] **User started onboarding**: onboarding can be started if a user successfully signs up after tapping sign up on the initial splash screen or if the user chooses to try without account and later starts onboarding (and trigger this event) after chooosing to sign up after trying to follow an artist/partner/category, favorite an artwork, tap YOU or BELL on the main nav. Note that currently this is fired when a user taps on the signup button after the initial slideshow while in fact they have NOT started onboarding at that point -- [screenshot here](http://cl.ly/3j461g2J1s0g).
  * properties: {signup_context: [initial, follow artist, follow category, follow partner, favorite, you, bell]}
- [ ] **Login splash**: fired when the login splash screen is shown; the login splash can be triggered from the signup splash screen
  * properties: {signup_context: [initial, follow artist, follow category, follow partner, favorite, you, bell]}
- [ ] **Follow category**: fired every time a user successfully follows a category.
  * properties: {source_screen: [onboarding, category page, etc.]}

## Cleanup of old events

**Screens**:
- [ ] We are still firing a screen view called `sign_up_splash` when sign up splash is triggered. This is outdated and should be removed. The newly implemented screen view is called `Splash`.

- [ ] We are still firing a screen view called `signup` when the user chooses to sign up from the onboarding splash,  This is outdated and should be removed. The newly implemented screen view is called `Signup` (capitalized).

**Comment by anipetrov** [comment]
@alloy: 

Outstanding questions:
Do we trigger the same sign up splash after an inquiry? Do we show onboarding?
Do we trigger the same sign up splash in the process of auction registration? Do we show onboarding?

Let me know if you know the answers to these off the top of your head, else I will test myself later today.The answers to these might add more types of `signup_context`s for the above events. Additionally, I would like to QA onboarding steps events but realistically, I don't think I can fit it in today or tomorrow. 

Let me know if there is anything else I should add/take a look at?

**Comment by alloy** [comment]
> Do we trigger the same sign up splash if a users chooses to sign up as part of the post-inquiry flow? Do we show on boarding?

There is no sign-up at all as part of post-inquiry flow.

Maybe I’m misunderstanding where this would be triggered? When I tap the ‘contact gallery’ button I just get an email form that asks for my name + email and a message.

> Do we trigger the same sign up splash in the process of auction registration? Do we show onboarding?

Yes and no, at least that’s how we made it at some point, I will verify if this still works as expected when a mock auction opens later today.

**Comment by anipetrov** [comment]
Closing this in favor of https://github.com/artsy/eigen/issues/1459
