### ISSUE TITLE
Artsy podcast can't play

### ISSUE THREAD

**Issue by ashfurrow** [artsy/eigen#1250]
Artsy's first podcast episode is up at https://www.artsy.net/article/artsy-editorial-the-artsy-podcast-no-1-instagram-vs-the-world but when loaded in Eigen's "Mag" tab, the audio player doesn't work; it gives the error message "origin is not allowed by access-control-allow-origin", but it works in Safari.

![img_4855](https://cloud.githubusercontent.com/assets/498212/13691671/b618b748-e708-11e5-84bf-fbf7ab76daff.jpg)

They're adding a link to Soundcloud for now.

**Comment by orta** [comment]
What changed? Works for me 

![screen shot 2016-03-18 at 4 25 33 pm](https://cloud.githubusercontent.com/assets/49038/13891206/12c35642-ed26-11e5-99c9-b2b80815ae52.png)

**Comment by alloy** [comment]
They added an iframe iirc. Discussion is somewhere in Slack.
