### ISSUE TITLE
Register to Bid button doesn't work

### ISSUE THREAD

**Issue by ashfurrow** [artsy/eigen#1257]
On Native auctions views.

**Comment by orta** [comment]
Addressed in https://github.com/artsy/eigen/pull/1253

**Comment by ashfurrow** [comment]
:tada: There are a few other issues reported about the button ([doesn't change after you register for example](https://rink.hockeyapp.net/manage/apps/37020/feedback/454937)). I imagine you and Alessandra followed up on that too, though :wink:
