### ISSUE TITLE
Works for You Blank State

### ISSUE THREAD

**Issue by ashfurrow** [artsy/eigen#1259]
Should we remove the title view? Reported at https://rink.hockeyapp.net/manage/apps/37020/feedback/455965

![image_0-2](https://cloud.githubusercontent.com/assets/498212/13748697/4a22f3fe-e9d4-11e5-8f6b-e423aa30db4e.jpg)

/cc @katarinabatina @sarahscott

**Comment by alloy** [comment]
Fixed in https://github.com/artsy/eigen/pull/1255.

**Comment by katarinabatina** [comment]
Think the title helps you understand what content to expect in that section 

Sent with thumbs,
Katarina Batina 
Product Designer
Artsy.net

**Comment by alloy** [comment]
Fixed by #1255.
