### ISSUE TITLE
[Fair map] Annotations disappearing when callout is shown.

### ISSUE THREAD

**Issue by alloy** [artsy/eigen#126]
Related to #40.

![ios simulator screen shot 07 feb 2015 02 05 55](https://cloud.githubusercontent.com/assets/2320/6090112/a7e78960-ae6f-11e4-8f32-ac2c00980341.png)

**Comment by alloy** [comment]
@katarinabatina Should this be fixed for the fair milestone?

**Comment by alloy** [comment]
@katarinabatina Oops, I didn’t mean to still submit that comment, I’m just assuming that these details should be fixed for the fair milestone.

**Comment by katarinabatina** [comment]
Yes this should make it into the milestone thanks for double checking! 

Katarina
