### ISSUE TITLE
Works for You labels are cut off

### ISSUE THREAD

**Issue by ashfurrow** [artsy/eigen#1261]
Not truncating with ellipsis or wrapping. Reported at https://rink.hockeyapp.net/manage/apps/37020/feedback/455893

![image_0-3](https://cloud.githubusercontent.com/assets/498212/13748768/99f198f4-e9d4-11e5-94ac-1289a57437a8.jpg)

/cc @sarahscott

**Comment by alloy** [comment]
As requested by @katarinabatina, this should be truncated with ellipsis: https://github.com/artsy/eigen/issues/1230#issuecomment-195448152

**Comment by alloy** [comment]
Fixed by #1255.
