### ISSUE TITLE
How bidding works button / wrong auction

### ISSUE THREAD

**Issue by ashfurrow** [artsy/eigen#1262]
> 'How bidding works' link from overview of an upcoming auction takes me to a different view than from a past auction.

Reported from https://rink.hockeyapp.net/manage/apps/37020/feedback/454937

I think this may be a limitation of a hard-coded (ish) conditions of sales problem on the server side. I'll need to follow up.

**Comment by ashfurrow** [comment]
This appears to be a problem on martsy, not the native auction views. I checked microgravity and there doesn't appear to be any open issues, but I'm not even sure this is a bug or intended behaviour 🤔 

Pull in @bhoggard and see if these two "how bidding works" martsy views should be the same.

![asset png](https://cloud.githubusercontent.com/assets/498212/13786744/61238dc6-eaaf-11e5-937a-6392d4ae23ce.jpeg)

![image_0-6](https://cloud.githubusercontent.com/assets/498212/13786745/61291b6a-eaaf-11e5-8fa2-ac0213e198fa.jpg)

**Comment by ashfurrow** [comment]
@craigspaeth it seems to go to https://www.artsy.net/auction-info or https://www.artsy.net/how-auctions-work depending on the state of the auction. Is this something we should take a look at?

**Comment by alloy** [comment]
@ashfurrow @bhoggard @craigspaeth bump

**Comment by craigspaeth** [comment]
Yeah it appears as if the code reflects different links for different states (not sure if that's intentional, doubt it)

![image](https://cloud.githubusercontent.com/assets/555859/14089432/e24957d4-f502-11e5-93bc-0d571241f6d4.png)

Which url do we want to use across the board?

**Comment by ashfurrow** [comment]
Thanks for looking into that Craig. That's a good question, @katarinabatina should the "How Bidding Works" button always point to the same location? Currently it switches between `/how-auctions-work` and `/auction-info` depending on wether or not the auction is upcoming or closed.

**Comment by devangt** [comment]
Closing based on Triage
