### ISSUE TITLE
Misplaced Info Button

### ISSUE THREAD

**Issue by ashfurrow** [artsy/eigen#1263]
On Auctions native views. Reported at https://rink.hockeyapp.net/manage/apps/37020/feedback/454937

Example:

![image_0-4](https://cloud.githubusercontent.com/assets/498212/13749403/94996c12-e9d7-11e5-93f2-f6a69a331d33.jpg)

**Comment by orta** [comment]
Will be fixed in https://github.com/artsy/Artsy-UILabels/pull/19 by https://github.com/artsy/Artsy-UILabels/pull/19#discussion_r55339406

**Comment by ashfurrow** [comment]
https://github.com/artsy/Artsy-UILabels/pull/19 is merged, going to chat with @orta about next steps.

**Comment by orta** [comment]
We need labels, fonts and colors all updated before we can introduce this, it's  mega PR I may get done today.

**Comment by ashfurrow** [comment]
OK cool, let me know where I can help :bow:

**Comment by alloy** [comment]
This does not appear to have been fixed, at least not in a satisfactory way.

![asset png-2](https://cloud.githubusercontent.com/assets/2320/13901130/3805e1d2-ee1a-11e5-9666-80421ae76259.jpeg)

**Comment by ashfurrow** [comment]
Strange! I'll take a look – @orta had done some research on this, he might have a quick insight.

**Comment by orta** [comment]
I think this is cause, yes, we're now setting the margins better for most use cases. However, this case isn't like the most, this label will need it's `maxLayoutThingy` being set manually as it's still smaller. If I recall, you can look at it in reveal and see it breaking it's bounds.

**Comment by ashfurrow** [comment]
Cool, I'll create a failing snapshot test case first and then do a fix to make sure this doesn't happen again. Might be able to get a good blog post out of it :wink:
