### ISSUE TITLE
[WorksForYou] Add a max height for single artworks

### ISSUE THREAD

**Issue by sarahscott** [artsy/eigen#1266]
Such that they fit in-screen

**Comment by alloy** [comment]
Would these get horizontally centered?

**Comment by sarahscott** [comment]
@katarinabatina ideally should single images be horizontally centered on iPhone and left-aligned on iPad, or centered on both?

![](https://cloud.githubusercontent.com/assets/6482926/13061215/9f36ac4a-d404-11e5-844b-082b323ad7d9.png)

**Comment by katarinabatina** [comment]
Ideally yes

Sent with thumbs,
Katarina Batina 
Product Designer
Artsy.net

**Comment by orta** [comment]
Fixed by #1282

**Comment by alloy** [comment]
Which has now been merged.
