### ISSUE TITLE
[WorksForYou] Fix extra padding in masonry grid

### ISSUE THREAD

**Issue by sarahscott** [artsy/eigen#1267]
![simulator screen shot mar 14 2016 5 13 09 pm](https://cloud.githubusercontent.com/assets/2712962/13760236/765411ae-ea08-11e5-91d8-c4ef8ad3e7d5.png)

**Comment by katarinabatina** [comment]
![image](https://cloud.githubusercontent.com/assets/6482926/13789945/9e7fee50-eabc-11e5-86f4-b283be621ec1.png)
