### ISSUE TITLE
[Fair map] Some annotations get a small chevron in callout

### ISSUE THREAD

**Issue by alloy** [artsy/eigen#127]
![fair artist - callout small chevron](https://cloud.githubusercontent.com/assets/2320/6090117/f6945ade-ae6f-11e4-9849-1c5a8ebeb167.png)

**Comment by alloy** [comment]
@katarinabatina @orta

So this happens because the ‘partner name’ is too long to fit, in which case the chevron is deemed less important and becomes smaller. As can be seen when making the ‘partner name’ text shorter:

![ios simulator screen shot 09 feb 2015 17 54 44](https://cloud.githubusercontent.com/assets/2320/6110912/4cf80a3a-b085-11e4-8d63-28ec03f77c0b.png)

Unfortunately this is no guarantee that the ‘partner name’ will actually fit, which, as can be seen in the origin example, leads to a truncated label _and_ a small chevron.

Unless this behaviour should stay as-is, I think the prettiest option would be to resize the callout vertically to fit the content and keep the chevron always the same size.

**Comment by katarinabatina** [comment]
I think a good starting place would be to decrease the text size in both fields and increase the available space to the partner name. Is there a way to invoke truncation without making the chevron small (as shown in the second example below 
![image](https://cloud.githubusercontent.com/assets/6482926/6113334/9e32ab06-b064-11e4-8685-77b4442807d1.png)

**Comment by katarinabatina** [comment]
I think there is also an issue with the way the data we're getting is structured. It would be great if we could eliminate the additional data coming in for the second line "booth number" and "section/pier"

**Comment by alloy** [comment]
@katarinabatina Great points :+1:

I’ll look into that extra data and never shrinking the chevron is definitely doable.

**Comment by alloy** [comment]
This is what I ended up with based on your feedback:

![ios simulator screen shot 11 feb 2015 19 01 46](https://cloud.githubusercontent.com/assets/2320/6152838/8c72198e-b220-11e4-8cef-484f9eddb741.png)

![ios simulator screen shot 11 feb 2015 19 02 09](https://cloud.githubusercontent.com/assets/2320/6152840/8ec25708-b220-11e4-9cc0-9c2623ad7128.png)

Obviously there are still cases where there isn’t enough room, but it’s probably best if we check the data once the 2015 data set is available? Can I track the availability progress on that somewhere or how should I progress on that point?

**Comment by orta** [comment]
can you try run this on a phone  and get a sense of whether that subtitle fonts is too hard to read>

re:availability, that's pretty adhoc, we might only end up getting most of it a week or two before the fair.

**Comment by alloy** [comment]
> can you try run this on a phone and get a sense of whether that subtitle fonts is too hard to read>

Aye, good point, will do that :+1:

**Comment by alloy** [comment]
@orta It’s very crisp and readable to me and Dionne (who has less good eyes than I do), so I’d say it’s good.

**Comment by orta** [comment]
thanks
