### ISSUE TITLE
[WorksForYou] Only show for-sale artworks.

### ISSUE THREAD

**Issue by alloy** [artsy/eigen#1271]
With regards to the sale works, Gravity will change the way they generate bundles (only with for-sale works), but as this VC does not use that endpoint, we should simply add the for-sale only query parameter.

https://github.com/artsy/gravity/blob/be08dee7d13ead9e66f75e022ccfe70fb4136402/app/api/v1/me_notifications_endpoint.rb#L30

**Comment by sarahscott** [comment]
Fixed in #1275
