### ISSUE TITLE
submit new app description, app title, and keywords to itunes

### ISSUE THREAD

**Issue by katarinabatina** [artsy/eigen#1272]
for 2.4.1

**Comment by alloy** [comment]
Are all the localisations being worked on yet?

**Comment by katarinabatina** [comment]
@alloy according to @orta we don't have to have them localized

**Comment by katarinabatina** [comment]
## Title 

Artsy –– Collect and Bid on Fine Art & Design

## Keywords
gallery,fairs,exhibition,collector,museum,auction,buy,artwork,artist,armory,bid,interior,banksy,fair

## Description
Artsy is the world’s top resource for buying, collecting and learning about fine art. Use Artsy to discover and buy art (over 250,000 artworks for sale) from the the top galleries and auction houses. Find the perfect artwork, contact art galleries, and bid on live auctions on the go.

DISCOVER ALL THE WORLD’S ART
Artsy works with over 4,000 galleries, 600 museums and institutions, and 60 art fairs to bring you over 400,000 works of art spanning the entire art world. 

BUY WORKS FROM THE TOP ARTISTS AND GALLERIES
With Artsy, you instantly receive unprecedented access to for-sale artworks from over 4,000 of the world’s top galleries, including available pricing information. Find an artwork you’re interested in and inquire with any gallery directly from the app, wherever you are. On Artsy, the average distance between collectors and the galleries they work with is 2,700 mi / 4,345 km!

BID ON WORKS FROM THE TOP AUCTION HOUSES
Artsy’s partners include world-renowned auction houses like Sotheby’s and Christie’s, as well as many charitable institutions. Bid on works by artists like Banksy, Warhol, Picasso, Koons, Hirst, Sherman, Calder, Lichtenstein, and many more. Artsy allows you to bid with confidence, get real time updates about your bid status including outbid notifications, and alerts when works by artists you follow are up for auction.

FOLLOW ARTISTS FOR PERSONALIZED RECOMMENDATIONS
Don’t miss out on new available works by artists you would like to collect. Follow artists to get real time updates when new artworks become available at an auction, art fair, or new gallery show.

SPEAK WITH A PERSONAL ART ADVISOR
Artsy’s art advisors and specialists have decades of experience working with top galleries and auction houses like Christie's and Sotheby’s. Whether you’re a beginner or a seasoned collector, our team is ready to help. We offer this as a complementary service for art collectors.

**Comment by orta** [comment]
Don't have to doesn't mean shouldn't :P

**Comment by katarinabatina** [comment]
@orta I don't disagree, I just want to get the change out there, I can schedule translations with some teammates internally I'm sure. I want to know more about how we organized that last time.

**Comment by orta** [comment]
@dblock did you organize the translations in Eigen's app store pages? No-one has a clue how we got them translated :D

**Comment by alloy** [comment]
This is done, moving further discussion about localization to #1372.
