### ISSUE TITLE
[Fair map] Annotations are clipped on iOS 8

### ISSUE THREAD

**Issue by alloy** [artsy/eigen#128]
![fair artist - ios 8 - clipped annotation](https://cloud.githubusercontent.com/assets/2320/6090146/68785fe2-ae70-11e4-981c-44ae6b3b0146.png)

**Comment by orta** [comment]
nice spot

**Comment by alloy** [comment]
This appears to only be a problem on the simulator, I was unable to reproduce it on a device. I suspect it has to do with me having a non-retina mac. Thus, closing this.
