### ISSUE TITLE
x button misplaced on modals in auction view

### ISSUE THREAD

**Issue by katarinabatina** [artsy/eigen#1284]
![image](https://cloud.githubusercontent.com/assets/6482926/13826819/d036f80c-eb8f-11e5-910c-97861ced0dca.png)

![image](https://cloud.githubusercontent.com/assets/6482926/13826867/02e248a6-eb90-11e5-8cba-e45685150d1c.png)

**Comment by katarinabatina** [comment]
@ashfurrow is this a relatively small fix?

**Comment by ashfurrow** [comment]
It's just the X button? Should be small.

**Comment by orta** [comment]
This will be tricky, you've got to manipulate the rightBarItems on a toolbar

**Comment by katarinabatina** [comment]
@ashfurrow @orta is this a global element that applies to the Refine modal as well?

**Comment by orta** [comment]
yep, and in the auction live interface

**Comment by ashfurrow** [comment]
Ah I see. Hmm.
