### ISSUE TITLE
[Tests] Stop any tests from hitting the external network

### ISSUE THREAD

**Issue by alloy** [artsy/eigen#1287]
In short, the test suite should be able to run without a network connection being present.

---

Currently this ARWebViewCacheHost one slips through the cracks, presumably because the webview runs in an external process: https://github.com/artsy/eigen/blob/52df3bdce5427136a59f354471d952d8fcd173c0/Artsy_Tests/App_Tests/ARWebViewCacheHostSpec.m#L20-L28

**Comment by alloy** [comment]
I had a quick look at how we could automate this enforcement.

I tried to use `sandbox_init`, but that didn’t work in my naive testing, it’s also deprecated, and I think it won’t work in cases like the webview where the networking is done in an external process.

So the only real way is probably to have a kernel extension that blocks all outgoing networking for a given process, which hopefully could be done on the simulator process? Need to test that with e.g. LittleSnitch.

**Comment by orta** [comment]
Did you look if there are central functions on NSURLSession that we could swizzle?

**Comment by alloy** [comment]
That won't help with things like `WKWebView`.

**Comment by orta** [comment]
I think testing for out of process is probably going to be more effort than it's worth, better to grab these as one offs, I work offline a lot, surprised this fails
