### ISSUE TITLE
registration state does not update after completing registration in martsy

### ISSUE THREAD

**Issue by katarinabatina** [artsy/eigen#1288]
in an ongoing auction when i tap the register button i get sent to martsy, have a successful registration, but when I get kicked back to eigen on the page I don't see the approved to bid, I still see the registration button.

On an auction that hasn't opened yet, when I tap register button (and am already registered) I get to martsy, see a spinner, come back to eigen. I again, have successfully registered however again, I don't get the updated approved to bid.

**Comment by katarinabatina** [comment]
@ashfurrow or @orta consider this top priority today as we were looking to ship this on Monday.

**Comment by alloy** [comment]
Something here must not work right anymore:

* https://github.com/artsy/eigen/blob/adaa5d857c16df7b411db268d7af9a7d53dc3774/Artsy/View_Controllers/Auction_Results/ARAuctionWebViewController.m#L141-L151

* https://github.com/artsy/eigen/blob/adaa5d857c16df7b411db268d7af9a7d53dc3774/Artsy/View_Controllers/Auction_Results/ARAuctionWebViewController.m#L156-L163

**Comment by ashfurrow** [comment]
Looking into it.

**Comment by ashfurrow** [comment]
I've reproduced this, even without martsy. Having a trial account, hitting register, and logging in with existing credentials doesn't change the register button. And tapping it takes me briefly to martsy before immediately popping back to this view, where the register button _still_ doesn't change.

**Comment by ashfurrow** [comment]
@alloy those are the non-native auctions views, right? The bug seems to be that no one ever changes the `registrationStatus` property on `AuctionTitleView`, which would cause it to re-setup its views (and do away with the register button). Continuing to look into it...

**Comment by alloy** [comment]
Yeah indeed. The native views should listen for that notification sent by the webview and then reload such views as the registration button.

**Comment by ashfurrow** [comment]
Awesome, thanks @alloy!

**Comment by ashfurrow** [comment]
OK, I believe I have a fix. Writing tests now, will push shortly.
