### ISSUE TITLE
upgrade gene pages

### ISSUE THREAD

**Issue by katarinabatina** [artsy/eigen#1292]
##Guide Story 

- [ ] display for sale works only
- [ ] add refine UI
- [ ] remove share/heart buttons and gene description 

current: 

![img_7121](https://cloud.githubusercontent.com/assets/6482926/13855758/4aff4522-ec48-11e5-915a-673cab6f2b30.PNG)

update:
![image](https://cloud.githubusercontent.com/assets/6482926/13855514/36f47076-ec47-11e5-82d6-cae69e601923.png)

this "feels" like a smaller item, wondering if it can fit in the next sprint thoughts @alloy

**Comment by alloy** [comment]
What’s the difference with #1293?

**Comment by katarinabatina** [comment]
dupe..dunno how that happened
