### ISSUE TITLE
[Gene] Upgrade

### ISSUE THREAD

**Issue by katarinabatina** [artsy/eigen#1293]
Update Gene VC

![image](https://cloud.githubusercontent.com/assets/6482926/14026408/22139952-f1c9-11e5-882a-6fe8d90103fb.png)
![image](https://cloud.githubusercontent.com/assets/6482926/14029198/2bcf76ba-f1d7-11e5-8a3d-69243f0245f5.png)

![image](https://cloud.githubusercontent.com/assets/6482926/14026417/2e8d194c-f1c9-11e5-81ff-fad45edf9fd5.png)

**Comment by alloy** [comment]
Possibly, yeah. Is that ‘FOLLOW’ button always visible if you don’t follow a category yet, or does it scroll away and is that the second screen?

**Comment by katarinabatina** [comment]
@alloy it scrolls away to the second screen

**Comment by orta** [comment]
Yeah, should be the same model as the native auctionVC. 

If this is being done in native, it might be worth trying to make a version of the `ARInifiniteScrollVC` that can be passed a configuration object that represents the feed of artworks, and the refine settings - there's a lot of hardcoding in the current refine settings vc for auctions that can be un-done.

**Comment by alloy** [comment]
Ok, yeah, if it’s all the same as existing views for native auctions then it should be fairly simple :+1:

**Comment by orta** [comment]
It'll be tricky, but I think Sarah can pull it off ( gotta turn pretty concrete classes `AuctionRefineViewController` `AuctionRefineSettings` into abstracts )

**Comment by sarahscott** [comment]
Fancy swift time 

![](http://media0.giphy.com/media/ztvX6SzPUmOBi/giphy.gif)

**Comment by katarinabatina** [comment]
^^ haaaaa, going to devote any spare time today to developing more detailed mocks

**Comment by katarinabatina** [comment]
@sarahscott updated comps with more detail up top

**Comment by sarahscott** [comment]
Q: What happens to works if they're for sale but don't have prices published? Will changing the slider values hide them?

**Comment by katarinabatina** [comment]
@briansw to @sarahscott question above is this what currently happens on /collect?

**Comment by briansw** [comment]
@katarina @sarahscott on /collect works for sale without a price stay in the flow as they normally would. When the user adjusts the price slider, they move to the end of the results.

**Comment by katarinabatina** [comment]
@sarahscott @alloy as I mentioned in the meeting as a V1 I think it would be sufficient for us to just add the refine UI to the existing view without any of the additional changes.

**Comment by alloy** [comment]
@katarinabatina @sarahscott …that is, assuming that the filtering is a drop-in addition to the existing ‘embedded models VC’. If it’s not that easy, then we should still defer it to the next sprint.

**Comment by orta** [comment]
It's not, it requires switching the view controller entirely

**Comment by alloy** [comment]
These filters need to be routable for the new Home view. Specifically, we should be able to set a budget, for e.g.:

> Minimalism under $10,000 => Minimalism gene page with price filter set to 0-10,000

**Comment by orta** [comment]
Places where this could get tricksy:

So the way this stuff works in the auctionsVC is there's a childVC that is the arembeddedVC that can have a header view (for above artworks) and a sticky header view (the refine bar that sticks over)

* The switch view in the header is a new concept, the header would exist _inside_ a collection view reused view, I'm not sure what the behaviour would look like when you scroll up/down, and how well it will handle all the the resizing happening inside the "header" - could end up with a lot of "layoutIfNeeded" kind of things in there

* I'm not 100% on how you can pass data between the refine overlay and the routing, but probably can generate a data model - think there's swift generics in there so be wary

* There is still an ongoing bug around having the first tap on the "refine" button tapping through to artworks once you've scrolled

* Refine view will need to handle scrolling internally, think right now it is a stack v-aligned center

**Comment by alloy** [comment]
If we end up punting on this for the v1 of the home view, then it might be worth considering redoing it in React Native instead.

**Comment by orta** [comment]
WIP over on emission: https://github.com/artsy/emission/pull/305

**Comment by katarinabatina** [comment]
@orta ok to close? The refine component should ship in our next build yea?

**Comment by orta** [comment]
Yep
