### ISSUE TITLE
Add dude view to portrait

### ISSUE THREAD

**Issue by dblock** [artsy/eigen#1294]
@orta says that the reason why we don't have the dude in the vertical view is because it didn't fit on an iPhone 4. Times have changed. What about showing the dude in the view on portrait too?

![screen shot 2016-03-17 at 4 32 21 pm](https://cloud.githubusercontent.com/assets/542335/13860358/42732598-ec5e-11e5-9520-edee760959c5.png)

I am happy to PR this. What do you think @katarinabatina?

**Comment by robertlenne** [comment]
I'm happy with this FWIW. Is this implemented and testable? ( I could see that there might be issues with different sizes,)

**Comment by katarinabatina** [comment]
If you can deploy a beta to test flight so we can have a quick look tha'd be great

**Comment by orta** [comment]
I faked it here, but it's not much effort, can pick it up between a tea and make a feature flag if someone doesn't get around to it inbetween features

**Comment by katarinabatina** [comment]
if it takes more than just dB's time I'd prefer we left it alone.

[A.] Katarina Batina
Product Designer

Artsy <http://artsy.net/>


katarina@artsymail.com

                @katarinabatina <https://twitter.com/katarinabatina>

253 225 5812

**Comment by robertlenne** [comment]
Annoyingly, this is an (irrational) investor request which we would benefit from doing. If QAing is a procedure maybe we can just ship it since the important part is getting it in.

**Comment by orta** [comment]
Looks like dB is on it :+1:

**Comment by dblock** [comment]
https://github.com/artsy/eigen/pull/1295 is working code.

![dude](https://cloud.githubusercontent.com/assets/542335/13862741/7803bfee-ec6b-11e5-8e5c-42d52b2b1c9c.gif)

**Comment by alloy** [comment]
Those walls no longer appear to line up correctly after the rotation.

![room](https://cloud.githubusercontent.com/assets/2320/13863027/2348b5f0-ec97-11e5-9ac4-7aad7ec1ed94.jpg)

**Comment by dblock** [comment]
@alloy That's not new, @orta said he'll look into it.

**Comment by alloy** [comment]
Ah, worked fine on my device, so must have to do with device size. Cool :+1:
