### ISSUE TITLE
More info goes to empy screen

### ISSUE THREAD

**Issue by robertlenne** [artsy/eigen#130]
eg. https://www.artsy.net/artwork/thomas-jeppe-vista-vertical-m

Could it be because we don't have the capability to list exhibition history?

**Comment by alloy** [comment]
I _think_ this is about e.g. “More Works in Show”, which works nowadays.

![ios simulator screen shot 29 jun 2015 21 18 13](https://cloud.githubusercontent.com/assets/2320/8416214/77cfc35a-1ea4-11e5-95e8-09ee3a44ddf4.png)

**Comment by alloy** [comment]
Deleted previous comment, this is definitely still an issue, I was totally looking in the wrong place 😒

**Comment by orta** [comment]
Yeah, I've seen this recently

**Comment by alloy** [comment]
> Could it be because we don't have the capability to list exhibition history?

 Yup, that’s the issue.

Looking at [the code](https://github.com/artsy/eigen/blob/master/Artsy/View_Controllers/Artwork/ARArtworkInfoViewController.m.), it seems like a very uninteresting view controller. While trying to find some examples of what it looks like when it _does_ work I found these:

![ios simulator screen shot 23 jul 2015 14 40 31](https://cloud.githubusercontent.com/assets/2320/8850551/3b963ec0-3149-11e5-8ddf-970a187b05e7.png)
![ios simulator screen shot 23 jul 2015 14 40 42](https://cloud.githubusercontent.com/assets/2320/8850553/3bb9aba8-3149-11e5-9ec4-3a77f7898ce9.png)
![ios simulator screen shot 23 jul 2015 14 41 03](https://cloud.githubusercontent.com/assets/2320/8850552/3bb6f6c4-3149-11e5-9afc-dd43e45d97a6.png)

@orta I am unconvinced this needs to be a native view at all, but if that’s the preference then adding the missing field shouldn’t take much time.

**Comment by alloy** [comment]
Fixed by #730.
