### ISSUE TITLE
[WorksForYou] Fix sizing issue for embedded models vc on iPad Pro

### ISSUE THREAD

**Issue by sarahscott** [artsy/eigen#1302]
On iPad Pro, the embedded models view controller doesn't size properly:

![simulator screen shot mar 18 2016 11 04 28 am](https://cloud.githubusercontent.com/assets/2712962/13881892/4fff3760-ecf9-11e5-8d6e-bc1a3710a960.png)

On a happier note, single artworks are :+1: 

![simulator screen shot mar 18 2016 11 06 01 am](https://cloud.githubusercontent.com/assets/2712962/13881917/6842c440-ecf9-11e5-8dc3-5cd977cffcad.png)

**Comment by alloy** [comment]
Does it resize properly in other parts of the app? And by resize, do you mean that this is only an issue after rotation?

**Comment by sarahscott** [comment]
Ah I meant size instead of resize.

**Comment by sarahscott** [comment]
I think elsewhere in the app, it's similar. I don't know that it's necessarily *wrong* but it doesn't stretch to the sides the way it does on smaller iPads. 

![simulator screen shot mar 18 2016 11 19 10 am](https://cloud.githubusercontent.com/assets/2712962/13882305/521431e8-ecfb-11e5-8be0-0f3c56217eb9.png)


![simulator screen shot mar 18 2016 11 19 20 am](https://cloud.githubusercontent.com/assets/2712962/13882311/5573c380-ecfb-11e5-99e6-9c6532c01784.png)

**Comment by sarahscott** [comment]
Closing this
