### ISSUE TITLE
Feedback 'I want to see my analytics logs, so I'm sending...'

### ISSUE THREAD

**Issue by artsyit** [artsy/eigen#1304]
### Message from 56ec4863139b21562100026e sent on 2016-03-18 18:30:16 UTC###

> I want to see my analytics logs, so I'm sending myself feedback to see them - orta

### Link to HockeyApp ###

* [https://rink.hockeyapp.net/manage/apps/37020/feedback/465705](https://rink.hockeyapp.net/manage/apps/37020/feedback/465705)

**Comment by orta** [comment]
This should auto-close in hockey too, I think.

**Comment by alloy** [comment]
Noice! Do we need to do anything special to make feedback show up here?
