### ISSUE TITLE
Live Auctions Logo Questions

### ISSUE THREAD

**Issue by orta** [artsy/eigen#1305]
Looking at this:

![screen shot 2016-03-18 at 3 27 15 pm](https://cloud.githubusercontent.com/assets/49038/13889622/f5e213c2-ed1d-11e5-9c5e-12606995310e.png)

We don't have any images that would work in the space where it says Christies ATM. Should this be a small display name in garamond, or would it work better as the square profile image we use in the sale information VC?

**Comment by katarinabatina** [comment]
@orta as you can (hopefully) see in the spec that's not their logo it's just type, at size 17px I think. It's just the partner name only.

**Comment by orta** [comment]
:+1:
