### ISSUE TITLE
Feedback 'Hero: unreadable and cut-off subtitle.'

### ISSUE THREAD

**Issue by artsyit** [artsy/eigen#1311]
### Message from Eloy Durán sent on 2016-03-19 19:44:33 UTC###

> Hero: unreadable and cut-off subtitle.

### Link to HockeyApp ###

* [https://rink.hockeyapp.net/manage/apps/37020/feedback/466519](https://rink.hockeyapp.net/manage/apps/37020/feedback/466519)

**Comment by alloy** [comment]
<img width="1280" alt="screen shot 2016-03-22 at 18 04 45" src="https://cloud.githubusercontent.com/assets/2320/13960440/afdf6a94-f058-11e5-8ff2-17e1fa6b833e.png">

**Comment by alloy** [comment]
So we only show 1 line of text max.

@orta Is this intentional design that you know of, or should that label in reality grow in height?

**Comment by orta** [comment]
It should grow to two lines - it's got a max layout width of `-40` which sounds bad to me ( use Reveal)

**Comment by orta** [comment]
Likely being added to a view with a 0,0,0,0 frame - [making this have wrong logic](https://github.com/artsy/Artsy-UILabels/blob/master/Pod/Classes/Artsy%2BUILabels.m#L70-L72), perhaps answer is to check for Zero rect in the UILabels thing

**Comment by orta** [comment]
Or have the label set maxBlahBlah once it's got a known width after `updateConstraints` is done

**Comment by alloy** [comment]
Yeah, good call, thanks :ok_hand:

**Comment by alloy** [comment]
Ok, that fix for Artsy-UILabels was causing Eigen’s test suite to hang, and I didn’t want to get sucked into a rabbit hole, so I opted to just revert [the change that broke these hero units](https://github.com/artsy/Artsy-UILabels/pull/19) in the hero unit view.
