### ISSUE TITLE
WFU ipad layout not working when rotated, layout structure doesn't seem right in general

### ISSUE THREAD

**Issue by katarinabatina** [artsy/eigen#1312]
Looking at the iPad it seems like every new batch of works adheres to a different set of rules. Sometimes two works are centered, sometimes left aligned. When rotating the iPad the works don't fill in newly available columns. 

If  we were to use our standard masonry view for each of these artwork groupings it would mean that a single work wouldn't take up so much of the viewport as it would be fixed to a 2-column width. The scale shift between an artist that has one artwork versus another that has two is so large I easily scroll by some of the batches of work. 

![image](https://cloud.githubusercontent.com/assets/6482926/13900965/9657f594-ede9-11e5-9454-7dbf278fc441.png)

**Comment by sarahscott** [comment]
This PR was interesting - 
https://github.com/artsy/eigen/pull/1232/files#diff-52ea9874f40bb71942d60f7be0942a69R86

This seemed to solve rotation problems app-wide, but if they're still occurring, it warrants another look. Basically, we found that anything that should happen during or after a rotation needs to occur inside this animateAlongsideTransition block. I used it in the NotificationItemVC for single artworks as well: https://github.com/artsy/eigen/blob/master/Artsy/View_Controllers/WorksForYou/ARWorksForYouNotificationItemViewController.m#L190.

Perhaps this is where we should look?

**Comment by alloy** [comment]
Ok, from some debugging I’ve been able to determine that [that location](https://github.com/artsy/eigen/pull/1232/files#diff-52ea9874f40bb71942d60f7be0942a69R86) you mention is not being called at all. Why this is the case is not clear to me yet.

**Comment by orta** [comment]
could something not be in the right view container hierarchy?
