### ISSUE TITLE
Profile VC needs to redirect to native auctions

### ISSUE THREAD

**Issue by ashfurrow** [artsy/eigen#1314]
Hero units with profile IDs like `/rago` are currently showing the generic Profile view controller. We have [an existing solution](https://github.com/artsy/eigen/blob/c1d6fdbb75e8601092be92c6f99937d806bcfc49/Artsy/View_Controllers/Fair/ARProfileViewController.m#L59-L79) for fairs, something similar would work here and, given time constraints, feels like the right approach. See slack for discussion: https://artsy.slack.com/archives/auctions-dev/p1458417933000172

However, I don't want the Profile VC to have its own miniature router, so we may want to think of a longer-term solution.

**Comment by alloy** [comment]
What about just removing the use of vanity URLs from Hero units?

_Disclaimer: I’m from the ‘:fire: the vanity URL’ camp._

**Comment by alloy** [comment]
To be honest, as long as we ​_do_​ have vanity URLs (_and even if we decide to stop introducing them, we can’t just break them, as the URLs are out there_), we should have a better solution. I think we need to do a `HEAD` on all `/root` routes to see if they respond with `3xx` before actually routing the view :disappointed:

**Comment by ashfurrow** [comment]
Yeah, agreed. 

Also, my proposed solution won't work, as the profile lookup for sales comes back as a 404.

**Comment by devangt** [comment]
cc @ashfurrow please remind us to do this for upcoming auctions

**Comment by ashfurrow** [comment]
@devangt we should do this for the upcoming auctions.

**Comment by katarinabatina** [comment]
@ashfurrow @orta should this be in QA now or? let me know if there's anything more actionable.

**Comment by alloy** [comment]
@katarinabatina It is not in the current version. There is preliminary work done by @orta here https://github.com/artsy/eigen/pull/1691.

**Comment by ashfurrow** [comment]
@katarinabatina important to note that the stop-gap workaround for this is not linking to the vanity URLs on the eigen home screen, but their full URLs instead.

**Comment by ashfurrow** [comment]
@orta this was fixed by our work Live, right?

**Comment by katarinabatina** [comment]
I've not noticed any problems on this for a while, going to close.

**Comment by orta** [comment]
Yep - fixed by https://github.com/artsy/eigen/blob/master/Artsy/View_Controllers/ARMutableLinkViewController.m
