### ISSUE TITLE
Feedback 'Hey there I have some feedback: Additional work...'

### ISSUE THREAD

**Issue by artsyit** [artsy/eigen#1316]
### Message from katarina batina sent on 2016-03-20 15:05:09 UTC###

> Hey there
> I have some feedback:
> 
> Additional works under works tab won't load, artist and category tabs won't load (spinner is frozen)

### Link to HockeyApp ###

* [https://rink.hockeyapp.net/manage/apps/37020/feedback/466947](https://rink.hockeyapp.net/manage/apps/37020/feedback/466947)

**Comment by alloy** [comment]
@katarinabatina Could it be that you were testing against staging? On staging I’m not seeing any of my saves show up at the moment.

That still shouldn’t leave you with a spinner, though, but that might have been a fluke, because I’m getting the expected zero state.

**Comment by katarinabatina** [comment]
@alloy possibly but now I can't quite remember...would be cool if we could somehow let Hockey know if the user was in staging or not.

**Comment by alloy** [comment]
Ok, adding it to the ‘Needs QA’ pipeline to remind some last on device checking.

**Comment by alloy** [comment]
Have not been able to reproduce this. Please re-open if it happens again.
