### ISSUE TITLE
Guide: Onboarding Update

### ISSUE THREAD

**Issue by katarinabatina** [artsy/eigen#1318]
##Guide: Onboarding Redesign

![image](https://cloud.githubusercontent.com/assets/6482926/13940727/7a2dacc8-efb6-11e5-82fc-6a79b77f497b.png)

**Comment by alloy** [comment]
@mennenia You might want to start by printing all these designs and start identifying questions on how to implement certain elements etc.

**Comment by mennenia** [comment]
Awesome, sounds great.

**Comment by katarinabatina** [comment]
@mennenia @alloy one piece missing here is how search and the Recommendations Module connect. Will add after my morning meeting. @mennenia if you download the Flinto app on your phone (it's free) I can also send you a prototype.

**Comment by mennenia** [comment]
I'm going to close this issue as we now have #1363 and there's no concrete implementation task in here..
