### ISSUE TITLE
HeaderModule: Onboarding Update

### ISSUE THREAD

**Issue by katarinabatina** [artsy/eigen#1319]
![image](https://cloud.githubusercontent.com/assets/6482926/13907372/040d8426-eec3-11e5-8acf-fc4dc1f01d8d.png)

**Comment by alloy** [comment]
Can we change ‘search artist name’ to e.g. ‘search artist’ ?

**Comment by katarinabatina** [comment]
Sure

Sent with thumbs,
Katarina Batina 
Product Designer
Artsy.net
