### ISSUE TITLE
Too small margin on banner text

### ISSUE THREAD

**Issue by robertlenne** [artsy/eigen#132]
Headlines should probably scaled down when in portrait

![image](https://cloud.githubusercontent.com/assets/566531/6093072/e9858a18-aec7-11e4-894f-c6c800601c20.png)

**Comment by orta** [comment]
![screen shot 2015-02-07 at 12 53 58 pm](https://cloud.githubusercontent.com/assets/49038/6093093/6738a936-aec8-11e4-8abf-ffb5c65621d0.png)

These ones? ^

**Comment by robertlenne** [comment]
Yes. Minimum right margin should be roughly 150% of the left margin.

**Comment by 1aurabrown** [comment]
This text is actually an image, which is provided by the api. We can add some logic so that it will scale down if it gets too close to the right hand side.
