### ISSUE TITLE
Sign up/ Login in: Onboarding Update

### ISSUE THREAD

**Issue by katarinabatina** [artsy/eigen#1324]
![image](https://cloud.githubusercontent.com/assets/6482926/13907409/c86ea9e4-eec3-11e5-9e03-bd5c57d299ef.png)

**Comment by alloy** [comment]
‘conect’ -> ‘connect’ ;)

**Comment by mennenia** [comment]
@katarinabatina two questions:

- Where would you like the forgot password button on the login screen?
- Just confirming: we're removing the terms and conditions from the signup screen as it's now in the splash screen?

Cheers!

**Comment by katarinabatina** [comment]
Oops, my oversight, let's keep it in a similar position to where it is today, illustrated below.

![image](https://cloud.githubusercontent.com/assets/6482926/14816542/889ab2a8-0b7f-11e6-9e11-5e660a3f03a9.png)

Confirming your confirmation, we're good to remove as it will be on the splash screen 👍
