### ISSUE TITLE
Splash Screen: Onboarding Update

### ISSUE THREAD

**Issue by katarinabatina** [artsy/eigen#1325]
iPhone
![image](https://cloud.githubusercontent.com/assets/6482926/13907479/6dbd00e8-eec5-11e5-95d7-3e729f4ca9d4.png)

iPad Vertical
![image](https://cloud.githubusercontent.com/assets/6482926/13907481/752df5e4-eec5-11e5-90d2-1aad88564117.png)

iPad Horizontal
![image](https://cloud.githubusercontent.com/assets/6482926/13907482/80a9c36c-eec5-11e5-9019-608d844c258b.png)

**Comment by mennenia** [comment]
Would you like this particular background image? (if so, could you link or attach the asset)

**Comment by katarinabatina** [comment]
@mennenia here's a link to the two images! http://cl.ly/371L2P0H2g2U

**Comment by mennenia** [comment]
iPhone has a different string to iPad ("Buy" vs "Collect") 

@katarinabatina is this intentional? Or will it be one or the other (and if so which one ^_^)

**Comment by katarinabatina** [comment]
Nope an oversight! Collect is the choice! 

Sent with thumbs,
Katarina Batina 
Product Designer
Artsy.net
