### ISSUE TITLE
Search Functionality: Onboarding Update

### ISSUE THREAD

**Issue by katarinabatina** [artsy/eigen#1337]
![image](https://cloud.githubusercontent.com/assets/6482926/13938399/e1480eca-efa3-11e5-9637-b4fbbed54c3a.png)

Download the free Flinto App from the app store and grab the full prototype from here --> http://cl.ly/2p3d443b3M41

**Comment by mennenia** [comment]
Behavioural / state representation:

<img width="1130" alt="screen shot 2016-03-24 at 15 21 07" src="https://cloud.githubusercontent.com/assets/373860/14028731/65ba498e-f1d4-11e5-8c79-5cf453e013d6.png">

**Comment by mennenia** [comment]
@katarinabatina  would you have the + and tick assets for the follow status please :D?

**Comment by katarinabatina** [comment]
@mennenia here ya go let me know if you need anything else http://cl.ly/2c1z02053f19

**Comment by mennenia** [comment]
Thank youuuuu @katarinabatina! :D
