### ISSUE TITLE
Personalized Rails: Onboarding Update

### ISSUE THREAD

**Issue by katarinabatina** [artsy/eigen#1338]
As a precursor to rewriting the entire home VC, to create an aha moment for users who are personalizing their accounts through onboarding, I am curious if we can use the same form factor that we use for Current Shows to power these two rail types. 

![image](https://cloud.githubusercontent.com/assets/6482926/13940324/bd768788-efb2-11e5-9e58-75d791b871c9.png)

**Comment by alloy** [comment]
I would prefer to not take too much time away from getting to the new personalised home instead, and there are some things here I could easily see taking up more time, especially with the crossover to React.

**Comment by katarinabatina** [comment]
@alloy do you think the new home will be a full sprint of work? (based on our recent discussions)

**Comment by alloy** [comment]
It’s going to be quite some work yeah. There’s an element of sharing ‘pain’ with web by doing most of these data aggregations in the shared metaphysics API, but still hard to judge how much time that’s gonna end-up costing.

**Comment by mennenia** [comment]
Closing for now, it is referred to in the onboarding master issue
