### ISSUE TITLE
Notification Permission Request: Onboarding Update

### ISSUE THREAD

**Issue by katarinabatina** [artsy/eigen#1339]
Show dummy iOS notification permission request following onboarding, If user taps no, do not show the *real* request. If the user taps yes, then show the real request

![image](https://cloud.githubusercontent.com/assets/6482926/13940782/02621de0-efb7-11e5-9ad3-7990f8689e28.png)

**Comment by alloy** [comment]
Can’t we have our alert be a bit more helpful instead of exactly copying the default copy? Because seeing the same alert twice is a bit awkward and users might be more inclined to allow notifications if we mention that we ‘sometimes send a notification that works-for-you are available’.

**Comment by orta** [comment]
> ‘sometimes send a notification that works-for-you are available'

That string could go in Echo BTW

**Comment by mennenia** [comment]
Assigning @katarinabatina for updated copy (as agreed on in sprint planning). 

(assign me back afterwards ^_^)

**Comment by katarinabatina** [comment]
"We periodically send you updates about new works by artists you follow"

**Comment by katarinabatina** [comment]
@mennenia if a user tells us no can we surface this alert when they do finally follow an artist. For existing users who don't have push enabled can we ask them for permission next time they follow an artist but instead of a yes or no they just get a go to settings button?

**Comment by mennenia** [comment]
Go to settings button? Whatchamean?

**Comment by alloy** [comment]
@mennenia The iOS Settings app. See http://stackoverflow.com/a/4092236/95397 for how to do it.

**Comment by mennenia** [comment]
@alloy: yup aware of that, but I was confused as to where this button would appear and what we're asking them to do.

@katarinabatina, this is currently my understanding, please correct if wrong:

1) complete new user - we ask via pre-push on the home screen. 
2) new user who said no on home screen follows artist - we show the actual push notification popup
3) user who hasn't gone through new onboarding and has said no before follows artist - we show a notification popup with the option to go to settings

If this is correct then in the third case we should probably have different copy clearly stating that they need to enable push notifications themselves in the settings so they don't expect the "easy popup" if you will. To answer your question, yes we can totally give them a button to open Settings for them.

**Comment by katarinabatina** [comment]
![image](https://cloud.githubusercontent.com/assets/6482926/14720910/b25cb2e6-07d1-11e6-847e-2e86883e5d2f.png)

**Comment by katarinabatina** [comment]
@mennenia to point (2) we would not show the real modal but again the dummy.

**Comment by mennenia** [comment]
:+1: 

Also, thanks for the illustration, it clarifies everything!
