### ISSUE TITLE
get rid of rule on auction sale modal

### ISSUE THREAD

**Issue by katarinabatina** [artsy/eigen#1340]
![image](https://cloud.githubusercontent.com/assets/6482926/13958803/dcac348e-f027-11e5-8916-ea095d8cf800.png)

**Comment by ashfurrow** [comment]
Looks like the code has been written this way _on purpose_: https://github.com/artsy/eigen/blob/cba98db60b034a032fd0eec2327d4138598a34d4/Artsy/View_Controllers/ARSerifNavigationViewController.m#L106-L110 When we have > 1 view controller on our stack, we show the default line. I'm fine to remove this, just wanted to check in with @orta and @katarinabatina about the widespread implications.

**Comment by orta** [comment]
Pretty sure it was on some designs, happy with whatever :+1:
