### ISSUE TITLE
artwork metadata formatting on auction sale page seems broken 

### ISSUE THREAD

**Issue by katarinabatina** [artsy/eigen#1343]
![image](https://cloud.githubusercontent.com/assets/6482926/13960138/73ac5af8-f02d-11e5-8af5-d75281adf2c2.png)

**Comment by katarinabatina** [comment]
@ashfurrow @alloy considering we have an auction running consider this a blocker

**Comment by katarinabatina** [comment]
examples from iPad
![image](https://cloud.githubusercontent.com/assets/6482926/13960255/f62a73fc-f02d-11e5-8182-8ae91312fcf0.png)

![image](https://cloud.githubusercontent.com/assets/6482926/13960275/05a88c88-f02e-11e5-857c-32175f5f44f7.png)

**Comment by ashfurrow** [comment]
Looks like it's due to wrapping of labels – the cell heights are calculated with _just_ the image aspect ratio plus a constant for labels. Labels that grow and shrink weren't intended.
