### ISSUE TITLE
coming from a banner on ipad still sends me to force not native auction view

### ISSUE THREAD

**Issue by katarinabatina** [artsy/eigen#1344]

**Comment by orta** [comment]
What does the banner look like?

**Comment by katarinabatina** [comment]
![image](https://cloud.githubusercontent.com/assets/6482926/13961110/8705498a-f031-11e5-92c7-3b11006175d6.png)

**Comment by orta** [comment]
I think this might be the profile thing

**Comment by alloy** [comment]
The use of vanity URL was removed specifically to fix that:

<img width="492" alt="screen shot 2016-03-22 at 18 29 18" src="https://cloud.githubusercontent.com/assets/2320/13961249/1432f13e-f05c-11e5-9592-1d1a74f0b37a.png">

**Comment by ashfurrow** [comment]
Looks like this was cached on Katarina's iPad, an app relaunch fixed the problem.
