### ISSUE TITLE
Fix crash in - [NSExtension _completeRequestReturningItems:forExtensionContextWithUUID:completion:]

### ISSUE THREAD

**Issue by artsyit** [artsy/eigen#1349]
### Reason

No reason found. Full stack trace includes ???, libextension.dylib, libdispatch.dylib, libsystem_pthread.dylib.
### Link to HockeyApp
- [https://rink.hockeyapp.net/manage/apps/37029/crash_reasons/114879452](https://rink.hockeyapp.net/manage/apps/37029/crash_reasons/114879452)

**Comment by devinross** [comment]
I see the same crash!
