### ISSUE TITLE
Feedback 'Hey there I have some feedback: We are showing ...'

### ISSUE THREAD

**Issue by artsyit** [artsy/eigen#1358]
### Message from Devang Thakkar sent on 2016-03-24 17:17:44 UTC###

> Hey there
> I have some feedback:
> 
> We are showing register to bid button on past auctions and it doesn't do anything (rightfully) but should instead say online bidding closed.

### Link to HockeyApp ###

* [https://rink.hockeyapp.net/manage/apps/37029/feedback/473587](https://rink.hockeyapp.net/manage/apps/37029/feedback/473587)

**Comment by alloy** [comment]
I believe this was mentioned in a Slack as not being the case with the released version, I also can’t reproduce it.

/cc @devangt @ashfurrow

**Comment by alloy** [comment]
Ah, it was #1359.
