### ISSUE TITLE
Register to bid button on past auctions

### ISSUE THREAD

**Issue by ashfurrow** [artsy/eigen#1359]
> We are showing register to bid button on past auctions and it doesn't do anything (rightfully) but should instead say online bidding closed.

Reported at https://rink.hockeyapp.net/manage/apps/37029/feedback/473587

![image_0-7](https://cloud.githubusercontent.com/assets/498212/14025203/4b5ee074-f1c3-11e5-830a-33d684036371.jpg)

**Comment by katarinabatina** [comment]
@ashfurrow this isn't actually the case. We remove the register button and the banner says Auction closed. Do you know who reported it?

**Comment by ashfurrow** [comment]
Thanks for following up – it was @devangt. It's possibly a problem look at inconsistent data from Staging? There's no countdown on this auction screenshot, for example.

**Comment by devangt** [comment]
Ok to close. Looks like my beta got into a wired state. Not seeing in latest app

-devang




On Thu, Mar 24, 2016 at 12:03 PM -0700, "Ash Furrow" <notifications@github.com> wrote:












Thanks for following up – it was @devangt. It's possibly a problem look at inconsistent data from Staging? There's no countdown on this auction screenshot, for example.

**Comment by katarinabatina** [comment]
![image](https://cloud.githubusercontent.com/assets/6482926/14028193/ab881548-f1d1-11e5-8f6b-dfdf448c99d0.png)

yeah I am not sure what version of the app he had but it was all kinds of whack, not sure if it was test flight or what but this is a screen shot the store version that just released

**Comment by alloy** [comment]
Closing this until I hear otherwise.
