### ISSUE TITLE
Back button stuck in opacity 50

### ISSUE THREAD

**Issue by robertlenne** [artsy/eigen#136]
Pull view back and and forth using edgeswipe. Voila ----->. Button now not functional.

![image](https://cloud.githubusercontent.com/assets/566531/6093194/1fa42e4a-aeca-11e4-8f8f-772482aca257.png)

**Comment by alloy** [comment]
I’m unable to reproduce this right now, so it might be fixed since then. Can you please re-open if you are still able to reproduce this?

**Comment by robertlenne** [comment]
Can't reproduce!

**Comment by alloy** [comment]
Thanks for the update!
