### ISSUE TITLE
Fix crash in AuctionRefineViewController

### ISSUE THREAD

**Issue by sarahscott** [artsy/eigen#1360]
If an auction has 0 works, pressing 'Refine' will crash the app. I can fix this in the generalized version.

**Comment by alloy** [comment]
@ashfurrow Is this still an issue?

**Comment by ashfurrow** [comment]
Not sure, will test.

**Comment by ashfurrow** [comment]
Testing this is difficult, since auctions list view doesn't display sales with zero lots. I think we can safely close this since I don't think we'll ever have a sale without any lots (FWIW opening a live sale with zero lots crashes the app too).

**Comment by alloy** [comment]
👍
