### ISSUE TITLE
Auction Sale name text not wrapping to 

### ISSUE THREAD

**Issue by katarinabatina** [artsy/eigen#1361]
the sale title should be wrapping not going off the screen 
![image](https://cloud.githubusercontent.com/assets/6482926/14028232/dfae961c-f1d1-11e5-856b-ac3a4f99a5e4.png)

**Comment by ashfurrow** [comment]
Ah, interesting. Looks like it happens whenever there's a long title and no info button.

**Comment by katarinabatina** [comment]
weeeirddd

**Comment by ashfurrow** [comment]
Nah, the info button was what the label used as a right-hand side anchor. Without it, it makes sense it would sort of trail off...

**Comment by katarinabatina** [comment]
ah I see
