### ISSUE TITLE
dupe shows in the show feed 

### ISSUE THREAD

**Issue by katarinabatina** [artsy/eigen#1362]
![image](https://cloud.githubusercontent.com/assets/6482926/14028270/0b54e384-f1d2-11e5-8be9-209494796df9.png)

**Comment by katarinabatina** [comment]
For context I'm not seeing this on store version of the app, where i'm not logged in

**Comment by alloy** [comment]
Are you saying that you only saw this in the beta/staging app?

**Comment by katarinabatina** [comment]
It was beta but it was production
