### ISSUE TITLE
[Onboarding Update] - Master Issue UX 

### ISSUE THREAD

**Issue by mennenia** [artsy/eigen#1363]
**Context:**

We’re looking at onboarding as a way of trying to increase the size of our engaged audience by personalizing their experience, hopefully making it more relevant for users and create a home feed  they’ll want to come back to more frequently.

Onboarding redesign aims to:
- Clarify value proposition (= collecting art)
- Gather the user's interest in order to personalise the mobile experience
 

### Overall Design:

![7a2dacc8-efb6-11e5-82fc-6a79b77f497b-1](https://cloud.githubusercontent.com/assets/373860/14028348/6e24a288-f1d2-11e5-8470-ca7a5749c62d.png)

**Flow chart:**

<img width="1251" alt="screen shot 2016-03-24 at 15 21 30" src="https://cloud.githubusercontent.com/assets/373860/14028691/29539dce-f1d4-11e5-8d36-982d872ce787.png">

**Previous onboarding:** 

[Video](https://youtu.be/JHhYXMcLqA0) - (mute the video :S)

**Behaviours:**

- Artist search #1337, [Flowchart](https://cloud.githubusercontent.com/assets/373860/14028731/65ba498e-f1d4-11e5-8c79-5cf453e013d6.png)
- Navigation #1323 
- Sequence [Flowchart](https://cloud.githubusercontent.com/assets/373860/14028691/29539dce-f1d4-11e5-8d36-982d872ce787.png)
- Personalization decoupled from sign in / start splash, to be potentially used for existing users later. 

**Prototypes:**

- [Search](http://cl.ly/2p3d443b3M41) in Flinto

**Differences with current onboarding:**

- [Add] Pre-push notification info #1339
- [Remove] Trial user #1330
- Removal of the "Are you interested in collecting art" question

**Postponed:**
- Personalised Home Screen #1338 (closed)

**Visuals specifications:**
- Splash screen #1325 
- Header #1319 
- Navigation #1323 
- Artist / Category list #1320 
- Recommendation segment #1321 
- Budget screen #1322 
- Sign up / Login #1324  

**Animations:**

- [Search](http://cl.ly/2p3d443b3M41) in Flinto
- Any other specific animations, add a gif or video here.

**Analytics**
- #1247

**Comment by katarinabatina** [comment]
@mennenia as we spoke about in DReview it would be awesome if we could implement onboarding in a way so that users who have existing artsy accounts, but have yet to follow anything can be sent to "personalize their account." Practically speaking it, this would mean de coupling the sign up and account creation from the artist follow, category follow, and budget setting screens.

**Comment by mennenia** [comment]
@katarinabatina no prob, added!

**Comment by mennenia** [comment]
I'm going to close some of the design spec issues as they've been captured here, and I've now created separate dev tickets.
