### ISSUE TITLE
[Auction] Artworks VC refinement status label should wrap before Refine button.

### ISSUE THREAD

**Issue by alloy** [artsy/eigen#1367]
Given enough refinement options to generate a long status message, the following UI bug can be triggered:

![img_7676](https://cloud.githubusercontent.com/assets/2320/14043509/57e4cf8a-f285-11e5-93c3-c7f2f361b6b7.PNG)

**Comment by ashfurrow** [comment]
"1 Lots" 😒

**Comment by alloy** [comment]
@ashfurrow Excellent catch :ok_hand:

**Comment by ashfurrow** [comment]
@katarinabatina could use some advice on wrapping vs. truncation and other things we could do to make this shorter ($45,000 vs $45k for example).

**Comment by alloy** [comment]
I also wonder if at some point you can just leave the count out. E.g. ‘1 lot’ is going to be pretty obvious when just 1 work shows up.

**Comment by katarinabatina** [comment]
could imagine this
![image](https://cloud.githubusercontent.com/assets/6482926/16066967/e3cc4380-3285-11e6-9d2e-34c4044bdbb1.png)
 with an ability to slide the component left to right

**Comment by acjay** [comment]
Might be a decent one for another Eigen team member to grab

**Comment by ashfurrow** [comment]
I'm thinking using the `maskLayer` property with a gradient layer, then using Autolayout to pin the trailing edge to the button (note: the gradient direction should be reversed for users with right-to-left languages).

**Comment by alloy** [comment]
@katarinabatina What would that look like on the leading side if you were to scroll to the end of the label? Would it add the fade over the start of the label where previously there was no fade?

**Comment by ashfurrow** [comment]
I interpreted this as not scrolling, but just masking out. The user can open the refine settings to see exactly what the refine parameters are.

**Comment by alloy** [comment]
> with an ability to slide the line of text left to right

That’s what I interpreted as scrolling.

I see your point, but I’m not sure if that totally applies, because you could also argument that there would be no need to show any current refine settings in that label.

**Comment by alloy** [comment]
Found [a pod](https://github.com/stephsharp/SSFadingScrollView) that pretty much does the things I would think it needs to do btw.
