### ISSUE TITLE
registering for an auction from auction sale page doesn't land me back on the page

### ISSUE THREAD

**Issue by katarinabatina** [artsy/eigen#1369]
On staging:

I tapped the register to bid button the auction sale page. I got the eigen sign up splash. Entered in my details, onboarding was skipped and I was able to get to the force registration screen. After entering in my cc info and billing info i was landed back on the explore menu instead of being put back on the auction sale page. When I arrive back on the sale page the registration status IS up to date which is good.

**Comment by acjay** [comment]
Dupe of #1586
