### ISSUE TITLE
Multiple layers of Body Copy shown in ARSignUpSplashViewController.

### ISSUE THREAD

**Issue by vijaytholpadi** [artsy/eigen#1376]
**Steps to reproduce:**
-> Download app for the first time.
-> Click on login/Signup
-> Press back
-> Swipe the splashViewController and you can notice the previous body copy fixed statically.

![img_9155](https://cloud.githubusercontent.com/assets/1171868/14131556/174ae300-f65a-11e5-9c16-b662fcf192dd.PNG)
![img_9156](https://cloud.githubusercontent.com/assets/1171868/14131557/174b6f0a-f65a-11e5-91c6-6fc6d027b623.PNG)

**Comment by alloy** [comment]
@vijaytholpadi Great report :clap:

However, we’re in the process of completely overhauling the on-boarding, so we won’t be spending any time on this for now #1363. Thanks for taking the time, though!
