### ISSUE TITLE
Repo not found

### ISSUE THREAD

**Issue by slashrover** [artsy/eigen#1377]
After following README:

I got this error when installing pods

Installing Artsy+UIFonts (1.1.0)

[!] Error installing Artsy+UIFonts
[!] /usr/bin/git clone https://github.com/artsy/Artsy-UIFonts.git /var/folders/p0/12x6wtfj1v5d3d6dqz1pfqv80000gn/T/d20160331-48277-132r1ew --single-branch --depth 1 --branch 1.1.0

Cloning into '/var/folders/p0/12x6wtfj1v5d3d6dqz1pfqv80000gn/T/d20160331-48277-132r1ew'...
remote: Repository not found.
fatal: repository 'https://github.com/artsy/Artsy-UIFonts.git/' not found

Seems like the repo has been removed. Some solution for this ? Thanks!

**Comment by ashfurrow** [comment]
I believe @orta changed the OSS font pod name to avoid problems importing modules. Not sure what to do here, will take a look when I get to a computer.

**Comment by orta** [comment]
needs to be    ` pod 'Artsy+UIFonts', :git => "https://github.com/artsy/Artsy-OSSUIFonts.git"`

**Comment by slashrover** [comment]
@orta Solved. Thx.

**Comment by alloy** [comment]
Thanks for the verification :+1:
