### ISSUE TITLE
Log In button touch area too small 

### ISSUE THREAD

**Issue by robertlenne** [artsy/eigen#138]
On onboardignonboarding screen:

![image](https://cloud.githubusercontent.com/assets/566531/6093231/b183af88-aecb-11e4-8987-52de96487a91.png)

**Comment by 1aurabrown** [comment]
@robertlenne do you want it to be visibly bigger, or to extend the touch area? I think it already has an extended touch area.

**Comment by robertlenne** [comment]
I was thinking extending the touch area... How big it is? I felt like the button was unresponsive, it COULD be that this the touch area is not instantly activiated when I enter the view but I had a hard time judging.

**Comment by alloy** [comment]
I think the touch area is good enough, but please re-open if you disagree.

I did notice that it takes a bit for the view to show up, so maybe you had the experience that it didn’t register the tap whereas it actually just took a long time? Filed that as #561.

**Comment by robertlenne** [comment]
yeah. that's probably it!

**Comment by alloy** [comment]
Alrighty then :+1:
