### ISSUE TITLE
[Push Notifications] Received notification analytics

### ISSUE THREAD

**Issue by alloy** [artsy/eigen#1381]
Looking at looker/mixpanel, the `notification received` count is very low, like ~70 instead of thousands. Something definitely seems off.

I’m wondering:
- How up-to-date is the analytics data in Looker/Mixpanel, is it (almost) real-time?
- How many users that have registered for notifications have updated to Eigen 2.4.1?
- Do many people tend to force-quit apps that they don’t use? (This is a more general question, I’m not sure how/if we can measure that.)

The latter is because I just found [this in the documentation](https://developer.apple.com/library/ios/documentation/UIKit/Reference/UIApplicationDelegate_Protocol/index.html#//apple_ref/occ/intfm/UIApplicationDelegate/application:didReceiveRemoteNotification:fetchCompletionHandler:) (emphasis mine):

> In addition, if you enabled the remote notifications background mode, the system launches your app (or wakes it from the suspended state) and puts it in the background state when a remote notification arrives. However, **the system does not automatically launch your app if the user has force-quit it**. In that situation, the user must relaunch your app or restart the device before the system attempts to launch your app automatically again.

I definitely _did_ find analytics data for both receiving notifications [in the background](https://github.com/artsy/eigen/blob/60a027481da0ab74997ccbbb6428169f49b1d2a8/Artsy/App/ARAppNotificationsDelegate.m#L99-L101) and for [when the app was active](https://github.com/artsy/eigen/blob/60a027481da0ab74997ccbbb6428169f49b1d2a8/Artsy/App/ARAppNotificationsDelegate.m#L103-L105), just not a lot. There is far more ‘tapped’ analytics data.

/cc @katarinabatina @anipetrov

**Comment by alloy** [comment]
From @dbgrandi:

> There’s no great way to account for that, and it changes over time because the force-quit switch is reset if a user reboots their phone or if they restart the app and it subsequently crashes. We get a bump after iOS pushes out an update.

**Comment by alloy** [comment]
I’ve done some searching to see how others are doing it, but haven’t found much examples just yet.

I’m wondering if there might be an issue of the Segment library not being able to finish its work before the background fetch handler is called.

**Comment by alloy** [comment]
If the app is launched with remote notification data, we currently [treat that as if the app was inactive](https://github.com/artsy/eigen/blob/60a027481da0ab74997ccbbb6428169f49b1d2a8/Artsy/App/ARAppDelegate.m#L171-L176), which we [don’t end up counting as ‘received’](https://github.com/artsy/eigen/blob/60a027481da0ab74997ccbbb6428169f49b1d2a8/Artsy/App/ARAppNotificationsDelegate.m#L114-L117).

I’m not sure yet how that affects all of the current data.

**Comment by alloy** [comment]
@anipetrov 

For 2.4.1:
- What is the ‘notifications tapped’ count?
- What is the ‘notifications received’ count?

**Comment by anipetrov** [comment]
https://artsy.looker.com/x/8ShqJ6r
![image](https://cloud.githubusercontent.com/assets/8701687/14252361/ff580eae-fa54-11e5-90a8-4d2e5ac9fd3c.png)

**Comment by alloy** [comment]
Thanks :ok_hand: 

So yeah, that cannot be right, something is wrong.

**Comment by alloy** [comment]
Going to close this for now. There’s not much we can do and maybe we’ll switch to a service provider in the future.
