### ISSUE TITLE
"Contact Gallery" button appearing for works that are marked as uninquireable

### ISSUE THREAD

**Issue by broskoski** [artsy/eigen#1385]
See https://api.artsy.net/api/v1/artwork/amadeo-luciano-lorenzato-untitled-1 for example
https://www.artsy.net/artwork/amadeo-luciano-lorenzato-untitled-1

**Comment by alloy** [comment]
It appears from a chat message by @broskoski that this line is what’s causing the issue https://github.com/artsy/eigen/blob/24cce11c042f018ac2e7f0618c20b67b6a2780fb/Artsy/Views/Artwork/ARArtworkActionsView.m#L365.

**Comment by sarahscott** [comment]
Should this show anything else in lieu of the button?

![screen shot 2016-04-12 at 4 25 57 pm](https://cloud.githubusercontent.com/assets/2712962/14474466/403e88f4-00cb-11e6-9273-adb5ff544064.png)

**Comment by sarahscott** [comment]
Nvm I see the notForSaleLabel
