### ISSUE TITLE
Fix alignment of artwork metadata in WorksForYou

### ISSUE THREAD

**Issue by sarahscott** [artsy/eigen#1394]
It should be aligned left with the artwork

![asset](https://cloud.githubusercontent.com/assets/2712962/14296953/858ae370-fb4a-11e5-991e-f0493425b41c.jpg)

**Comment by katarinabatina** [comment]
Worth noting that the vertical spacing between the bottom of the artwork and the beginning of the metadata should always be the same, I notice it wavers in these views
