### ISSUE TITLE
svgs? to do or not to do

### ISSUE THREAD

**Issue by katarinabatina** [artsy/eigen#1400]
any ideas?

**Comment by alloy** [comment]
There’s code available that should support it https://github.com/SVGKit/SVGKit, but from @mennenia’s experience there were still rough edges and frankly I’m a bit worried about the amount of code it adds to our codebase.

So it seems like PDF is the way to go after all.

I also have existing code for PDF -> image rendering https://github.com/Fingertips/FTAssetRenderer.

**Comment by alloy** [comment]
As discussed, we’re not going to do SVG. We’ll have more discussion in the near future about what the best way forward is.
