### ISSUE TITLE
Fix dimension parsing in Artwork model

### ISSUE THREAD

**Issue by sarahscott** [artsy/eigen#1407]
Our Artwork model says that width is a NSNumber, but it clearly is a NSString:  https://github.com/artsy/eigen/blob/75dd8c86fdcfcf6e12101869d4dc1b6b8001fd57/Artsy/Models/API_Models/Partner_Metadata/Artwork.h#L36

**Comment by orta** [comment]
I checked some other artworks, 
![screen shot 2016-04-13 at 10 04 49](https://cloud.githubusercontent.com/assets/49038/14488256/2e7470d6-015f-11e6-9f32-78fbd76a21b5.png)

https://api.artsy.net/api/v1/artwork/55fafa9d7261694d3c0002f9

Looks like they also use strings, I saw in Folio that there is code specifically around dealing with this:

``` objc
- (NSDecimalNumber *)onlyDecimalForKey:(NSString *)key
{
    id object = self[key];
    if ([object isKindOfClass:[NSDecimalNumber class]]) {
        return object;
    }
    // could still be a string
    if ([object isKindOfClass:[NSString class]] && ![object isEqualToString:@""]) {
        return [NSDecimalNumber decimalNumberWithString:object];
    }
    return nil;
}
```

**Comment by alloy** [comment]
It seems to me that Gravity will only return strings https://github.com/artsy/gravity/blob/26a3cdb52e2c5aba68ff222857a6b632700fdd75/app/models/util/dimensions.rb#L7-L8.

Btw, when we convert them, I don’t think we need the costly precision that `NSDecimalNumber` provides, it can just be a `NSNumber`.
