### ISSUE TITLE
Embedded articles show share button

### ISSUE THREAD

**Issue by robertlenne** [artsy/eigen#141]
Shouldn't be displayed

![image](https://cloud.githubusercontent.com/assets/566531/6093253/992cf646-aecc-11e4-98f8-4714689327de.png)

**Comment by 1aurabrown** [comment]
I think this may have been fixed, can you check this out in the newest beta?

**Comment by robertlenne** [comment]
Looks fixed. Closing.

**Comment by 1aurabrown** [comment]
closing!
