### ISSUE TITLE
Remove horizontal animation of elements on sign up modal

### ISSUE THREAD

**Issue by robertlenne** [artsy/eigen#142]
![image](https://cloud.githubusercontent.com/assets/566531/6093333/4c4b95ac-aecd-11e4-8575-decf652a976a.png)

**Comment by 1aurabrown** [comment]
@robertlenne You're referring to the animation when the buttons and text come in from the sides? Do you want it removed on iPhone & iPad or only iPad?

**Comment by robertlenne** [comment]
yes, the animation were they "slide" in. Both iPhone and iPAd.

[A.] Robert Lenne

Artsy <http://artsy.net/>


robert@artsy.net

                @robertlenne <https://twitter.com/robertlenne>

+1 347 439 0325
