### ISSUE TITLE
Create more sophisticated request for renewing network calls upon failure for root views

### ISSUE THREAD

**Issue by sarahscott** [artsy/eigen#1429]
Currently, tab views don't provide messaging around network failures (with the exception of the home view and small banners for certain actions). It would be nice to have a network failure view that's modular, simple to implement, and consistent app-wide.

**Comment by sarahscott** [comment]
@katarinabatina  how do you feel about this?

**Comment by katarinabatina** [comment]
@sarahscott does the user have to manually kick off a new network call or can we do it automatically for them?

**Comment by sarahscott** [comment]
We can try automatic calls, but we should be thoughtful about how often. If the user is on a plane or something, for example, we could be firing off useless network requests for hours on end.

**Comment by alloy** [comment]
I think it could just be this one:

![slack_for_ios_upload png](https://cloud.githubusercontent.com/assets/2320/14574696/7316ed2c-035d-11e6-90ce-6ab8dd61f767.jpeg)

* It allows the user to manually trigger reloading
* It tries to detect when the network becomes available and auto-reloads

**Comment by katarinabatina** [comment]
But that's not _really_ the issue...at least in the bug I reported right? Technically it's our issue not that the user doesn't have a connection.

**Comment by sarahscott** [comment]
@katarinabatina to deal with the bug you reported, I made the WorksForYouVC behave the way the other tabs do, which is reload when navigated away from and then returned to.

**Comment by katarinabatina** [comment]
@sarahscott got it 👍  but what this story suggests is that the user would actually see this in place of the frozen spinner correct?

**Comment by sarahscott** [comment]
Correct.

**Comment by alloy** [comment]
Correct. And you're right about the copy, my point was more about the general feel and functionality of the view.

**Comment by katarinabatina** [comment]
UNABLE TO LOAD

Please try again
