### ISSUE TITLE
Aborting Twitter/Facebook login leaves me on white screen with spinner.

### ISSUE THREAD

**Issue by robertlenne** [artsy/eigen#143]
1. Login
2. Select Twitter/Facebook
3. Get thrown out to web browser
4. Think "ah, can't be bothered" and go back to app

![image](https://cloud.githubusercontent.com/assets/566531/6093529/a3eabb96-aed0-11e4-91e4-a48a9df92fc9.png)

**Comment by ashfurrow** [comment]
Not able to reproduce this on either simulator – @alloy you say this is a confirmed bug?

**Comment by ashfurrow** [comment]
Ah, I see. The failure block on [the twitter auth call](https://github.com/artsy/eigen/blob/6a0f19ff4d39fac24b1933b994b88b4fe2c47aa5/Artsy/View_Controllers/Login_and_Onboarding/AROnboardingViewController.m#L409-L414) isn't being executed, but the indeterminate view _is_ dismissed, but only on the sign up page and not the sign _in_ page.

**Comment by ashfurrow** [comment]
Looks like this could be a problem with our OAuth provider. The library we're using [registers for launch-with-URL notifications](https://github.com/AFNetworking/AFOAuth1Client/blob/b5a17d9aaa27f025352545525988019b0c59195a/AFOAuth1Client/AFOAuth1Client.m#L33), but not become-active ones, meaning it can't know when the user has cancelled the operation. Looking into why it works in the sign up case.

**Comment by ashfurrow** [comment]
[This](https://github.com/artsy/eigen/blob/6a0f19ff4d39fac24b1933b994b88b4fe2c47aa5/Artsy/View_Controllers/Login_and_Onboarding/AROnboardingViewController.m#L112-L119) is where that's happening. 

So the issue is that the presentation/dismissing is called on different view controller instances. 

```objc
/// Presenting...
<ARLoginViewController: 0x7fda3e0afd50>
(lldb) c
/// Dismissing...
(lldb) po self
<AROnboardingViewController: 0x7fda3e83a800>
```

So the associated object lookup returns `nil` and we can't dismiss it.
