### ISSUE TITLE
Labels are clipping instead of showing full height.

### ISSUE THREAD

**Issue by artsyit** [artsy/eigen#1430]
### Message from 54e0ff6b7261692c49d10000 sent on 2016-04-15 20:25:42 UTC

> Hey there
> I have some feedback:
> 
> I've only ever seen this in the sim, but now it's happening on-device
### Link to HockeyApp
- [https://rink.hockeyapp.net/manage/apps/37020/feedback/502676](https://rink.hockeyapp.net/manage/apps/37020/feedback/502676)

**Comment by orta** [comment]
This doesn\t have a screenshot or anything

**Comment by sarahscott** [comment]
Weird - in the email it does.

**Comment by sarahscott** [comment]
![asset-2](https://cloud.githubusercontent.com/assets/2712962/14575127/d0c842fc-032d-11e6-9d03-054b4e05adb4.jpg)

**Comment by orta** [comment]
Ah, yeah, you have the fix on your PR which isn't merged yet - #1423 should fix this

**Comment by alloy** [comment]
#1423 isn’t necessarily going to be merged soon, might be delayed until next sprint. Can you PR just the fix for this?

**Comment by sarahscott** [comment]
@alloy did you want me to do that or orta?

**Comment by alloy** [comment]
@sarahscott My bad, I meant you 😑

**Comment by sarahscott** [comment]
😁

**Comment by katarinabatina** [comment]
I'm seeing this on device as well ✋

**Comment by alloy** [comment]
AFAIK this issue still exists, not sure why it’s in QA.

**Comment by orta** [comment]
Screen doesn't exists anymore
