### ISSUE TITLE
Hide Auction results from artwork/artist pages

### ISSUE THREAD

**Issue by katarinabatina** [artsy/eigen#1437]
Auction results have been removed in force and microgravity. It's unclear if we will want them again in the future (our contact with the data provider is almost up and we're looking to replace the data). If we can hide them for now without fully deleting the code that would be 👌 .

**Comment by alloy** [comment]
We can just remove the code, it will still be in the history of the repo if we ever want it back.

**Comment by sarahscott** [comment]
Closed via #1444
