### ISSUE TITLE
Home Update: Banners

### ISSUE THREAD

**Issue by katarinabatina** [artsy/eigen#1439]
![image](https://cloud.githubusercontent.com/assets/6482926/14619870/ab7d6912-0587-11e6-84a8-937dc3405e4b.png)

**Comment by katarinabatina** [comment]
Issue #1442 outlines what should happen when there are no banners

**Comment by alloy** [comment]
@katarinabatina Do you think this is a must in the first public version?

**Comment by katarinabatina** [comment]
@alloy not necessarily but if we're moving forward with changing search then the current design will still need to be adjusted somewhat

**Comment by alloy** [comment]
@katarinabatina I’m not entirely sure what the part is that would still need to be adjusted. Could you elaborate?

**Comment by katarinabatina** [comment]
@alloy adjustments based on discussion we had this morning continuing to use existing data. 
![image](https://cloud.githubusercontent.com/assets/6482926/18994749/3c0e8600-86f7-11e6-849c-c5f23254b5e0.png)

**Comment by alloy** [comment]
@katarinabatina Thanks! Just want to confirm that we’re using the `name` attribute on both iPhone and iPad and ignoring the `mobile_title` attribute?

```json
{
    "name": "ArtRio 2016 #3",
    "mobile_title": "ArtRio",
}
```

(I don’t know what purpose the `mobile_title` is supposed to serve, maybe it’s purely a martsy thing?)

**Comment by katarinabatina** [comment]
@alloy I am not sure the difference between them, I imagine the mobile one displays on martsy/iphone and the name displays on desktop. Perhaps we should pull the mobile_title to be safe.

**Comment by alloy** [comment]
@katarinabatina Ok, what I’ll do is use `mobile_title` on iPhone and `name` on iPad.

**Comment by katarinabatina** [comment]
@alloy yeah that sounds like a good idea. It's interesting because the "name" isn't actually used to display the text on the banner in desktop (the text is an image). My guess is that "name" is used to identify which banner is being shown (hence the "Art Rio #3")

**Comment by alloy** [comment]
Ahhhhh, I naively assumed that that was just a staging data thing. Ok, so then it doesn’t really make sense to ever use `name`, right? I’ll just use `mobile_title` which probably just holds ‘the textual version of the same title’?

**Comment by alloy** [comment]
@katarinabatina What’s the black background rectangle with 30% opacity about? Is it an overlay over the image that’s meant to darken it?

**Comment by orta** [comment]
Yeah, I bet it's to make sure that any pure whites on the image don't make the text unreadbale

**Comment by katarinabatina** [comment]
Yup, what Orta suggested!

Sent with thumbs,
Katarina Batina 
Product Designer
Artsy.net

**Comment by alloy** [comment]
Gotcha! 👍

**Comment by katarinabatina** [comment]
@alloy looking at this today, looks pretty good I think just

**Comment by alloy** [comment]
@katarinabatina continuing here https://github.com/artsy/eigen/issues/1912
