### ISSUE TITLE
Home Update: Artist Follow

### ISSUE THREAD

**Issue by katarinabatina** [artsy/eigen#1440]
![image](https://cloud.githubusercontent.com/assets/6482926/14644594/981325d0-0620-11e6-9f1e-0ae157cc37ef.png)

**Comment by katarinabatina** [comment]
Opted for a simple cross fade from black to purple in the success state here. 
![principalfollow_04](https://cloud.githubusercontent.com/assets/6482926/14718343/2577843a-07c4-11e6-9fe7-a53a18e2a8c2.gif)

**Comment by alloy** [comment]
@katarinabatina Related to this, is the idea the follow button on the new artist page will also work like that? i.e. cross fade to purple and always be purple when you are already follow an artist? And I assume when you unfollow it’s just the opposite cross fade?

**Comment by alloy** [comment]
Still need to do the animation.
