### ISSUE TITLE
Home Update: UI Adjustment to Search VC

### ISSUE THREAD

**Issue by katarinabatina** [artsy/eigen#1447]
![image](https://cloud.githubusercontent.com/assets/6482926/18935450/2cb731f6-85ae-11e6-89ef-c417faf3d715.png)

**Comment by katarinabatina** [comment]
![search](https://cloud.githubusercontent.com/assets/6482926/14708729/b214b216-079a-11e6-8316-c644f9a64559.gif)

**Comment by mennenia** [comment]
@orta seeing as you're doing the gene view in Eigen, any chance you're up for this? :D

**Comment by orta** [comment]
This is a lot of work, and I'm predominantly on partner-success ATM, so probably not a good idea to assign to me

**Comment by alloy** [comment]
On hold for the final decision to be made on https://github.com/artsy/eigen/issues/1870

**Comment by katarinabatina** [comment]
Updated comp and animation, slight change from previous. As per our discussion today I think search is on the table regardless.

**Comment by alloy** [comment]
@sarahscott This is all done, yeah?

**Comment by sarahscott** [comment]
Yes
