### ISSUE TITLE
Navigation Update

### ISSUE THREAD

**Issue by katarinabatina** [artsy/eigen#1450]
Making room for the search to become apart of the bottom navigation.

Moving in Shows and Magazine to be apart of the explore section (that's done all in admin I will take care of it) we just need to remove these two items from the main navigation and make the following changes. This also removes the circular search button that is persistent everywhere. This behavior will now be taken over by the search icon in the tab. 

![image](https://cloud.githubusercontent.com/assets/6482926/14719283/61155382-07c9-11e6-89fa-031d483f4864.png)

**Comment by sarahscott** [comment]
Fixed by #1884
