### ISSUE TITLE
[Gravity] Gene / Categories Endpoints

### ISSUE THREAD

**Issue by mennenia** [artsy/eigen#1454]
<img width="563" alt="screen shot 2016-04-25 at 11 07 51" src="https://cloud.githubusercontent.com/assets/373860/14780673/f11d4048-0ad5-11e6-9f9e-90c6f5aa17c6.png">

For the new onboarding we want to:

1) Allow users to search for artists and categories 
2) Suggest new related artists and categories based on artists and categories they follow respectively.
3) Suggest placeholder popular artists and categories, before they start searching 

To facilitate this I need to get the following data, and am unsure which endpoints to use. 

- "Top Artists" 
I'm using trending artists `/api/v1/artists/trending`, is this correct?

- "Popular Categories" 
I couldn't find an endpoint. Looking for something like `/api/v1/genes/popular`.

- Related categories
I follow "Light and Space Movement" and want to request categories similar to "Light and Space Movement", e.g. `GET /api/v1/related/genes?gene="light-and-space-movement"` or ``GET /api/v1/me/suggested/genes?gene="light-and-space-movement"`.

- Search categories
I request categories with the term "min" and expect to get only categories containing "min" in them, like "Minimalism", e.g. `GET /api/v1/match/genes?term=min`.

@mzikherman any thoughts? :)

**Comment by alloy** [comment]
And the same ‘exclude list’ requirement applies to the ‘related categories’ as for artists (#1449).

**Comment by katarinabatina** [comment]
@mennenia for Category lists I'm not sure what endpoint we would need to generate the popular list but ideally we want to pull in the 80 categories featured in /collect on the web

https://www.artsy.net/collect

![image](https://cloud.githubusercontent.com/assets/6482926/14819214/06da7b08-0b8f-11e6-89f8-a4e2d755cc91.png)

plus the mediums 
![image](https://cloud.githubusercontent.com/assets/6482926/14819223/115b4666-0b8f-11e6-8980-c68d206db6d7.png)

**Comment by mzikherman** [comment]
@mennenia, I don't have the answers to everything unfortunately.

> "Top Artists" 
I'm using trending artists /api/v1/artists/trending, is this correct?

I think so! @cavvia can you confirm this is cool?

> "Popular Categories" 
I couldn't find an endpoint. Looking for something like /api/v1/genes/popular

We don't really have an endpoint for this. The categories and images on https://www.artsy.net/collect live in an S3 file: https://s3.amazonaws.com/force-production/json/browse-categories.json (probably need to sign in first to our old it@ managed account), this includes the mapping of which categories show up, which image to use, etc.

> "Related categories"
I follow "Light and Space Movement" and want to request categories similar to "Light and Space Movement", e.g. GET /api/v1/related/genes?gene="light-and-space-movement" or `GET /api/v1/me/suggested/genes?gene="light-and-space-movement".

Honestly, no clue what's an appropriate endpoint to use (cc @cavvia if you know?).

> "Search categories"
I request categories with the term "min" and expect to get only categories containing "min" in them, like "Minimalism", e.g. GET /api/v1/match/genes?term=min.

Yes I think this is correct :)

**Comment by cavvia** [comment]
* For 'Top Artists' you can use the trending endpoint that's correct.
* For 'Related Categories' the `/api/v1/related/genes` only takes an `artist` parameter - so you can only show related categories based on *artist* follows not *gene* follows. We do not have a gene similarity index as such. We could create one. It would probably take a couple of days of dev time.

**Comment by mennenia** [comment]
@mzikherman @cavvia Thanks so much for your responses, that's great clarification.

Creating a "Related Categories" API would be great. 

- @katarinabatina am I right in thinking that the behaviour of recommending related categories will also come to web / other places in iOS?
- @cavvia I assume I will need to file an issue on the Gravity repo? :) 

(also, @mzikherman you were totally right, I seem to have been testing `GET /api/v1/match/genes?term=min` without the `/match/` - apologies!).

**Comment by cavvia** [comment]
@mennenia We would queue up the gene similarity work in the Platform trello backlog. I'll add a ticket and notify you.

**Comment by mennenia** [comment]
Thanks @cavvia!
