### ISSUE TITLE
Ensure support for cultural makers

### ISSUE THREAD

**Issue by katarinabatina** [artsy/eigen#1456]
Ref https://github.com/artsy/gravity/pull/9787

If there is no artist then there should be a cultural maker, then then the cultural maker name goes where the artist name goes currently. That cultural maker does not link to any artist view (meaning there is not chevron)

**Comment by alloy** [comment]
There will always be an artist _OR_ a cultural maker(s) https://github.com/artsy/gravity/pull/9787#issuecomment-215449151
