### ISSUE TITLE
[Show] Discuss the need for higher-res preview images

### ISSUE THREAD

**Issue by alloy** [artsy/eigen#1460]
Re #1436.

The code has already been merged, so we need to discuss it and take action asap.

**Comment by alloy** [comment]
@orta bump, this needs to be decided before we start making releases next week

**Comment by alloy** [comment]
…otherwise I will just revert it for now

**Comment by orta** [comment]
I still think the PR is a net positive, it's not https://github.com/artsy/eigen/issues/415 - but I wasn't going to build that entire thing, that's a tonne of work, this fixes the majority of an annoying problem, that can be someone's real feature work. Not a part of my fix things that annoy me fridays.

![screen shot 2016-05-04 at 08 27 15](https://cloud.githubusercontent.com/assets/49038/15007628/5be9cb3c-11d2-11e6-9ffe-31dfc3083367.png)

Going through our current top shows I couldn't find one show that looked bad

These were the worst image I could find for each set

![screen shot 2016-05-04 at 08 30 37](https://cloud.githubusercontent.com/assets/49038/15007673/a46467be-11d2-11e6-871d-2f4974377a83.png)
![screen shot 2016-05-04 at 08 31 02](https://cloud.githubusercontent.com/assets/49038/15007675/a5d3489a-11d2-11e6-99a2-2ae254ee8ec9.png)
![screen shot 2016-05-04 at 08 31 28](https://cloud.githubusercontent.com/assets/49038/15007676/a782a244-11d2-11e6-8895-b63befa9af39.png)

![screen shot 2016-05-04 at 08 35 38](https://cloud.githubusercontent.com/assets/49038/15007751/3356b4ea-11d3-11e6-8145-950114c34580.png)


We don't show anything if there are no installation shots, so portrait artworks aren't show

![screen shot 2016-05-04 at 08 33 33](https://cloud.githubusercontent.com/assets/49038/15007717/f0d182d0-11d2-11e6-8c19-18e24428b862.png)

**Comment by orta** [comment]
The images we're using are `:large` -> e.g. https://d32dm0rphc51dk.cloudfront.net/hNLQY7ebdbKw9Z6MlRreqg/large.jpg

**Comment by alloy** [comment]
To be clear, the issue it’s fixing is that in the past portrait images would get shown with whitespace on the left and right side?

> The images we're using are `:large`

👍

**Comment by orta** [comment]
Yep

**Comment by alloy** [comment]
Ok, I’m fine with this then.

@katarinabatina Did you have any other concerns?

**Comment by katarinabatina** [comment]
No, we will prioritize the rest of the work after messaging.
