### ISSUE TITLE
[Analytics] New artist page events

### ISSUE THREAD

**Issue by anipetrov** [artsy/eigen#1469]
## Tracks
- [ ] **Follow artist**: An artist can be followed from artist page, from fair artist pages, or during onboarding
  * properties: {artist_slug, artist_id, source_screen: [artist page, artist fair page, onboarding top artists, onboarding search, onboarding recommended]}

- [ ] **Unfollow artist**: An artist can be unfollowed from artist page, from fair artist pages (wherever there is a follow/unfollow button)
  * properties: {artist_slug, artist_id, source_screen: [artist page, artist fair page]}

- [ ] **Tapped artist view tab**: Fired when tapping on one of the three tabs on the artist view
  * properties: {artist_slug, artist_id, tab: [about, works, shows]}

## Screens
- [ ] **Artist**: single screen view when you land on the artist view, as opposed to screen view per tab which is what we have done so far. We would now fire events when a user switches across taps as opposed to screen views.
  * properties: {owner_type: "artist", owner_id: artist.id, owner_slug: artist.slug}

## Questions
* Is it possible to somehow record `referring_screen` information for screen views? I went through segment's documentation for iOS and did not find anything on the subject, happy to contact them if you think it's worth it.

cc @alloy @katarinabatina

**Comment by alloy** [comment]
> Is it possible to somehow record `referring_screen` information for screen views? I went through segment's documentation for iOS and did not find anything on the subject, happy to contact them if you think it's worth it.

Everything is possible, but this would certainly involve a bunch more work.

**Comment by katarinabatina** [comment]
Let's pass on it for now. 

Sent with thumbs,
Katarina Batina 
Product Designer
Artsy.net
