### ISSUE TITLE
Push notifications don't lead to bell tab

### ISSUE THREAD

**Issue by katarinabatina** [artsy/eigen#1470]
They lead you to the home screen

**Comment by katarinabatina** [comment]
Had this happen again today

**Comment by alloy** [comment]
Are you signed in?

**Comment by katarinabatina** [comment]
yup

[A.] Katarina Batina
Product Designer

Artsy <http://artsy.net/>


katarina@artsymail.com

                @katarinabatina <https://twitter.com/katarinabatina>

253 225 5812

**Comment by katarinabatina** [comment]
happened again this morning...I'm starting to think maybe it's something funky with test flight + being admin....maybe? @ashfurrow got through just fine on his phone but he's on the app store version.

**Comment by alloy** [comment]
I have been getting through fine as well every time. Seeing as you seem to be able to reproduce it often, let’s put your theory to the test by starting with deleting the app and re-installing from the store.
