### ISSUE TITLE
Version access to the websocket API

### ISSUE THREAD

**Issue by ashfurrow** [artsy/eigen#1471]
Consider the following scenario:

1. A user installs eigen.
1. We make a breaking change to the way eigen communicates with the live integration websocket.
1. We release an update to eigen, but the user doesn't upgrade.
1. They try to access live on their outdated eigen install, but they're presented an inconsistent or misleading user interface.

This is a problem I'd like to mitigate. This is different from the usual REST APIs we use because websockets operate in a fundamentally different way (for example, we can always add new things to an endpoint response, but if we change the order of events sent form the websocket, or add a new event, we have new way to reflect that in eigen without updating the app).

My initial idea, discussed with @acjay, was have some sort of version compiled into the app and reflected on echo. If the app is "out of date", we fall back to the internal web browser for live auctions. @devangt has raised the idea of asking the user to update. I think this warrants some UX thought from @katarinabatina before we pursue an implementation.

**Comment by mennenia** [comment]
My 2 cents: I like the idea of asking the user to update. Lots of apps do this, and I think it's a fair ask if you're providing a native, live bidding service.

From what we discussed around the dyld crash, our users seem to just go with the flow.

If we know an auction is coming up and there's an update available, we could even prompt the user ahead of time (a few days), to let them know they can and probably should update.

**Comment by alloy** [comment]
While that's very true, I do think that's the situation of an auction is a special one.  What we definitely do not want is to _force_ the user to update, because that will lead to aggravation if they are trying to make a bid and feel under pressure.

 So I am plus one on adding a suggestion to update for a more native auction experience, but we should definitely full back to the web version from auctions  if the user decides not to update.

**Comment by katarinabatina** [comment]
I've thought about a generic "new update available" pop up when a new update is available. To prioritize I will look at what our average adoption rate is from one version to the rest to determine our baseline and what improvement we'd expect.

**Comment by acjay** [comment]
Perhaps we can nag the user to update, but if they choose not to, use the fall-back.
