### ISSUE TITLE
Support event undo

### ISSUE THREAD

**Issue by ashfurrow** [artsy/eigen#1472]
See [causality PR](https://github.com/artsy/causality/pull/128).

Basically what we do currently is insufficient, which is `events to add = new events - old events`. We need to also do `events to remove = old events - current events from causality`. The details are still being worked out, but this should be a priority after I get https://github.com/artsy/eigen/issues/1110 done.

**Comment by katarinabatina** [comment]
not currently working as of June 6th QA

**Comment by ashfurrow** [comment]
Is this happening in all cases or is there a specific way to reproduce this?

**Comment by devangt** [comment]
done for now. Individual updates will be tackled with new issues/epics
