### ISSUE TITLE
Universal Link (trial run)

### ISSUE THREAD

**Issue by sperle** [artsy/eigen#1473]
We would like to try out universal links in our Sailthru emails because we think we'll see a benefit in terms of conversions for our more commercial-focused emails -- but we're a little uncertain that the switch will be positive for our editorial content (re: perceived load time when the app opens, general feeling that the mobile web experience is better from a design perspective), so we'd like to implement it for a ~2 week period minimum and then evaluate the results.  Note - in the future we might have the ability to toggle between multiple link domains so we'd be able to apply universal links on a campaign-by-campaign basis, but right now it's not supported.

Ideally, we'd like to try this out a little before and during an auction campaign (early June would be a good target start time).

Documentation: https://getstarted.sailthru.com/mobile/apple-ios-app-universal-links/

I can also provide you with a ST login if that's helpful or do the sailthru updates on my end when necessary.

cc: @alloy 

---
- [ ] Get SSL certificate for link domain.
- [ ] Setup link domain NS record.
- [ ] Configure Sailthru:
  - [ ] Certificate and key pair.
  - [ ] Signed site association file.
  - [ ] Specify link domain.
- [ ] Add code to Eigen that performs a request to Sailthru for each incoming link, which then returns data needed to actually route the user. The request to Sailthru is also required for click tracking purposes.
  - [ ] Recognise Sailthru links based on the hostname, for example: http://link.artsy.net/click/58edf4fce9328bb6438b5659/aHR0cHM6Ly93d3cuYXJ0c3kubmV0L3dvcmtzLWZvci15b3U_YXJ0aXN0X2lkPWRhbWllbi1oaXJzdCZmcm9tX2VtYWlsPXRydWUmdXRtX2NhbXBhaWduPXBlcnNvbmFsaXplZF9lbWFpbF93ZWQtMDQtMTItMTcmdXRtX2NvbnRlbnQ9cGVyc29uYWxpemVkX2FydGlzdHNfYW5kX2FydHdvcmtzJnV0bV9zb3VyY2U9c2FpbHRocnUmdXRtX21lZGl1bT1lbWFpbA/56a63e2717893fbc408b8420B1dcfb035
  - [ ] Make a request to Sailthru with that URL so Sailthru can register the click and we get back the actual artsy.net URL, e.g.: https://www.artsy.net/works-for-you?artist_id=damien-hirst&from_email=true&utm_campaign=personalized_email_wed-04-12-17&utm_content=personalized_artists_and_artworks&utm_source=sailthru&utm_medium=email
  - [ ] Send that artsty.net URL Eigen’s analytics URL registration and pick-up the UTM params.
  - [ ] Open the URL with Eigen’s Switchboard, which should take the `artist_id` from the URL and instantiate a WorksForYou VC with that.

**Comment by alloy** [comment]
It looks like a small work item (few hours), so should be able to do at pretty much any time.

What about personalised emails, wouldn’t we always want to send those to the app?

**Comment by sperle** [comment]
As best I can tell this would apply to all emails sent through Sailthru -- since it'd be related to the link domain link.artsy.net which is what all our links get encoded to, including for the personalized. I think those are the emails we'll see the best results for this!

**Comment by alloy** [comment]
Ok, so you can’t, say, only encode links to the `link.artsy.net` domain for temporary periods? i.e. always use `link.artsy.net` for personalised emails and only some of the time for editorial emails?

**Comment by sperle** [comment]
correct -- they're working on a multi link domain thing to allow this to be selectively applied but right now all links automatically get encoded. Even if there were some way to turn off the encoding (which I don't think there is, like there was for MailChimp) that would prevent click tracking.

**Comment by alloy** [comment]
Ohhhh, I just noticed that they require us to get a HTTPS certificate for the specific link domain. I’ll check who’s responsible for that and what it’s gonna cost us.

**Comment by sperle** [comment]
Let me know if you need/want to be connected to anyone on the ST side btw.

**Comment by alloy** [comment]
@sperle Thanks, I think that for now it’s all pretty clear :+1: I’ve added a list of TODOs to your original ticket.

**Comment by sperle** [comment]
Was chatting with @robertlenne who called out that we should make sure that the native works-for-you has support for putting the works by the artist you clicked through (in the personalized email) at the top the way martsy view does.  cc @katarinabatina

**Comment by katarinabatina** [comment]
@sperle great point. We don't currently support this but we can make it a work item.

**Comment by sperle** [comment]
Hi @katarinabatina following up on the native works-for-you support, since it sounds like auction emails would really benefit from universal linking, but we don't want to implement at the expense of the recommendation emails.

**Comment by sperle** [comment]
@katarinabatina following up on this again!

**Comment by katarinabatina** [comment]
hi @sperle I think we still need to support a way to mimic what happens on microgravity (where when a user taps an artists/artworks and we're able to throw those works at the top of their works for you feed).

I don't have a sense for how easy that would be @alloy

**Comment by katarinabatina** [comment]
![image](https://cloud.githubusercontent.com/assets/6482926/20809351/d492530e-b7d3-11e6-8cd0-acc0d0cbe0c0.png)

**Comment by alloy** [comment]
Ok, so regardless of how old the suggestion is, it gets added to the top of the feed above the absolute latest suggestions. It’s hard to say how easy that would be, will have to dive into the details a bit.
