### ISSUE TITLE
dupe icons on status update

### ISSUE THREAD

**Issue by katarinabatina** [artsy/eigen#1495]

**Comment by alloy** [comment]
Can you elaborate on what this is about?

**Comment by katarinabatina** [comment]
@orta @ashfurrow this is on the live auction view the icons related to the bid status we're duplicate and overlapping one another. I don't have a screen shot because we weren't testing on my device.

**Comment by orta** [comment]
This happens when a state changes on a live lot, this should be fixed now 👍
