### ISSUE TITLE
Feedback 'Hey there I have some feedback: Hidden text on ...'

### ISSUE THREAD

**Issue by artsyit** [artsy/eigen#1498]
### Message from Jesse Kedy sent on 2016-05-12 19:41:41 UTC###

> Hey there
> I have some feedback:
> 
> Hidden text on the artist page...

### Link to HockeyApp ###

* [https://rink.hockeyapp.net/manage/apps/37020/feedback/547448](https://rink.hockeyapp.net/manage/apps/37020/feedback/547448)

**Comment by alloy** [comment]
![image_0-4](https://cloud.githubusercontent.com/assets/2320/15244114/e6fc527e-18ff-11e6-8764-ec4ae50c2598.jpg)

This looks very much like the issue we had on the home feed, which iirc has been fixed. Correct @sarahscott ?

We just need to ensure this is the case during QA.

**Comment by alloy** [comment]
The artist view is gone now anyways, but the core issue still exists and is being tracked at #1625
