### ISSUE TITLE
Seeing two push notifications

### ISSUE THREAD

**Issue by katarinabatina** [artsy/eigen#1499]
this is a story @anipetrov reported, @anipetrov can you add anymore context? 

![image](https://cloud.githubusercontent.com/assets/6482926/15257585/0098b1c2-1915-11e6-899e-618529bd4ca7.png)

**Comment by alloy** [comment]
This must be from different (test) accounts.

**Comment by alloy** [comment]
@anipetrov I bet that if you dive into the analytics data you will see that two notifications for different user accounts are sent to your device token.

**Comment by anipetrov** [comment]
Ahhhh I bet you are right! Will do some digging

On Mon, May 16, 2016 at 10:59 AM, Eloy Durán <notifications@github.com>
wrote:

> @anipetrov <https://github.com/anipetrov> I bet that if you dive into the
> analytics data you will see that two notifications for different user
> accounts are sent to your device token.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/artsy/eigen/issues/1499#issuecomment-219447597>
>



-- 
[A.]      Ani Petrov

           Artsy <https://artsy.net/>
           ani@artsy.net
           +1 609 216 4575
