### ISSUE TITLE
Segment-Quantcast integration

### ISSUE THREAD

**Issue by anipetrov** [artsy/eigen#1510]
Hey team, we would like to enable a free marketing service called Quantcast - this should include adding a library to the eigen project and enabling the integration on the segment site: [link to Segment integration docs](https://segment.com/artsy-engineering/sources/eigen-production/integrations/quantcast).

cc @jessekedy @katarinabatina

**Comment by katarinabatina** [comment]
@anipetrov could you tell us more about the service?

**Comment by anipetrov** [comment]
@jessekedy will be able to provide the most context

**Comment by jessekedy** [comment]
This is a service that give us aggregate (not individual) demographic info on our visitors (regardless of logged state), such as: 

![Example](http://cl.ly/46020n310u2u/Image%202016-06-07%20at%201.14.02%20PM.png)
