### ISSUE TITLE
New error state for socket

### ISSUE THREAD

**Issue by ashfurrow** [artsy/eigen#1513]
Two things:

- When the socket has not yet connected.
- When the socket becomes disconnected.

**Comment by orta** [comment]
Going to look at this, mainly the disconnection - based on this: https://github.com/artsy/eigen/issues/1527#issuecomment-220620708

**Comment by ashfurrow** [comment]
I'd like to expand this slightly in scope to also include when causality has lost connection with the operator.

**Comment by acjay** [comment]
We don't yet have this implemented in Causality. I'll see if I can take a quick stab at an API for this, and if you wanted, you could build forward-compatible support.

**Comment by ashfurrow** [comment]
Sounds like a plan 👍

**Comment by acjay** [comment]
Alright, so I think it'll be pretty simple. There would be an `operatorConnected: Boolean` added to [`InitialFullSaleState`](https://github.com/artsy/causality/blob/master/src/main/scala/net/artsy/auction/domain/WebSocketEventModel.scala#L48-L53) and then a new event called `case class OperatorConnectedBrodcast(operatorConnected: Boolean) extends OutgoingWebSocketEvent`, which would be sent whenever that state changed.

**Comment by ashfurrow** [comment]
@acjay to confirm, the event payload will include `operatorConnected` at the top-level of the JSON?

**Comment by acjay** [comment]
Yep yep

**Comment by acjay** [comment]
Is it too late to change this to `OutOfOrder`? I'm wondering whether we're being too specific on the particular error, and if it would be more versatile to be more generic.

**Comment by ashfurrow** [comment]
We're submitting tomorrow, can we get it in by then?

**Comment by acjay** [comment]
I'm doing it with OperatorConnected for now but let me know if you switch
it. While it would be preferred to switch, it's cool either way. One thing
to note is that the way it's being implemented, an update will come across
when the status is switched for any sale, so be sure not to assume the
status has changed.

**Comment by ashfurrow** [comment]
Cool 👍

**Comment by devangt** [comment]
done for now. Individual updates will be tackled with new issues/epics
