### ISSUE TITLE
Nuclear Error State for Live Auction

### ISSUE THREAD

**Issue by katarinabatina** [artsy/eigen#1527]
We should show this alert when we've lost connection with the operator on the auction room floor. 

![image](https://cloud.githubusercontent.com/assets/6482926/15430844/1b4a58b2-1e75-11e6-8019-0ec60061332f.png)

**Comment by katarinabatina** [comment]
@orta @ashfurrow

**Comment by orta** [comment]
What does the number represent? Is it a counter for every second disconnected?

**Comment by katarinabatina** [comment]
It was meant to countdown to the next "try" but I suppose we would be trying to reconnect continuously?? In which case it can act as more of a spinner.

**Comment by orta** [comment]
Yeah, I think we would probably give it ~`0.5-1` seconds between attempts in order to make sure we don't take down the server by accident due to demand, so probably doesn't make sense to ditch the number, but keep the spinner 👍 

any preference on how that animates?

**Comment by orta** [comment]
This is in
