### ISSUE TITLE
Support jumping into a live app directly from inside the AuctionViewController 

### ISSUE THREAD

**Issue by orta** [artsy/eigen#1533]
Relates to https://github.com/artsy/auctions/issues/67

Rough gist:

* When we download all data for a Sale in the `AuctionViewController`
* Check to see if it's a live auction, that is currently happening
* If so, then show the LiveAuction model, and behind the scenes pop the `AuctionViewController` so the user is the same state as before.

**Comment by orta** [comment]
Fixed by https://github.com/artsy/eigen/pull/1556

**Comment by katarinabatina** [comment]
not working in current mocktion

![image](https://cloud.githubusercontent.com/assets/6482926/15838182/adf891d6-2c0a-11e6-8e11-99d409284d0a.png)

**Comment by katarinabatina** [comment]
@orta

**Comment by orta** [comment]
This is loading force, it shouldn't be ^
