### ISSUE TITLE
Current Lot link should not scroll with lots

### ISSUE THREAD

**Issue by ashfurrow** [artsy/eigen#1538]
It should stay fixed like the auction progress bar and not be duplicated across lots. Reported on [Hockey](https://rink.hockeyapp.net/manage/apps/37020/feedback/555470).

**Comment by ashfurrow** [comment]
Shouldn't be _too_ difficult, but it is a change to our layout. I'll roll this into #1506.

@katarinabatina are there details available for how this is shown/hidden when the user navigates between lots by swiping on iPhone?

**Comment by katarinabatina** [comment]
The live lot link should animate from the bottom up when navigating to a lot that is not the live lot, and animate down and away when the user navigates back to the live lot.

**Comment by ashfurrow** [comment]
Talked with Katarina, we need to present the sale info VC in a modal, not a push.

**Comment by katarinabatina** [comment]
@ashfurrow from today in sprint kickoff

**Comment by ashfurrow** [comment]
Issue moved to [artsy/auctions #191](https://github.com/artsy/auctions/issues/191) via [**ZenHub**](https://www.zenhub.com/)
