### ISSUE TITLE
Remove buyer's premium note on lot view

### ISSUE THREAD

**Issue by katarinabatina** [artsy/eigen#1539]
screen shot forthcoming 

#1506

**Comment by katarinabatina** [comment]
@ashfurrow could we potentially replace the buyers premium data instead with the current bid: 
![image](https://cloud.githubusercontent.com/assets/6482926/15550450/8727dc22-227f-11e6-9d9c-adf16c52d6fa.png)

**Comment by orta** [comment]
10/10, I like this idea ^

**Comment by katarinabatina** [comment]
Really an oversight on my part because if the lot isn't live we don't show the user the value they would potentially setting a max bid towards.

**Comment by ashfurrow** [comment]
Fixed in 1598edb.
