### ISSUE TITLE
Remove banner image from partners at fair view

### ISSUE THREAD

**Issue by katarinabatina** [artsy/eigen#155]
Also remove map button from this view and make same dimension changes on map preview as artist at fair 

![image](https://cloud.githubusercontent.com/assets/6482926/6155972/12004f70-b204-11e4-8254-28dd19a28604.png)

**Comment by orta** [comment]
@katarinabatina to be certain, this should not affect the show view? ( They are the same thing right now )

**Comment by katarinabatina** [comment]
Correct, this is just for fairs


[A.] Katarina Batina

Artsy <http://artsy.net/>


katarina@artsymail.com

                @katarina_batina <https://twitter.com/katarina_batina>

253 225 5812

**Comment by katarinabatina** [comment]
actually, can we just hide it when there aren't instal shots?

**Comment by orta** [comment]
Sure, that's basically removing the ability to show Artwork Images in any show page.
