### ISSUE TITLE
Adjustment to iphone onboarding flow 

### ISSUE THREAD

**Issue by katarinabatina** [artsy/eigen#156]
current 
![image](https://cloud.githubusercontent.com/assets/6482926/6156084/15905f94-b205-11e4-9c08-adaa77e6ee2d.png)

change to 
![image](https://cloud.githubusercontent.com/assets/6482926/6156090/1d9f5d98-b205-11e4-84eb-9548b238a834.png)

**Comment by alloy** [comment]
Currently looks like:

![Uploading iOS Simulator Screen Shot 29 Jun 2015 20.52.56.png…]()

I assume this change still needs to be applied.

**Comment by katarinabatina** [comment]
haha oops, lets close this one and stick with the update one I posted
