### ISSUE TITLE
Feedback 'From: Ash Furrow Hide scrollbar on expanded lot...'

### ISSUE THREAD

**Issue by artsyit** [artsy/eigen#1564]
### Message from Ash Furrow sent on 2016-05-28 00:47:35 UTC###

> From: Ash Furrow
> 
> Hide scrollbar on expanded lot info.

### Link to HockeyApp ###

* [https://rink.hockeyapp.net/manage/apps/37020/feedback/557611](https://rink.hockeyapp.net/manage/apps/37020/feedback/557611)

**Comment by katarinabatina** [comment]
working
