### ISSUE TITLE
Feedback 'From: Sarah Scott article title missing'

### ISSUE THREAD

**Issue by artsyit** [artsy/eigen#1565]
### Message from 54e0ff6b7261692c49d10000 sent on 2016-05-28 01:42:38 UTC###

> From: Sarah Scott
> 
> article title missing

### Link to HockeyApp ###

* [https://rink.hockeyapp.net/manage/apps/37020/feedback/557620](https://rink.hockeyapp.net/manage/apps/37020/feedback/557620)

**Comment by alloy** [comment]
Moving to https://github.com/artsy/emission/issues/130.
