### ISSUE TITLE
Lot information QA

### ISSUE THREAD

**Issue by katarinabatina** [artsy/eigen#1568]
Current: 

![image](https://cloud.githubusercontent.com/assets/6482926/15633607/5c368c72-257f-11e6-8c24-5a42e0b45429.png)

It looks like the view is partially transparent and partially solid (meaning sometimes you see the works in the background but when you scroll the background is solid white). 

Spec: If making this consistent poses a challenge I think it's ok to make the background of the expanded lot info totally white. 

![image](https://cloud.githubusercontent.com/assets/6482926/15633615/c12cc4b6-257f-11e6-847b-c680a84a7e3c.png)

The scroll view should also go all the way down to the status bar (if possible)

current:

![image](https://cloud.githubusercontent.com/assets/6482926/15633641/a1cba55a-2580-11e6-83ed-767d63f9ce6f.png)

spec: 
![image](https://cloud.githubusercontent.com/assets/6482926/15633643/a812f76a-2580-11e6-92fe-7643fef35c9b.png)

**Comment by orta** [comment]
Fixed.
