### ISSUE TITLE
Feedback 'From: Trial user Crashed when tapping Alex Katz...'

### ISSUE THREAD

**Issue by artsyit** [artsy/eigen#1570]
### Message from Orta sent on 2016-05-31 01:06:31 UTC###

> From: Trial user
> 
> Crashed when tapping Alex Katz' shows tab

### Link to HockeyApp ###

* [https://rink.hockeyapp.net/manage/apps/37020/feedback/559003](https://rink.hockeyapp.net/manage/apps/37020/feedback/559003)

**Comment by alloy** [comment]
See https://github.com/artsy/emission/issues/139
