### ISSUE TITLE
[Search] Opened view does not correctly inset top and bottom.

### ISSUE THREAD

**Issue by alloy** [artsy/eigen#1571]
E.g. an artist view:

![](https://cloud.githubusercontent.com/assets/2712962/15636307/52086cb8-25af-11e6-8684-90678c6f8197.jpg)

![](https://cloud.githubusercontent.com/assets/2320/15622892/f9b2cfc8-246d-11e6-95cd-f9ff1e240e70.png)

**Comment by mennenia** [comment]
Going to spend 1-2hrs on it this week. Otherwise I'm bucketing it under the re-doing of our status bar / top layout guide work (#1955).
