### ISSUE TITLE
Works for you QA

### ISSUE THREAD

**Issue by katarinabatina** [artsy/eigen#1572]
A few issues that have been outstanding since we launched works for you
- [x] Add "Contact for Price" underneath artworks that don't have visible pricing information
- [x] Margins for ipad should be 40px and all content (rules, labels, works) should live within those margins
  ![image](https://cloud.githubusercontent.com/assets/6482926/15680675/97cd4108-2724-11e6-8a3e-5a46903f4886.png)
- [x] Adjust vertical spacing between each of the artworks 
  ![image](https://cloud.githubusercontent.com/assets/6482926/15680685/9e4d9d2a-2724-11e6-862a-e2d0e4ef0f11.png)
- [x] Works masonry grid should operate as other masonry grids throughout the app. Right now the works sometimes center, sometimes extend the full content area (I remember this was a choice we made in order to ship but we should no revisit this to correct it. 
- [x] Artwork metadata should always be left aligned with the left edge of the artwork
  ![image](https://cloud.githubusercontent.com/assets/6482926/15680809/08d97cc2-2725-11e6-8fdd-1e8eb6c88c8b.png)

Larger summary with examples of how works for you currently looks and what adjustments should be made

![image](https://cloud.githubusercontent.com/assets/6482926/15680672/9403b73c-2724-11e6-8030-27254bb13027.png)

**Comment by sarahscott** [comment]
@katarinabatina, we use this artwork w/metadata view across the app. Would it be alright if the 'Contact For Price' label showed up for all available artworks without prices app-wide?

There is a useful `sale_message` field that we use on the home page for artworks that returns `null` for institutional works, "Contact For Price" for hidden-price works, and a dollar amount for priced works. Is there any reason not to use that?

**Comment by katarinabatina** [comment]
@sarahscott yes we SHOULD use the sale_message field, that's what I meant to say ;)
