### ISSUE TITLE
[Live] Handle migration to supporting two production/staging servers for causality

### ISSUE THREAD

**Issue by orta** [artsy/eigen#1578]
See [Causality#meta](https://github.com/artsy/causality#meta)

> Staging: https://causality-bidders-staging.artsy.net/ & https://causality-observers-staging.artsy.net/ | AWS

We will already know the bidder state when logging in, as that should be sent back by metaphysics, so when we create the socket - we can use that data

**Comment by devangt** [comment]
done for now. Individual updates will be tackled with new issues/epics
