### ISSUE TITLE
[Live] Update the Max bid UI to use a scroller instead of steppers

### ISSUE THREAD

**Issue by orta** [artsy/eigen#1579]
From https://github.com/artsy/eigen/issues/1102

> And we've come full circle in this issue, back we go to the scrolly picker! 
> ![image](https://cloud.githubusercontent.com/assets/6482926/15595429/0a9f1d28-238d-11e6-85f4-3fc99db4965d.png)

---

> ![image](https://cloud.githubusercontent.com/assets/6482926/15609578/d4c9a5bc-23ee-11e6-8325-396218fa91e2.png)

**Comment by katarinabatina** [comment]
I'm going to guess that getting this in would be a stretch for 2.6.1?

**Comment by alloy** [comment]
@ashfurrow Has this UI component been made before?

**Comment by ashfurrow** [comment]
Not that I'm aware of.

**Comment by orta** [comment]
#1737

**Comment by devangt** [comment]
done for now. Individual updates will be tackled with new issues/epics
