### ISSUE TITLE
Feedback 'From: Katarina Batina Bid in the bid history sh...'

### ISSUE THREAD

**Issue by artsyit** [artsy/eigen#1585]
### Message from katarina batina sent on 2016-06-01 21:31:03 UTC###

> From: Katarina Batina
> 
> Bid in the bid history should not exist

### Link to HockeyApp ###

* [https://rink.hockeyapp.net/manage/apps/37020/feedback/560256](https://rink.hockeyapp.net/manage/apps/37020/feedback/560256)

**Comment by katarinabatina** [comment]
Haven't seen again looks fixed
