### ISSUE TITLE
Register to bid from live bidding not working

### ISSUE THREAD

**Issue by katarinabatina** [artsy/eigen#1586]
1. Tap register to bid from live bidding UI
2. get sent to force
3. register to bid 
4. reg closes and i end up back on live bidding UI with bid button still telling me i need to register to bid
5. if I press register to bid again it just opens and shuts the force view, i see the spinner for a moment but that's it.

**Comment by katarinabatina** [comment]
closing an reopening the auction does not help to solve the problem

**Comment by ashfurrow** [comment]
This should be fixed with the work that Orta has.

**Comment by devangt** [comment]
done for now. Individual updates will be tackled with new issues/epics
