### ISSUE TITLE
Feedback 'From: Trial user I have a network connection by...'

### ISSUE THREAD

**Issue by artsyit** [artsy/eigen#1587]
### Message from Unknown User sent on 2016-06-01 21:36:13 UTC###

> From: Trial user
> 
> I have a network connection by I'm getting a 401

### Link to HockeyApp ###

* [https://rink.hockeyapp.net/manage/apps/37020/feedback/560259](https://rink.hockeyapp.net/manage/apps/37020/feedback/560259)

**Comment by ashfurrow** [comment]
Issue moved to [artsy/auctions #190](https://github.com/artsy/auctions/issues/190) via [**ZenHub**](https://www.zenhub.com/)
