### ISSUE TITLE
Socket, trying to disconnect, is never deallocated and continues to attempt reconnection forever

### ISSUE THREAD

**Issue by ashfurrow** [artsy/eigen#1589]
Steps:

1. Open live auction view controller in a state that the socket will connect, then disconnect. 
1. Navigate away from the auction view controller.
1. Logs indicate that the socket continues to try to reconnect, over and over.

**Comment by orta** [comment]
I think I fixed this as a side-effect of https://github.com/artsy/eigen/pull/1580 - `viewDid/WillDisappear` was never called on the whole nav hierarchy - now it's done manually - https://github.com/artsy/eigen/blob/master/Artsy/View_Controllers/Live_Auctions/LiveAuctionViewController.swift#L131-L144

**Comment by ashfurrow** [comment]
Interesting! Didn't know that about split view controllers. I'll double check this tomorrow.
