### ISSUE TITLE
UI Issues for Live Auctions

### ISSUE THREAD

**Issue by ashfurrow** [artsy/eigen#1591]
- [x] X button missing again.
- [ ] Buyer's Premium view on iPad is zoomable, content too small.
- [x] Remove watchers placeholder, getting cut for mvp.
- [ ] When closing the bid history, the bid history should scroll to the top so new events show up.
- [ ] ~~Empty descriptions still show the "Description" header.~~
- [ ] ~~Additional Information not shown.~~
- [ ] Lot list should always scroll, even if the list doesn't fill the views (this is a collection view default, needs to be set explicitly).

**Comment by orta** [comment]
re:  `Additional Information not shown.`

This is working perfectly with `los-angeles-modern-auctions-march-2015`

**Comment by orta** [comment]
re: ` Empty descriptions still show the "Description" header.`

Might have been the build, should be fixed

**Comment by ashfurrow** [comment]
Issue moved to [artsy/auctions #189](https://github.com/artsy/auctions/issues/189) via [**ZenHub**](https://www.zenhub.com/)
