### ISSUE TITLE
Jump to Current Lot not showing on non-current lots

### ISSUE THREAD

**Issue by orta** [artsy/eigen#1595]
![screen shot 2016-06-02 at 3 04 11 pm](https://cloud.githubusercontent.com/assets/49038/15757394/57c4b0c2-28d3-11e6-8c53-a995227d2cf2.png)

Lot at index 1 is definitely open.

**Comment by ashfurrow** [comment]
Have not been able to reproduce, this could be due to inconsistent staging data. Let's keep an eye on it.

**Comment by orta** [comment]
We think this is something that you don't see if you're not registered for an auction, cause I went from being not-logged in, where I didn't see it, to logged in where I did.

**Comment by orta** [comment]
#1638 should fix this

**Comment by devangt** [comment]
Verified! 
<img width="395" alt="screenshot 2016-06-12 18 17 30" src="https://cloud.githubusercontent.com/assets/753098/15994141/f68717c4-30c9-11e6-84c3-02a0d4fc6a53.png">
