### ISSUE TITLE
Ausstellungsdauer naming

### ISSUE THREAD

**Issue by orta** [artsy/eigen#16]
https://github.com/artsy/eigen/blob/master/Artsy/Classes/Categories/Apple/NSDate+DateRange.m

Might make sense to move category name to `dateRangeToDate`. It's been refactored out of it's original context. 

/thanks @ tangphillip

**Comment by 1aurabrown** [comment]
what about `dateRangeToString` ? or `dateRangeAsString` ?

**Comment by 1aurabrown** [comment]
i still like `austellungsdauer`

**Comment by orta** [comment]
Me too. It's staying.

**Comment by alloy** [comment]
Didn’t know this was up for debate before, I’m not a fan, I always have to look it up.
