### ISSUE TITLE
Network calls failing due to NECP policy.

### ISSUE THREAD

**Issue by alloy** [artsy/eigen#1601]
```
Jun  3 12:02:43 Carter-Clevelands-iPhone-6 Artsy[3299] <Error>: tcp_connection_handle_connect_conditions_bad 20 failed: 2 - Path was denied by NECP policy
Jun  3 12:02:43 Carter-Clevelands-iPhone-6 Artsy[3299] <Critical>: 2016-06-03 12:02:43.423 [ERROR] | Couldn't get an Xapp token.
Jun  3 12:02:43 Carter-Clevelands-iPhone-6 Artsy[3299] <Debug>: [Can't reach Artsy.] {
        description = "Can\U2019t reach Artsy.";
        failureReason = "(empty)";
        recoveryOptions = "(empty)";
        recoverySuggestion = "(empty)";
    }
```

**Comment by alloy** [comment]
This is pretty much the _only_ thing I can find on the topic http://forum.unity3d.com/threads/ios-9-cellular-data-error.357779/#post-2318300, which links to http://forum.unity3d.com/threads/ios-9-cellular-data-error.357779/#post-2318300, and eventually to http://apple.stackexchange.com/questions/206484/cant-modify-selection-of-use-cellular-data-for-for-some-apps-in-iphone-6-afte.

What that issue says is that mobile data is disabled for the app in either of the below settings screens. If I disable it on my device I do indeed get the same error message:

```
Jun 10 17:10:57 Eloy-Durans-iPhone-5S Artsy[666] <Error>: tcp_connection_handle_connect_conditions_bad 12 failed: 2 - Path was denied by NECP policy
```

Alas the issue is essentially about the settings DB being corrupted and it being impossible to re-enable data access. The only way appears to be to restore your device from a backup _before_ the issue started occurring. 

#### Settings -> Mobile Data -> USE MOBILE DATA FOR:

![img_7831](https://cloud.githubusercontent.com/assets/2320/15969150/ff7d2f5e-2f2e-11e6-9cfd-6aec551fe7c3.PNG)

#### Settings -> Artsy

![img_7832](https://cloud.githubusercontent.com/assets/2320/15969151/01719e12-2f2f-11e6-89af-75cf3ef81616.PNG)

**Comment by alloy** [comment]
@carterac / @katarinabatina Can you confirm whether or not this is the case?

**Comment by katarinabatina** [comment]
@alloy yup, mobile data was switched off for Artsy on Carter's settings

**Comment by orta** [comment]
Aww that's a shame
