### ISSUE TITLE
release notes and screen shots 2.5

### ISSUE THREAD

**Issue by katarinabatina** [artsy/eigen#1603]
Copy:

We’re excited to introduce a brand new way to discover and follow artists with the entirely redesigned Artist Profile. Never miss an important show, news article, or new works by artists you love. Get a list of where the artist is currently exhibiting and never let another work by an artist you’re interested in pass you by. With Art Basel and Design Miami/ Basel around the corner, you won’t want to miss out on this exciting update.

update screen shot for artist view, switch out 
![image](https://cloud.githubusercontent.com/assets/6482926/15791318/abf072fe-29a4-11e6-8eb4-1e227ee89a88.png)

in favor of 

![2 4 2 artist iphone6](https://cloud.githubusercontent.com/assets/6482926/15791329/b8375366-29a4-11e6-93a0-57e11308c2f7.png)

all screen shots here--> http://cl.ly/2Z2g2O3C2P2J

**Comment by orta** [comment]
This is in.
