### ISSUE TITLE
Sharing URLs can be m.artsy.net instead of artsy.net

### ISSUE THREAD

**Issue by orta** [artsy/eigen#161]
I did some pintrest sharing, and found that we had no metadata on the martsy version

**Comment by 1aurabrown** [comment]
so when sharing they should always be artsy.net and not m.artsy.net, right?

**Comment by alloy** [comment]
Yeah definitely, because artsy.net will redirect you to martsy anyways, so using the artsy.net URL will make sure that people always go to the right place, regardless of platform.

**Comment by alloy** [comment]
Ah, missed the part where you already submitted a PR 😁
