### ISSUE TITLE
Feedback 'From: Eloy Durán "1 Followers" should be singular.'

### ISSUE THREAD

**Issue by artsyit** [artsy/eigen#1613]
### Message from Eloy Durán sent on 2016-06-04 22:26:31 UTC###

> From: Eloy Durán
> 
> "1 Followers" should be singular.

### Link to HockeyApp ###

* [https://rink.hockeyapp.net/manage/apps/37020/feedback/561769](https://rink.hockeyapp.net/manage/apps/37020/feedback/561769)

**Comment by alloy** [comment]
Moved to Emission.
