### ISSUE TITLE
Live UI: If user not registered, bid button should say register to bid

### ISSUE THREAD

**Issue by katarinabatina** [artsy/eigen#1622]

**Comment by orta** [comment]
We determine most of this state based on whether we get a bidderID from metaphysics, perhaps they are now always coming in?

**Comment by orta** [comment]
I understand now, a `bidderID` is per-user, so you can have a bidder ID from having registered at another auction.

**Comment by orta** [comment]
#1638 should fix this

**Comment by devangt** [comment]
done for now. Individual updates will be tackled with new issues/epics
