### ISSUE TITLE
Live UI: Reserve met not met status for user

### ISSUE THREAD

**Issue by katarinabatina** [artsy/eigen#1623]
Reserve exists, but is not met

![image](https://cloud.githubusercontent.com/assets/6482926/15834120/db4d789e-2bf7-11e6-8fee-57c143a29845.png)

Reserve exists, and is met
![image](https://cloud.githubusercontent.com/assets/6482926/15834135/eb1b2758-2bf7-11e6-9af2-f930e3188155.png)

There is no reserve
![image](https://cloud.githubusercontent.com/assets/6482926/15834140/f4e2b364-2bf7-11e6-9190-a7d042455d7e.png)

![image](https://cloud.githubusercontent.com/assets/6482926/15834195/362f5f8e-2bf8-11e6-8ab8-1b1f4e49271a.png)

**Comment by devangt** [comment]
done for now. Individual updates will be tackled with new issues/epics
