### ISSUE TITLE
Registration status for bidders

### ISSUE THREAD

**Issue by katarinabatina** [artsy/eigen#1626]
We will now need to support two new instances in the bid registration status of users.

Partners can now:

1. Close registration at a certain point, likely 24-48hrs before a live sale begins
2. Choose to pre-approve every single bidder that wants to register.

Both these instances can happen at once. 

Below is a spec for what we should show in each instance

![image](https://cloud.githubusercontent.com/assets/6482926/15843535/d5b4d31c-2c30-11e6-8ab0-59fe450924a7.png)

If the bidder is approved, then that state "wins" regardless if registration closes prior to the sale going live or not.

**Comment by katarinabatina** [comment]
- [ ] Native auction sale page
- [ ] Sale information modal
- [ ] Live Bidding UI bid button
- [ ] Native artwork bid button

**Comment by orta** [comment]
As a part of this, we should add [another command](https://github.com/artsy/eigen/blob/master/Artsy/Networking/Live_Auctions/LiveAuctionSocketCommunicator.swift#L126-L154) that re recognize whose job it is to force a refresh. Thinking that maybe `"ConnectionRefresh"` could be the trigger? 

/cc @acjay

**Comment by acjay** [comment]
Works for me, or perhaps `HardRefresh`, just to emphasize that the intention is to reload the whole experience.

**Comment by orta** [comment]
👍

**Comment by orta** [comment]
@craigspaeth / @acjay any idea how I can determine this data? Would it come inside the JWT?

**Comment by orta** [comment]
Data should be in gravity already

**Comment by katarinabatina** [comment]
@orta I'm afraid we do need to change the status of the bid button on the artwork pages as follows

Logged out Experience: 
![image](https://cloud.githubusercontent.com/assets/6482926/15863607/b06d41fe-2ca1-11e6-89da-d23e12c0180e.png)

Logged In:
![image](https://cloud.githubusercontent.com/assets/6482926/15863615/bccae096-2ca1-11e6-9832-8a73b76d94cc.png)

**Comment by katarinabatina** [comment]
If the user is approved, the we give them the standard bid button
![image](https://cloud.githubusercontent.com/assets/6482926/15863822/8a3fe2f6-2ca2-11e6-980c-3e370bdc3122.png)

If this is the type of auction where registration actually closes at some point then we show the following 
![image](https://cloud.githubusercontent.com/assets/6482926/15863850/9e0d6eac-2ca2-11e6-82b6-ec0172a909df.png)

**Comment by acjay** [comment]
@orta In case your question was still open, "yet to register" would be the absence of a `Bidder` model from Gravity, and also the `observer` role being assigned, "sent registration in a pre-approval auction" would be the presences of a `Bidder` model, with `qualified_for_bidding: false` , which would be `true` if approved.

**Comment by orta** [comment]
#1654 gets half of this done, waiting on https://github.com/artsy/prediction/pull/263 to be deploy'd to work on the live section

**Comment by ashfurrow** [comment]
Going to take on the next half.

**Comment by orta** [comment]
@ashfurrow you wanna do this TODO too - https://github.com/artsy/eigen/pull/1661/files#diff-6d73ebd58fdd2d00c32813f60608fbd1R111

**Comment by devangt** [comment]
done for now. Individual updates will be tackled with new issues/epics
