### ISSUE TITLE
waiting for auctioneer state missing on first lot

### ISSUE THREAD

**Issue by katarinabatina** [artsy/eigen#1628]
![image](https://cloud.githubusercontent.com/assets/6482926/15838093/48cd51ca-2c0a-11e6-9604-7d3f09be48b0.png)

when the auction opens but has not started yet the first lot should say waiting for auctioneer

**Comment by katarinabatina** [comment]
![image](https://cloud.githubusercontent.com/assets/6482926/15839366/f94250ea-2c10-11e6-8742-ff9f0e43aea9.png)

**Comment by orta** [comment]
This is a side-effect of https://github.com/artsy/eigen/issues/1651 - closing as dupe
