### ISSUE TITLE
Bid history events coming in out of order

### ISSUE THREAD

**Issue by katarinabatina** [artsy/eigen#1632]
gif 
http://cl.ly/200z0O1y1b1U

![image](https://cloud.githubusercontent.com/assets/6482926/15838416/eb02fd7c-2c0b-11e6-87f1-470d8ab0f42f.png)

**Comment by orta** [comment]
maybe we just have to order them by date before presenting

**Comment by katarinabatina** [comment]
Probably worth asking Sarah how she tackled it for web 

Sent with thumbs,
Katarina Batina 
Product Designer
Artsy.net

**Comment by orta** [comment]
This _may_ be fixed from https://github.com/artsy/eigen/pull/1642 and https://github.com/artsy/eigen/pull/1640

**Comment by devangt** [comment]
done for now. Individual updates will be tackled with new issues/epics
