### ISSUE TITLE
Feedback 'From: orta@artsymail.com I got stuck like this,...'

### ISSUE THREAD

**Issue by artsyit** [artsy/eigen#1634]
### Message from 4ec92ccb56ae88000100038e sent on 2016-06-06 21:40:45 UTC###

> From: orta@artsymail.com
> 
> I got stuck like this, wonder what the state is

### Link to HockeyApp ###

* [https://rink.hockeyapp.net/manage/apps/37020/feedback/562571](https://rink.hockeyapp.net/manage/apps/37020/feedback/562571)

**Comment by katarinabatina** [comment]
@orta can't get access to the hockey images can you explain more or close if you think we've got it covered?

**Comment by ashfurrow** [comment]
I've attached the image, should be resolved already:

![asset png](https://cloud.githubusercontent.com/assets/498212/16080418/bbd3dd92-32d6-11e6-8339-9f6df1ea6ed2.jpeg)

**Comment by ashfurrow** [comment]
Issue moved to [artsy/auctions #188](https://github.com/artsy/auctions/issues/188) via [**ZenHub**](https://www.zenhub.com/)
