### ISSUE TITLE
Reflect proper bid history events to user

### ISSUE THREAD

**Issue by katarinabatina** [artsy/eigen#1637]
Your Bid and the state changes related to that bid history entry are not currently working 

![image](https://cloud.githubusercontent.com/assets/6482926/15839716/ee7fa016-2c12-11e6-9404-491546af24bc.png)

**Comment by katarinabatina** [comment]
ref #1082

**Comment by orta** [comment]
This is in with https://github.com/artsy/eigen/pull/1642
