### ISSUE TITLE
Use SellingToBidder to determine whether current bidder is outbid

### ISSUE THREAD

**Issue by devangt** [artsy/eigen#1644]
Internalize causality change: https://github.com/artsy/causality/pull/195

**Comment by ashfurrow** [comment]
This was addressed in https://github.com/artsy/eigen/pull/1653

**Comment by ashfurrow** [comment]
Issue moved to [artsy/auctions #187](https://github.com/artsy/auctions/issues/187) via [**ZenHub**](https://www.zenhub.com/)
