### ISSUE TITLE
Live lot should be ArtsyPurple in lost list view on iPad

### ISSUE THREAD

**Issue by katarinabatina** [artsy/eigen#1646]
![image](https://cloud.githubusercontent.com/assets/6482926/15874174/f8c6da5e-2ccf-11e6-98ed-3a72738c06bc.png)

**Comment by orta** [comment]
I _think_ this is also a side-effect of https://github.com/artsy/eigen/issues/1651 - I've not seen this anywhere in-app. Not closing but moving to QA for validation.

**Comment by ashfurrow** [comment]
Issue moved to [artsy/auctions #186](https://github.com/artsy/auctions/issues/186) via [**ZenHub**](https://www.zenhub.com/)
