### ISSUE TITLE
Bid button state: loading

### ISSUE THREAD

**Issue by katarinabatina** [artsy/eigen#1648]
In between the time that we've sent a bid to the server and we get an answer back, in lieu of showing Bidding OR bid sent we should use our standard spinner. There is currently some confusion for the user as to how to interpret that stat and our standard animated spinner may do a better job of communicating "fetching or loading" 

![image](https://cloud.githubusercontent.com/assets/6482926/15874747/a90aa808-2cd2-11e6-8cd8-ed2af2910e41.png)

**Comment by ashfurrow** [comment]
Cool, we can prioritize tomorrow morning during triage, but it shouldn't be too difficult. We can roll it into the changes we're making to causality/prediction/eigen tomorrow afternoon.

**Comment by katarinabatina** [comment]
related to #1711

**Comment by devangt** [comment]
done for now. Individual updates will be tackled with new issues/epics
