### ISSUE TITLE
[Live Lot] Showing "Current Bid" for closed lots doesn't make sense

### ISSUE THREAD

**Issue by orta** [artsy/eigen#1657]
![img_0105](https://cloud.githubusercontent.com/assets/49038/15911723/012ccc88-2d9f-11e6-8c59-60e5ab2a84bd.PNG)

ATM we currently show "current bid" which I think it is the cost of the next possible bid, I think for closed sales it should probably be something like "Went for: Xx,xxx" ( or whatever )

**Comment by katarinabatina** [comment]
Where is the estimate? I notice that is missing now...
![image](https://cloud.githubusercontent.com/assets/6482926/15916874/2074430c-2dc5-11e6-88f5-90bb43aa0386.png)

when the lot has been closed it should not say anything, the current/starting bid should simply be removed

**Comment by devangt** [comment]
Verified on latest beta.
