### ISSUE TITLE
first tap on map point does not reveal map point preview

### ISSUE THREAD

**Issue by katarinabatina** [artsy/eigen#166]
go to map, zoom in, tap a point, no point preview, partner name disappears

**Comment by katarinabatina** [comment]
http://cl.ly/2M1C252A240x

**Comment by alloy** [comment]
I was able to reproduce this earlier this weekend, but haven’t been able to do so today. Is there a specific special step I _have_ to take to trigger this? Otherwise, can you please try it again once #167 is merged?

**Comment by orta** [comment]
Tested on a device> ( I'm seeing it good on iOS7 sim too )

**Comment by alloy** [comment]
@orta Now that #167 has been merged, can you still reproduce it?

**Comment by orta** [comment]
Yes, on device, you load it up, and it's still loading the fair shows, then when its done them the firs click is just a purple circle

**Comment by alloy** [comment]
Ok I can easily reproduce it now, but only on iOS 8.
