### ISSUE TITLE
Feedback 'From: Orta Bid countdown doesn't fit well in la...'

### ISSUE THREAD

**Issue by artsyit** [artsy/eigen#1678]
### Message from 54e0ff6b7261692c49d10000 sent on 2016-06-10 17:12:44 UTC###

> From: Orta
> 
> 
> Bid countdown doesn't fit well in landscape iPad

### Link to HockeyApp ###

* [https://rink.hockeyapp.net/manage/apps/37020/feedback/564741](https://rink.hockeyapp.net/manage/apps/37020/feedback/564741)

**Comment by ashfurrow** [comment]
Issue moved to [artsy/auctions #185](https://github.com/artsy/auctions/issues/185) via [**ZenHub**](https://www.zenhub.com/)
