### ISSUE TITLE
Live lot should be shown when Live lot is opened 

### ISSUE THREAD

**Issue by katarinabatina** [artsy/eigen#1679]
Launch live bidding experience, see the following lot 

![image](https://cloud.githubusercontent.com/assets/6482926/15974060/86cb0b22-2f14-11e6-8871-faba42cbe10a.png)

**Comment by ashfurrow** [comment]
This should be fixed in the latest beta, please confirm.

**Comment by devangt** [comment]
verified that this was fixed on latest build.
