### ISSUE TITLE
Live UI: I shouldn't be able to outbid myself

### ISSUE THREAD

**Issue by katarinabatina** [artsy/eigen#1682]
![image](https://cloud.githubusercontent.com/assets/6482926/15974367/1020b736-2f16-11e6-8167-983ca3471bab.png)

**Comment by ashfurrow** [comment]
This is related to the fix @acjay put in: https://github.com/artsy/causality/pull/209

**Comment by devangt** [comment]
Keeping as Critical P0 and will mitigate on causality side.

**Comment by devangt** [comment]
done for now. Individual updates will be tackled with new issues/epics
