### ISSUE TITLE
Live UI: Don't tell users they are outbid when a jump bid comes through that is lower than highest online ask

### ISSUE THREAD

**Issue by katarinabatina** [artsy/eigen#1684]
When a jump bid comes through and it is lower than my highest bid we should not tell the user they are outbid.

**Comment by ashfurrow** [comment]
This and the related issues should be fixed by https://github.com/artsy/eigen/pull/1685 and @acjay's work on Causality

**Comment by devangt** [comment]
Keeping as critical show stopper and will review when the causality fix comes in.

**Comment by ashfurrow** [comment]
I think this is a problem with how we infer the user has been outbid, which is when the button state goes from "became the highest bidder" to "biddable". I don't know if it's possible to have a state in between those two that breaks our flow, but we should be relying on the "Outbidded" state instead. /cc @orta

**Comment by ashfurrow** [comment]
Based on Causality's deploy last night (thanks for the quick fix on a Friday afternoon @acjay!) it looks like we're getting consistent results now. The bid history events indicate the correct states for the auction, so getting the bid button to behave similarly shouldn't be difficult. 

## Current Behaviour

Haven't bid yet:

<img width="487" alt="screen shot 2016-06-11 at 8 57 45 am" src="https://cloud.githubusercontent.com/assets/498212/15985166/af7d4b7c-2fb2-11e6-9384-4b31b55102af.png">

Bid, hasn't yet been accepted:

<img width="487" alt="screen shot 2016-06-11 at 8 57 47 am" src="https://cloud.githubusercontent.com/assets/498212/15985168/c507c86e-2fb2-11e6-8b2c-b6eaef9657b4.png">

Bid has been accepted:

<img width="487" alt="screen shot 2016-06-11 at 8 57 50 am" src="https://cloud.githubusercontent.com/assets/498212/15985169/ca63ee00-2fb2-11e6-978c-2e5363a90e31.png">

Outbid:

<img width="487" alt="screen shot 2016-06-11 at 9 00 16 am" src="https://cloud.githubusercontent.com/assets/498212/15985173/d42e06be-2fb2-11e6-9e9b-92cf3e662a0c.png">

A fix for this issue should involve just changing the second state, where the bid hasn't yet been accepted. I'll take a look asap.

**Comment by devangt** [comment]
done for now. Individual updates will be tackled with new issues/epics
