### ISSUE TITLE
Bid Button Highest Bidder State

### ISSUE THREAD

**Issue by katarinabatina** [artsy/eigen#1686]
Before the lot goes live, if I place a max bid and get the success state int the max bid modal, than I should see a green you are the highest bidder button instead of just the bid button.

I get this

![image](https://cloud.githubusercontent.com/assets/6482926/15974939/111ec5c6-2f19-11e6-8688-b85b7996f221.png)

then I get this 
![image](https://cloud.githubusercontent.com/assets/6482926/15974947/18720108-2f19-11e6-8c93-3af49c291628.png)

that bid button should say you are the highest bidder and be "disabled"

**Comment by acjay** [comment]
Probably an Ash ticket

**Comment by devangt** [comment]
done for now. Individual updates will be tackled with new issues/epics
