### ISSUE TITLE
Live UI: Lot that is skipped should not show up in the lot list in order

### ISSUE THREAD

**Issue by katarinabatina** [artsy/eigen#1687]
![image](https://cloud.githubusercontent.com/assets/6482926/15975036/7a8407a6-2f19-11e6-8719-fa5e132141ed.png)

Lot 19 should be put at the back or bottom of the list instead of staying in order.

**Comment by ashfurrow** [comment]
We discussed this in triage last week and decided to go with the current behaviour. Did that decision change?

**Comment by devangt** [comment]
This is bad but not a critical show stopper.

**Comment by ashfurrow** [comment]
Issue moved to [artsy/auctions #184](https://github.com/artsy/auctions/issues/184) via [**ZenHub**](https://www.zenhub.com/)
