### ISSUE TITLE
Live UI: Link redirect to live ui not working from embeded martsy view

### ISSUE THREAD

**Issue by katarinabatina** [artsy/eigen#1689]
Shouldn't say its "not working" but I don't get an accurate state of the sale when it opens
tap here
![image](https://cloud.githubusercontent.com/assets/6482926/15975157/20a322ca-2f1a-11e6-8ba9-04fe8b2e6f20.png)
get this
![image](https://cloud.githubusercontent.com/assets/6482926/15975150/1a192b70-2f1a-11e6-8a81-99a61b6228c6.png)

**Comment by orta** [comment]
This one is complicated, we have metaphysics data, but can't connect to causality

**Comment by orta** [comment]
I noted this  here: https://github.com/artsy/eigen/issues/1633

**Comment by acjay** [comment]
Closing as dupe, also loading state, feel free to reopen if I'm wrong
