### ISSUE TITLE
Live: Outbid state did not come through, bid events out of order

### ISSUE THREAD

**Issue by katarinabatina** [artsy/eigen#1695]
![image](https://cloud.githubusercontent.com/assets/6482926/15978831/9b8d1356-2f2e-11e6-821a-24c6385b66c2.png)

currently the highest bid 19,500, I should have been outbid at 18,500 and told I was outbid with a red "your bid" state

**Comment by katarinabatina** [comment]
see web 

![image](https://cloud.githubusercontent.com/assets/6482926/15978866/c6402548-2f2e-11e6-8424-4f6562d0a9e0.png)

**Comment by devangt** [comment]
Keeping as critical as the user is told the wrong message

**Comment by devangt** [comment]
Verified!

**Comment by devangt** [comment]
done for now. Individual updates will be tackled with new issues/epics
