### ISSUE TITLE
Live: Number of bids is incorrect

### ISSUE THREAD

**Issue by katarinabatina** [artsy/eigen#1697]
![image](https://cloud.githubusercontent.com/assets/6482926/15979137/24961426-2f30-11e6-9fb5-3513c9f0afbe.png)

true bid count is 
![image](https://cloud.githubusercontent.com/assets/6482926/15979146/2fdf9636-2f30-11e6-843d-20e07b4c7f8b.png)

**Comment by devangt** [comment]
Really bad. But not show stopper. Keeping P0.
