### ISSUE TITLE
Menu isn't reflowing to 3 equal widths on iPad rotation

### ISSUE THREAD

**Issue by orta** [artsy/eigen#17]
_From @orta on January 16, 2015 20:14_

Went from Portrait to Landscape

![screen shot 2015-01-16 at 3 12 59 pm](https://cloud.githubusercontent.com/assets/49038/5783595/609f14da-9d92-11e4-9240-374d4912dbd7.png)

_Copied from original issue: artsy/eigen-private#2128_

**Comment by 1aurabrown** [comment]
This has been fixed for iOS8, and i took out the code that was specific to iOS7. Can someone confirm this on a device?Sent using CloudMagicOn Wed, Mar 25, 2015 at 16:10,  artsy/eigen <reply@reply.github.com> wrote:            Assigned #17 to @1aurabrown.

**Comment by alloy** [comment]
I’ll verify this on my iPad later today.

**Comment by 1aurabrown** [comment]
this is iOS7 only, so i'm closing
