### ISSUE TITLE
Release notes and screen shots for 2.5.1

### ISSUE THREAD

**Issue by katarinabatina** [artsy/eigen#1706]
Going once, going twice, SOLD! Introducing Artsy Live Auctions, a new way to bid in real time in auctions happening around the world. Compete with bidders on the auction room floor of Sotheby’s, Phillips and many more premier auction houses. No need for you to raise your paddle for the auctioneer to see you, simply register, set your max bid, and let Artsy do your bidding for you.   

screen shots here
http://cl.ly/2q1E3z470E3g

should be shown in iTunes in the following order
![image](https://cloud.githubusercontent.com/assets/6482926/15996276/f10542e2-30f3-11e6-8db0-7c3326a46e8b.png)

**Comment by devangt** [comment]
Suggest we say top auction houses as opposed to names given contract sensitivities and PR announcements to come this week.

**Comment by alloy** [comment]
Hold-up, I need to get fixes into this release as well. Please do not deploy the current beta.

Also, this version should be 2.6.0, as we’re adding a new feature.

**Comment by ashfurrow** [comment]
I believe we only get five screenshots. @alloy ping me if I can help.

**Comment by alloy** [comment]
Ah yes, indeed, max 5 are allowed https://developer.apple.com/library/ios/documentation/LanguagesUtilities/Conceptual/iTunesConnect_Guide/Appendices/Properties.html#//apple_ref/doc/uid/TP40011225-CH26-SW2

**Comment by katarinabatina** [comment]
So many cool features, so little screen shots. Let's cut the last screen shot about shows.

**Comment by alloy** [comment]
Apple can’t handle our scale of awesomeness.

**Comment by ashfurrow** [comment]
![](http://gifs.ashfurrow.com/scale.gif)

**Comment by devangt** [comment]
👍
