### ISSUE TITLE
Bid Button Passed Lot State

### ISSUE THREAD

**Issue by katarinabatina** [artsy/eigen#1711]
If the lot has been passed show this 
![image](https://cloud.githubusercontent.com/assets/6482926/16059775/90a05ff8-3252-11e6-890e-b10f46190746.png)

If the lot sold show this
![image](https://cloud.githubusercontent.com/assets/6482926/16059768/8a0dffa6-3252-11e6-8d48-d0ae2ae16dab.png)

If causality doesn't make this distinction at all then we should just show this all the time
![image](https://cloud.githubusercontent.com/assets/6482926/16059798/a450acce-3252-11e6-84c1-908fae2bd993.png)

**Comment by katarinabatina** [comment]
Currently we show this which is very confusing 

![image](https://cloud.githubusercontent.com/assets/6482926/16059820/bb872102-3252-11e6-8a4f-d9b07b68de59.png)
 because the button does not look disabled

**Comment by acjay** [comment]
Probably an Ash ticket

**Comment by devangt** [comment]
verified
