### ISSUE TITLE
Artworks scale and zoom into weird mask, they should not 

### ISSUE THREAD

**Issue by katarinabatina** [artsy/eigen#1713]
The aspect ratio of this work is portrait
![image](https://cloud.githubusercontent.com/assets/6482926/16060709/27c305c6-3257-11e6-9970-203b9731e5fe.png)

But we seem to be squishing it into a square
![img_8806](https://cloud.githubusercontent.com/assets/6482926/16060665/f7cb1282-3256-11e6-8c7f-27cb110ee9d6.PNG)

**Comment by ashfurrow** [comment]
I've already submitted a PR to fix this, actually: https://github.com/artsy/eigen/pull/1709

**Comment by katarinabatina** [comment]
that's the best kind of issue, a non-issue! closing
