### ISSUE TITLE
Two lots selected at the same time

### ISSUE THREAD

**Issue by katarinabatina** [artsy/eigen#1714]
![image](https://cloud.githubusercontent.com/assets/6482926/16060937/6a039454-3258-11e6-9b65-05eb26a5b17d.png)

**Comment by ashfurrow** [comment]
Can you describe how you got the app into this state? Having trouble reproducing this bug.

**Comment by katarinabatina** [comment]
It was pretty inconsistent and I too can't repo but one thing that is true is the lot that is live is currently not noted in the (purple with the hammer) I wonder if somehow that purple state is lost somehow??

**Comment by ashfurrow** [comment]
That helps, I'll double-check that code.

**Comment by devangt** [comment]
still repros? @katarinabatina @ashfurrow

**Comment by katarinabatina** [comment]
i got this last week when i was testing on staging on the LAMA sale

[A.] Katarina Batina
Design Lead

Artsy <http://artsy.net/>


katarina@artsymail.com

                @katarinabatina <https://twitter.com/katarinabatina>

253 225 5812

**Comment by ashfurrow** [comment]
Issue moved to [artsy/auctions #172](https://github.com/artsy/auctions/issues/172) via [**ZenHub**](https://www.zenhub.com/)
