### ISSUE TITLE
Title missing from top of live UI

### ISSUE THREAD

**Issue by katarinabatina** [artsy/eigen#1715]
![image](https://cloud.githubusercontent.com/assets/6482926/16061035/003f84d2-3259-11e6-9fa0-634fa836d6c1.png)

**Comment by katarinabatina** [comment]
On a scale of 0 to hack how terrible would it be to only show any characters/words before ":" in the sale name to get this desired result--
![image](https://cloud.githubusercontent.com/assets/6482926/16067454/cd4eae36-328a-11e6-9496-16c1b3a8305c.png)

 Ideally the title was to be reserve for the partner names only but since the partner doesn't really exist I am wondering if we just make a rule that we only display everything before the colon of a sale name. We have a naming convention of "Partner: Sale name" therefore this system could work until we properly model auction houses as partners. Thoughts?

**Comment by ashfurrow** [comment]
It's not too difficult to do, if there is no `:` character, we'll display the full title, right?

**Comment by katarinabatina** [comment]
yup!

**Comment by acjay** [comment]
Probably an Ash issue

**Comment by acjay** [comment]
Uf, I'm not a huge fan of adding these sorts of behavioral wrinkles. If I weren't reading the ticket now, I'd have no idea that colons had special significance in the sale field. If we want to go this route temporarily, we should explicitly ticket a path back toward removing the special behavior.

**Comment by ashfurrow** [comment]
Makes sense, I think long-term we should be using the Sale's Partner's name, but Sale's don't always _have_ partners yet.

**Comment by acjay** [comment]
Or maybe just a Sale Mobile Title field. It's annoying to manage multiple titles, but at least it gives the operators full control, and would be entirely predictable. Many CMS systems have to do this to account for abbreviated versions of fields.

**Comment by acjay** [comment]
I notice in the view controller test, we're cutting off part of the partner name (https://github.com/artsy/eigen/blob/1ddb604b5fe7557c4e5ebbd6fa8636d22c7623a4/Artsy_Tests/ReferenceImages/LiveAuctionViewControllerTests/looks_good_by_default%402x.png). It makes me think there's got to be a better solution.

**Comment by katarinabatina** [comment]
There are lots of viable solutions but when we tried crossing this bridge months ago we ran into roadblocks of the partner not being the modeled correctly and deciding we weren't going to devote resources to addressing that in the short term (until we move to do CMS work). This was a stop-gab solution without having to do work in ohm or the backend.

**Comment by devangt** [comment]
done for now. Individual updates will be tackled with new issues/epics
