### ISSUE TITLE
Artist view should support swiping horizontally between works

### ISSUE THREAD

**Issue by katarinabatina** [artsy/eigen#1717]
current version does not support this.

**Comment by alloy** [comment]
This is going to require more extensive work than just re-enabling the previous state, as in the previous state it did not work as you’d expect. It would only cycle through the pages of artworks that were already loaded on the artist view.

E.g.
* Load previous Artist view for Andy Warhol, who was +1400 works.
* Do **NOT** scroll horizontal works view, i.e. only the first few pages of works are loaded.
* Select Artwork and swipe between works.
* After 20 works (2 pages) it wraps around and shows the first work again.

It would be expected that you can swipe through all +1400 works.

**Comment by orta** [comment]
I'd always wanted to make a `ArtworkSetEnumerator` object that you can pass to the VC that always knows how to paginate through a set of artworks, perhaps that's a good time for ti
