### ISSUE TITLE
Make all models consistently use the new `image_urls` property.

### ISSUE THREAD

**Issue by alloy** [artsy/eigen#172]
The JSON payload now includes a `image_urls` property which contains full URLs, meaning no interpolation is needed.

Related to #163 and https://github.com/artsy/eigen/pull/173.

**Comment by orta** [comment]
want this in the fairs milestone?

**Comment by alloy** [comment]
I was thinking to specifically delay this after all fairs stuff is done.

**Comment by orta** [comment]
:+1:

**Comment by alloy** [comment]
@1aurabrown This is still on-going, yeah?

**Comment by 1aurabrown** [comment]
yeah, haven't touched it in a little while
