### ISSUE TITLE
Fix NSRangeException in - [ARCollectionViewMasonryLayout layoutAttributesForItemAtIndexPath:], line 314

### ISSUE THREAD

**Issue by artsyit** [artsy/eigen#1722]
### Stacktrace (first of multiple) ###

<pre>ARCollectionViewMasonryLayout;layoutAttributesForItemAtIndexPath:;ARCollectionViewMasonryLayout.m;314
AREmbeddedModelsViewController;setActiveModule:;AREmbeddedModelsViewController.m;102
ARModernPartnerShowTableViewCell;configureWithFeedItem:;ARModernPartnerShowTableViewCell.m;166
ARFeedViewController;tableView:cellForRowAtIndexPath:;ARFeedViewController.m;155</pre>

### Reason ###

*** Terminating app due to uncaught exception 'NSRangeException', reason: '*** -[__NSArrayI objectAtIndex:]: index 0 beyond bounds for empty array'

### Link to HockeyApp ###

* [https://rink.hockeyapp.net/manage/apps/37029/crash_reasons/125167931](https://rink.hockeyapp.net/manage/apps/37029/crash_reasons/125167931)

**Comment by alloy** [comment]
Closing in favour of #917
