### ISSUE TITLE
Feedback 'From: Devang Thakkar Koller auction listing on ...'

### ISSUE THREAD

**Issue by artsyit** [artsy/eigen#1729]
### Message from 4f69f1819a717c0002001b6f sent on 2016-06-18 02:26:52 UTC###

> From: Devang Thakkar
> 
> Koller auction listing on artist page should say "bid now" as opposed to contact for price

### Link to HockeyApp ###

* [https://rink.hockeyapp.net/manage/apps/37020/feedback/570472](https://rink.hockeyapp.net/manage/apps/37020/feedback/570472)

**Comment by devangt** [comment]
Unpublished work. False alarm.
