### ISSUE TITLE
Update ArtworkVC for missing partner edge case

### ISSUE THREAD

**Issue by sarahscott** [artsy/eigen#1732]
It's possible for works to exist without partners; how should the artwork vc handle these cases?

**Comment by alloy** [comment]
Can you include an example artwork?

**Comment by sarahscott** [comment]
Here is one: 
https://api.artsy.net/api/v1/artwork/alexander-girard-an-uncommon-vision-installation-4

**Comment by katarinabatina** [comment]
@sarahscott could you add more context to this story?

**Comment by sarahscott** [comment]
It used to be a crasher, and then it was fixed. I think it's fine for now:

![img_1280](https://cloud.githubusercontent.com/assets/2712962/16766722/0e0208bc-483c-11e6-8274-496170614857.PNG)

**Comment by alloy** [comment]
Closing this for now.
