### ISSUE TITLE
Feedback 'From: Katarina Batina X button on this modal is...'

### ISSUE THREAD

**Issue by artsyit** [artsy/eigen#1739]
### Message from katarina batina sent on 2016-06-21 12:04:54 UTC###

> From: Katarina Batina
> 
> X button on this modal is out of place should be further over to the right

### Link to HockeyApp ###

* [https://rink.hockeyapp.net/manage/apps/37020/feedback/571887](https://rink.hockeyapp.net/manage/apps/37020/feedback/571887)

**Comment by ashfurrow** [comment]
Issue moved to [artsy/auctions #183](https://github.com/artsy/auctions/issues/183) via [**ZenHub**](https://www.zenhub.com/)
