### ISSUE TITLE
Fix NSUnknownKeyException in Artsy.LiveAuctionViewController.viewWillDisappear (Swift.Bool) -> (), line 187

### ISSUE THREAD

**Issue by artsyit** [artsy/eigen#1741]
### Stacktrace ###

<pre>-;Artsy.LiveAuctionViewController.viewWillDisappear (Swift.Bool) -> ();LiveAuctionViewController.swift;187
-;@objc Artsy.LiveAuctionViewController.viewWillDisappear (Swift.Bool) -> ();LiveAuctionViewController.swift;0</pre>

### Reason ###

*** Terminating app due to uncaught exception 'NSUnknownKeyException', reason: '[<Artsy.LiveAuctionViewController 0x121a3a5d0> valueForUndefinedKey:]: this class is not key value coding-compliant for the key _hiddenPopoverController.'

### Link to HockeyApp ###

* [https://rink.hockeyapp.net/manage/apps/37020/crash_reasons/125760922](https://rink.hockeyapp.net/manage/apps/37020/crash_reasons/125760922)

**Comment by orta** [comment]
This is an iOS 10 issue, can't hurt to prepare for it
