### ISSUE TITLE
[Explore] Ensure links don’t need to perform an extra HEAD request.

### ISSUE THREAD

**Issue by alloy** [artsy/eigen#1753]
We should define routes for those vanity URLs and just immediately route to the right location.

**Comment by alloy** [comment]
@ashfurrow We do this nowadays, right?

**Comment by alloy** [comment]
(Re-open if we don’t)

**Comment by orta** [comment]
We don't - there are too many now, it's literally any Profile ( which can effectively be attached to so many model objects )

**Comment by orta** [comment]
This is only for the ARMutableLinkViewController - https://github.com/artsy/eigen/blob/master/Artsy/View_Controllers/ARMutableLinkViewController.m

**Comment by alloy** [comment]
Isn’t that good enough?

**Comment by orta** [comment]
IMO Yes - just wanted to make sure everyone is on the same page
