### ISSUE TITLE
Lot numbers not sync'd with actual lot numbers

### ISSUE THREAD

**Issue by ashfurrow** [artsy/eigen#1755]
<img width="487" alt="screen shot 2016-06-25 at 7 44 40 am" src="https://cloud.githubusercontent.com/assets/498212/16356518/8859abe8-3aa8-11e6-834d-136b7ed65f17.png">

It says "Lot 1" instead of "Lot 3601" because we never expected lots to have numbers not starting at 1. 

You can see a similar change in prediction here: https://github.com/artsy/prediction/pull/320/files#diff-d2f132171d82eaee180e19c2b57c7ad3R34

**Comment by ashfurrow** [comment]
@katarinabatina probably needs some design around how to say "Lot 3601 / 155"

**Comment by devangt** [comment]
Closing as dupe of #1791
