### ISSUE TITLE
Feedback 'From: Rebecca Bronfein Raphael Many bids regist...'

### ISSUE THREAD

**Issue by artsyit** [artsy/eigen#1757]
### Message from 4f724768a7aaa900010003f4 sent on 2016-06-25 13:17:07 UTC###

> From: Rebecca Bronfein Raphael
> 
> Many bids registered quickly then crossed out.

### Link to HockeyApp ###

* [https://rink.hockeyapp.net/manage/apps/37029/feedback/574282](https://rink.hockeyapp.net/manage/apps/37029/feedback/574282)

**Comment by ashfurrow** [comment]
Issue moved to [artsy/auctions #182](https://github.com/artsy/auctions/issues/182) via [**ZenHub**](https://www.zenhub.com/)
