### ISSUE TITLE
vertical layout change for artwork view on ipad 

### ISSUE THREAD

**Issue by katarinabatina** [artsy/eigen#176]
![image 2015-02-16 at 2 32 20 pm](https://cloud.githubusercontent.com/assets/49038/6871086/9b859bd0-d476-11e4-8aa6-37189d8527d3.png)

**Comment by katarinabatina** [comment]
not sure what layout restrictions there are but it would be nice to get the share, save, view in room buttons on right hand column in the horizontal layout

**Comment by 1aurabrown** [comment]
not to self: also see https://github.com/artsy/eigen/issues/240, and ensure that the auction timer is laid out properly
