### ISSUE TITLE
[Rails] Artist

### ISSUE THREAD

**Issue by mennenia** [artsy/eigen#1760]
### Visual Spec:

<img width="1021" alt="screen shot 2016-06-27 at 15 22 43" src="https://cloud.githubusercontent.com/assets/373860/16381083/0d6892b2-3c7b-11e6-90b1-aa9a9fcd25f3.png">

Spacing detailed in #1440.

__Assumptions__:
- If we don't have the date/nationality string, the works count string will move up in its place, leaving a blank slot below, aligning the the follow buttons and keeping the size of the cards consistent. 

### Data work:
- [x] Metaphysics will need to support a `formatted_nationality_and_date_string` piece of data, as the string "American, b.1939" will be used in more than one place now. 
- [x] Metaphysics will need to support a `formatted_works_count_for_artist_string`. 

### Questions:
- If you tap an artist, do you go to the artist page or do you follow the artist? (i.e. is the whole cell tappable, if so which action). @katarinabatina 
- Is the year more important than the artist's nationality? E.g. if there's a long nationality name plus the year and there's a chance of it being clipped, do we clip or do we prioritise the date?

**Comment by katarinabatina** [comment]
Assumption about missing data/nationality string is correct 👍 

Q: If you tap an artist, do you go to the artist page or do you follow the artist? (i.e. is the whole cell tappable, if so which action)
A: Only the follow button follows the artist if you tap the entire card you get taken to the artist page

Q: Is the year more important than the artist's nationality? 
A: No, we can use standard truncation, e.g. Croatian b. 19...

**Comment by mennenia** [comment]
Thanks @katarinabatina!

**Comment by alloy** [comment]
This is done.
