### ISSUE TITLE
[Navigation] Routing "View All" to the correct pages

### ISSUE THREAD

**Issue by mennenia** [artsy/eigen#1761]
<img width="1023" alt="screen shot 2016-06-27 at 15 38 35" src="https://cloud.githubusercontent.com/assets/373860/16381511/419f8f8e-3c7d-11e6-9c4d-bd48b8b397de.png">

__Assumptions:__

- Works By Artists You Follow rail => works for you page
- Recently Saved rail => Favourites / "YOU" page, on artworks
- Gene rail => Gene view (with potential filters enabled, such as pricing)
	- Black and White Photography rail => Black and White Photography gene page
	- Minimalism under $10,000 => Minimalism gene page with price filter set to 0-10,000
- Art Fair Picks rail => Fair page, artworks tab/content
- Auction rail => Auction page with overview of artworks

@katarinabatina correct?

**Comment by katarinabatina** [comment]
Assumptions are correct!!!

**Comment by sarahscott** [comment]
@katarinabatina if the rail is for a user's active bids, should it have a View All button or should it just show the artworks that a user has bid on and be treated like other rails without additional content?

**Comment by alloy** [comment]
Seeing as we don’t have such a view yet, I would say that, for now at least, we only show it on the home view.

**Comment by katarinabatina** [comment]
To Eloy's point, no other view to take them to so no need for view all.

**Comment by alloy** [comment]
This is pretty much done, I moved the Gene budget filtering here https://github.com/artsy/eigen/issues/1293#issuecomment-244327547
