### ISSUE TITLE
[Rails] Artworks

### ISSUE THREAD

**Issue by sarahscott** [artsy/eigen#1762]
### Visual Spec:

![screen shot 2016-06-27 at 3 53 15 pm](https://cloud.githubusercontent.com/assets/2712962/16381988/4888257a-3c7f-11e6-82f4-48f75a953aae.png)

**Comment by alloy** [comment]
Also be sure to take all edge cases into account that are outlined in the design spec https://github.com/artsy/eigen/issues/1441.

**Comment by alloy** [comment]
This still needs to switch between 4 and 3 columns on iPad.

**Comment by sarahscott** [comment]
Closing - https://github.com/artsy/emission/pull/292
