### ISSUE TITLE
Extract & polish artwork component

### ISSUE THREAD

**Issue by sarahscott** [artsy/eigen#1764]
For artworks in an auction:

![screen shot 2016-06-27 at 3 56 09 pm](https://cloud.githubusercontent.com/assets/2712962/16382168/f15a0e0c-3c7f-11e6-9a03-7853808d1c49.png)

**Comment by katarinabatina** [comment]
Check-in with web what the status of getting data for this component is.

**Comment by alloy** [comment]
As can be seen [here](https://github.com/artsy/emission/issues/191#issuecomment-231088336), metaphysics does have ‘current bid’ information.

@katarinabatina Could you elaborate on what you thought was the issue?

**Comment by alloy** [comment]
We _are_ missing the bid count, I think. I guess we could use the `bid_increments` list for that and count the entries, but that feels like using a lot of bandwidth inefficiently.

**Comment by alloy** [comment]
Deferring in favour of https://github.com/artsy/emission/issues/282

**Comment by alloy** [comment]
Considering done.
