### ISSUE TITLE
Feedback 'From: Legacy Russell Error message appears when...'

### ISSUE THREAD

**Issue by artsyit** [artsy/eigen#1773]
### Message from 4f949c90357afa0001000091 sent on 2016-06-28 13:28:42 UTC###

> From: Legacy Russell
> 
> Error message appears when trying to view Phillips auction on iPhone app

### Link to HockeyApp ###

* [https://rink.hockeyapp.net/manage/apps/37029/feedback/575827](https://rink.hockeyapp.net/manage/apps/37029/feedback/575827)

**Comment by alloy** [comment]
@ashfurrow this one is known, right?

**Comment by orta** [comment]
Yep, think this was a bad redirect URL that got fixed

**Comment by alloy** [comment]
Ok, so close?

**Comment by orta** [comment]
Yes
