### ISSUE TITLE
Fix NSUnknownKeyException in Artsy.LiveAuctionViewController.viewWillDisappear (Swift.Bool) -> (), line 188

### ISSUE THREAD

**Issue by artsyit** [artsy/eigen#1776]
### Stacktrace ###

<pre>-;Artsy.LiveAuctionViewController.viewWillDisappear (Swift.Bool) -> ();LiveAuctionViewController.swift;188
-;@objc Artsy.LiveAuctionViewController.viewWillDisappear (Swift.Bool) -> ();LiveAuctionViewController.swift;0</pre>

### Reason ###

*** Terminating app due to uncaught exception 'NSUnknownKeyException', reason: '[<Artsy.LiveAuctionViewController 0x101924560> valueForUndefinedKey:]: this class is not key value coding-compliant for the key _hiddenPopoverController.'

### Link to HockeyApp ###

* [https://rink.hockeyapp.net/manage/apps/37020/crash_reasons/126598392](https://rink.hockeyapp.net/manage/apps/37020/crash_reasons/126598392)

**Comment by ashfurrow** [comment]
Closing in favour of #1777.
