### ISSUE TITLE
Estimated value should appear on auction artwork pages

### ISSUE THREAD

**Issue by alessandra-castillo** [artsy/eigen#1781]
An auction artwork's estimated value (which we input in the "Estimate" field in Ohm) should appear on the auction artwork pages. When we launched HJFA Benefit Auction, we noticed that the "Estimate" field was not appearing on the auction lot artwork pages in the App.

![slack_for_ios_upload_1024](https://cloud.githubusercontent.com/assets/9465284/16502655/76d0b6e4-3edd-11e6-845b-3bb6b39d8b7b.jpg)

**Comment by ashfurrow** [comment]
Issue moved to [artsy/auctions #177](https://github.com/artsy/auctions/issues/177) via [**ZenHub**](https://www.zenhub.com/)
