### ISSUE TITLE
[Artwork] Only try to use the largest available image version.

### ISSUE THREAD

**Issue by alloy** [artsy/eigen#1782]
We currently _always_ try to use the `larger` version, but there are cases where that resolution is not available.

E.g. this work only has images up-to `tall` https://www.artsy.net/artwork/june-wayne-col-noir

```json
      "image_versions": [
        "large_rectangle",
        "small",
        "tall"
      ],
```

I’m not sure yet if it is expected that this specific work does not have a `larger` version, however, seeing as in practice it’s always a possibility, we should fallback to the largest available version.

**Comment by alloy** [comment]
@mzikherman In the case of the example artwork, is it expected that the largest available version is `tall`? Is that because the partner uploaded a too low-res original?

**Comment by mzikherman** [comment]
I am not sure why all those versions are missing. I just reprocessed and look who showed up:

https://api.artsy.net/api/v1/artwork/june-wayne-col-noir/images

```
image_url: "https://d32dm0rphc51dk.cloudfront.net/80L4KBCaA8sRiCCNnjHqSw/:version.jpg",
image_versions: [
  "large_rectangle",
  "small",
  "tall",
  "square",
  "medium_rectangle",
  "large",
  "medium"
],
image_urls: {
  large_rectangle: "https://d32dm0rphc51dk.cloudfront.net/80L4KBCaA8sRiCCNnjHqSw/large_rectangle.jpg",
  small: "https://d32dm0rphc51dk.cloudfront.net/80L4KBCaA8sRiCCNnjHqSw/small.jpg",
  tall: "https://d32dm0rphc51dk.cloudfront.net/80L4KBCaA8sRiCCNnjHqSw/tall.jpg",
  square: "https://d32dm0rphc51dk.cloudfront.net/80L4KBCaA8sRiCCNnjHqSw/square.jpg",
  medium_rectangle: "https://d32dm0rphc51dk.cloudfront.net/80L4KBCaA8sRiCCNnjHqSw/medium_rectangle.jpg",
  large: "https://d32dm0rphc51dk.cloudfront.net/80L4KBCaA8sRiCCNnjHqSw/large.jpg",
  medium: "https://d32dm0rphc51dk.cloudfront.net/80L4KBCaA8sRiCCNnjHqSw/medium.jpg"
},
```

Basically, `larger` and `normalized` are watermarked, and so those can definitely fail (which is ok), so I would for sure still be defensive about falling back from `larger`. 

I don't quite know why those other ones are missing...I just reprocessed the image w/o doing anything else and they showed up.

**Comment by alloy** [comment]
Well it’s great that Gemini/Gravity only returns the versions it really has, so yeah we totally still going to be defensive about that.

So if I understand you correctly, all artworks are expected to provide all versions, if they don’t something went wrong?
