### ISSUE TITLE
Feedback 'Cant get shows feed to load. - Dylan'

### ISSUE THREAD

**Issue by artsyit** [artsy/eigen#1785]
### Message from Dylan Fareed sent on 2016-07-06 01:28:01 UTC###

> Cant get shows feed to load. 
> 
> - Dylan

### Link to HockeyApp ###

* [https://rink.hockeyapp.net/manage/apps/37029/feedback/580234](https://rink.hockeyapp.net/manage/apps/37029/feedback/580234)

**Comment by alloy** [comment]
Not very actionable.
