### ISSUE TITLE
Need navigation to auction page from auction artwork page

### ISSUE THREAD

**Issue by alessandra-castillo** [artsy/eigen#1790]
Unless you come from the auction landing page to an auction artwork page, there's no way to navigate to the auction. There's no link back to the auction landing, and only the first 10 lots appear under "Other Works in the Auction" (and it's the same 10 lots under "Other Works" on every auction artwork page).

**Comment by alessandra-castillo** [comment]
cc: @katarinabatina @orta

**Comment by ashfurrow** [comment]
Issue moved to [artsy/auctions #176](https://github.com/artsy/auctions/issues/176) via [**ZenHub**](https://www.zenhub.com/)
