### ISSUE TITLE
Eigen needs to display lot number for Live Auction

### ISSUE THREAD

**Issue by devangt** [artsy/eigen#1791]
Issue:
In a Live Auction we don't provide the user with Lot number but rather provide lot position. This gets tricky because both - the auction catalog and the prediction web (and the live video feed) call out Lot number for the lot.

Solution:
We need to add actual Lot Number information

**Comment by devangt** [comment]
Related to #1755

**Comment by acjay** [comment]
@katarinabatina What do we want this to look like? It seems as though it would be easy to replace the lot progress with the lot number, but then we'd lose our indication of progress.

**Comment by devangt** [comment]
@katarinabatina @acjay bumping to next sprint. Def need this one before the mid-september phillips sale.

**Comment by katarinabatina** [comment]
@ashfurrow lets move towards just displaying the actual lot number, not lot progress 

![image](https://cloud.githubusercontent.com/assets/6482926/18799641/9ea48914-81a6-11e6-9155-d8318f9bdaeb.png)

**Comment by ashfurrow** [comment]
@katarinabatina Sure, so remove the purple bar?

**Comment by katarinabatina** [comment]
@ashfurrow no, the bar stays just remove the /x and only post the real lot number

**Comment by acjay** [comment]
I did that in my very first Eigen PR about a week ago: https://github.com/artsy/eigen/pull/1827 :) Probably should have linked it to this issue.

**Comment by katarinabatina** [comment]
@acjay I don't understand your PR what was it that you did?

**Comment by acjay** [comment]
Just what you said. Whenever the new version hits the store, it'll have the assigned lot number, not the index anymore. And no total.

So if your on the 30th lot out of 200, and it's what Phillips calls _Lot 35_, the user sees _Lot 35_, and that's it.

**Comment by katarinabatina** [comment]
@acjay ah cool, but the progress indicator still functions correct?

**Comment by acjay** [comment]
Yep, no change there.

**Comment by katarinabatina** [comment]
@acjay rockin', just wanted to double check! (congrats on your first eigen PR 🎉  )

**Comment by ashfurrow** [comment]
Cool! Are we good to close this issue then?

**Comment by acjay** [comment]
Sure, if it's pretty much hands-off for getting it to the Store at this point.

**Comment by acjay** [comment]
We've shipped this, right?

**Comment by ashfurrow** [comment]
Yup!
