### ISSUE TITLE
Remove applewebdata from our list of supported schemes

### ISSUE THREAD

**Issue by orta** [artsy/eigen#1798]
Artsy can get opened unpredictably, due to other apps working around the same kind of bugs we did for ios7, we're not using supporting it anymore. 

I think we used it in ARTextView, and I believe that we can now use it's API for handling routing from inside them.

**Comment by alloy** [comment]
Orly? Just for shits ‘n giggles, do you have any examples?

**Comment by orta** [comment]
Yeah, https://sparkmailapp.com - it changes all internal links on an email into these: `applewebdata://28922D74-E266-491E-8BA8-C84C4D215D75#toc_item_3`
