### ISSUE TITLE
Install and integrate Space Commander to deal with code formatting

### ISSUE THREAD

**Issue by orta** [artsy/eigen#18]
_From @orta on January 16, 2015 18:52_

_Copied from original issue: artsy/eigen-private#2124_

**Comment by alloy** [comment]
Not sure what that formatter does, but since we don't use AppCode it feels kinda moot. We'll have to look into one of those clang based ones.

**Comment by orta** [comment]
we're using space commander on folio: https://github.com/square/spacecommander
Would recommend using it, it's worked out good for me so far.

**Comment by alloy** [comment]
Yeah, that’s the one we should try :+1:

**Comment by orta** [comment]
Ideally, once #520 is merged then that's all long running PRs ( with the exception of https://github.com/artsy/eigen/pull/227 ) closed, and you can also run synx too.
