### ISSUE TITLE
Feedback 'From: Devang Thakkar Seems to be some network f...'

### ISSUE THREAD

**Issue by artsyit** [artsy/eigen#1801]
### Message from Devang Thakkar sent on 2016-07-29 23:05:45 UTC

> From: Devang Thakkar
> 
> Seems to be some network failure but there's no feedback
### Link to HockeyApp
- [https://rink.hockeyapp.net/manage/apps/37029/feedback/593704](https://rink.hockeyapp.net/manage/apps/37029/feedback/593704)

**Comment by alloy** [comment]
We have better tickets about this.
