### ISSUE TITLE
[Home] [Artwork] Polish and wrap up Artwork grid 

### ISSUE THREAD

**Issue by mennenia** [artsy/eigen#1804]
- [x] iPad 
- [x] iPhone
- [ ] Rotation
- [x] Edge cases of data #1441

**Comment by alloy** [comment]
@sarahscott How far would you say you are with this ticket?

**Comment by sarahscott** [comment]
I have to add a Recently Viewed context to metaphysics (or think of a
better way to deal with the Recently Saved rail) and make the masonry grid
change its number of columns upon rotation.

**Comment by alloy** [comment]
Seeing as rotation is the only thing left, I’m leaving that in https://github.com/artsy/eigen/issues/1762
