### ISSUE TITLE
Live Auctions: Change "Auction Begins" to reflect Live Start time

### ISSUE THREAD

**Issue by alessandra-castillo** [artsy/eigen#1812]
In the "Info" page for live auctions on Artsy, it lists "Auctions Begins" as the time that preliminary bidding started on Artsy (the * Start at (UTC) field in Ohm).
![img_3395](https://cloud.githubusercontent.com/assets/9465284/17780327/f7feeea8-6538-11e6-92a7-bf80e56dd698.jpg)

"Auction Begins" should instead reflect the "Live Start at (UTC)" field in Ohm. Then it matches the description and time clock too. 
![img_3396](https://cloud.githubusercontent.com/assets/9465284/17780363/13527bfc-6539-11e6-93ef-fd7b21e143e8.jpg)

**Comment by ashfurrow** [comment]
Gotcha, should be a simple to change.

**Comment by ashfurrow** [comment]
Issue moved to [artsy/auctions #175](https://github.com/artsy/auctions/issues/175) via [**ZenHub**](https://www.zenhub.com/)
