### ISSUE TITLE
Feedback 'From: Remy Ferber Map not loading in me Collect...'

### ISSUE THREAD

**Issue by artsyit** [artsy/eigen#1828]
### Message from 53c70a737261696fb3010100 sent on 2016-09-16 13:47:02 UTC###

> From: Remy Ferber
> 
> Map not loading in me Collectors Room contact page.

### Link to HockeyApp ###

* [https://rink.hockeyapp.net/manage/apps/37029/feedback/621104](https://rink.hockeyapp.net/manage/apps/37029/feedback/621104)

**Comment by alloy** [comment]
@ferberre Thanks for reporting! Must have been a temporary (network possibly) issue, it appears to work right now:

![img_8192](https://cloud.githubusercontent.com/assets/2320/18631984/5c5fa964-7e75-11e6-9250-54b72decccf1.PNG)
