### ISSUE TITLE
Feedback 'From: Katarina Batina'

### ISSUE THREAD

**Issue by artsyit** [artsy/eigen#1829]
### Message from katarina batina sent on 2016-09-19 21:22:50 UTC###

> From: Katarina Batina

### Link to HockeyApp ###

* [https://rink.hockeyapp.net/manage/apps/37029/feedback/623065](https://rink.hockeyapp.net/manage/apps/37029/feedback/623065)

**Comment by alloy** [comment]
This seems like a fluke.
