### ISSUE TITLE
Treat new, `reserve_unknown` status the same way we deal with `no_reserve` currently

### ISSUE THREAD

**Issue by sweir27** [artsy/eigen#1835]
Currently, the `reserve_status` returned on a sale artwork in gravity treats lots that have 'unknown reserve' and 'no reserve' the same. We want to decouple these attributes, so eventually want `reserve_status` to have 4 values: `['no_reserve', 'reserve_met', 'reserve_not_met', 'reserve_unknown']`.

In order to maintain backward compatibility, a first step is to have eigen set up to handle receiving `'reserve_unknown'`, and treat it the same way that we treat `'no_reserve'`, such as here: https://github.com/artsy/eigen/blob/5b9dd6d1a945b97402821d634f86c62a8844776d/Artsy/Views/Artwork/Auctions/ARArtworkAuctionPriceView.m#L42-L43

Note that this is for the general artwork page. The live auction views should be fine because they get their data from causality 😄 .

**Comment by ashfurrow** [comment]
Thanks for the detailed issue @sweir27!
