### ISSUE TITLE
Delete background fetch work from eigen

### ISSUE THREAD

**Issue by orta** [artsy/eigen#1842]
in an ideal world, that'd be replaced with a new version in the future that grabs your home modules and puts it in relay's cache, but for now you need to:

* remove https://github.com/artsy/eigen/blob/master/Artsy/App/ARAppBackgroundFetchDelegate.m
* and remove the fetch attribute from the plist, see this PR - https://github.com/artsy/eigen/commit/cd55459785c4ee379206122406ca5ddfb3bfcfd8

**Comment by alloy** [comment]
Done in https://github.com/artsy/eigen/issues/1872.
