### ISSUE TITLE
Feedback 'From: Robert Lenne Missing arrow icon'

### ISSUE THREAD

**Issue by artsyit** [artsy/eigen#1847]
### Message from Robert Lenne sent on 2016-09-23 21:55:45 UTC###

> From: Robert Lenne
> 
> Missing arrow icon

### Link to HockeyApp ###

* [https://rink.hockeyapp.net/manage/apps/37020/feedback/625816](https://rink.hockeyapp.net/manage/apps/37020/feedback/625816)

**Comment by alloy** [comment]
Duplicate of #1833
