### ISSUE TITLE
Fix NSInvalidArgumentException in - [ARTopMenuViewController tabContentView:shouldChangeToIndex:], line 446

### ISSUE THREAD

**Issue by artsyit** [artsy/eigen#1849]
### Stacktrace (first of multiple) ###

<pre>ARTopMenuViewController;tabContentView:shouldChangeToIndex:;ARTopMenuViewController.m;446
ARTabContentView;setCurrentViewIndex:animated:;ARTabContentView.m;132
-;__RACSwizzleForwardInvocation_block_invoke;NSObject+RACSelectorSignal.m;49</pre>

### Reason ###

*** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[ARHomeComponentViewController tableView]: unrecognized selector sent to instance 0x147ec1170'

### Link to HockeyApp ###

* [https://rink.hockeyapp.net/manage/apps/37020/crash_reasons/137553287](https://rink.hockeyapp.net/manage/apps/37020/crash_reasons/137553287)

**Comment by sarahscott** [comment]
I think (and I can investigate further today) I encountered this when I tapped the Home icon while on the Home view.

To repro:
- Go to Home View in new beta
- Tap Artsy logo Home icon while on Home page

This immediately crashes the app for me.

**Comment by alloy** [comment]
@sarahscott Yup, that sounds correct and in line with https://github.com/artsy/emission/issues/310.

**Comment by alloy** [comment]
Might be related to scroll to top feature of top menu VC.

**Comment by orta** [comment]
Yep @mennenia and I got this 👍
