### ISSUE TITLE
iOS 7 - Kill Switch

### ISSUE THREAD

**Issue by orta** [artsy/eigen#185]
Add support for a optional kill switch for iOS 7 if there's something unexpected.

**Comment by ashfurrow** [comment]
Kyle suggests returning an error on a main API endpoint for specific user agent strings.

**Comment by ashfurrow** [comment]
Some libraries also exist: https://github.com/kazu0620/SRGVersionUpdater

**Comment by orta** [comment]
@alloy suggested a route that 404s until it's added saying that it's time to shut off ios7 support

**Comment by orta** [comment]
I think this is probably the best option: https://twitter.com/emiliopavia/status/567745937959698433

**Comment by katarinabatina** [comment]
![image](https://cloud.githubusercontent.com/assets/6482926/6238769/b56c436e-b6cb-11e4-8cdd-598e21414037.png)

**Comment by katarinabatina** [comment]
maybe ui to open artsy in safari???

**Comment by orta** [comment]
Thanks Kat

**Comment by orta** [comment]
yeah, actually, think I'm going to make it so it redirects to a Martsy page ( that doesn't exist )

**Comment by orta** [comment]
so that it can say whatever we want, according to whatever constraints exist in the time.

**Comment by alloy** [comment]
Ah ok, so completely kill it. I thought you meant only specific parts. Yeah, love the simplicity :+1:

**Comment by orta** [comment]
this is/was an option, but I lost a day to meetings, not prepared to do something nuanced in the timeframe I want.
