### ISSUE TITLE
Fix crash in function signature specialization <Arg[0] = Owned To Guaranteed, Arg[1] = Dead> of Artsy.ARHockeyFeedbackDelegate.showFeedback (__ObjC.UIImage?) -> (), line 36

### ISSUE THREAD

**Issue by artsyit** [artsy/eigen#1850]
### Stacktrace ###

<pre>-;function signature specialization <Arg[0] = Owned To Guaranteed, Arg[1] = Dead> of Artsy.ARHockeyFeedbackDelegate.showFeedback (__ObjC.UIImage?) -> ();ARHockeyFeedbackDelegate.swift;36
-;Artsy.ARHockeyFeedbackDelegate.(showFeedbackWithRecentScreenshot () -> ()).(closure #1);ARHockeyFeedbackDelegate.swift;52
-;Artsy.ARHockeyFeedbackDelegate.showFeedbackWithRecentScreenshot () -> ();ARHockeyFeedbackDelegate.swift;53
-;partial apply forwarder;ARHockeyFeedbackDelegate.swift;0</pre>

### Reason ###

Selector name found in current argument registers: currentUser

### Link to HockeyApp ###

* [https://rink.hockeyapp.net/manage/apps/37020/crash_reasons/137622556](https://rink.hockeyapp.net/manage/apps/37020/crash_reasons/137622556)

**Comment by alloy** [comment]
Fixed!
