### ISSUE TITLE
[Onboarding] What to do with local cache of trial users

### ISSUE THREAD

**Issue by mennenia** [artsy/eigen#1852]
@alloy commented before:

> Since 2.4.0 we have also been keeping track of all the artists/artworks/categories a trial user visits in a local cache file, we can use that data to improve suggestions.
1 Need to determine what the best way is to do that. E.g. sorts artists by number of artworks viewed of that artist?
2 The code that does the collection of that data needs to be removed once the new on-boarding is released.

I'm assuming I may have deleted the data collection bit of the code in the trial code 🔥, but want to double check and in general, make sure we're firm on how we want to proceed.

**Comment by alloy** [comment]
Just make sure the code is 🔥

**Comment by ashfurrow** [comment]
Having trouble finding where the data is stored in master. any pointers?

**Comment by orta** [comment]
Think it was in-memory on an ARAnalytics provide

**Comment by ashfurrow** [comment]
Thanks! Looks like `ARAnalyticsPapertrail` is still around, I'll take it out.

**Comment by alloy** [comment]
Fixed by #1951.
