### ISSUE TITLE
Deal with case where authentication token is no longer valid.

### ISSUE THREAD

**Issue by alloy** [artsy/eigen#1853]
First of all, this is really an edge-case and something that mostly hits us that use staging (where the DB gets reset).
- If an authentication token is invalid, this will be noticed by the code that pings `/api/v1/system/time`
- When that happens we should try to get a new token with the stored user creds
- If that fails, show an alert that offers user to throw user back into on-boarding / sign-in.

**Comment by orta** [comment]
I think a new copy of emission will need to be made too
