### ISSUE TITLE
[Onboarding] When to show what notifications prompt.

### ISSUE THREAD

**Issue by alloy** [artsy/eigen#1855]
From @robertlenne:

> I hit a follow button in the feed and the app asks me to turn on push notification. I feel like this is abrupt and will make people say "don't allow" at which point we loose them. Suggest an simple pre-alert saying "Want to receive push notification new works and shows by <Artist name> are added?" and only show this if they say yes.

Related to https://github.com/artsy/eigen/issues/1339#issuecomment-213043376

![img_8204](https://cloud.githubusercontent.com/assets/2320/18835888/a9d8b75c-83fd-11e6-8556-43029951ca38.PNG)

**Comment by alloy** [comment]
@robertlenne The alert that we show is actually a pre-alert, so we don’t loose our 1 shot at actually registering for notifications. However, using the app it did annoy me a little to get this alert after each follow, so I’m slightly more afraid that people might stop following out of annoyance.

**Comment by mennenia** [comment]
Hmm that's my bad then. 

The spec is that it should show upon following an artist only once. In that case, it's also a bug on my part which I'll fix.

**Comment by alloy** [comment]
@mennenia Can you also add the missing trailing period in the alert message? That’s the format that Apple uses as well:

![](http://i.stack.imgur.com/uxdykm.png)

**Comment by robertlenne** [comment]
Ah, realized that it was a pre-alert after playing with it a bit more. Makes sense. One think that you probably want to confirm is that we don't ask people who have their notifications on and then upgrade to this new version. I think I got the questions even though I had notifications on (Could be because I downloaded the beta through Testflight though)

**Comment by alloy** [comment]
Show the alert max once a week and only show it from the artist VC.

@mennenia Please check ASAP if this needs work in the native emission module (to know what VC it comes from).
