### ISSUE TITLE
[Onboarding] Selection is lost after scrolling.

### ISSUE THREAD

**Issue by alloy** [artsy/eigen#1856]
This happens on both the artist and categories selection view.

![lost selection](https://cloud.githubusercontent.com/assets/2320/18836499/98289920-8400-11e6-89b0-0b0c782d1828.gif)

**Comment by katarinabatina** [comment]
maybe not necessary to address this in favor of replacing the followed artist with another?

**Comment by alloy** [comment]
Yup 👍
