### ISSUE TITLE
[Onboarding] Replace followed popular artists in-line

### ISSUE THREAD

**Issue by katarinabatina** [artsy/eigen#1859]
instead of bundling all the selections

![image](https://cloud.githubusercontent.com/assets/6482926/18839198/1cbb8748-83d8-11e6-9e46-fe5d0a98eb82.png)

use the replace functionality that we offer after a user has searched for artists

**Comment by mennenia** [comment]
Fixed :)

**Comment by katarinabatina** [comment]
woop woooooop!!!!
