### ISSUE TITLE
Preload the fair content from a local data source.

### ISSUE THREAD

**Issue by alloy** [artsy/eigen#186]
The goal of this feature is for a (new) user to be able to appreciate the content that Artsy/the app provides _without_ the need for a reliable internet connection.

According to Katherine and Madeleine, users (and Artsy volunteers demoing the app) will typically browse content of the fair they’re at, which gives us the opportunity to preload that finite amount of data onto the user’s device.
### General
- [ ] Configure server Mac’s Apache to host the manifest and package and announce as Bonjour service.
- [ ] Connect a host Mac to the fair wifi that broadcasts a Bonjour service.
- [ ] Create first content packages, for testing at the fair, by packaging up the cache directory of a session of using the app on the simulator.
### Eigen
- [x] Discover a FairEnough Bonjour service and resolve its address.
- [x] Fetch metadata about the fair and content package.
- [x] Download the package.
- [x] Resume a previously failed download of the package.
- [x] Unpack the archive to the caches folder. (The archive should have the same disk layout as the iOS app would normally cache to disk so that no extra work on the iOS side is necessary.)
- [x] Cache NSURLRequest/NSURLSession requests.
- [x] Cache requests made by UIWebView.
- [x] Load from cache when the device has no internet connection at all.
- [ ] Load from cache when the device has a very slow internet connection.
- [ ] Perform the work on app startup.
- [ ] The iOS app should be able to navigate to the fair content directly from the home view so that no internet is needed to get there. https://github.com/artsy/eigen/issues/187
### Later
- [ ] Generate fair content zip archives in an automated fashion if needed.
- [ ] Currently using AFCache, which provides all the features we need, but not sure yet if I really like the implementation or if we could use our own subset of it.

**Comment by orta** [comment]
> Create a (zip) archive that contains all of the fairs content.

The Mac App, ideally, would need to be able to update every hour or so. Things do change quite often at the fair.

**Comment by katarinabatina** [comment]
How much time do we realistically think this will take? I want to be mindful of other priorities during this sprint.

**Comment by alloy** [comment]
@katarinabatina Based on what I know now (that not everything was being cached), I’d say it would take the better part of this week to get it in a state where Artsy volunteers can beta test it at the Armory.

**Comment by alloy** [comment]
Also look at preloading/caching content such as https://github.com/artsy/eigen/issues/330.

**Comment by katarinabatina** [comment]
no longer relevant
