### ISSUE TITLE
[WorksForYou] Does not work as expected after onboarding.

### ISSUE THREAD

**Issue by alloy** [artsy/eigen#1863]
During onboarding we ask the user to follow some artists. When they do that, the works by artists that they follow correctly show up on the home view, with a “VIEW ALL” link that takes them to the works-for-you view. The works-for-you view says that the user doesn’t follow any artists.

The reason for this is that the works-for-you view currently uses the ‘notification bundles’ feature of Gravity, which are only generated at specific times (I think once a day or when a new work is published?).

There are other issues that have led @mzikherman and me question whether [we shouldn’t just query for all (for sale) artworks by artists the user follows](https://github.com/artsy/force-private/issues/5015#issuecomment-226318639), changing that would solve this issue as well.

![img_8207](https://cloud.githubusercontent.com/assets/2320/18836889/2566ca86-8402-11e6-896e-64dcd4dc873a.PNG)

![img_8206](https://cloud.githubusercontent.com/assets/2320/18836894/285dd888-8402-11e6-9eee-c8e458b08ce8.PNG)

**Comment by alloy** [comment]
Spend 1 hour max to see if the WFU VC can easily be changed.

**Comment by alloy** [comment]
Otherwise change the copy to not implicate that they are not following any artists.

**Comment by mennenia** [comment]
So, I spent a bit more time on it and I'm not there yet. I'm going to change the copy for this beta, and then continue.

**Comment by alloy** [comment]
Fixed by #1929.
