### ISSUE TITLE
[Live UI] Tapping lot info makes info disappear completely 

### ISSUE THREAD

**Issue by katarinabatina** [artsy/eigen#1866]
enter live auction, tap lot info, lot info button disappears and no lot info is shown 
![image](https://cloud.githubusercontent.com/assets/6482926/18847997/64b0c492-83fa-11e6-802f-24c94e059b82.png)

**Comment by ashfurrow** [comment]
Seeing this too. I'll take a look, thanks :+1:

**Comment by ashfurrow** [comment]
Tricky, looks like interference caused by the drag-up-to-see-bid-history gesture recognizer. Looking into a fix now.
