### ISSUE TITLE
Design for jump straight to fair you're already in

### ISSUE THREAD

**Issue by orta** [artsy/eigen#187]
Ideally something simple, time isn't on our side here.

**Comment by alloy** [comment]
Should this flow also include a question about if the user wants to preload the content at all?

**Comment by orta** [comment]
No

**Comment by orta** [comment]
@alloy I'll do the visual aspects of this, and leave the actual calling to you

**Comment by katarinabatina** [comment]
@orta we won't want to include the partner logo as outlined

**Comment by katarinabatina** [comment]
ideally we'd want to source the new image i've outlined but something tells me we're strapped for time

**Comment by orta** [comment]
Sure, I'll keep that in mind as I build it 👍

**Comment by orta** [comment]
![screen shot 2015-02-18 at 12 04 37 pm](https://cloud.githubusercontent.com/assets/49038/6252167/584bb34a-b766-11e4-940a-39781c8eee8c.png)
