### ISSUE TITLE
[Home] Banners, search

### ISSUE THREAD

**Issue by alloy** [artsy/eigen#1870]
An option would be to keep using the existing banner component in favour of the following two, for now.

* https://github.com/artsy/eigen/issues/1439
* https://github.com/artsy/eigen/issues/1447

**Comment by alloy** [comment]
We decided to go forward with the banner and search.

**Comment by katarinabatina** [comment]
go for the gold

**Comment by alloy** [comment]
![](http://media2.giphy.com/media/vsVfZbUPdnSJa/giphy.gif)
