### ISSUE TITLE
Artist Search for Raymond Pettibon returns no results

### ISSUE THREAD

**Issue by katarinabatina** [artsy/eigen#1873]
![img_1781](https://cloud.githubusercontent.com/assets/6482926/18919535/92d5163e-856c-11e6-91ba-6fcc725a1f3c.PNG)
![img_1782](https://cloud.githubusercontent.com/assets/6482926/18919540/94adb8a8-856c-11e6-905d-52df37afc8c9.PNG)

**Comment by katarinabatina** [comment]
no idea what's going on https://www.artsy.net/artist/raymond-pettibon

I know Alex B reported this in #collecor-gmv today as well

**Comment by alloy** [comment]
This is a metaphysics/backend problem, so doesn’t necessarily need to be fixed before we deploy 3.0.1

**Comment by alloy** [comment]
This is fixed, but metaphysics needs to get deployed to production.

**Comment by alloy** [comment]
Deployed and confirmed to work.
