### ISSUE TITLE
ASCII Easter egg broken

### ISSUE THREAD

**Issue by alloy** [artsy/eigen#1874]
The code for this probably got torn out when removing the old home feed.

**Comment by mennenia** [comment]
P1??? This has to be our biggest showstopper!

**Comment by orta** [comment]
Hah - aye, this can _only_ run on that VC would need to be re-attached to another view controller. Might work on the TopVC - hard to say

**Comment by alloy** [comment]
I don’t see why the gestures couldn’t be recognised on the window?
