### ISSUE TITLE
[Home] Eliminate black rectangle behind status bar

### ISSUE THREAD

**Issue by katarinabatina** [artsy/eigen#1876]
![image](https://cloud.githubusercontent.com/assets/6482926/18936342/92b41dba-85b4-11e6-945d-ac24cd6be098.png)

![image](https://cloud.githubusercontent.com/assets/6482926/18936355/a6e48892-85b4-11e6-9940-9800e86bade1.png)

**Comment by mennenia** [comment]
@sarahscott can this be closed?

**Comment by sarahscott** [comment]
Yes, but this is related and should be left open: #1955

**Comment by mennenia** [comment]
Yup that's for this sprint! :)
