### ISSUE TITLE
Fair Guide padding adjustment for fairs with no map

### ISSUE THREAD

**Issue by katarinabatina** [artsy/eigen#188]
![image](https://cloud.githubusercontent.com/assets/6482926/6234343/31fc3a70-b6a8-11e4-852a-3686b211a186.png)
![image](https://cloud.githubusercontent.com/assets/6482926/6234347/36f942f2-b6a8-11e4-8c18-196cadf146e6.png)
![image](https://cloud.githubusercontent.com/assets/6482926/6234350/3bf301a8-b6a8-11e4-9a8a-035266afc8aa.png)

**Comment by katarinabatina** [comment]
change title font to avant garde

**Comment by 1aurabrown** [comment]
With the avant garde titles, i think in general we make them so that the first line is centered vertically with the button. you wan this to be different?

**Comment by katarinabatina** [comment]
The problem is that the view controller tabs will sit under the button

**Comment by katarinabatina** [comment]
for the logged out use case I think that works great

**Comment by 1aurabrown** [comment]
gotcha

**Comment by 1aurabrown** [comment]
how is this:
![screen shot 2015-03-05 at 1 28 53 pm](https://cloud.githubusercontent.com/assets/3171662/6511585/d8165536-c33b-11e4-9870-7171b3e6bed8.png)
![screen shot 2015-03-05 at 1 29 16 pm](https://cloud.githubusercontent.com/assets/3171662/6511586/d82004e6-c33b-11e4-89bd-c6296040b21c.png)
