### ISSUE TITLE
Fair Guide data inconsistent with web 

### ISSUE THREAD

**Issue by katarinabatina** [artsy/eigen#189]
Look at my fair guide on eigen, only see one work, view the same data on the web and see many works 
https://www.artsy.net/palm-springs-fine-art-fair/for-you

**Comment by orta** [comment]
We need to add de-duping to our FeaturedLists, which the website does to accommodate cray data inputs.

**Comment by orta** [comment]
think you can grab this laura? 
I have two guesses, the code to check "is eigen" vs "is martsy" is being true for both, or there really are dupes in the sets.

**Comment by 1aurabrown** [comment]
ok

On Tue, Feb 24, 2015 at 1:23 PM, Orta <notifications@github.com> wrote:

> think you can grab this laura?
> I have two guesses, the code to check "is eigen" vs "is martsy" is being
> true for both, or there really are dupes in the sets.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/artsy/eigen/issues/189#issuecomment-75826195>.
>



-- 

[A.]


Laura Brown

Artsy <http://artsy.net/>

laura@artsy.net <caroline@artsy.net>

**Comment by 1aurabrown** [comment]
fixed in https://github.com/artsy/eigen/pull/217
