### ISSUE TITLE
[Home] Tap status bar to go to top of view not working

### ISSUE THREAD

**Issue by katarinabatina** [artsy/eigen#1891]
on home view, down in the feed, tap status bar to go to top of feed, nothing happens

**Comment by katarinabatina** [comment]
Will test on tomorrow's beta... @alloy will double check

**Comment by alloy** [comment]
This is working in the current beta.

**Comment by katarinabatina** [comment]
@alloy seeing again in this morning's beta

**Comment by alloy** [comment]
Hmm, indeed I have seen it too now. It worked fine for a while and then after opening the search view it stopped working.

Alas I wasn't able to reproduce it with those exact same steps. It would be great if we can find exact reproducible steps, will continue to dig.

**Comment by orta** [comment]
I'm struggling to reproduce this ( even with going into search, or changing tabs ) on an iPad 8.4

**Comment by orta** [comment]
However, it's much easier to reproduce on iPhone though, will try get a repro

**Comment by orta** [comment]
Repro from scratch: Restart app, home works, go to explore, explore does not scroll to top, nor will home when you come back

Same for "you."

Hitting search does seem to break i

**Comment by orta** [comment]
Switching to Explore, then turning `scrollsToTop` off on the home, means that the explore scrolls to top correctly. I'm assuming that somehow the Home is being prioritised by [the algorithm described as](https://developer.apple.com/reference/uikit/uiscrollview/1619421-scrollstotop):

> the system asks the scroll view closest to the status bar

**Comment by alloy** [comment]
Yikes… Might be time to axe our ARTopMenuVC and rebuild it with a plain UITabBarController?

**Comment by orta** [comment]
Is it a good idea? Definitely. Can it be done for 3, nopes

**Comment by alloy** [comment]
Oh no, totally not doing that for v3.

**Comment by katarinabatina** [comment]
I haven't seen this come up since our last build, I'm going to close for now, feel free to reopen if necessary @orta @alloy
