### ISSUE TITLE
Fix NSInvalidArgumentException in - [ARSwitchBoard(Eigen) loadLiveAuction:], line 73

### ISSUE THREAD

**Issue by artsyit** [artsy/eigen#1897]
### Stacktrace (first of multiple) ###

<pre>ARSwitchBoard(Eigen);loadLiveAuction:;ARSwitchboard+Eigen.m;73
-;Artsy.AuctionViewController.(viewWillAppear (Swift.Bool) -> ()).(closure #1);AuctionViewController.swift;57
-;(extension in Artsy):Interstellar.Observable.(merge <A> (Interstellar.Observable<A1>) -> Interstellar.Observable<(A, A1)>).(closure #2);InterstellarExtensions.swift;13
-;Artsy.AuctionSaleArtworksNetworkModel.(fetchSaleArtworks (Swift.String) -> Interstellar.Observable<Interstellar.Result<[__ObjC.SaleArtwork]>>).(closure #1);AuctionSaleArtworksNetworkModel.swift;23
-;Artsy.((fetchPage in _A2CC32B3077A45794C7542EE6485D1A5) (Swift.Int, forSaleID : Swift.String, alreadyFetched : [__ObjC.SaleArtwork], callback : (Interstellar.Result<[__ObjC.SaleArtwork]>) -> ()) -> ()).(closure #1);AuctionSaleArtworksNetworkModel.swift;47</pre>

### Reason ###

*** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '*** -[NSURL URLByAppendingPathComponent:]: component, components, or pathExtension cannot be nil.'

### Link to HockeyApp ###

* [https://rink.hockeyapp.net/manage/apps/37029/crash_reasons/137110204](https://rink.hockeyapp.net/manage/apps/37029/crash_reasons/137110204)

**Comment by ashfurrow** [comment]
Issue moved to [artsy/auctions #174](https://github.com/artsy/auctions/issues/174) via [**ZenHub**](https://www.zenhub.com/)
