### ISSUE TITLE
Remove Explore artwork categories on fair overview

### ISSUE THREAD

**Issue by katarinabatina** [artsy/eigen#190]
Unfortunately this information is moving into a sub view (martsy) under the Works section meaning we really don't need to repeat it. Also find that many fairs only have one or two featured categories and the current UI doesn't accommodated this very well :/ 
![image](https://cloud.githubusercontent.com/assets/6482926/6234425/dfca3418-b6a8-11e4-826b-40b545af683c.png)

**Comment by orta** [comment]
Leaving in the pile for someone else to pick up, I'm back to doing Folio work

**Comment by katarinabatina** [comment]
is there an easy way of telling when things make it into the current build or not? (I can tell this one didn't make it into what we shipped to apple but I was curious of how to confirm that)
