### ISSUE TITLE
[Tests] Trait collections are nil at the time of running tests

### ISSUE THREAD

**Issue by mennenia** [artsy/eigen#1902]
So one can't accurately determine whether we should use a compact or large layout. 

This was causing issues in the `ARCreateAccountViewControllerTests`, and is used in other places.

**Comment by orta** [comment]
Our guess was that it was related to the view setup structure of the test when using the trait collections instead of the `[UIDevice isPad]`

**Comment by alloy** [comment]
@mennenia What’s the status on this?

**Comment by mennenia** [comment]
These tests are now covered in integration test, and this particular view controller will be removed in the new onboarding anyway.
