### ISSUE TITLE
Feedback 'From: Kmefmiem Jdnfidnf Banners too narrow shou...'

### ISSUE THREAD

**Issue by artsyit** [artsy/eigen#1912]
### Message from 57fe450d139b2151650006b5 sent on 2016-10-12 14:15:30 UTC###

> From: Kmefmiem Jdnfidnf
> 
> Banners too narrow should be 160 tall

### Link to HockeyApp ###

* [https://rink.hockeyapp.net/manage/apps/37020/feedback/637307](https://rink.hockeyapp.net/manage/apps/37020/feedback/637307)

**Comment by alloy** [comment]
Continuing from here https://github.com/artsy/eigen/issues/1439

@katarinabatina The banners are currently 160 points on both iPhone and iPad, should there be a difference?

**Comment by katarinabatina** [comment]
I fucked up on the spec sorry, I said the value was 160 when in reality its 300

![image](https://cloud.githubusercontent.com/assets/6482926/19407554/c3c53850-9273-11e6-91b4-404b76aad634.png)

**Comment by alloy** [comment]
I should have caught that too, 160 points was very narrow indeed.

**Comment by alloy** [comment]
![simulator screen shot 15 oct 2016 13 14 52](https://cloud.githubusercontent.com/assets/2320/19409675/61c83dda-92d9-11e6-96b4-4f7233a12220.png)
