### ISSUE TITLE
Institutions partners featured on the front page have a "Following Gallery" button 

### ISSUE THREAD

**Issue by alessandra-castillo** [artsy/eigen#192]
After I clicked on an institutions partner from the app's front page (ex: Brooklyn Museum, Guggenheim, Surikov Foundation) I see a "Following Gallery" button. (Note - I was following these partners before opening the app).  When I search for these partners then click on them, the button simply says "Following". 
![img_0210](https://cloud.githubusercontent.com/assets/9465284/6239107/a5b3fdd8-b6ce-11e4-9aed-8770c0a01744.PNG)

**Comment by 1aurabrown** [comment]
@alessandra-castillo should it say "following" in both cases? (or "follow" instead of "follow gallery" if you are not yet following?)

**Comment by alessandra-castillo** [comment]
@1aurabrown sorry to get to this so late! was away this weekend. 

so, if you're in fact following the museum, it should say "follow" instead of "following gallery". if not, it should only say "follow". hope this clears it up!
