### ISSUE TITLE
[Fair] Fix failing fair search VC.

### ISSUE THREAD

**Issue by alloy** [artsy/eigen#1920]
Specifically [this disabled test](https://github.com/artsy/eigen/pull/1917/commits/8b7cfa686e0f17731cfa7f43a0f114fa91daf327) in #1917.

**Comment by ashfurrow** [comment]
Are we looking to bring the fair search inline with the new main search design, or revert the changes from #1917 for only fair search?

**Comment by alloy** [comment]
Fixed by #1936.
