### ISSUE TITLE
onboarding flashes no results prior to loading first time

### ISSUE THREAD

**Issue by katarinabatina** [artsy/eigen#1923]
open app, tap get started, see zero state of follow artist screen "no results found" then the popular artist list flashes in.

**Comment by mennenia** [comment]
@ash this is just a case of "if table content array = 0, show empty label", and just before the data populates it upon loading, the length of that array is ofc 0... 

This is in `ARPersonalizeTableViewController`. Data comes from `ARPersonalizeViewController`.

**Comment by alloy** [comment]
Fixed by #1930.
