### ISSUE TITLE
Fix crash in - [ARTemporaryAPIModule followStatusForGene:completion:], line 19

### ISSUE THREAD

**Issue by artsyit** [artsy/eigen#1924]
### Stacktrace ###

<pre>ARTemporaryAPIModule;followStatusForGene:completion:;ARTemporaryAPIModule.m;19
RCTModuleMethod;invokeWithBridge:module:arguments:;RCTModuleMethod.m;484
RCTBatchedBridge;callNativeModule:method:params:;RCTBatchedBridge.m;1035
RCTBatchedBridge;handleBuffer:;RCTBatchedBridge.m;976</pre>

### Reason ###

Selector name found in current argument registers: geneFollowStatusProvider

### Link to HockeyApp ###

* [https://rink.hockeyapp.net/manage/apps/37020/crash_reasons/140606378](https://rink.hockeyapp.net/manage/apps/37020/crash_reasons/140606378)

**Comment by alloy** [comment]
Fixed by #1925.
