### ISSUE TITLE
popular categories should be replaced by recommendations

### ISSUE THREAD

**Issue by katarinabatina** [artsy/eigen#1933]
get to follow category screen in onboarding, select photography, photography remains selected, does not get replaced. this functionality should mirror what we do on the artist portion of onboarding.

**Comment by mennenia** [comment]
@alloy @ashfurrow I think this one might be related to #1932, which I'm looking at now.

**Comment by mennenia** [comment]
Same as #1932 

Missing `_id`s in the json file, now have been added. 

updated: https://s3.amazonaws.com/eigen-production/json/eigen_categories.json
