### ISSUE TITLE
Feedback 'From: Ani Petrov Not seeing any properties when...'

### ISSUE THREAD

**Issue by artsyit** [artsy/eigen#1934]
### Message from 540caa167261692d6b550000 sent on 2016-10-18 02:19:05 UTC###

> From: Ani Petrov
> 
> Not seeing any properties when I try clicking into the analytics popover here. Not sure if it's because we no longer gather those properties or because of a bug with the popover itself.
> 
> I also see a lot of double firing of screen views -- a single view will get a fired with multiple names (onboarding, personalize, etc.). I will try to catch and describe all of them in an subsequent issue.

### Link to HockeyApp ###

* [https://rink.hockeyapp.net/manage/apps/37020/feedback/641629](https://rink.hockeyapp.net/manage/apps/37020/feedback/641629)

**Comment by alloy** [comment]
Closing in favour of #1939.
