### ISSUE TITLE
[Analytics] Eigen 3.0 QA

### ISSUE THREAD

**Issue by anipetrov** [artsy/eigen#1939]
## Screens
We should attempt to move towards firing a single screenview per screen. Onboarding screenviews that are double firing currently:
- [x] `Onboarding start` and `sign_up_splash`: we should deprecate `sign_up_splash` and only fire `Onboarding start`

<img src="https://cloud.githubusercontent.com/assets/8701687/19488993/4c31d868-9537-11e6-93cd-45f47831551f.PNG" width="326.25" height="580"> <img src="https://cloud.githubusercontent.com/assets/8701687/19488992/4c30d77e-9537-11e6-8fe0-baa4f508d528.PNG" width="326.25" height="580">

- [x] `Onboarding signup` and `create_account`: we should deprecate `create_account` and only fire `Onboarding signup`

<img src="https://cloud.githubusercontent.com/assets/8701687/19490609/d5b2db22-953d-11e6-8e92-a2eab25517be.PNG" width="326.25" height="580"> <img src="https://cloud.githubusercontent.com/assets/8701687/19490608/d5a2444c-953d-11e6-8e95-be85b9a67f64.PNG" width="326.25" height="580">

- [x] `Onboarding login` and `login`: we should deprecate `login` and only fire `Onboarding login`

<img src="https://cloud.githubusercontent.com/assets/8701687/19490691/227e3956-953e-11e6-8ef3-2bdfcaefbd97.PNG" width="326.25" height="580"> <img src="https://cloud.githubusercontent.com/assets/8701687/19490692/227e76be-953e-11e6-981e-9e8c28ab288d.PNG" width="326.25" height="580">

- [x] Every other onboarding screen fires a proper screenview and an additional screenview `personalize` which should be removed; we should only fire `Onboarding follow artists`, `Onboarding follow categories`, `Onboarding select budget`

- [ ] Pressing the home button and the app while on an onboarding screen and then opening it again does not fire another screenview, and maybe it should if we consider reopening the app the start of a new session; a similar thing is happening with events, in the below case `Follow artist`:

![screen recording 2016-10-18 at 14 33](https://cloud.githubusercontent.com/assets/8701687/19491168/efda4bdc-953f-11e6-8e46-200c0122b3a2.gif)

## Tracks
- [x] When following a category from the Onboarding follow categories screen, a `gene favorite` track -- an outdated event with no properties -- fires. Instead, we should fire `Follow category`. Nore that a category can be followed from a gene page or during onboarding. Contextual properties:
  * properties: {  
                         gene_id,  
                         source_screen: [gene page, onboarding top categories, onboarding search, onboarding recommended]  
                         }

- [x] `Follow artist` fires with no contextual properties. Instead we should append to the event:
  * properties: {  
                         artist_slug,  
                         artist_id,  
                         source_screen:[artist page, artist fair page, onboarding top artists, onboarding search, onboarding recommended]  
                         }

- [x] We do not fire an event when user logs in using safari keychain. Instead, we should fire `Successfully logged in` with the following property:
  * properties: {  
                        context_type: safari keychain  
                        }  

![img_0167 2](https://cloud.githubusercontent.com/assets/8701687/19499190/0ab4fede-9563-11e6-9faf-a6639e35784b.PNG)

**Comment by alloy** [comment]
@anipetrov What a great and clear issue 👏

**Comment by mennenia** [comment]
@ani FYI, there's another source screen for Artist Follow events, which would be the rails from the home page. @alloy did we put any analytics around that?

**Comment by mennenia** [comment]
Closing this as most of it is implemented. Have moved the outstanding issue to #1947. Thanks @anipetrov and @ashfurrow!
