### ISSUE TITLE
Glitchy line appears after clicking "Sort By" in LAMA auction

### ISSUE THREAD

**Issue by alessandra-castillo** [artsy/eigen#194]
I couldn't capture it in a screen shot but when you click the "Sort By" button a black line flashes across, like 80% of the time. 

![img_0212](https://cloud.githubusercontent.com/assets/9465284/6239183/51103e1c-b6cf-11e4-9487-bde0a195d384.PNG)

**Comment by katarinabatina** [comment]
this sort is being redesigned, the problem might fix itself https://github.com/artsy/microgravity/issues/663

**Comment by alloy** [comment]
This uses a real select control nowadays:

![ios simulator screen shot 29 jun 2015 20 34 32](https://cloud.githubusercontent.com/assets/2320/8415325/4faf35fa-1e9e-11e5-80d7-19cdf96ba1ec.png)
