### ISSUE TITLE
Feedback 'From: orta@artsymail.com Looks like we need to ...'

### ISSUE THREAD

**Issue by artsyit** [artsy/eigen#1940]
### Message from 4ec92ccb56ae88000100038e sent on 2016-10-19 10:46:04 UTC###

> From: orta@artsymail.com
> 
> Looks like we need to crop artwork names at maybe 4-6 lines

### Link to HockeyApp ###

* [https://rink.hockeyapp.net/manage/apps/37020/feedback/642795](https://rink.hockeyapp.net/manage/apps/37020/feedback/642795)

**Comment by orta** [comment]
This is old
