### ISSUE TITLE
[Analytics] Add support for event trigger upon background/foreground change

### ISSUE THREAD

**Issue by mennenia** [artsy/eigen#1947]
Copied from #1939, from @anipetrov:

Pressing the home button and the app while on an onboarding screen and then opening it again does not fire another screenview, and maybe it should if we consider reopening the app the start of a new session; a similar thing is happening with events, in the below case Follow artist:

![efda4bdc-953f-11e6-8e46-200c0122b3a2](https://cloud.githubusercontent.com/assets/373860/19527147/d5271632-961e-11e6-8f00-bd3c92a124ff.gif)

**Comment by anipetrov** [comment]
Did we fix the tracks firing and only have screens outstanding, or can we not get any analytics with the foreground -> background -> foreground transition?

**Comment by ashfurrow** [comment]
Talked with Ani on slack, the problem is that analytics popovers don't appear after the app goes from foreground -> background -> foreground. I've double-checked and the events _are_ firing, just the popover is missing.

**Comment by alloy** [comment]
@ashfurrow @mennenia Ok, so this can be closed, yeah?

**Comment by mennenia** [comment]
From my understanding:

- The events we need are firing, so that's 👍 
- On the topic of starting new sessions from FG > BG > FG, this seems a more general analytics issue that I think we should tackle in separately. 

But @ashfurrow please verify ^_^.

**Comment by mennenia** [comment]
I'm closing this for now.
