### ISSUE TITLE
Feedback 'From: Sarah Scott Broken layout on search VC af...'

### ISSUE THREAD

**Issue by artsyit** [artsy/eigen#1953]
### Message from 5501de167261696e34610200 sent on 2016-10-20 09:43:47 UTC

> From: Sarah Scott
> 
> Broken layout on search VC after rotating from portrait while search VC is being presented.
### Link to HockeyApp
- [https://rink.hockeyapp.net/manage/apps/37029/feedback/643468](https://rink.hockeyapp.net/manage/apps/37029/feedback/643468)

**Comment by sarahscott** [comment]
Closing in favor of #1954
