### ISSUE TITLE
Fix zooming-in of background view when search is presented

### ISSUE THREAD

**Issue by sarahscott** [artsy/eigen#1956]
![searchvcbackground](https://cloud.githubusercontent.com/assets/2712962/19558182/68f07e12-96c9-11e6-8b21-0ae4d18ccec1.gif)

**Comment by orta** [comment]
That is how the blur works, I think, we zoom in so it can support parallax on the phone moving that image horizontally/vertically

**Comment by sarahscott** [comment]
Which image?

**Comment by orta** [comment]
we blur into a rendered image, as older phones can't do blurring at runtime

**Comment by sarahscott** [comment]
Ok. If we move to the spec outlined in #1917 , where nothing should be moving horizontally or vertically, will this be a problem?

**Comment by orta** [comment]
Shouldn't be - I think you'll have to do some work though, I think our blurring tooling takes a those ^ constraints into account
