### ISSUE TITLE
[Search] Increase vertical hit area of close button

### ISSUE THREAD

**Issue by sarahscott** [artsy/eigen#1957]
Tried `ar_extendHitTestSize` but it doesn't work because the close button's superview is [top-and-bottom-aligned with its superview](https://github.com/artsy/eigen/blob/master/Artsy/View_Controllers/Search/ARSearchViewController.m#L91)

**Comment by orta** [comment]
`ar_extendHitTestSize` works by extending it's tappable region, unless it's totally covered by other views - it should be fine for this case. I think there's a sibling function that will show you what it looks like for tapping too.

**Comment by sarahscott** [comment]
Yes, I tried `ar_visuallyExtendHitTestSize` and could see the tappable area; however, that extended area would not actually register the taps. I am guessing this is because they were outside the bounds of the close button's superview.

**Comment by orta** [comment]
yeah, sounds right 👍
