### ISSUE TITLE
remove partner profile icon from fair overview

### ISSUE THREAD

**Issue by katarinabatina** [artsy/eigen#196]
current 
![image](https://cloud.githubusercontent.com/assets/6482926/6248244/8e034914-b74b-11e4-829d-5f485931a561.png)

new
![image](https://cloud.githubusercontent.com/assets/6482926/6248248/96b1a006-b74b-11e4-9e1d-7b4e08231d0f.png)

**Comment by orta** [comment]
this actually happens if we don't find an icon right now

**Comment by katarinabatina** [comment]
I think as an interim solution, if we don't get the request in time from core 
![image](https://cloud.githubusercontent.com/assets/6482926/6255246/a2aea940-b77c-11e4-931e-778cb68b7bf3.png)

**Comment by orta** [comment]
https://github.com/artsy/gravity/pull/8632

**Comment by katarinabatina** [comment]
still displaying as follows in the current beta
![image](https://cloud.githubusercontent.com/assets/6482926/6307391/4972b676-b909-11e4-823f-fd788f92c228.png)

**Comment by orta** [comment]
That's backwards compatibility if there's no branded banner set :+1:

**Comment by katarinabatina** [comment]
ok so we will want to revert to the new design I outlined instead of current

**Comment by katarinabatina** [comment]
new issue for that?

**Comment by orta** [comment]
new issue, this one's getting overloaded ( also might make sense to make a Fairs improvements milestone )

**Comment by katarinabatina** [comment]
sounds good

**Comment by orta** [comment]
Pretty sure this is in now, just the issue wasn't closed.
