### ISSUE TITLE
getting blank home screen often during active session

### ISSUE THREAD

**Issue by katarinabatina** [artsy/eigen#1961]
open app, home loads, go to explore, go to other places in the app, come back to home and I just get a completely blank screen with the nav bar

**Comment by alloy** [comment]
Oh god… I just saw it too. I got a blank screen until I scrolled 😭 

It appears to be a React Native bug that’s described [here](https://github.com/facebook/react-native/issues/8607). A WIP fix is available [here](https://github.com/facebook/react-native/issues/8607#issuecomment-249530803) which some use in production with success.
