### ISSUE TITLE
What up with 'Pop Art' 

### ISSUE THREAD

**Issue by mennenia** [artsy/eigen#1966]
Pop art in the popular categories doesn't trigger recommendation.

**Comment by alloy** [comment]
What is this about exactly?

**Comment by mennenia** [comment]
Pop Art used to be in the popular categories list, and when you clicked it it would just kind of freeze. I've taken it out of the json file for now, but need to debug it properly - about to do that now.

**Comment by alloy** [comment]
Thanks!

**Comment by mennenia** [comment]
Fixed! Had the wrong ID and _id in the json file (`pop-and-contemporary-pop` no longer exists). Now just `pop-art`.
