### ISSUE TITLE
Fix NSRangeException in - [AROnboardingPersonalizeTableViewController updateTableContentsFor:replaceContents:animated:], line 67

### ISSUE THREAD

**Issue by artsyit** [artsy/eigen#1968]
### Stacktrace ###

<pre>AROnboardingPersonalizeTableViewController;updateTableContentsFor:replaceContents:animated:;AROnboardingPersonalizeTableViewController.m;67
ARPersonalizeViewController;categoryFollowed:;ARPersonalizeViewController.m;316</pre>

### Reason ###

*** Terminating app due to uncaught exception 'NSRangeException', reason: '*** -[__NSArrayM objectAtIndex:]: index 0 beyond bounds for empty array'

### Link to HockeyApp ###

* [https://rink.hockeyapp.net/manage/apps/37029/crash_reasons/142005904](https://rink.hockeyapp.net/manage/apps/37029/crash_reasons/142005904)

**Comment by alloy** [comment]
Fixed by #1972.
