### ISSUE TITLE
Expand Snapshot support to generate our images

### ISSUE THREAD

**Issue by orta** [artsy/eigen#197]
While we don't necessarily have to have the exact screenshots, I think we  should use the same works / hero units:

![screen shot 2015-02-16 at 8 19 32 pm](https://cloud.githubusercontent.com/assets/49038/6248957/c6cbcacc-b751-11e4-88e8-198249b5f798.png)

re: https://github.com/artsy/eigen/pull/195

**Comment by orta** [comment]
Perhaps we could have it logged in as a specific user?

**Comment by alloy** [comment]
Our current App Store images aren’t pure screenshots, so this seems kind of moot for now. Please re-open if disagree.
