### ISSUE TITLE
Feedback 'From: Devang Thakkar Seeing inconsistent behavi...'

### ISSUE THREAD

**Issue by artsyit** [artsy/eigen#1970]
### Message from 4f69f1819a717c0002001b6f sent on 2016-10-25 23:54:13 UTC

> From: Devang Thakkar
> 
> Seeing inconsistent behavior on for auction lots. Two on them on the Roy Lichtenstein page say bid now but this third one says contact for price .. all of them are currently biddable
### Link to HockeyApp
- [https://rink.hockeyapp.net/manage/apps/37029/feedback/646679](https://rink.hockeyapp.net/manage/apps/37029/feedback/646679)

**Comment by alloy** [comment]
iirc this has been fixed
