### ISSUE TITLE
Fix crash in Artsy.LiveAuctionsSalesPerson.init (sale : __ObjC.LiveSale, jwt : Artsy.JWT, biddingCredentials : Artsy.BiddingCredentials, defaults : __ObjC.NSUserDefaults, stateManagerCreator : (host : Swift.String, sale : __ObjC.LiveSale, saleArtworks : [Artsy.LiveAuc, line 70

### ISSUE THREAD

**Issue by artsyit** [artsy/eigen#1973]
### Stacktrace (first of multiple) ###

<pre>-;Artsy.LiveAuctionsSalesPerson.init (sale : __ObjC.LiveSale, jwt : Artsy.JWT, biddingCredentials : Artsy.BiddingCredentials, defaults : __ObjC.NSUserDefaults, stateManagerCreator : (host : Swift.String, sale : __ObjC.LiveSale, saleArtworks : [Artsy.LiveAuctionLotViewModel], jwt : Artsy.JWT, bidderCredentials : Artsy.BiddingCredentials) -> Artsy.LiveAuctionStateManager, auctionViewModelCreator : (sale : __ObjC.LiveSale, currentLotSignal : Interstellar.Observable<Artsy.LiveAuctionLotViewModelType?>, biddingCredentials : Artsy.BiddingCredentials) -> Artsy.LiveAuctionViewModelType) -> Artsy.LiveAuctionsSalesPerson;LiveAuctionSalesPerson.swift;70
-;static Artsy.LiveAuctionViewController.salesPerson (__ObjC.LiveSale, jwt : Artsy.JWT, biddingCredentials : Artsy.BiddingCredentials) -> Artsy.LiveAuctionsSalesPersonType;LiveAuctionViewController.swift;258
-;function signature specialization <Arg[0] = Owned To Guaranteed, Arg[1] = Owned To Guaranteed, Arg[2] = Owned To Guaranteed> of Artsy.LiveAuctionViewController.setupWithSale (__ObjC.LiveSale, jwt : Artsy.JWT, bidderCredentials : Artsy.BiddingCredentials) -> ();LiveAuctionViewController.swift;227
-;Artsy.LiveAuctionViewController.(connectToNetwork () -> ()).(closure #1);LiveAuctionViewController.swift;79
-;Artsy.LiveAuctionStaticDataFetcher.(fetchStaticData () -> Interstellar.Observable<Interstellar.Result<(sale : __ObjC.LiveSale, jwt : Artsy.JWT, bidderCredentials : Artsy.BiddingCredentials)>>).(closure #1);LiveAuctionStaticDataFetcher.swift;92
AFHTTPRequestOperation(JSON);JSONRequestOperationWithRequest:success:failure:;AFHTTPRequestOperation+JSON.m;11</pre>

### Reason ###

Selector name found in current argument registers: saleArtworks

### Link to HockeyApp ###

* [https://rink.hockeyapp.net/manage/apps/37029/crash_reasons/142225561](https://rink.hockeyapp.net/manage/apps/37029/crash_reasons/142225561)

**Comment by ashfurrow** [comment]
This appears to be a bug with Swift, possibly the runtime. It's working on Devang's iOS 10 device (but crashing consistently on Robert's iOS 9 device). I've asked Robert to reboot his device as a way to test if it's the Swift runtime (if it is, then there's not much we can do to fix the bug).

**Comment by ashfurrow** [comment]
This is caused by the device being set to use staging, where the auction had no lots.
