### ISSUE TITLE
Fix NSInvalidArgumentException in __RACSwizzleForwardInvocation_block_invoke, line 84

### ISSUE THREAD

**Issue by artsyit** [artsy/eigen#1978]
### Stacktrace ###

<pre>-;__RACSwizzleForwardInvocation_block_invoke;NSObject+RACSelectorSignal.m;84
ARTabContentView;forceSetCurrentViewIndex:animated:;ARTabContentView.m;178
-;__RACSwizzleForwardInvocation_block_invoke;NSObject+RACSelectorSignal.m;49
-;__RACSwizzleForwardInvocation_block_invoke;NSObject+RACSelectorSignal.m;49
ARWindow;sendEvent:;ARAppDelegate.m;455</pre>

### Reason ###

*** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[ARAppSearchViewController menuAwareScrollView]: unrecognized selector sent to instance 0x1161034a0'

### Link to HockeyApp ###

* [https://rink.hockeyapp.net/manage/apps/37029/crash_reasons/142145466](https://rink.hockeyapp.net/manage/apps/37029/crash_reasons/142145466)

**Comment by alloy** [comment]
Seems very similar to #1976, closing this in favour of that one.
