### ISSUE TITLE
Feedback 'From: orta@artsymail.com Fair artist pages are ...'

### ISSUE THREAD

**Issue by artsyit** [artsy/eigen#1986]
### Message from 4ec92ccb56ae88000100038e sent on 2016-11-01 19:32:00 UTC###

> From: orta@artsymail.com
> 
> Fair artist pages are a bit naff on the old nab buttons

### Link to HockeyApp ###

* [https://rink.hockeyapp.net/manage/apps/37029/feedback/650479](https://rink.hockeyapp.net/manage/apps/37029/feedback/650479)

**Comment by alloy** [comment]
Duplicate of #1625
