### ISSUE TITLE
Fix NSRangeException in - [AROnboardingPersonalizeTableViewController updateTableContentsFor:replaceContents:animated:], line 68

### ISSUE THREAD

**Issue by artsyit** [artsy/eigen#1988]
### Stacktrace ###

<pre>AROnboardingPersonalizeTableViewController;updateTableContentsFor:replaceContents:animated:;AROnboardingPersonalizeTableViewController.m;68
ARPersonalizeViewController;categoryFollowed:;ARPersonalizeViewController.m;316</pre>

### Reason ###

*** Terminating app due to uncaught exception 'NSRangeException', reason: '*** -[__NSArrayM objectAtIndex:]: index 0 beyond bounds for empty array'

### Link to HockeyApp ###

* [https://rink.hockeyapp.net/manage/apps/37029/crash_reasons/143258922](https://rink.hockeyapp.net/manage/apps/37029/crash_reasons/143258922)

**Comment by sarahscott** [comment]
taking a look at this

**Comment by alloy** [comment]
Can you document the steps to reproduce the issue?

**Comment by sarahscott** [comment]
I am not sure exactly how to reproduce this perfectly, but the crash is caused by either `self.searchResults` or `searchResults` being empty.

**Comment by sarahscott** [comment]
So `self.searchResults` will be empty if network is cut before the view is loaded, and `searchResults` can be manually set to an empty array. I think this happens with really spotty network connectivity; i.e. when some data is successfully fetched but not everything.

**Comment by mennenia** [comment]
Spotty network connectivity is a great catch. This might be why we didn't encounter this during our internal testing.
