### ISSUE TITLE
Fix NSInvalidArgumentException in - [AROnboardingPersonalizationGeneImageStateReconciler addReplacedGene:], line 37

### ISSUE THREAD

**Issue by artsyit** [artsy/eigen#1994]
### Stacktrace ###

<pre>AROnboardingPersonalizationGeneImageStateReconciler;addReplacedGene:;AROnboardingPersonalizationGeneImageStateReconciler.m;37
AROnboardingPersonalizeTableViewController;updateTableContentsFor:replaceContents:animated:;AROnboardingPersonalizeTableViewController.m;70
ARPersonalizeViewController;artistFollowed:;ARPersonalizeViewController.m;279</pre>

### Reason ###

*** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '*** -[__NSSetM addObject:]: object cannot be nil'

### Link to HockeyApp ###

* [https://rink.hockeyapp.net/manage/apps/37029/crash_reasons/143301624](https://rink.hockeyapp.net/manage/apps/37029/crash_reasons/143301624)

**Comment by sarahscott** [comment]
@mennenia Is this related to the Onboarding crashes in #1972 ?

**Comment by mennenia** [comment]
@sarahscott doesn't seem like it!

I think I've cracked it (self.selectedRow gets set to nil outside the completion block) and need to add one more code change (somewhere today) and will then push the PR! :) (with more detailed explanation, lol).
