### ISSUE TITLE
Facebook login issues

### ISSUE THREAD

**Issue by mennenia** [artsy/eigen#2004]
- It doesn't seem to be an option to use Apple's integrated Facebook account (at least, it's not working for me when I try this on my devices).

- When a user unauthenticates / removes Artsy from their apps in their profile, and then opens Artsy, they remain logged in. (this is because `ARUserManager` doesn't really talk to Facebook's Login state manager anymore after account creation). 

Also, as an FYI when I then create a new account with the same facebook ID (after having removed it from my apps), I still have my original data (artist follows and favourites, etc). I _think_ this is expected behaviour - when removing an app Facebook does say that it doesn't mean the app will delete the data. Just wanted to flag it, in case we did want to remove those users / that data.

I'm putting this in the tech debt sprint because I'd like to fix it, but if it's not important we can move it to the icebox.

**Comment by alloy** [comment]
> Also, as an FYI when I then create a new account with the same facebook ID (after having removed it from my apps), I still have my original data (artist follows and favourites, etc). I think this is expected behaviour - when removing an app Facebook does say that it doesn't mean the app will delete the data. Just wanted to flag it, in case we did want to remove those users / that data.

I don’t think we want to remove the data.

**Comment by alloy** [comment]
@mennenia What’s the status on this?

**Comment by mennenia** [comment]
I'll have a quick look at what needs to be done to link up with the Apple setting's facebook account and I'll close it after onboarding is approved and shipped.
