### ISSUE TITLE
Fix Danger bug

### ISSUE THREAD

**Issue by sarahscott** [artsy/eigen#2007]
in https://circleci.com/gh/artsy/eigen/3516:

`bundler: failed to load command: danger (/Users/distiller/eigen/vendor/bundle/ruby/2.3.0/bin/danger)
Danger::DSLError: 
[!] Invalid `Dangerfile` file: dlopen(/Users/distiller/eigen/vendor/bundle/ruby/2.3.0/gems/ox-2.4.4/ext/ox/ox.bundle, 9): Library not loaded: /usr/local/opt/ruby/lib/libruby.2.3.0.dylib
  Referenced from: /Users/distiller/eigen/vendor/bundle/ruby/2.3.0/gems/ox-2.4.4/ext/ox/ox.bundle
  Reason: image not found - /Users/distiller/eigen/vendor/bundle/ruby/2.3.0/gems/ox-2.4.4/ext/ox/ox.bundle. Updating the Danger gem might fix the issue. Your Danger version: 3.5.1, latest Danger version: 4.0.0`

**Comment by orta** [comment]
I've removed the gem in https://github.com/artsy/eigen/pull/2040

**Comment by alloy** [comment]
So this can be closed?
