### ISSUE TITLE
App is slow to load, even when network seems to be solid

### ISSUE THREAD

**Issue by artsyit** [artsy/eigen#2011]
### Message from katarina batina sent on 2016-11-13 23:41:00 UTC###

> From: Katarina Batina
> 
> Slow responses it seems in the app. Can't get content to load despite having a full connection (have restarted the app twice and still experiencing slowness)

### Link to HockeyApp ###

* [https://rink.hockeyapp.net/manage/apps/37029/feedback/658302](https://rink.hockeyapp.net/manage/apps/37029/feedback/658302)

**Comment by katarinabatina** [comment]
have been unable to reproduce reliably going to close for now
