### ISSUE TITLE
Onboarding sign up screen updates

### ISSUE THREAD

**Issue by katarinabatina** [artsy/eigen#2012]
Prior to thinking about larger order changes I'd like us to ship the following two smaller changes

- [x] Change copy from current to Set up your Artsy account
- [x] Change button copy to Complete
- [x] Have the keyboard called up at this screen with the cursor blinking in the name field
- [x] Create emphasis on the selected field by making the rule black while selected
- [x] Change input label text in ArtsyGrayMedium when input is selected

![image](https://cloud.githubusercontent.com/assets/6482926/20283130/c4e763a0-aa85-11e6-8b29-983eb52d846b.png)

**Comment by katarinabatina** [comment]
@mennenia @alloy if this represents more than a few days work then I say we table it in favor of a larger shift in onboaring. I'm making some assumptions about the sizes of these changes being small so if I'm wrong on that let me know.

**Comment by mennenia** [comment]
Sounds good!

It should be fine to go into 3.1.0. I won't be able to get it in for today's 3.0.2 deadline I think.

**Comment by mennenia** [comment]
Actually done earlier with some of the other 3.0.2 tickets - can have a shot at this, to see if we can ship it today and get some more data.
