### ISSUE TITLE
Main image for artist shows screenshot of biography

### ISSUE THREAD

**Issue by artsyit** [artsy/eigen#2018]
![asset](https://cloud.githubusercontent.com/assets/2712962/20430585/7ed750ce-ad95-11e6-937d-9c4268eebb8b.jpg)

### Message from Eloy Durán sent on 2016-11-17 04:27:37 UTC###

> From: Eloy Durán
> 
> Found myself another one of those biography screenshots.

### Link to HockeyApp ###

* [https://rink.hockeyapp.net/manage/apps/37020/feedback/660228](https://rink.hockeyapp.net/manage/apps/37020/feedback/660228)

**Comment by sarahscott** [comment]
Happens on web too: 
<img width="470" alt="screen shot 2016-11-18 at 1 44 52 pm" src="https://cloud.githubusercontent.com/assets/2712962/20430559/47d2dc2e-ad95-11e6-8176-9d0614abeda5.png">

**Comment by alloy** [comment]
Aye @sarahscott, this is a funny one, ask @mzikherman for an explanation 😄 

@mzikherman Can you get rid of this one?

**Comment by orta** [comment]
http://artsy.github.io/blog/2015/11/05/Using-OCR-To-Fix-A-Hilarious-Bug/

**Comment by mzikherman** [comment]
It didn't wind up fixing/catching all of them :( but a good amount!

This can be fixed with an easy one or two liner from a gravity console, I'll do that and post it here for posterity.

**Comment by katarinabatina** [comment]
Have seen big improvements here, going to close for now
