### ISSUE TITLE
Fix NSInvalidArgumentException in __RACSwizzleForwardInvocation_block_invoke, line 84

### ISSUE THREAD

**Issue by artsyit** [artsy/eigen#2019]
### Stacktrace ###

<pre>-;__RACSwizzleForwardInvocation_block_invoke;NSObject+RACSelectorSignal.m;84
ARCreateAccountViewController;submit:;ARCreateAccountViewController.m;220
ARUserManager;loginWithUsername:password:successWithCredentials:gotUser:authenticationFailure:networkFailure:saveSharedWebCredentials:;ARUserManager.m;207
AFHTTPRequestOperation(JSON);JSONRequestOperationWithRequest:success:failure:;AFHTTPRequestOperation+JSON.m;11</pre>

### Reason ###

*** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[AROnboardingViewController didSignUpAndLogin]: unrecognized selector sent to instance 0x102000600'

### Link to HockeyApp ###

* [https://rink.hockeyapp.net/manage/apps/37020/crash_reasons/145348333](https://rink.hockeyapp.net/manage/apps/37020/crash_reasons/145348333)

**Comment by alloy** [comment]
I can’t find `didSignUpAndLogin` in our codebase anymore, so going to assume this is fixed.

/cc @mennenia

**Comment by mennenia** [comment]
This was part of the issue that we put the hotfix out for.

**Comment by alloy** [comment]
Right, perfect 👌
