### ISSUE TITLE
ArtistVC routing is messed up in PartnerVC

### ISSUE THREAD

**Issue by artsyit** [artsy/eigen#2023]
### Message from 5501de167261696e34610200 sent on 2016-11-18 12:53:22 UTC###

> From: Sarah Scott
> 
> tapping artist from partner's page pushes old version of artistVC

### Link to HockeyApp ###

* [https://rink.hockeyapp.net/manage/apps/37020/feedback/661100](https://rink.hockeyapp.net/manage/apps/37020/feedback/661100)

**Comment by sarahscott** [comment]
To repro: 
- Go to a Partner's VC
- Tap 'Artists'
- Tap on an Artist

The resulting VC is not our new RN version.

**Comment by sarahscott** [comment]
This happens because the PartnerVC is a martsy view and it routes to the martsy version of an artist view instead of the native one.

**Comment by alloy** [comment]
@sarahscott What’s the URL being used, normally Eigen’s routing should still intercept routes from webviews.

**Comment by sarahscott** [comment]
For the partner or for the artist? The url for an artist selected from the partner's page looks like:
`https://m-staging.artsy.net/[partner_slug]/artist/[artist_slug]`

**Comment by alloy** [comment]
For the artist, yeah. So the `[partner_slug]` part is the reason why Eigen’s routes isn’t matching it. We currently match artist routes [in 1 way only](https://github.com/artsy/eigen/blob/6f05115b3dbcea78b90b3a9dfd42b39cad716d81/Artsy/App/ARSwitchBoard.m#L144-L147), which is defined [here](https://github.com/artsy/eigen/blob/4454d6bb595a4fcc0d491c75eed07e24cae52300/Artsy/App/Echo.json) as:

```json
{"name":"ARArtistRoute","path":"/artist/:id"}
```

I guess you’d need to add a `ARPartnerArtist` route which just shows the same VC? /cc @orta
