### ISSUE TITLE
Search VC pushed twice.

### ISSUE THREAD

**Issue by artsyit** [artsy/eigen#2025]
### Stacktrace ###

<pre>-;main;main.m;14</pre>

### Reason ###

*** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: 'Pushing the same view controller instance more than once is not supported (<ARAppSearchViewController: 0x10f5e6090>)'

### Link to HockeyApp ###

* [https://rink.hockeyapp.net/manage/apps/37029/crash_reasons/144970824](https://rink.hockeyapp.net/manage/apps/37029/crash_reasons/144970824)

**Comment by alloy** [comment]
I was able to reproduce this crash by:

1. tap a search result
2. immediately (while the search VC is still on screen) tap the search icon in the tab bar

**Comment by alloy** [comment]
Reproducing is simplified by enabling slow animations in the sim (Command+T)
