### ISSUE TITLE
A/B testing framework for iOS

### ISSUE THREAD

**Issue by tayapage6** [artsy/eigen#2032]
Placeholder for future discussion. Would be nice to have both iOS only and iOS + Web testing ability.

**Comment by mennenia** [comment]
@alloy @orta we don't have anything in place currently, right? 

Is it something we could easily add, considering we have switchboard to route to pages?

**Comment by alloy** [comment]
> we don't have anything in place currently, right?

Correct.

> Is it something we could easily add, considering we have switchboard to route to pages?

That could be easy, but I think @tayapage6 will want to be able to A/B test single small components within views too. Still might be simple to implement, just can’t do that through the switchboard.

@craigspaeth @broskoski Can you give me an overview of how you’ve been performing these on the web?

**Comment by alloy** [comment]
Moving this to CE repo.

**Comment by alloy** [comment]
Issue moved to [artsy/collector-experience #153](https://github.com/artsy/collector-experience/issues/153) via [**ZenHub**](https://www.zenhub.com/)
