### ISSUE TITLE
Fix crash in - [SDWebImageDownloaderOperation connectionDidFinishLoading:], line 376

### ISSUE THREAD

**Issue by artsyit** [artsy/eigen#2038]
### Stacktrace ###

<pre>SDWebImageDownloaderOperation;connectionDidFinishLoading:;SDWebImageDownloaderOperation.m;376
SDWebImageDownloaderOperation;start;SDWebImageDownloaderOperation.m;117</pre>

### Link to HockeyApp ###

* [https://rink.hockeyapp.net/manage/apps/37029/crash_reasons/146712659](https://rink.hockeyapp.net/manage/apps/37029/crash_reasons/146712659)

**Comment by alloy** [comment]
Possibly related #2046
