### ISSUE TITLE
Feedback 'From: Katarina Batina Still seeing dual selecte...'

### ISSUE THREAD

**Issue by artsyit** [artsy/eigen#2041]
### Message from katarina batina sent on 2016-11-28 23:21:41 UTC###

> From: Katarina Batina
> 
> Still seeing dual selected lots, in staging

### Link to HockeyApp ###

* [https://rink.hockeyapp.net/manage/apps/37020/feedback/667616](https://rink.hockeyapp.net/manage/apps/37020/feedback/667616)

**Comment by ashfurrow** [comment]
Yeah, staging's data around that particular auction isn't reliable, I looked into this and that's just the data that's coming from staging. It should work on other, freshly created staging auctions.
