### ISSUE TITLE
LoginVC has an extra field if compiled from Xcode8

### ISSUE THREAD

**Issue by sarahscott** [artsy/eigen#2044]
This isn't happening in the app store version but it does happen in the sim and on-device if you install from Xcode 8:

![simulator screen shot nov 29 2016 12 34 09 pm](https://cloud.githubusercontent.com/assets/2712962/20721266/45d874e4-b630-11e6-9557-bd0330a4e13c.png)

**Comment by mennenia** [comment]
Fixed in #2118
