### ISSUE TITLE
Fix crash in - [SDWebImageDownloaderOperation start], line 117

### ISSUE THREAD

**Issue by artsyit** [artsy/eigen#2046]
### Stacktrace ###

<pre>SDWebImageDownloaderOperation;start;SDWebImageDownloaderOperation.m;117</pre>

### Reason ###

No reason found. Full stack trace includes libsystem_kernel.dylib, libsystem_pthread.dylib, libsystem_c.dylib, libsystem_malloc.dylib, CoreFoundation, CFNetwork, libdispatch.dylib, Foundation.

### Link to HockeyApp ###

* [https://rink.hockeyapp.net/manage/apps/37029/crash_reasons/144645731](https://rink.hockeyapp.net/manage/apps/37029/crash_reasons/144645731)

**Comment by alloy** [comment]
Possibly related #2038
