### ISSUE TITLE
[Onboarding] Fix / add tests

### ISSUE THREAD

**Issue by mennenia** [artsy/eigen#2047]
Patch up the test suite after having removed bits due to release.

**Comment by alloy** [comment]
@mennenia Can this be closed?

**Comment by mennenia** [comment]
I consider onboarding sufficiently tested with the integration tests - but there aren't many snapshot or unit tests for it (which is what this ticket was hinting at). I'd say close this.. What do you think @alloy?

**Comment by alloy** [comment]
Let's do it 👍
