### ISSUE TITLE
[Testing] Investigate XCode's integration testing options

### ISSUE THREAD

**Issue by mennenia** [artsy/eigen#2053]
They've introduced UI Testing and UI Recording (docs [here](https://developer.apple.com/library/content/documentation/DeveloperTools/Conceptual/testing_with_xcode/chapters/09-ui_testing.html))

From our discussion earlier, I think having various UI recordings (a series of actions), would be great. I'll start investigating this at the hand of onboarding.

**Comment by mennenia** [comment]
So, I've looked into and used Xcode's built in UI testing and it's great. It's a separate process that runs in the background and interacts with your default app using accessibility. It's still based on XCTest, so you can add assertions etc for elements you expect to be on screen etc.

A first round of onboarding tests have gone in, using environment variables to signal to the main app what context to load up in (you could also store this in NSUserDefaults I've heard).

The problem however seems with CI. It seems difficult to run the tests consistently on Circle - they have passed, but they fail more often than not. 

The errors started with the fact that certain elements weren't "tappable" or interactable, perhaps because the elements hadn't loaded yet. A recommendation often given in this case, is to add code that waits for elements to show on screen. This now results in the fails often citing a timeout instead. The issue is not that the element takes time to appear on screen, it's that the element sometimes (most times) just does not appear. 

When looking at the screenshots (they can be found in derived data), everything looks fine. There is nothing funky going on with the UI, where elements are missing, or no data is being loaded etc. 

It's not a performance issue:
- The tests run and succeed locally 
- The tests run and succeed locally, with 10 second sleeps in API callbacks
- The tests run and succeed locally, on low spec devices (e.g. 12" macbook)

And the tests run and succeed (mostly), when using a different CI (Bitrise). I've ran the same branch and commit (no changes) 17 times, out of which it failed 3 times. When a build does fail, it's a similar issue: the timeout of those waits has been reached, meaning the element isn't there. But it seems a lot better than Circle.

Personally, I don't know what the difference is between their environments, but it's safe to say that it can and should work, but doesn't do so currently. 

@alloy should we park this for now? Should we keep the tests and run them locally before we push out a beta?

**Comment by alloy** [comment]
Let’s definitely keep them, but run them locally for now indeed. Maybe we can also ask CircleCI support for advice?

/cc @dantoml
