### ISSUE TITLE
Facebook connect creating crash

### ISSUE THREAD

**Issue by katarinabatina** [artsy/eigen#2056]
going through onboarding, tapped on connect with facebook (I have the facebook app and am logged in so I get sent there), I am asked to authorize artsy, when I get back to artsy, I see the splash screen and then it crashes.

**Comment by mennenia** [comment]
These two crashes showed up in hockey at that time (that could be the reason it’s happening)

https://rink.hockeyapp.net/manage/apps/37020/crash_reasons/147486486/multiple

https://rink.hockeyapp.net/manage/apps/37020/crash_reasons/147486579/multiple

(they look like they’re the same)

**Comment by mennenia** [comment]
Looks like I nuked a bit too much code in [the original PR](https://github.com/artsy/eigen/pull/2005).

Fixing it now, and will close the associated crashes (all of them regarding 3.0.2. that seem to be in the Emission App delegate about inserting a nil object). 

Thanks for flagging @katarinabatina :+1:

**Comment by mennenia** [comment]
This got fixed ages ago lol.
