### ISSUE TITLE
Fix crash in Artsy.LiveAuctionsSalesPerson.lotViewModelRelativeToShowingIndex (Swift.Int) -> Artsy.LiveAuctionLotViewModelType, line 148

### ISSUE THREAD

**Issue by artsyit** [artsy/eigen#2057]
### Stacktrace ###

<pre>-;Artsy.LiveAuctionsSalesPerson.lotViewModelRelativeToShowingIndex (Swift.Int) -> Artsy.LiveAuctionLotViewModelType;LiveAuctionSalesPerson.swift;148
-;protocol witness for Artsy.LiveAuctionsSalesPersonType.lotViewModelRelativeToShowingIndex (Swift.Int) -> Artsy.LiveAuctionLotViewModelType in conformance Artsy.LiveAuctionsSalesPerson : Artsy.LiveAuctionsSalesPersonType in Artsy;LiveAuctionSalesPerson.swift;135
-;@objc Artsy.LiveAuctionLotCollectionViewDataSource.aspectRatioForIndex (Swift.Int) -> CoreGraphics.CGFloat;LiveAuctionLotCollectionViewDataSource.swift;58
-;Artsy.LiveAuctionFancyLotCollectionViewLayout.(applyFancyLayoutToAttributes in _9C1733ABC9DFD66F67338882E9CCE054) (inout __ObjC.UICollectionViewLayoutAttributes, position : Artsy.(CellPosition in _9C1733ABC9DFD66F67338882E9CCE054)) -> ();LiveAuctionFancyLotCollectionViewLayout.swift;165
-;function signature specialization <Arg[0] = Owned To Guaranteed> of Artsy.LiveAuctionFancyLotCollectionViewLayout.(modifiedLayoutAttributesCopy in _9C1733ABC9DFD66F67338882E9CCE054) (__ObjC.UICollectionViewLayoutAttributes) -> __ObjC.UICollectionViewLayoutAttributes;LiveAuctionFancyLotCollectionViewLayout.swift;146
-;Artsy.LiveAuctionFancyLotCollectionViewLayout.(layoutAttributesForElementsInRect (__C.CGRect) -> [__ObjC.UICollectionViewLayoutAttributes]?).(closure #1);LiveAuctionFancyLotCollectionViewLayout.swift;77
-;function signature specialization <Arg[0] = Owned To Guaranteed> of generic specialization <[Swift.Int] with [Swift.Int] : Swift.SequenceType in Swift, Swift.IndexingGenerator<[Swift.Int]> with Swift.IndexingGenerator<[Swift.Int]> : Swift.GeneratorType in Swift, Swift.Int, Swift.ArraySlice<Swift.Int>, __ObjC.UICollectionViewLayoutAttributes> of (extension in Swift):Swift.SequenceType.flatMap <A> ((A.Generator.Element) throws -> A1?) throws -> [A1];LiveAuctionFancyLotCollectionViewLayout.swift;0
-;function signature specialization <Arg[0] = Dead> of Artsy.LiveAuctionFancyLotCollectionViewLayout.layoutAttributesForElementsInRect (__C.CGRect) -> [__ObjC.UICollectionViewLayoutAttributes]?;LiveAuctionFancyLotCollectionViewLayout.swift;73
-;@objc Artsy.LiveAuctionFancyLotCollectionViewLayout.layoutAttributesForElementsInRect (__C.CGRect) -> [__ObjC.UICollectionViewLayoutAttributes]?;LiveAuctionFancyLotCollectionViewLayout.swift;0</pre>

### Link to HockeyApp ###

* [https://rink.hockeyapp.net/manage/apps/37029/crash_reasons/147515899](https://rink.hockeyapp.net/manage/apps/37029/crash_reasons/147515899)

**Comment by ashfurrow** [comment]
Fixed in https://github.com/artsy/eigen/pull/2031.
