### ISSUE TITLE
Works by another artist in the artist page

### ISSUE THREAD

**Issue by dblock** [artsy/eigen#2065]
Haven't debugged of whether this is a client vs. API problem. David Shrigley's page shows works by another artist.

![img_8301](https://cloud.githubusercontent.com/assets/542335/20870034/0a542004-ba4e-11e6-8f94-c424a3bb2c0f.PNG)

**Comment by alloy** [comment]
Happens on web too, but wow what a weird one.

![img_9575](https://cloud.githubusercontent.com/assets/2320/21165878/0e0552c6-c170-11e6-8db3-f723058f9802.PNG)

**Comment by mzikherman** [comment]
These works actually have two artists associated with them, one of whom _is_ David Shrigley.

Microgravity (and presumably Eigen?) are only displaying the first artist, whereas desktop web for example displays all of them, in a comma-separated list:

<img width="657" alt="screen shot 2016-12-13 at 9 14 16 pm" src="https://cloud.githubusercontent.com/assets/1457859/21167284/81b53e26-c179-11e6-91cb-6d1250dea8ec.png">

**Comment by orta** [comment]
Yep, that sounds right to me - don't think Eigen was ever updated to add multi-artist support correctly throughout

Do we handle this in metaphysics? The possibilities for multiple artists, and cultural maker etc makes it possible for a lot of places to be out of sync

**Comment by alloy** [comment]
Good thinking @mzikherman.

The `artist` field in MP should be marked as deprecated then. It already has an `artists` field, so it should be easy enough to migrate. I’m thinking that we probably could also use the `shallow` arg for these.

@mzikherman Feeling up for diving into [Emission](https://github.com/artsy/emission/blob/master/lib/components/artwork_grids/artwork.js)? 😄

**Comment by alloy** [comment]
Fixed.
