### ISSUE TITLE
[Analytics] Improving Instrumentation 

### ISSUE THREAD

**Issue by mennenia** [artsy/eigen#2069]
[Initial discussion writeup](https://github.com/artsy/mobile/issues/104)

Based off my conversation with the analytics team, I've managed to distil the required data into 3 types of events:
- **Session** event (e.g. on app launch or close)
- **Screen view** event (e.g. the artist page of Damien Hirst opens)
- **Action** events (e.g. user input like signing up with Facebook, or favouriting an artwork)

Data required for each of these events:

| Session                   	| Screen view                                  	| Actions                    	|
|---------------------------	|----------------------------------------------	|----------------------------	|
| - Type: e.g. start / end  	| - Screen id / unique url*                   	| - Source/context screen*  	|
| - Length: int             	| - Referral screen*                          	| - Properties               	|
| - Anonymous id            	| - Deeplink source (this is the most elusive) 	| - Anonymous id             	|
| - User id                 	| - Anonymous id                               	| - User id                  	|
|                           	| - User id                                    	|                            	|

These events could be triggered from various places:

| Session 	| Screen view 	| Actions       	|
|-------------------	|-----------------------	|--------------------------	|
| - App delegate    	| - Switchboard         	| - Anywhere / ARAnalytics 	|
|                   	| - Tab switch          	|                          	|
|                   	| - viewDidLoad         	|                          	|

@anipetrov @wrgoldstein
- Is this correct based off last week's meeting?
- I'm making an assumption that the the screens (annotated with *) are of the same type/unique URL - is this correct?

@alloy @tayapage6 @katarinabatina From my understanding, we have a bit of time carved out in the upcoming pipeline for me to work on this, right? My plan was to wrap up most of the prior scoping work before EOY, and start with required implementations in January. I've created a collector experience ticket (for planning purposes and external stakeholders) [here](https://github.com/artsy/collector-experience/issues/63).

cc/ @jessekedy we had a chat about deeplinking. Anything else we should be aware of? 

Engineering questions to explore:
- Integration of SDKs? (e.g. [Segment](https://segment.com/docs/sources/mobile/ios/) and [Adjust](https://www.adjust.com/mobile-app-tracking-sdk/))
- How will we do analytics in Emission (i.e. directly from there, or via Eigen, and how would that look like)
- What's the best way to generate these unique URLs
- Probably a bunch more.

**Comment by mennenia** [comment]
Current, general outline (needs to be prioritised and perhaps split into different stages)

- [ ] Screen views / IDs (with dictionary, not URL style)
- [ ] General events / track should come with a more fleshed out dictionary (e.g. "follow artist",  type: tap, screen: screenid, etc) 
- [ ] Deeplink analytics events: when eigen is opened from a deeplink, we'd need to send an event that captures where we were opened from (e.g. email), so we can see what campaigns result in what type of app behaviour (e.g. did people inquire? did these inquiries lead anywhere?) similar to web where you can grab UTM parameters 
- [ ] see if we can fix issues with double firing (like artworks vc)
- [ ] distinguish eigen screens from web views within eigen (do we just want to open some of them in safari? -> more general product dicussion)
- [ ] find a more consistent way of adding analytics to our features (e.g. Danger rule on PRs? Maybe even something a bit more in advance?)
- [ ] set up more sophisticated instrumentation in Emission (separate issue will follow) 
- [ ] finalise and implement a set way of dealing with success / failure taps (e.g. following an artist - three types of events, the intent / tap, the success (including perhaps ids of generated inquiries etc, the failure).
- [ ] eventually it'd be great to have referral screens where you can see which screen id someone came from to be on the screen they are now (likely to be in V2). 

@anipetrov these are rough notes of our chat just now, anything missing?

**Comment by anipetrov** [comment]
This is 💯, thank you so much @mennenia!

**Comment by katarinabatina** [comment]
bump @orta to discuss tracking "activities" to better improve our chances of ranking in safari search

**Comment by mennenia** [comment]
OK! I've captured all of these requirements across various issues (linked above). @katarinabatina, your request is now in #2268  :).

Going to close this now. Project as a whole has been moved to: https://github.com/artsy/eigen/projects/1 😊
