### ISSUE TITLE
Increase search field height on fair overview

### ISSUE THREAD

**Issue by katarinabatina** [artsy/eigen#207]
![image](https://cloud.githubusercontent.com/assets/6482926/6307649/505a2a62-b90b-11e4-8a8a-2095ca257b62.png)

New size should be reflected when search is enabled  
![image](https://cloud.githubusercontent.com/assets/6482926/6307598/01bd5370-b90b-11e4-8823-9b5b3e8c7ef0.png)

**Comment by mennenia** [comment]
@katarinabatina Do you want to check the before and after of PR #1157? :)

**Comment by katarinabatina** [comment]
@mennenia I think this is done no?

**Comment by orta** [comment]
I'm not sure, I had to go in and fix something in `2.3.4` around this,  I might have done it

**Comment by mennenia** [comment]
`2.3.4` was before I joined, right? Because in that case it's done, as per PR #1157. I was just waiting for you to check / approve and then close, @katarinabatina

**Comment by katarinabatina** [comment]
yup we can close!
