### ISSUE TITLE
Feedback 'From: Owen Dodd Fonts not loading'

### ISSUE THREAD

**Issue by artsyit** [artsy/eigen#2075]
### Message from 54a9d9667261691d4c191200 sent on 2016-12-12 22:22:11 UTC###

> From: Owen Dodd
> 
> Fonts not loading

### Link to HockeyApp ###

* [https://rink.hockeyapp.net/manage/apps/37020/feedback/678798](https://rink.hockeyapp.net/manage/apps/37020/feedback/678798)

**Comment by l2succes** [comment]
Fixed with https://github.com/artsy/microgravity/pull/102
