### ISSUE TITLE
[OSS] Setup failure on `bundle exec pod install`

### ISSUE THREAD

**Issue by swizzlr** [artsy/eigen#2079]
This fails on both master and most recent tag, with the following output.

```
$ bundle exec pod install
Analyzing dependencies
Pre-downloading: `Artsy+UIFonts` from `https://github.com/artsy/Artsy-OSSUIFonts.git`
[!] Unable to find a specification for 'Artsy+UIFonts'.
```

I'm not quite sure what's going on here. I see @ashfurrow recently committed an update; adjusting the Podfile to point to the previous tag doesn't seem to help matters.

**Comment by ashfurrow** [comment]
Yikes, thanks for the issue. Would you mind trying a pod update on that one OSS font pod?

**Comment by swizzlr** [comment]
Yeah, unfortunately that didn't seem to change anything. I did discover that renaming the Pod name to Artsy+UIFonts (https://github.com/artsy/Artsy-OSSUIFonts/pull/6) sort of fixes matters, but then...

```
Generating Pods project
Abort trap: 6
```

![](http://i.giphy.com/12bVDtXPOzYwda.gif)

**Comment by swizzlr** [comment]
(I'm using bundle exec, ruby 2.3.0)

**Comment by ashfurrow** [comment]
Yeah, I had to deal with this on Eidolon over the weekend, I'll submit a PR to fix and let you know 👍
