### ISSUE TITLE
Feedback 'From: Katarina Batina Fonts aren't loading in m...'

### ISSUE THREAD

**Issue by artsyit** [artsy/eigen#2081]
### Message from katarina batina sent on 2016-12-21 16:37:17 UTC###

> From: Katarina Batina
> 
> Fonts aren't loading in mg views in eigen

### Link to HockeyApp ###

* [https://rink.hockeyapp.net/manage/apps/37020/feedback/686728](https://rink.hockeyapp.net/manage/apps/37020/feedback/686728)

**Comment by l2succes** [comment]
Fixed with https://github.com/artsy/microgravity/pull/102
