### ISSUE TITLE
Couldn't get Facebook credentials

### ISSUE THREAD

**Issue by jpmartha** [artsy/eigen#2082]
I tried to login with Facebook, but an error has occured.

1. "GET STARTED"
2. "Follow artists that most interest you" => NEXT
3. "Follow categories of art that most interest you" => NEXT
4. "Do you have a budget in mind?" => NEXT
5. "CONNECT WITH FACEBOOK"
6. "ユーザーはこのアプリケーションを見ることを許可されていません。:開発者の設定により、ユーザーはこのアプリケーションを見ることを許可されていません。" (This is a Japanese error message at the top of the screen.) => OK
7. "**Couldn't get Facebook credentials**"

6 | 7
---|---
<img src=https://cloud.githubusercontent.com/assets/16237019/21464687/d908c556-c9c8-11e6-9422-546d38e013fb.PNG width=240> | <img src=https://cloud.githubusercontent.com/assets/16237019/21464668/e6b009cc-c9c7-11e6-8947-550e424a5b6e.PNG width=240>

#### Device Information
- iPhone 6s Plus
- iOS version: 10.2
- Artsy app version: 3.0.3

**Comment by alloy** [comment]
Thanks so much for taking the time to report!

According to google translate, the meaning of the FB error message is the below, does that seem accurate?

> The user is not allowed to view this application. : Depending on the developer's settings, the user is not allowed to view this application.

**Comment by jpmartha** [comment]
@alloy 
No, problem. Yes! That's right.
Please feel free to contact me if you need any further information.

**Comment by alloy** [comment]
Thanks again 👍

**Comment by jpmartha** [comment]
I'm not sure if it's related to this issue, but I login as a user for our app development on Facebook. I'll let you know when I find out something.

**Comment by mennenia** [comment]
Hi @jpmartha, thanks for reporting!

When you say you're logging in as a user for your app development, do you mean using an email that facebook has given you? For example: `randomname_273847293@tfbnw.net`? 

In this case it would make sense you wouldn't be able to log in, as we haven't associated that test account with our app in the Facebook dev settings. Could you perhaps try with a personal account?

If you _are_ logging in with a personal account (you just happen to also use it for development), then I can try and dig deeper - let me know! :)

**Comment by jpmartha** [comment]
Hi, @mennenia 
I'm really sorry for the late reply.

> do you mean using an email that facebook has given you? For example: `randomname_273847293@tfbnw.net`?

Yes.

> In this case it would make sense you wouldn't be able to log in, as we haven't associated that test account with our app in the Facebook dev settings. Could you perhaps try with a personal account?
>
> If you are logging in with a personal account (you just happen to also use it for development), then I can try and dig deeper - let me know! :)

Okay, I see.
I tried to log in with my personal account, then this error didn't occured.
But, an another error occured and this app crashed.
So, I sent a report from dialog which this app displayed when the app restarted.

However, I don't think it's the same as this issue #2082.
Would you close this issue #2082?

I'm sorry to have caused trouble.

**Comment by mennenia** [comment]
Hi @jpmartha,

Thank you for checking that, and then sending a crash report! I'm sorry you had that experience. 

No trouble at all, it's a great help to get these reports 🎉
