### ISSUE TITLE
Fix crash in - [RACSubscriber sendNext:], line 73

### ISSUE THREAD

**Issue by artsyit** [artsy/eigen#2087]
### Stacktrace ###

<pre>RACSubscriber;sendNext:;RACSubscriber.m;73
RACPassthroughSubscriber;sendNext:;RACPassthroughSubscriber.m;74
RACSubject;enumerateSubscribersUsingBlock:;RACSubject.m;85
RACSubject;sendNext:;RACSubject.m;92
-;__RACSwizzleForwardInvocation_block_invoke;NSObject+RACSelectorSignal.m;54
ARArtworkSetViewController;viewDidLoad;ARArtworkSetViewController.m;80</pre>

### Link to HockeyApp ###

* [https://rink.hockeyapp.net/manage/apps/37029/crash_reasons/150498298](https://rink.hockeyapp.net/manage/apps/37029/crash_reasons/150498298)

**Comment by alloy** [comment]
Seems related to #2134
