### ISSUE TITLE
Failed to clone 

### ISSUE THREAD

**Issue by MarcSteven** [artsy/eigen#2089]
When I tried to do as you said, the error occurred...Pls see pic...
<img width="529" alt="2016-12-30 10 15 01" src="https://cloud.githubusercontent.com/assets/13824297/21558682/e2c897e2-ce78-11e6-9ee3-6a7ebac50f2c.png">

**Comment by susuyan** [comment]
Network problems, you can try to re-operate

**Comment by MarcSteven** [comment]
Actually the network works well,I can download any resources ......Retry more times.....

**Comment by susuyan** [comment]
oh,  change directory git clone.
 eg: cd Desktop 
       git clone https://github.com/artsy/eigen.git

**Comment by orta** [comment]
I'm assuming this is an issue with your network, we can't control if you can connect to GitHub alas.
