### ISSUE TITLE
Feedback 'From: Katarina Batina Auction title should be c...'

### ISSUE THREAD

**Issue by artsyit** [artsy/eigen#2103]
### Message from katarina batina sent on 2017-01-12 17:31:04 UTC###

> From: Katarina Batina
> 
> Auction title should be centered

### Link to HockeyApp ###

* [https://rink.hockeyapp.net/manage/apps/37020/feedback/702853](https://rink.hockeyapp.net/manage/apps/37020/feedback/702853)

**Comment by ashfurrow** [comment]
![image_0](https://cloud.githubusercontent.com/assets/498212/22026540/10d87a06-dc9f-11e6-95f9-246e4648e66c.jpg)
