### ISSUE TITLE
Fix crash in - [RCTBatchedBridge handleBuffer:], line 950

### ISSUE THREAD

**Issue by artsyit** [artsy/eigen#2105]
### Stacktrace (first of multiple) ###

<pre>RCTBatchedBridge;handleBuffer:;RCTBatchedBridge.m;950
RCTBatchedBridge;handleBuffer:;RCTBatchedBridge.m;942
RCTBatchedBridge;handleBuffer:batchEnded:;RCTBatchedBridge.m;900
RCTJSCExecutor;setUp;RCTJSCExecutor.mm;445
RCTJSCExecutor;_executeJSCall:arguments:unwrapResult:callback:;RCTJSCExecutor.mm;687
RCTJSCExecutor;executeBlockOnJavaScriptQueue:;RCTJSCExecutor.mm;822
RCTJSCExecutor;_executeJSCall:arguments:unwrapResult:callback:;RCTJSCExecutor.mm;650
RCTJSCExecutor;_callFunctionOnModule:method:arguments:flushQueue:unwrapResult:callback:;RCTJSCExecutor.mm;622
RCTJSCExecutor;callFunctionOnModule:method:arguments:callback:;RCTJSCExecutor.mm;627
RCTBatchedBridge;_actuallyInvokeAndProcessModule:method:arguments:;RCTBatchedBridge.m;855
RCTBatchedBridge;enqueueJSCall:method:args:completion:;RCTBatchedBridge.m;781
RCTJSCExecutor;executeBlockOnJavaScriptQueue:;RCTJSCExecutor.mm;822
RCTJSCExecutor;runRunLoopThread;RCTJSCExecutor.mm;275</pre>

### Link to HockeyApp ###

* [https://rink.hockeyapp.net/manage/apps/37029/crash_reasons/149423167](https://rink.hockeyapp.net/manage/apps/37029/crash_reasons/149423167)

**Comment by alloy** [comment]
Seems related to #2108
