### ISSUE TITLE
Don’t intercept `tel:` links

### ISSUE THREAD

**Issue by alloy** [artsy/eigen#2113]
From https://github.com/artsy/collector-experience/issues/74

Currently we end up showing this ugly alert when a user taps a `tel:` link in a webview:

![](https://cloud.githubusercontent.com/assets/23346526/21871412/ec54c23e-d82f-11e6-88e5-91e0fc7c1729.PNG)

**Comment by izakp** [comment]
@alloy what is the new behavior to be?  I don't imagine we want to get rid of handling the link all together? Also I don't believe we can bypass the alert modal, as stated in the documentation here https://developer.apple.com/library/content/featuredarticles/iPhoneURLScheme_Reference/PhoneLinks/PhoneLinks.html

**Comment by ArtsyPrivateDanger** [comment]
We shouldnt show our alert, just let it be the system one you linked to IMO

**Comment by alloy** [comment]
Yes, like @ArtsyPrivateDanger says, we shouldn’t be showing our alert, but rather let iOS show the default system one that takes you to Phone.app.
