### ISSUE TITLE
Feedback 'From: Ash Need to hide "contact gallery" if the...'

### ISSUE THREAD

**Issue by artsyit** [artsy/eigen#2115]
### Message from Ash Furrow sent on 2017-01-17 22:02:36 UTC###

> From: Ash
> 
> Need to hide "contact gallery" if the auction is live. This is related to the changes that retire end_at from eigen.

### Link to HockeyApp ###

* [https://rink.hockeyapp.net/manage/apps/37020/feedback/706807](https://rink.hockeyapp.net/manage/apps/37020/feedback/706807)

**Comment by ashfurrow** [comment]
![asset png](https://cloud.githubusercontent.com/assets/498212/22071144/3a7fb8e2-dd6c-11e6-9219-20515278e2ed.jpeg)
