### ISSUE TITLE
Investigate issues around login events / onboarding analytics

### ISSUE THREAD

**Issue by mennenia** [artsy/eigen#2123]
- Staggering drop from those viewing the login screen, to successfully logging in
- Duplicate events (not that they're sent twice, but we have two event names for the same thing): would like to simplify
- Downloads vs viewing the home screen

**Comment by mennenia** [comment]
Investigation from my side is done - pending a deeper dive perhaps with @anipetrov regarding the login events.

**Comment by alloy** [comment]
@anipetrov @mennenia What’s the status on this?

**Comment by anipetrov** [comment]
Ah did not realize there is an issue around this. I messaged Maxim about this a few weeks ago, this is the thread (copied from slack, so excuse the formatting):

>hi maxim! i have some findings about the login stuff! the mixpanel funnel building is kind of off it seems :flushed:
>
>there are also 2286 logins we have seen from safari keychain (long live properties!!!!), so those won’t have been from users that have tapped log in: https://artsy.looker.com/sql/pxmdt9dkkjy9kk 
>
>this is a mixpanel-esque funnel i wrote to see how the flow between screens goes:
>https://artsy.looker.com/sql/cznngpszbwbgmm
looks like ~25% that tap the log in on the start screen actually log in after tapping on the onboarding start screen log in button, or about 5,000 people 
>
>finally, i cannot really see `successfully logged in` event firing because the “Artsy would like to update the safari saved password for m.artsy.net” popup blocking the analytics popovers upon sign up but i guess it’s hooked up. if it is hooked up properly, there is another way (other than keychain) to log in without tapping on log in on the start screen: it happens if you try to sign up from get started and use an email that is already associated with a user
>
>if all the tracking there is in order, we should be seeing 839 people logging in in that fashion: 
https://artsy.looker.com/sql/pfdn3zrqmqrhxg
>
>there are some people with multiple successfully_logged_in events fired so i will def dig into their event stream and see what’s happening

**Comment by mennenia** [comment]
@anipetrov yup, awesome! So, my question is basically whether we need to change any of the events we're reporting for login and signup, although with the new onboarding it's all changing anyway I guess.

**Comment by mennenia** [comment]
All sorted now with new onboarding events! There were two types of events being sent - from our User Manager as it were, and the onboarding code itself.
