### ISSUE TITLE
Onboarding V2 Prototype

### ISSUE THREAD

**Issue by mennenia** [artsy/eigen#2124]
Prototype, purposefully created for a quick user test. 

![full](https://cloud.githubusercontent.com/assets/373860/22201104/21893718-e15a-11e6-92ba-1629ae6f9ae2.png)

**Comment by orta** [comment]
ah yeah, I've always preferred this kind of setup process

**Comment by mennenia** [comment]
Done - video can be viewed on [wake](https://artsy.wake.com/set/97/1474) :)
