### ISSUE TITLE
Feedback 'From: Katie Higgins'

### ISSUE THREAD

**Issue by artsyit** [artsy/eigen#2136]
### Message from 537963418b3b8122330012f3 sent on 2017-02-01 13:16:26 UTC###

> From: Katie Higgins

### Link to HockeyApp ###

* [https://rink.hockeyapp.net/manage/apps/37029/feedback/717869](https://rink.hockeyapp.net/manage/apps/37029/feedback/717869)

**Comment by katarinabatina** [comment]
I think this might have been a mistake
