### ISSUE TITLE
repeat inquiries?

### ISSUE THREAD

**Issue by joeyAghion** [artsy/eigen#2138]
We were alerted to several batches of seemingly repeat inquiries. Upon investigation, they shared a recent version of Eigen in their user-agent (including `2017.01.24`, so apparently a very recent version).

IDs of example inquiries:
* `["58916d3bc9dc2416f12f398d", "58916d31b202a303a562b2bc", "58916d34139b2116f23b2802"]`
* `["5891d6388b3b814a73b7caa7", "5891d63bb202a34cc7d50df2", "5891d63a8b3b814b48db040f"]`

Each batch had both very short intervals and somewhat longer intervals (hours) between individual inquiry creations.

Let me know if I can provide any additional info.

**Comment by alloy** [comment]
Can you point out (possibly link) where the data is that you've learned this from? I should be able to start sleuthing from there 👍

**Comment by ashkan18** [comment]
Just got another example but this one is on another eigen version
```ruby
gravity:production> InquiryRequest.where(:id.in => ["5891f0f6a09a6717bbbd5bb7", "5891f0f47622dd6145a0046b"]).pluck(:user_agent)
=> ["Mozilla/5.0 Artsy-Mobile/2.6.4 Eigen/2016.10.06.09/2.6.4 (iPhone; iOS 8.3; Scale/2.00) AppleWebKit/601.1.46 (KHTML, like Gecko)", "Mozilla/5.0 Artsy-Mobile/2.6.4 Eigen/2016.10.06.09/2.6.4 (iPhone; iOS 8.3; Scale/2.00) AppleWebKit/601.1.46 (KHTML, like Gecko)"]
```

**Comment by joeyAghion** [comment]
This was surfaced by partners who are seeing repeat submissions (via email or in their "inbox"). To debug, we looked at the inquiries' (with ids above) raw data in a Gravity console.

**Comment by ashkan18** [comment]
more examples:
```
['5890e358b202a303a562abaf', '5890e507b202a303d9400e9e']
```
This is on `Mozilla/5.0 Artsy-Mobile/3.1.0 Eigen/2017.01.24.16/3.1.0 (iPhone; iOS 10.2.1; Scale/2.00) AppleWebKit/601.1.46 (KHTML, like Gecko)`

**Comment by alloy** [comment]
For reference, these are the times that one of the examples provided by @joeyAghion are made at:

```
gravity:production> InquiryRequest.where(inquireable_id: "57ed1c628b3b81398c000d12", inquirer_id: "52797b1ecd530e3f9e000244").pluck(:created_at).sort
=> [2017-02-01 05:08:01 UTC, 2017-02-01 05:08:04 UTC, 2017-02-01 05:08:11 UTC]
```

Looking for [inquiry errors that Eigen reported](https://artsy.looker.com/sql/rrzgwpzvd7x2sz) reveals the following:

| original_timestamp | errors | response
|--------------------|-------|----------
| 2017-02-01T00:08:01-0500 | Request failed: bad request (400) | SSL_connect SYSCALL returned=5 errno=0 state=SSLv2/v3 read server hello A
| 2017-02-01T00:08:04-0500 | Request failed: bad request (400) | SSL_connect SYSCALL returned=5 errno=0 state=SSLv2/v3 read server hello A
| 2017-02-01T00:08:11-0500 | Request failed: bad request (400) | SSL_connect SYSCALL returned=5 errno=0 state=SSLv2/v3 read server hello A

Those timestamps line-up perfectly. So it seems like Gravity is responding with a `400`, which triggers a UI in Eigen that asks the user to try again, which they do, etc etc.

However, while Gravity returns a `400` it _does_ actually make the inquiry request. Looking at the response message that’s recorded by Eigen, it seems like maybe Gravity tries to make a request to another service which fails during SSL negotiation?

**Comment by alloy** [comment]
It’s also worth noting that _all_ failed inquiries recorded by Eigen in 2017 were the exact same type (`400`, SSL related): https://artsy.looker.com/sql/mmxfx9bwhhbnnf

**Comment by ashkan18** [comment]
I know exactly what this error is, thanks @alloy , this was the weird issue we had with posting events to our RabbitMQ instance. We've already fix this by:
1) Queue a job instead of synchronously call RabbitMQ https://github.com/artsy/gravity/pull/10785
2) Fix the potential race-condition that has caused this https://github.com/artsy/artsy-eventservice/pull/3

I think we can close this issue then. So does Eigen retry these calls if they fail originally?

**Comment by mzikherman** [comment]
Wouldn't this also explain the Force-side error reports?

**Comment by alloy** [comment]
That’s great to hear!

I think there’s a remaining larger atomicity issue here, though, besides this specific SSL/RabbitMQ issue, which is that apparently Gravity (in a default exception handler?) is sending back error responses to Eigen while it still continues to process the request, leading to these repeated requests. I.e. either:

* Gravity returns an error and does *not* record the inquiry, Eigen shows the retry UI, and eventually 1 inquiry gets recorded.
* Gravity *does* record the inquiry, handles any internal errors internally, returns a `2xx`, Eigen says it was a success, and eventually 1 inquiry gets recorded.

I’m of the opinion that it should be the latter, if, as it turns out, the inquiry is recorded and delivered anyways.

**Comment by ashkan18** [comment]
Yes to @mzikherman, it can totally be related. 

@alloy this RabbitMQ connection is currently only used for our event stream and posting messages to slack, Gravity should basically handle it as a fire and forget call where the failure to call RabbmitMQ should not impact inquiry request creation. I think with queuing just call to rabbitMQ we handle this properly. From eigen's perspective, inquiry is created and 2xx is returned back even if rabbitmq call fails later.

**Comment by alloy** [comment]
@ashkan18 Gotcha, that sounds good then 👍

**Comment by ashkan18** [comment]
Sorry for the mess 

![](http://i.giphy.com/qQjRCovn40VsQ.gif)

**Comment by alloy** [comment]
![Giphy](http://media3.giphy.com/media/mrBEVU9zQIsZa/giphy.gif)

**Comment by joeyAghion** [comment]
Just to reiterate what should be our "policy" about this, Gravity should be very deliberate about any work it does outside of the core operation requested by an API endpoint. So, e.g., recording data changelogs is buffered locally, statsd metrics are sent in a UDP/fire-and-forget style, and any resulting errors are divorced from the request-flow.

The backgrounding in https://github.com/artsy/gravity/pull/10785 accomplishes this, and in general we should be free with queueing additional jobs when their result shouldn't impact the request.

@ashkan18 how confident are you that https://github.com/artsy/artsy-eventservice/pull/3 fixes the underlying RabbitMQ SSL issue? Have we seen any recurrences since then?

**Comment by ashkan18** [comment]
At this point im pretty confident since we went live with changes on Impulse, Radiation and Gravity, I haven't seen any instances of this error. So I'd say we are good.

**Comment by alloy** [comment]
There have not been any new errors reported by Eigen over the weekend 👍
