### ISSUE TITLE
OSS Setup issues with fonts.

### ISSUE THREAD

**Issue by ddhjy** [artsy/eigen#2158]
I was under the OSS Quick Start shell operation. When I run it in simulator, it warns me as below:

2017-02-08 14:54:12.622 [error][tid:com.facebook.react.ShadowQueue][RCTFont.mm:279] Unrecognized font family 'AGaramondPro-Regular'
...
...
2017-02-08 14:54:12.650 [error][tid:com.facebook.react.ShadowQueue][RCTFont.mm:279] Unrecognized font family 'AGaramondPro-Regula

**Comment by orta** [comment]
Nooooo, we were so close

Hrm, can you open `Pods/Artsy+UIFonts/Pod/Assets/` whatever looks like garamond regular, and show me a screenshot like this in the OSX font app:

![screen shot 2017-02-08 at 9 20 34 am](https://cloud.githubusercontent.com/assets/49038/22741056/e2823550-eddf-11e6-9687-d3f059841a71.png)

**Comment by ddhjy** [comment]
Thank you for your response. This is what you need:
![ee2fad70-64b1-48e9-8e93-3b0093738dda](https://cloud.githubusercontent.com/assets/14817828/22766946/41725bc0-eeb3-11e6-9bcb-84335921d9a7.png)
![ee2fad70-64b1-48e9-8e93-3b0093738dda](https://cloud.githubusercontent.com/assets/14817828/22766958/4f8c5b20-eeb3-11e6-82e0-f94d41fefe63.png)

**Comment by ddhjy** [comment]
Thank you for your response. This is what you need:
![ee2fad70-64b1-48e9-8e93-3b0093738dda](https://cloud.githubusercontent.com/assets/14817828/22766974/6a362208-eeb3-11e6-8c71-d1926a2d5479.png)

**Comment by ddhjy** [comment]
@orta

**Comment by orta** [comment]
Interesting, the postscript names match - I wonder if this needs to be changed in other places

**Comment by alloy** [comment]
This is done, right? (Closing before getting an answer.)

**Comment by orta** [comment]
IMO, think so
