### ISSUE TITLE
Fix crash in - [ARFairMapAnnotation updatePosition], line 129

### ISSUE THREAD

**Issue by artsyit** [artsy/eigen#216]
### Stacktrace ###

<pre>ARFairMapAnnotation;updatePosition;ARFairMapAnnotation.m;129
NAAnnotation;addToMapView:animated:;NAAnnotation.m;43
NAMapView;addAnnotation:animated:;NAMapView.m;97
ARFairShowMapper;setupMapFeatures;ARFairShowMapper.m;59
NSArray(ObjectiveSugar);each:;NSArray+ObjectiveSugar.m;54
ARFairShowMapper;setupMapFeatures;ARFairShowMapper.m;56
ARFairMapViewController;viewDidLoad;ARFairMapViewController.m;93</pre>

### Reason ###

*** Terminating app due to uncaught exception 'CALayerInvalidGeometry', reason: 'CALayer position contains NaN: [nan nan]'

### Link to HockeyApp ###

* [https://rink.hockeyapp.net/manage/apps/37020/crash_reasons/29027437](https://rink.hockeyapp.net/manage/apps/37020/crash_reasons/29027437)

**Comment by alloy** [comment]
This has been fixed in the backend https://github.com/artsy/gravity/pull/8651
