### ISSUE TITLE
Feedback 'From: Optional("Onboarding user") The connect w...'

### ISSUE THREAD

**Issue by artsyit** [artsy/eigen#2174]
### Message from Unknown User sent on 2017-02-15 18:04:27 UTC###

> From: Optional("Onboarding user")
> 
> The connect with Facebook link lays on top of the next button for me.

### Link to HockeyApp ###

* [https://rink.hockeyapp.net/manage/apps/37020/feedback/728723](https://rink.hockeyapp.net/manage/apps/37020/feedback/728723)

**Comment by mennenia** [comment]
Captured in #2191
