### ISSUE TITLE
Increase space between next button and form field content

### ISSUE THREAD

**Issue by katarinabatina** [artsy/eigen#2175]
currently at 18px should be closer to 40px

![image](https://cloud.githubusercontent.com/assets/6482926/22988923/cdab5574-f381-11e6-8256-fa3b6a2f0213.png)

![image](https://cloud.githubusercontent.com/assets/6482926/22988942/ddbdb09c-f381-11e6-966e-ee02e46c461a.png)

**Comment by alloy** [comment]
Closed by #2161
