### ISSUE TITLE
Replace iphone splash photo and copy placement

### ISSUE THREAD

**Issue by katarinabatina** [artsy/eigen#2176]
file asset: https://cl.ly/473C1G1y023d

![image](https://cloud.githubusercontent.com/assets/6482926/22992311/513821fa-f38d-11e6-896c-476f1fc7a7ac.png)

**Comment by alloy** [comment]
The end of an era 😢

**Comment by alloy** [comment]
Long Live Eigen!

**Comment by katarinabatina** [comment]
@alloy wha?????

**Comment by alloy** [comment]
The splash screen was such a fixed point in Eigen’s existence since forever, I’m just saying my goodbyes 🎩👌

**Comment by katarinabatina** [comment]
wha? we changed it in 3.0 lol...

**Comment by mennenia** [comment]
lol this is funny ^_^. 

Also, FYI, I've created new assets for the logos in black. 

[blacklogos.zip](https://github.com/artsy/eigen/files/789775/blacklogos.zip)

I'm assuming these are fine @katarinabatina :)?

**Comment by alloy** [comment]
When you’re as young as I am, time feels like it takes longer! 😛

**Comment by mennenia** [comment]
Current state:

![splash_ipad](https://cloud.githubusercontent.com/assets/373860/23163443/5c2da138-f82a-11e6-986c-531c4954ae62.png)
![splash_iphone](https://cloud.githubusercontent.com/assets/373860/23163442/5c2c7862-f82a-11e6-83b1-0c0ee81e6267.png)

**Comment by alloy** [comment]
Closed by #2161
