### ISSUE TITLE
Creating new account with facebook lands me in weird state

### ISSUE THREAD

**Issue by katarinabatina** [artsy/eigen#2177]
can't reliably reproduce but after tapping connect with facebook the keyboard gets stuck on the homeview. 
![img_2623](https://cloud.githubusercontent.com/assets/6482926/22992589/2161dace-f38e-11e6-8f05-081bf09d852e.PNG)

**Comment by alloy** [comment]
@mennenia What’s the status on this one?

**Comment by mennenia** [comment]
I couldn't reproduce. Also with the current onboarding, you wouldn't end with the log in / signup, but instead with budget selection, hence no keyboard. I don't see this happening again.
