### ISSUE TITLE
[Analytics] Onboarding

### ISSUE THREAD

**Issue by anipetrov** [artsy/eigen#2178]
## Screens
- [x] **Onboarding start**: fired on the first screen you land on after the slideshow, just like in the previous version of onboarding [screenshot](https://cl.ly/413C1N1G2x0z).This currently fires as expected.
- [x] **Onboarding enter your email address**: [screenshot](https://cl.ly/1l3Y2B0z2w1b)
- [x] **Onboarding enter your password**: [screenshot](https://cl.ly/0u1N1Y3o0z04)
- [x] **Onboarding create a password**: [screenshot](https://cl.ly/111Z1L0a0k1f)
- [x] **Onboarding enter your full name**: [screenshot](https://cl.ly/1L120K1g2Y0C)
- [x] **Onboarding follow artists**: [screenshot](http://cl.ly/1o282n0i0k0u)
- [x] **Onboarding select budget**: [screenshot](http://cl.ly/3h242X2D3d1j)

# Tracks
- [x] **Tapped get started**: Fired when tapping the "Get Started" button on the onboarding start screen. This currently fires as expected.
- [x] **Tapped connect with facebook** : Fired when tapping the "connect with Facebook" button on the *Enter your email address* onboarding screen
- [x] **Authentication error**: fired when we see an authentication error, either "There was a problem authenticating with Facebook", "Please check your email and password", "Could not create account"
       - properties: { 
          error_message: [error message string]
          } 
- [x] **Tapped forgot password**: fires when users taps on the forgot password link on the onboarding *Enter your password* screen
- [x] **Successfully sent password reset link**: fires if a password reset link is successfully sent
 - [x] **Successfully logged in**: fires when user log in successfully
       - properties: {  
          context_type: [email, facebook, safari keychain]
          }  
 - [x] **Created account**: Fired when account was successfully created
        - properties: {
          context_type: [email, facebook]
          }
- [x] **Tapped already have an account go back**: fires when user taps on _Go back_ on the _Create a password_ screen

**Comment by anipetrov** [comment]
i think i got the app in a weird state where i can no longer create account (keep on getting a _Could not create account_ error on the _Enter your full name_ screen) but when i figure that out, i might have to add some more events

**Comment by alloy** [comment]
Closed by #2161
