### ISSUE TITLE
Feedback 'From: Optional("Ani Petrov") I can click "next"...'

### ISSUE THREAD

**Issue by artsyit** [artsy/eigen#2179]
### Message from 540caa167261692d6b550000 sent on 2017-02-15 21:10:10 UTC###

> From: Optional("Ani Petrov")
> 
> I can click "next" on the create password screen even if I create a password that is shorter than 7 symbols

### Link to HockeyApp ###

* [https://rink.hockeyapp.net/manage/apps/37020/feedback/728870](https://rink.hockeyapp.net/manage/apps/37020/feedback/728870)

**Comment by mennenia** [comment]
👍 captured in #2190
