### ISSUE TITLE
Feedback 'From: Eloy Durán Seeing weird counts for Wilhel...'

### ISSUE THREAD

**Issue by artsyit** [artsy/eigen#2183]
### Message from Eloy Durán sent on 2017-02-16 20:52:40 UTC###

> From: Eloy Durán
> 
> Seeing weird counts for Wilhelmina Barns-Graham on staging. Production is fine.

### Link to HockeyApp ###

* [https://rink.hockeyapp.net/manage/apps/37020/feedback/729731](https://rink.hockeyapp.net/manage/apps/37020/feedback/729731)

**Comment by mennenia** [comment]
Pushed to #2161, for iPhone only the activity indicator now looks like:

![simulator screen shot 10 mar 2017 14 14 48](https://cloud.githubusercontent.com/assets/373860/23798304/f37ce994-059b-11e7-8d54-e79dafa21762.png)

**Comment by alloy** [comment]
Awesome 👏

**Comment by mennenia** [comment]
Wrong issue!! Arrgh haha.

**Comment by alloy** [comment]
No longer seeing this.
