### ISSUE TITLE
Fix crash in - [BITFeedbackMessageAttachment setData:], line 98

### ISSUE THREAD

**Issue by artsyit** [artsy/eigen#2189]
### Stacktrace ###

<pre>BITFeedbackMessageAttachment;setData:;BITFeedbackMessageAttachment.m;98
BITFeedbackMessageAttachment;attachmentWithData:contentType:;BITFeedbackMessageAttachment.m;71
BITFeedbackComposeViewController;prepareWithItems:;BITFeedbackComposeViewController.m;140
BITFeedbackManager;showFeedbackComposeViewWithPreparedItems:;BITFeedbackManager.m;249
-;function signature specialization <Arg[0] = Owned To Guaranteed, Arg[1] = Dead> of Artsy.ARHockeyFeedbackDelegate.showFeedback (__ObjC.UIImage?) -> ();ARHockeyFeedbackDelegate.swift;37
-;Artsy.ARHockeyFeedbackDelegate.showFeedbackWithRecentScreenshot () -> ();ARHockeyFeedbackDelegate.swift;0
-;partial apply forwarder;ARHockeyFeedbackDelegate.swift;0</pre>

### Link to HockeyApp ###

* [https://rink.hockeyapp.net/manage/apps/37029/crash_reasons/155796875](https://rink.hockeyapp.net/manage/apps/37029/crash_reasons/155796875)

**Comment by alloy** [comment]
This seems like an esotheric issue. Let’s first see if it occurs soon again.
