### ISSUE TITLE
Fix crash in - [ARArtworkWithMetadataThumbnailCell setupWithRepresentedObject:], line 86

### ISSUE THREAD

**Issue by artsyit** [artsy/eigen#2196]
### Stacktrace ###

<pre>ARArtworkWithMetadataThumbnailCell;setupWithRepresentedObject:;ARArtworkWithMetadataThumbnailCell.m;86
ARWorksForYouNotificationItemViewController;viewDidLoad;ARWorksForYouNotificationItemViewController.m;94
ORStackView;addViewController:toParent:withTopMargin:sideMargin:;ORStackView.m;226
ARWorksForYouViewController;addNotificationItems:;ARWorksForYouViewController.m;93
NSArray(ObjectiveSugar);eachWithIndex:;NSArray+ObjectiveSugar.m;60
ARWorksForYouViewController;addNotificationItems:;ARWorksForYouViewController.m;87
ARWorksForYouViewController;getNextItemSet;ARWorksForYouViewController.m;163
ARWorksForYouNetworkModel;getWorksForYou:failure:;ARWorksForYouNetworkModel.m;88
ARWorksForYouNetworkModel;performWorksForYouRequest:failure:;ARWorksForYouNetworkModel.m;111</pre>

### Link to HockeyApp ###

* [https://rink.hockeyapp.net/manage/apps/37029/crash_reasons/158267886](https://rink.hockeyapp.net/manage/apps/37029/crash_reasons/158267886)

**Comment by alloy** [comment]
If this cell is only used in the WFU VC, then this issue will be resolved when moving to the RN version.

/cc @sarahscott close this at that time, if this is the case.

**Comment by sarahscott** [comment]
`ARArtworkWithMetadataThumbnailCell` is used in a few other places as well - any view controller that specifies the `AREmbeddedArtworkPresentationStyleArtworkMetadata` on its masonry module will generate that kind of cell.
