### ISSUE TITLE
Feedback 'From: Optional("Devang Thakkar") Other works in...'

### ISSUE THREAD

**Issue by artsyit** [artsy/eigen#2200]
### Message from Devang Thakkar sent on 2017-03-04 19:51:25 UTC###

> From: Optional("Devang Thakkar")
> 
> Other works in auction shown below the current lot should not say "contact for price"

### Link to HockeyApp ###

* [https://rink.hockeyapp.net/manage/apps/37020/feedback/745650](https://rink.hockeyapp.net/manage/apps/37020/feedback/745650)

**Comment by ashfurrow** [comment]
Closing in favour of https://github.com/artsy/auctions/issues/338
