### ISSUE TITLE
Fix NSInvalidArgumentException in - [AROnboardingViewController keyboardWillShow:], line 161

### ISSUE THREAD

**Issue by artsyit** [artsy/eigen#2205]
### Stacktrace ###

<pre>AROnboardingViewController;keyboardWillShow:;AROnboardingViewController.m;161</pre>

### Reason ###

*** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[AROnboardingWebViewController updateKeyboardFrame:]: unrecognized selector sent to instance 0x115d84940'

### Link to HockeyApp ###

* [https://rink.hockeyapp.net/manage/apps/37020/crash_reasons/160093237](https://rink.hockeyapp.net/manage/apps/37020/crash_reasons/160093237)

**Comment by mennenia** [comment]
Fixed [here](https://github.com/artsy/eigen/pull/2161/commits/e8040221a531bfa84305c1a2874f1eea1c34d1e8)
