### ISSUE TITLE
Feedback 'From: Optional("Kana") Recommended for you sect...'

### ISSUE THREAD

**Issue by artsyit** [artsy/eigen#2209]
### Message from 54ce2d397261692aeab10300 sent on 2017-03-10 18:10:30 UTC###

> From: Optional("Kana")
> 
> Recommended for you section is only showing a loading spinner.

### Link to HockeyApp ###

* [https://rink.hockeyapp.net/manage/apps/37029/feedback/754433](https://rink.hockeyapp.net/manage/apps/37029/feedback/754433)

**Comment by alloy** [comment]
@kanaabe Is that staging or production?

**Comment by kanaabe** [comment]
Pretty sure it's Production. I shook my phone and went to the Developer section and it's all pointing to the production apis. Is that how to check?

**Comment by alloy** [comment]
Yup.

Are you reproducing this?

**Comment by kanaabe** [comment]
Yeah I'm still getting the spinner :/. My "for you" page is loading fine. other sections on the homepage are loading fine as well. let me know if you need more info or need someone to borrow my phone for a bit.

**Comment by alloy** [comment]
I’m not sure which page you mean by “for you” page. If it’s the notifications tab (with the bell icon), that’s a different one on the home page “Works by Artists you Follow”.

Can you check if on Force’s home page the “Recommended Works for You” section loads?

**Comment by alloy** [comment]
Bump

**Comment by kanaabe** [comment]
Whoops sorry for the radio silence. Ok so on Force, I see no "Recommended Works for You":

![image](https://cloud.githubusercontent.com/assets/2236794/24413110/7676a1d6-13a8-11e7-8ffb-7f0f5973a5ed.png)

On iOS, I'm still seeing the spinner on the "Recommended Works for You" section.

**Comment by alloy** [comment]
Closing in favour of https://github.com/artsy/collector-experience/issues/205
