### ISSUE TITLE
Switch Metaphysics query to use POST

### ISSUE THREAD

**Issue by ashfurrow** [artsy/eigen#2213]
To match https://github.com/artsy/emission/issues/455

**Comment by ashfurrow** [comment]
This is becoming non-trivial – our networking library is URL form-encoding the JSON string, so we get `query=JSON_BLOB` as an HTTP body instead of `{query: JSON_BLOB}`. Could use some help here, I don't want to add an additional AFNetworking session manager just to JSON-encode one request. Advice welcome /cc @alloy.

**Comment by mzikherman** [comment]
Yay thank you!
