### ISSUE TITLE
Feedback 'From: Optional("Katarina Batina") Refine UI broken'

### ISSUE THREAD

**Issue by artsyit** [artsy/eigen#2215]
### Message from katarina batina sent on 2017-03-16 21:00:58 UTC###

> From: Optional("Katarina Batina")
> 
> Refine UI broken

### Link to HockeyApp ###

* [https://rink.hockeyapp.net/manage/apps/37020/feedback/761287](https://rink.hockeyapp.net/manage/apps/37020/feedback/761287)

**Comment by ashfurrow** [comment]
Fixed in https://github.com/artsy/eigen/commit/a210c96f3084ff63689324d4eb81fdaa10fd204a
