### ISSUE TITLE
Fix crash in Artsy.RefinementOptionsViewController.((priceRangeView in _CD95F54751BCDCB240E3E0AEB7E2B572) () -> __ObjC.ORStackView?).(closure #3), line 159

### ISSUE THREAD

**Issue by artsyit** [artsy/eigen#2220]
### Stacktrace ###

<pre>-;Artsy.RefinementOptionsViewController.((priceRangeView in _CD95F54751BCDCB240E3E0AEB7E2B572) () -> __ObjC.ORStackView?).(closure #3);RefinementOptionsViewController+Private.swift;159
-;(extension in Then):Then.Then<A where A: Swift.AnyObject, A: Then.Then>.then ((A) -> ()) -> A;Then.swift;65
-;Artsy.RefinementOptionsViewController.(priceRangeView in _CD95F54751BCDCB240E3E0AEB7E2B572) () -> __ObjC.ORStackView?;RefinementOptionsViewController+Private.swift;160
-;Artsy.RefinementOptionsViewController.setupViews () -> ();RefinementOptionsViewController+Private.swift;92
-;Artsy.RefinementOptionsViewController.viewDidLoad () -> ();RefinementOptionsViewController.swift;92
-;@objc Artsy.RefinementOptionsViewController.viewDidLoad () -> ();RefinementOptionsViewController.swift;0
-;Artsy.AuctionViewController.showRefineTappedAnimated (Swift.Bool) -> ();AuctionViewController.swift;227
-;@objc Artsy.AuctionViewController.showRefineTappedAnimated (Swift.Bool) -> ();AuctionViewController.swift;0
-;@objc Artsy.AuctionViewController.showRefineTapped () -> ();AuctionViewController.swift;231
-;__RACSwizzleForwardInvocation_block_invoke;NSObject+RACSelectorSignal.m;49
ARWindow;sendEvent:;ARAppDelegate.m;455</pre>

### Link to HockeyApp ###

* [https://rink.hockeyapp.net/manage/apps/37029/crash_reasons/161477908](https://rink.hockeyapp.net/manage/apps/37029/crash_reasons/161477908)

**Comment by ashfurrow** [comment]
No idea what's happening here. The line of code is:

```swift
$0.minimumDistance = CGFloat(maxRange.max - maxRange.min) / 10.0
```

So it's not a divide-by-zero error, and `maxRange` isn't an IUO. Going to test and see if I can reproduce.

**Comment by ashfurrow** [comment]
Not sure, I can't reproduce. Going to wait and see if anyone else has issues. The crashes seem to have appeared during the auction data problems on Friday, so it might just be that. We'll see.

**Comment by ashfurrow** [comment]
There've been no subsequent crashes, going to chalk this one up to the auction server outage that overlapped with it.
