### ISSUE TITLE
[Auctions] Image downloading slow

### ISSUE THREAD

**Issue by alloy** [artsy/eigen#2221]
From @carterac:

> on Verizon with 4/5 bars, took about 10-12 seconds for the first image to load when tapping into an auction.

The example given was https://www.artsy.net/auction/phillips-photographs-1 (not a live auction).

**Comment by alloy** [comment]
In Emission we’ll soon have to do some optimising of image downloading too, I wonder if it would be beneficial/possible to make this auction view a RN one and consolidate optimised image downloading?

https://github.com/artsy/emission/issues/460

**Comment by katarinabatina** [comment]
@ashfurrow @alloy I can't tell from Carter's comment but I actual think he's speaking to the overall load time of the page which is very slow compared to other parts of the app. If I remember correctly this had something to do with vanity urls but at any rate the overall speed of loading this view should be improved.

**Comment by ashfurrow** [comment]
Yeah, tapping into an auction from a banner can add a few round trips to the server, slowing things down. That said, 10–12 seconds seems excessive. I'll take a look as soon as I can, maybe there's something funky going on.

There are some checks that need to happen for auctions (like, is it a live auction? is the live auction open yet? etc) that need to happen before we load the UI. For things like images, it might be possible to begin some of the downloads earlier. I'll take a look as soon as I can.

**Comment by ashfurrow** [comment]
I've opened an issue in the auctions team tracker to follow up on this: https://github.com/artsy/auctions/issues/353 I'm going to close this issue.
