### ISSUE TITLE
[Auctions] Don’t show “0 bids” label

### ISSUE THREAD

**Issue by alloy** [artsy/eigen#2222]
Reported by @carterac.

I assume this requirement is because showing “0 bids” doesn’t look nice and might discourage others from bidding? /cc @devangt 

![image uploaded from ios](https://cloud.githubusercontent.com/assets/2320/24098177/7bb6294a-0d69-11e7-9d81-e5c34fb85130.jpg)

**Comment by katarinabatina** [comment]
@alloy @ashfurrow yes your assumptions are correct which is why we opt to eliminate the bid count all together 
![image](https://cloud.githubusercontent.com/assets/6482926/24102375/1e625fc8-0d52-11e7-905b-f4c781a43bcb.png)

**Comment by ashfurrow** [comment]
Yup, Katarina is correct. There's already a ticket capturing this: https://github.com/artsy/auctions/issues/316 So I'm going to close this issue.

**Comment by alloy** [comment]
👍
