### ISSUE TITLE
Feedback 'From: Ash Bottom 2 pixels of refine slider is c...'

### ISSUE THREAD

**Issue by artsyit** [artsy/eigen#2224]
### Message from Ash Furrow sent on 2017-03-20 17:34:07 UTC###

> From: Ash
> 
> Bottom 2 pixels of refine slider is cut off.

### Link to HockeyApp ###

* [https://rink.hockeyapp.net/manage/apps/37020/feedback/764963](https://rink.hockeyapp.net/manage/apps/37020/feedback/764963)

**Comment by ashfurrow** [comment]
![asset png-2](https://cloud.githubusercontent.com/assets/498212/24113098/0c163e6e-0d72-11e7-9223-1fa343ee557d.jpeg)
