### ISSUE TITLE
Empty Active Bids module at bottom of feed

### ISSUE THREAD

**Issue by ashfurrow** [artsy/eigen#2237]
![image uploaded from ios](https://cloud.githubusercontent.com/assets/498212/24266577/a6d6820c-0fdd-11e7-9ad1-b6a6636e51d2.jpg)

It's a RN view coming from Metaphysics. That's about as far as I've got.

**Comment by ashfurrow** [comment]
So Gravity is saying to display these if there are any active bids on the user account: https://github.com/artsy/gravity/blob/master/app/api/v1/me_modules_endpoint.rb#L14

Metaphysics resolves the results to... any empty array: https://github.com/artsy/metaphysics/blob/a5c40a79680bf1a7799514123fd721eee96be8b8/schema/home/results.js#L20

The solution is to query gravity for active bids when they exist. I've talked to @devangt and we're going to add those.

**Comment by alloy** [comment]
Oh, one thing I just remembered, while it is true that showing/hiding the module can be done from outside of Eigen, moving the module’s location in the feed does require changes (in Emission), so let me know if there’s a desire to do so and to where.

/cc @katarinabatina

**Comment by katarinabatina** [comment]
@alloy this should be the first unit in the feed

**Comment by alloy** [comment]
Moved it to the top, now it just needs content.

**Comment by ashfurrow** [comment]
It's at the top of today's todo list 😄

**Comment by ashfurrow** [comment]
Reopening until https://github.com/artsy/emission/pull/468 or similar is merged.
