### ISSUE TITLE
Unable to Login

### ISSUE THREAD

**Issue by mparrish91** [artsy/eigen#2251]
I'm unable to login on the current build.  I don't see the Login option only the Get Started option.  From there it does not accept my account password. I verified my credentials work on the current App Store version
![screen shot 2017-03-29 at 4 01 10 pm](https://cloud.githubusercontent.com/assets/5642923/24536724/28aebdb8-1591-11e7-8edc-4e37be3f18fb.png)

I also noticed a URL scheme error for FB login.  "'InvalidOperationException', reason: 'fb- is not registered as a URL scheme. Please add it in"

**Comment by orta** [comment]
The OSS version runs against our staging API, which may not have your existing credentials

**Comment by alloy** [comment]
…but you can create an account on https://staging.artsy.net to remedy that.

**Comment by mparrish91** [comment]
thank you. I'm having trouble logging in to the staging server.  It let me
make an account ,but then did not accept my credentials.

The forgot password didn't work. Sorry for hassle!

**Comment by alloy** [comment]
Yeah staging does not send password reset emails, sorry about that. So you should make sure to not get it wrong 😉
