### ISSUE TITLE
Feedback 'From: Optional("Rachel Goss") Current bid amoun...'

### ISSUE THREAD

**Issue by artsyit** [artsy/eigen#2255]
### Message from 5509b09d7261692ae7c40700 sent on 2017-04-03 22:17:24 UTC###

> From: Optional("Rachel Goss")
> 
> Current bid amount on live lot is actually different ($49k)

### Link to HockeyApp ###

* [https://rink.hockeyapp.net/manage/apps/37029/feedback/782628](https://rink.hockeyapp.net/manage/apps/37029/feedback/782628)

**Comment by ashfurrow** [comment]
I'll take a look, could just be a data blip or something.
