### ISSUE TITLE
[Analytics] New events

### ISSUE THREAD

**Issue by mennenia** [artsy/eigen#2264]
## Page events that need updating or adding

- [x] Implement new spreadsheet of page views with updated parameters (in place of #2262 )

## Events that need updating or adding

- [ ] 'Tapped on home screen recommendation', request [here](https://github.com/artsy/collector-experience/issues/63#issuecomment-292488115)

**Comment by mennenia** [comment]
@cavvia I've captured your request here. If there are any more / any changes, feel free to add to this thread :)

**Comment by cavvia** [comment]
Thanks @mennenia! This is all I need for now.

**Comment by mennenia** [comment]
Blocked by Emission needing analytics support.
