### ISSUE TITLE
[Analytics] Troubleshooting 

### ISSUE THREAD

**Issue by mennenia** [artsy/eigen#2265]
## Outstanding issues 

- [ ] Double fire, specifically on artwork screens
- [x] Mobile views (e.g. editorial articles) - do we send any analytics there?

**Comment by mennenia** [comment]
I've cleaned up a lot of the analytics code - @anipetrov I'm moving this to QA. Can you let me know whether or not you're still seeing the double fire? 

Also, we no longer send analytics page views for mobile views within Eigen.

**Comment by mennenia** [comment]
Double fire still happens, moving this back a few pipelines

**Comment by anipetrov** [comment]
A few other problems I am noticing, again if you guys are pressed for time we should do this for the next release:
- [ ] we are not firing a search screen view
- [ ] when you press back arrow and go back to a screen, we do not fire a screen view for the screen you go back to
- [ ] we do not pass the artist id under `owner_id` for artist screen views

**Comment by mennenia** [comment]
Thanks @anipetrov !!

> we are not firing a search screen view

I am getting these in code - they just don't show up in the screen popover (I was just trying to get it, and when I try to dismiss the keyboard, it comes up as a hockey thing I can copy or something?). Is there any way you can check in redshift / where you receive all the analytics? :o.

> when you press back arrow and go back to a screen, we do not fire a screen view for the screen you go back to

For me it does seem to work? e.g. Home > artist > back to home, or You > artwork > back to you

Is it between specific screens or something that you tried? Then I can try to reproduce :).

> we do not pass the artist id under owner_id for artist screen views

Yup this is what I mean with I can't access the gravity ID for artists currently (because they're coming from emission and aren't sending this data). The same holds for Genes. Captured [here](https://github.com/artsy/emission/issues/536) :).

**Comment by mennenia** [comment]
@anipetrov any thoughts on your env? I can't seem to reproduce :(
