### ISSUE TITLE
[Analytics] Send event when we're opened from deeplink

### ISSUE THREAD

**Issue by mennenia** [artsy/eigen#2267]
## Goal:
When Eigen launches by way of a deeplink, we should send an event preferably noting _which_ campaign/source referred to the app. (like UTM parameters on web)

---

@sarahscott you're working on the WFY view that can be triggered from email. Could you have a look at whether we can do this? 

cc/ @anipetrov

**Comment by alloy** [comment]
Closing in favour of https://github.com/artsy/collector-experience/issues/239
