### ISSUE TITLE
Fix crash in Starscream.WebSocket.(dequeueInput in _E91840E7069A0D2D302D042308E9D928) () -> (), line 470

### ISSUE THREAD

**Issue by artsyit** [artsy/eigen#2281]
### Stacktrace ###

<pre>-;Starscream.WebSocket.(dequeueInput in _E91840E7069A0D2D302D042308E9D928) () -> ();WebSocket.swift;470
-;Starscream.WebSocket.(processInputStream in _E91840E7069A0D2D302D042308E9D928) () -> ();WebSocket.swift;457
-;function signature specialization <Arg[0] = Owned To Guaranteed> of Starscream.WebSocket.stream (__ObjC.Stream, handle : __ObjC.Stream.Event) -> ();WebSocket.swift;403
-;@objc Starscream.WebSocket.stream (__ObjC.Stream, handle : __ObjC.Stream.Event) -> ();WebSocket.swift;0</pre>

### Link to HockeyApp ###

* [https://rink.hockeyapp.net/manage/apps/37029/crash_reasons/165826270](https://rink.hockeyapp.net/manage/apps/37029/crash_reasons/165826270)

**Comment by ashfurrow** [comment]
Hmm, looks like it occurs when the live view controller is being opened. Wonder if there's a threading things happening.

**Comment by ashfurrow** [comment]
Moving to https://github.com/artsy/auctions/issues/410
