### ISSUE TITLE
Fix NSInvalidArgumentException in Starscream.WebSocket.(dequeueInput in _E91840E7069A0D2D302D042308E9D928) () -> (), line 0

### ISSUE THREAD

**Issue by artsyit** [artsy/eigen#2284]
### Stacktrace ###

<pre>-;Starscream.WebSocket.(dequeueInput in _E91840E7069A0D2D302D042308E9D928) () -> ();WebSocket.swift;0
-;Starscream.WebSocket.(processInputStream in _E91840E7069A0D2D302D042308E9D928) () -> ();WebSocket.swift;457
-;function signature specialization <Arg[0] = Owned To Guaranteed> of Starscream.WebSocket.stream (__ObjC.Stream, handle : __ObjC.Stream.Event) -> ();WebSocket.swift;403
-;@objc Starscream.WebSocket.stream (__ObjC.Stream, handle : __ObjC.Stream.Event) -> ();WebSocket.swift;0</pre>

### Reason ###

*** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '*** NSAllocateMemoryPages(1314624) failed'

### Link to HockeyApp ###

* [https://rink.hockeyapp.net/manage/apps/37029/crash_reasons/165816277](https://rink.hockeyapp.net/manage/apps/37029/crash_reasons/165816277)

**Comment by ashfurrow** [comment]
Closing in favour of https://github.com/artsy/auctions/issues/410
