### ISSUE TITLE
Fix NSInvalidArgumentException in function signature specialization <Arg[0] = Exploded> of Starscream.WebSocket.(processOneRawMessage in _E91840E7069A0D2D302D042308E9D928) (inBuffer : Swift.UnsafeBufferPointer<Swift.UInt8>) -> Swift.UnsafeBufferPointer<Swift.UInt8>, line 673

### ISSUE THREAD

**Issue by artsyit** [artsy/eigen#2285]
### Stacktrace ###

<pre>-;function signature specialization <Arg[0] = Exploded> of Starscream.WebSocket.(processOneRawMessage in _E91840E7069A0D2D302D042308E9D928) (inBuffer : Swift.UnsafeBufferPointer<Swift.UInt8>) -> Swift.UnsafeBufferPointer<Swift.UInt8>;WebSocket.swift;673
-;Starscream.WebSocket.(processRawMessagesInBuffer in _E91840E7069A0D2D302D042308E9D928) (Swift.UnsafePointer<Swift.UInt8>, bufferLen : Swift.Int) -> ();WebSocket.swift;0
-;Starscream.WebSocket.(dequeueInput in _E91840E7069A0D2D302D042308E9D928) () -> ();WebSocket.swift;479
-;Starscream.WebSocket.(processInputStream in _E91840E7069A0D2D302D042308E9D928) () -> ();WebSocket.swift;457
-;function signature specialization <Arg[0] = Owned To Guaranteed> of Starscream.WebSocket.stream (__ObjC.Stream, handle : __ObjC.Stream.Event) -> ();WebSocket.swift;403
-;@objc Starscream.WebSocket.stream (__ObjC.Stream, handle : __ObjC.Stream.Event) -> ();WebSocket.swift;0</pre>

### Reason ###

*** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '*** NSAllocateMemoryPages(3280704) failed'

### Link to HockeyApp ###

* [https://rink.hockeyapp.net/manage/apps/37029/crash_reasons/165839662](https://rink.hockeyapp.net/manage/apps/37029/crash_reasons/165839662)

**Comment by ashfurrow** [comment]
Closing in favour of https://github.com/artsy/auctions/issues/410
