### ISSUE TITLE
Fix NSInvalidArgumentException in NSAllocateMemoryPages

### ISSUE THREAD

**Issue by artsyit** [artsy/eigen#2287]
### Reason ###

*** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '*** NSAllocateMemoryPages(1314624) failed'

### Link to HockeyApp ###

* [https://rink.hockeyapp.net/manage/apps/37029/crash_reasons/165816270](https://rink.hockeyapp.net/manage/apps/37029/crash_reasons/165816270)

**Comment by ashfurrow** [comment]
Duplicate of https://github.com/artsy/eigen/issues/2285
