### ISSUE TITLE
No prompt to allow push notifications

### ISSUE THREAD

**Issue by joeyAghion** [artsy/eigen#2294]
I recently joined to cool club and started using a [loaner] ipad (mini, iOS 9). My first act was to install the Artsy app so I can get timely notifications.

However, when I check my user's `devices` with the Artsy API, there are none. Thinking back, I don't recall ever being prompted to allow push notifications. @alloy confirmed that he also didn't get prompted upon re-installing the app.

**Comment by alloy** [comment]
@mennenia I believe this is an issue with existing accounts vs new accounts.

**Comment by orta** [comment]
Guess: Could it have happened when we switch to a RN homefeed?

**Comment by joeyAghion** [comment]
Confirmed that I _was_ prompted upon reinstalling and creating a new account.

**Comment by alloy** [comment]
Nah, pretty sure this used to work before the recent on boarding changes.

**Comment by mennenia** [comment]
Yup found it - it now only shows after onboarding. My bad, expect a PR shortly.

Thanks for the find / report @joeyAghion and welcome to the "cool" club! :D
