### ISSUE TITLE
Feedback 'From: Eloy Durán On: Production Signal: 3 Artis...'

### ISSUE THREAD

**Issue by artsyit** [artsy/eigen#2296]
### Message from Eloy Durán sent on 2017-04-22 18:27:08 UTC###

> From: Eloy Durán
> On: Production
> Signal: 3
> 
> Artist label should be less wide so unread status indicator won't overlap.

### Link to HockeyApp ###

* [https://rink.hockeyapp.net/manage/apps/37020/feedback/819317](https://rink.hockeyapp.net/manage/apps/37020/feedback/819317)

**Comment by sarahscott** [comment]
Fixed by https://github.com/artsy/emission/pull/498
