### ISSUE TITLE
Feedback 'From: Sarah Scott On: Production Signal: 4 Reco...'

### ISSUE THREAD

**Issue by artsyit** [artsy/eigen#2300]
### Message from 5501de167261696e34610200 sent on 2017-04-23 17:51:58 UTC###

> From: Sarah Scott
> On: Production
> Signal: 4
> 
> Recommend Works For You rail should not be tappable. It used to be untappable but for some reason it now links to a messed-up web view

### Link to HockeyApp ###

* [https://rink.hockeyapp.net/manage/apps/37020/feedback/821153](https://rink.hockeyapp.net/manage/apps/37020/feedback/821153)

**Comment by sarahscott** [comment]
Replaced by #2302
