### ISSUE TITLE
error C2338: OUT_OF_RANGE_ACCESS

### ISSUE THREAD

**Issue by RenFeiTemp** [artsy/eigen#2305]
come from DenseCoeffsBase.h

**Comment by alloy** [comment]
Pretty sure this is not the repo you were thinking of, I can’t find that file in our codebase. If it is, please elaborate.

**Comment by RenFeiTemp** [comment]
the error come from "Eigen\src\Core\DenseCoeffsBase.h"
EIGEN_DEVICE_FUNC
    EIGEN_STRONG_INLINE CoeffReturnType
    z() const
    {
      EIGEN_STATIC_ASSERT(Derived::SizeAtCompileTime==-1 || Derived::SizeAtCompileTime>=3, OUT_OF_RANGE_ACCESS);
      return (*this)[2];
    }

**Comment by alloy** [comment]
That code is _not_ from this repository, I think you meant a different project.

**Comment by RenFeiTemp** [comment]
you mean to say that the header file "DenseCoeffsBase.h" don't belong to eigen?

**Comment by alloy** [comment]
Yes, this is not the Eigen you're thinking of.
