### ISSUE TITLE
When the homepage fails to load there's no way to see the error message

### ISSUE THREAD

**Issue by dblock** [artsy/eigen#2317]
Cannot be debugged.

![image uploaded from ios](https://cloud.githubusercontent.com/assets/542335/25646271/cdec0abc-2f84-11e7-83ee-3ebc9d54a68f.jpg)

**Comment by dblock** [comment]
Got a simulator to work, shows this:

```
    1. Cannot read property 'artist' of undefined
       orm_0) {__id,...F0},_artwork_modules1FRCKl:artwork_modules(m
                           ^^^
```

**Comment by alloy** [comment]
We don’t show raw errors to end-users anywhere in the app, so this is always going to require connecting a debugger/console, e.g. through running on the sim from Xcode.
