### ISSUE TITLE
Editing developer URLs regression?

### ISSUE THREAD

**Issue by craigspaeth** [artsy/eigen#2318]
1. Open Eigen
2. Shake for the admin settings
3. Edit Metaphysics under "DEVELOPER" to point to a junk url
4. Reload the app
5. Everything still works and it appears Metaphysics is still pointing to production/staging

Could this be settings not carrying over into Emission?

**Comment by orta** [comment]
I don't know if this is carried over to Emission, good q

**Comment by orta** [comment]
Nope, that'd require some changes inside Emission - the bridge between them only has a "useStaging" flag, and so you can't DI in the URL from Eigen

**Comment by alloy** [comment]
Yeah we should probably get rid of the `useStaging` flag and just let the host app inject the URL to use.
