### ISSUE TITLE
@orta => Eigen 1.7.0 release email

### ISSUE THREAD

**Issue by alloy** [artsy/eigen#232]
And the profile photo is still black?

----

Hi Artsyisians,

We released a new version of the Artsy iPhone application (1.7.0), specifically updated for the Armory 2015 fair. Be sure to update to the latest version before heading out to the fair.

As always, please give the application a spin and let us know if you find any issues.

Have a great weekend and an awesome fair,
Eloy

![ios simulator screen shot 27 feb 2015 13 37 52](https://cloud.githubusercontent.com/assets/2320/6412598/452b0e42-be86-11e4-8f0e-8ef429dd7b7f.png)
![ios simulator screen shot 27 feb 2015 13 38 00](https://cloud.githubusercontent.com/assets/2320/6412602/4c10cb0c-be86-11e4-82f4-0abe344da7b0.png)
![ios simulator screen shot 27 feb 2015 13 38 14](https://cloud.githubusercontent.com/assets/2320/6412611/68f9b99a-be86-11e4-9d0a-b826a33b4224.png)
![ios simulator screen shot 27 feb 2015 13 38 45](https://cloud.githubusercontent.com/assets/2320/6412613/6c8477bc-be86-11e4-84d6-27eecafbe48d.png)
![ios simulator screen shot 27 feb 2015 13 39 59](https://cloud.githubusercontent.com/assets/2320/6412616/6ff34072-be86-11e4-81a7-557f5f998c4c.png)
![ios simulator screen shot 27 feb 2015 13 40 30](https://cloud.githubusercontent.com/assets/2320/6412617/736b6414-be86-11e4-9e32-c5c3021f4571.png)

**Comment by katarinabatina** [comment]
this didn't go out yet did it?

**Comment by alloy** [comment]
This is what the release in the store does, so that’s a-ok 👌

![ios simulator screen shot 27 feb 2015 17 51 29](https://cloud.githubusercontent.com/assets/2320/6416956/68cf93bc-beaa-11e4-94ae-2e222ecdeb07.png)

**Comment by alloy** [comment]
Email sent.
