### ISSUE TITLE
Feedback 'From: Katarina Batina On: Production Signal: 2'

### ISSUE THREAD

**Issue by artsyit** [artsy/eigen#2362]
### Message from katarina batina sent on 2017-05-30 20:50:37 UTC###

> From: Katarina Batina
> On: Production
> Signal: 2

### Link to HockeyApp ###

* [https://rink.hockeyapp.net/manage/apps/37029/feedback/913459](https://rink.hockeyapp.net/manage/apps/37029/feedback/913459)

**Comment by alloy** [comment]
@katarinabatina told us in Slack to ignore this one
