### ISSUE TITLE
[Signup] No feedback when a password doesn't validate.

### ISSUE THREAD

**Issue by alloy** [artsy/eigen#238]
E.g. with a password such as `test` (I assume too short) tapping submit doesn’t provide any visual feedback about it performing any work and/or letting the user know that the password doesn’t validate.

**Comment by orta** [comment]
That's when pressing "return" to log in?  As I don't think the login button is available to tap at that point.

**Comment by alloy** [comment]
Yup, the return button.

**Comment by ashfurrow** [comment]
Do we need design help on this? Maybe tag it?

**Comment by alloy** [comment]
Too bad you can't really control the return key being enabled.

**Comment by ashfurrow** [comment]
Is this one of those things that I always think _must_ be possible, but actually isn't?

**Comment by alloy** [comment]
@ashfurrow Yah, pretty much. Maybe we can use a keyboard type that has no return key (I think one exists, no?) and use a button as accessory view that is conditionally enabled and says ‘Signup’ ?

**Comment by ashfurrow** [comment]
Yeah, one does exist.

**Comment by ashfurrow** [comment]
It's meant for twitter though.

**Comment by alloy** [comment]
We can post their credentials to Twitter as well, if Apple prefers ;)

**Comment by katarinabatina** [comment]
![image](https://cloud.githubusercontent.com/assets/6482926/8686219/633019a4-2a52-11e5-8e53-bb03e9a5c6cc.png)

**Comment by alloy** [comment]
@katarinabatina Thanks, looks great 👌
