### ISSUE TITLE
Feedback 'From: Rachel Goss On: Production Signal: 0 Auct...'

### ISSUE THREAD

**Issue by artsyit** [artsy/eigen#2399]
### Message from 5509b09d7261692ae7c40700 sent on 2017-07-16 16:24:33 UTC###

> From: Rachel Goss
> On: Production
> Signal: 0
> 
> Auction works price info is listed as "contact for price" not current bid amounts

### Link to HockeyApp ###

* [https://rink.hockeyapp.net/manage/apps/37029/feedback/1051797](https://rink.hockeyapp.net/manage/apps/37029/feedback/1051797)

**Comment by ashfurrow** [comment]
Fixed in #2391 – will be included in an upcoming beta.
