### ISSUE TITLE
[iPad/Auction] Shows timer in portrait orientation.

### ISSUE THREAD

**Issue by alloy** [artsy/eigen#240]
When holding the device in portrait orientation and selecting an artwork, the detail view will show part of, what seems to be, the auction countdown timer:

![ios simulator screen shot 02 mar 2015 16 43 24](https://cloud.githubusercontent.com/assets/2320/6444338/4afbca36-c0fd-11e4-98d5-f39aaeeea13e.png)

**Comment by 1aurabrown** [comment]
Yes, this artwork was part of an auction. Not sure why the timer is off to the side like that, or why it doesn't say that the auction is closed.

**Comment by alloy** [comment]
Maybe it wasn’t closed because this was on staging?

**Comment by orta** [comment]
yeah, that auction is on daily, so it could be legit

**Comment by 1aurabrown** [comment]
since this view has been redesigned anyway, i'm going to close this issue. see https://github.com/artsy/eigen/issues/176.
