### ISSUE TITLE
[iPad/Auction] Artwork remains highlighted.

### ISSUE THREAD

**Issue by alloy** [artsy/eigen#241]
After navigating back from an artwork to the auction overview, the previously selected artwork’s ‘Info’ button remains highlighted:

![ios simulator screen shot 02 mar 2015 16 43 28](https://cloud.githubusercontent.com/assets/2320/6444380/83bc3388-c0fd-11e4-8b8b-7beb510071e6.png)

**Comment by orta** [comment]
This is a force issue /cc @craigspaeth

**Comment by 1aurabrown** [comment]
closing and moving to force
