### ISSUE TITLE
Cannot create a iOS App Development provisioning profile for "koel.artsy".

### ISSUE THREAD

**Issue by alelordelo** [artsy/eigen#2410]
Hi Artsy team!

I'm trying to install eigen on my iPhone 7 9 (iOS 10), I changed the bundle identifier on Xcode and got the error bellow. 

Any idea on what could be wrong?

_"Cannot create a iOS App Development provisioning profile for "koel.artsy".
Your development team, "Alexandre Gomes", does not support the Push Notifications and Associated Domains capabilities."_

https://gyazo.com/6da490aa5414ff35f7fdceee8d7e7569
https://gyazo.com/240b0ddbc829e5e86f3d582b0b590b0f

**Comment by orta** [comment]
Our app uses both of those features on production, you can probably turn them off inside the Xcode screen for the target under capabilities and the errors will go away

<img width="1392" alt="screen shot 2017-08-10 at 08 51 40" src="https://user-images.githubusercontent.com/49038/29171056-25eca1b4-7da9-11e7-9e05-6080cb07631b.png">
