### ISSUE TITLE
Unrecognized font family

### ISSUE THREAD

**Issue by alelordelo** [artsy/eigen#2411]
Hey guys,

How can I solve this this?

https://gyazo.com/2362aaf893a90163ab55ce819399e296

thanks!

**Comment by orta** [comment]
Can you verify that this is the font that is installed in your `Artsy-UIFonts` pod, https://github.com/artsy/Artsy-OSSUIFonts/blob/master/Pod/Assets/texgyreadventor-regular.ttf

It should have this font family: 
<img width="512" alt="screen shot 2017-08-10 at 08 57 49" src="https://user-images.githubusercontent.com/49038/29171312-235f8b36-7daa-11e7-8b93-9ab64ee59d82.png">
