### ISSUE TITLE
Auctions countdown timer not centered

### ISSUE THREAD

**Issue by dblock** [artsy/eigen#242]
![2015-02-17 07 24 30](https://cloud.githubusercontent.com/assets/542335/6447178/45e68cc6-c0de-11e4-9196-ce848cdad00a.png)

**Comment by orta** [comment]
Should be fixed in latest app store build, last friday or so. 
Can someone confirm? Think you need a big phone to get it.

**Comment by katarinabatina** [comment]
checked iphone 6 and 6+ I think we can close issue.

**Comment by orta** [comment]
:+1:
