### ISSUE TITLE
Support for iPhone X

### ISSUE THREAD

**Issue by orta** [artsy/eigen#2422]
- [ ] Onboarding 

![screen shot 2017-09-12 at 4 24 21 pm](https://user-images.githubusercontent.com/49038/30347012-a84a965e-97d8-11e7-9eaf-7344660b0e1f.png)

![screen shot 2017-09-12 at 4 24 25 pm](https://user-images.githubusercontent.com/49038/30347144-189c2f44-97d9-11e7-9aa3-cea669d7fdd0.png)

- [ ] Tab bar
- [ ] Default scroll positions?

![screen shot 2017-09-12 at 4 25 07 pm](https://user-images.githubusercontent.com/49038/30347025-b5a7cfba-97d8-11e7-93c1-f083291b848a.png)

- [ ] Back button
- [ ] nav item space at top

![screen shot 2017-09-12 at 4 38 31 pm](https://user-images.githubusercontent.com/49038/30347051-d2a5700e-97d8-11e7-9721-5541157df534.png)

- [ ] LAI loading exit button

![screen shot 2017-09-12 at 4 29 17 pm](https://user-images.githubusercontent.com/49038/30347092-ea4e11e8-97d8-11e7-9111-778a94ace7a3.png)

- [ ] Auctions information
![screen shot 2017-09-12 at 4 29 47 pm](https://user-images.githubusercontent.com/49038/30347121-0369b420-97d9-11e7-9790-82df4d6e6fcb.png)

**Comment by katarinabatina** [comment]
Issue moved to [artsy/collector-experience #917](https://github.com/artsy/collector-experience/issues/917) via [**ZenHub**](https://www.zenhub.com/)
