### ISSUE TITLE
Broken links to articles in artist pages

### ISSUE THREAD

**Issue by dblock** [artsy/eigen#2433]
Could only reproduce in Eigen. Some articles in artist pages, such as this one under Louise Bourgeois lead to a 404.

![2017-10-15 15 01 01](https://user-images.githubusercontent.com/542335/31666029-cfcc6cf6-b318-11e7-8fe6-0c5f2d0daea4.png)
![2017-10-15 15 01 06](https://user-images.githubusercontent.com/542335/31666030-cfd9b848-b318-11e7-9083-623a5338cde0.png)

**Comment by kanaabe** [comment]
@dblock are you seeing this issue in production or staging? It works fine for me in production but I can replicate the 404 only with staging env.
