### ISSUE TITLE
React Native view are often blank when re-appearing

### ISSUE THREAD

**Issue by ashfurrow** [artsy/eigen#2439]
Very similar to this issue: https://github.com/artsy/eigen/issues/1961

Steps to reproduce:

- Open app, navigate to Explore tab, then Auctions
- Open (this consistently works) a live auction view controller
- Dismiss it
- Go back to Home tab

Expected results: the home tab is displayed

Actual results: the home tab is empty until the user scrolls.

**Comment by orta** [comment]
I think this relates to https://github.com/artsy/emission/pull/504

**Comment by katarinabatina** [comment]
@tayapage6 @alloy let's figure out who can focus on this on collector gmv

**Comment by ashfurrow** [comment]
Whoever picks this up should make sure to apply the fix to this branch: https://github.com/artsy/eigen/tree/3.2.7-release Otherwise, the fix would have to wait for Messaging to ship.

**Comment by alloy** [comment]
@sarahscott Can you get on this ASAP?

**Comment by sarahscott** [comment]
Taking a look now

**Comment by alloy** [comment]
Should be fixed by #2440.
