### ISSUE TITLE
Right font not being used

### ISSUE THREAD

**Issue by alloy** [artsy/eigen#2441]
![img_1254](https://user-images.githubusercontent.com/2320/31996759-f2aba7ce-b989-11e7-9cc5-2e9fa6a920be.PNG)

**Comment by alloy** [comment]
This is in the 3.2.7 beta.

**Comment by orta** [comment]
I have a guess at why this is, a current `bundle exec pod install` of Eigen would like exhibit the same behavior. This PR: https://github.com/artsy/Artsy-UIFonts/pull/6 changed the [name of the Avante Garde] (https://github.com/artsy/Artsy-UIFonts/pull/6/files#diff-b56f0c984409b5dcd2461ce521b336c8L39) font. 

The version of the pod is locked, but the file resources inside are different. I'd bet that a pod update for the fonts _should_ fix that.

**Comment by orta** [comment]
@ashfurrow - wouldn't surprise me to see this happen in Kiosk
@jonallured - wouldn't surprise me to see this happen in Folio too

**Comment by orta** [comment]
This is in
