### ISSUE TITLE
Feedback 'From: Devang Thakkar On: Staging Signal: 1'

### ISSUE THREAD

**Issue by artsyit** [artsy/eigen#2458]
### Message from Devang Thakkar sent on 2017-11-09 20:22:59 UTC###

> From: Devang Thakkar
> On: Staging
> Signal: 1

### Link to HockeyApp ###

* [https://rink.hockeyapp.net/manage/apps/37020/feedback/1396864](https://rink.hockeyapp.net/manage/apps/37020/feedback/1396864)

**Comment by ashfurrow** [comment]
Tracked here: https://github.com/artsy/auctions/issues/708
