### ISSUE TITLE
banners do not load on app start up 

### ISSUE THREAD

**Issue by katarinabatina** [artsy/eigen#246]
text shows for hero banners but no photo until long after app has been open

**Comment by 1aurabrown** [comment]
this is really weird, i thought this had been fixed like twice. @orta didn't you make some changes to ensure that we are authenticated before fetching hero units?

**Comment by orta** [comment]
I did

**Comment by 1aurabrown** [comment]
fixed https://github.com/artsy/eigen/pull/475
