### ISSUE TITLE
First click on iOS Universal Link goes to /home instead of destination

### ISSUE THREAD

**Issue by kanaabe** [artsy/eigen#2460]
Steps to reproduce:
1. Close the Artsy iOS app
2. Click on a link that should get redirected to the App
3. Opens app, but goes to home
4. Click on link again and see that it goes to the destination url

**Comment by katarinabatina** [comment]
Kana which link?

**Comment by alloy** [comment]
I’m going to assume that @kanaabe was testing this because of the gender equality editorial content.

**Comment by kanaabe** [comment]
Yep it was. https://artsy.net/gender-equality. We don't want that link to redirect to the app at all, but I noticed this behavior in testing it out.

**Comment by orta** [comment]
I've been wondering if this is something that changed in iOS 11

**Comment by orta** [comment]
Looks likely: https://stackoverflow.com/questions/39548010/openurl-deprecated-in-ios-10/39548060

**Comment by orta** [comment]
Should be fixed in the next Eigen beta

**Comment by alloy** [comment]
Dope 👌
