### ISSUE TITLE
Launch image doesn’t show logo text when status bar frame is larger.

### ISSUE THREAD

**Issue by alloy** [artsy/eigen#2473]
Reproduce:

1. Kill Eigen
2. Launch Maps and start a navigation route
3. Tap home button and ensure the status bar is now large and blue
3. Launch Eigen and notice text from logo is gone

![img_1351](https://user-images.githubusercontent.com/2320/33380167-73ef57bc-d51a-11e7-8004-98b3ead73f69.PNG)

**Comment by orta** [comment]
This screen is an AL view - it probably just needs an enforced height assignment
