### ISSUE TITLE
Fix crash in - [ORStackView removeSubview:], line 180

### ISSUE THREAD

**Issue by artsyit** [artsy/eigen#249]
### Stacktrace (first of multiple) ###

<pre>ORStackView;removeSubview:;ORStackView.m;180
ARArtworkActionsView;updateUI;ARArtworkActionsView.m;60
ARArtworkActionsView;setDelegate:;ARArtworkActionsView.m;52
KSPromise;then:error:;KSPromise.m;107
ARArtworkActionsView;setDelegate:;ARArtworkActionsView.m;49
ARArtworkMetadataView;setDelegate:;ARArtworkMetadataView.m;69
ARArtworkViewController;viewDidDisappear:;ARArtworkViewController.m;106
ARDefaultNavigationTransition;popTransitionFrom:to:withContext:;ARDefaultNavigationTransition.m;124</pre>

### Link to HockeyApp ###

* [https://rink.hockeyapp.net/manage/apps/37029/crash_reasons/29286350](https://rink.hockeyapp.net/manage/apps/37029/crash_reasons/29286350)

**Comment by orta** [comment]
Think this got resolved by #218 also.
