### ISSUE TITLE
Eigen's Podfile could use RCTWebSocket, but have it removed on deploy 

### ISSUE THREAD

**Issue by orta** [artsy/eigen#2497]
In the guide: https://github.com/artsy/emission/blob/master/docs/running-emission-in-eigen.md

The biggest faff - and specifically the only thing stopping Eigen from being able to use Emission dev mode any-time is the lack of `RCTWebSocket`. 

We could add `RCTWebSocket` to our Podfile and then remove it in the Fastfile before a `pod install` on circle?

**Comment by alloy** [comment]
I’d normally be slightly hesitant about this, but seeing as this dependency has no external dependencies I guess there can’t really be any other differences that could occur between dev and prod. Give it a go 👍
