### ISSUE TITLE
Grey image view backgrounds are visible in carousel on home screen

### ISSUE THREAD

**Issue by alloy** [artsy/eigen#251]
This happens when the images have not been cached before.

![grey imageviews in carousel on home screen](https://cloud.githubusercontent.com/assets/2320/6483903/98c6c9e4-c276-11e4-89fe-97456ab572ab.gif)

**Comment by 1aurabrown** [comment]
@katarina: That's just happening before the image has been downloaded. It could be blank white if you prefer, but our default around the entire app is to show a grey box while the image is being downloaded. Once downloaded, it should be cached and available immediately.

**Comment by alloy** [comment]
@1aurabrown At least for images _after_ the first one we could definitely download the image _before_ automatically going to the next image, no?

**Comment by 1aurabrown** [comment]
We could, the view doesn't exist at that point in time so there's nowhere
to put those images in the UI, but we could hit all those image URLs
beforehand to ensure that they're cached.

On Thu, Mar 5, 2015 at 2:12 PM, Eloy Durán <notifications@github.com> wrote:

> @1aurabrown <https://github.com/1aurabrown> At least for images *after*
> the first one we could definitely download the image *before*
> automatically going to the next image, no?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/artsy/eigen/issues/251#issuecomment-77430448>.
>



-- 

[A.]


Laura Brown

Artsy <http://artsy.net/>

laura@artsy.net <caroline@artsy.net>

**Comment by ashfurrow** [comment]
Is this still a problem? Even with the network link conditioner set to "Very Bad Network", I still can't reproduce this. Images appear to be completely downloaded when swiped.

**Comment by 1aurabrown** [comment]
Its only when the images have never been downloaded/cached. Possibly yours are cached?Sent using CloudMagicOn Tue, Mar 10, 2015 at 15:32,  artsy/eigen <reply@reply.github.com> wrote:            Is this still a problem? Even with the network link conditioner set to "Very Bad Network", I still can't reproduce this. Images appear to be completely downloaded when swiped.

**Comment by ashfurrow** [comment]
Ah, I see. Thanks!
