### ISSUE TITLE
[Sale] Prices incorrectly use different currency symbols

### ISSUE THREAD

**Issue by alloy** [artsy/eigen#2514]
9500 USD:

![simulator screen shot 10 jan 2018 01 14 01](https://user-images.githubusercontent.com/2320/34749853-1c556e56-f5a4-11e7-892a-8ac8efd537ba.png)

9500 GBP:

![simulator screen shot 10 jan 2018 01 14 09](https://user-images.githubusercontent.com/2320/34749855-1e7c9c0e-f5a4-11e7-8828-a0570bbea71b.png)

**Comment by katarinabatina** [comment]
@ashfurrow this _feels_ like a regression of something that was fixed a while back. I might be wrong but wanted to check.

**Comment by orta** [comment]
It's possible that the fix I made for https://github.com/artsy/eigen/pull/2513 could also handle this

**Comment by orta** [comment]
I'll try port it over now

**Comment by ashfurrow** [comment]
I don't think it's a regression, it looks like the GraphQL request used by the view is missing `currency`:

https://github.com/artsy/eigen/blob/master/Artsy/Networking/artworks_in_sale.graphql

I'm testing a fix locally, will report back.

**Comment by orta** [comment]
ohhh

**Comment by orta** [comment]
can confirm from debugger

<img width="457" alt="screen shot 2018-01-09 at 8 41 21 pm" src="https://user-images.githubusercontent.com/49038/34751961-7a11e316-f57d-11e7-8945-8f90fdb10f8a.png">

**Comment by orta** [comment]
@ashfurrow wanna push direct to this branch?

**Comment by alloy** [comment]
Fixed by https://github.com/artsy/eigen/pull/2515
