### ISSUE TITLE
Selecting a photo on Live at Armory Show view may lead to a bad UX

### ISSUE THREAD

**Issue by alloy** [artsy/eigen#252]
Related to https://github.com/artsy/microgravity/issues/720.

This is likely because I don’t have the Instagram application installed, but we can check for that and open in the browser instead (if we have the full Instagram URL). There are even 2 alerts shown, I’m not sure why or what the purpose is.

![live at armory show - tap photo without instagram installed](https://cloud.githubusercontent.com/assets/2320/6484192/f0d79d36-c279-11e4-9189-48ebb5076835.gif)

**Comment by alloy** [comment]
Also see https://github.com/artsy/microgravity/issues/720#issuecomment-77156546.

**Comment by katarinabatina** [comment]
@alloy this is working smoothly in the current build but not in the beta

**Comment by alloy** [comment]
@katarinabatina I just double-checked with the current release from the App Store, it does the exact same thing there for me. (That is, it’s showing both these alerts.)

**Comment by katarinabatina** [comment]
@alloy you're right, this happens if you don't have instagram installed. Anything we can do to fix it?

**Comment by alloy** [comment]
Including from https://github.com/artsy/microgravity/issues/720#issuecomment-77175127

> @katarinabatina Agreed, but, the problem is this:
> 
> * A web application (such as martsy) running in a browser is not able to detect whether or not a iOS application is installed. As such, you have to either assume it does (and risk behaviour like the current broken behaviour) or accept that you cannot and thus always open in the browser.
>
> * A native application (such as Eigen), however, is able to detect whether or not an iOS application is installed. So there we can make a more informed decision and open the Instagram application where possible.

**Comment by alloy** [comment]
So the implementation of my suggestion would be this:

* martsy would use normal instagram.com URLs, e.g. http://instagram.com/p/qJu0a-OHMC
* We would have `ARSwitchboard` check for URLs with a `instagram.com` domain and:
  - Check if the user has the Instagram.app application installed (with `-[UIApplication canOpenURL:[NSURL URLWithString:@"instagram://media"]]`)
  - If Instagram.app is installed, query the Instagram API to get the right ID, e.g. http://api.instagram.com/oembed?url=http://instagram.com/p/qJu0a-OHMC and create the internal URL based on that.
  - If Instagram.app is not installed, simply open it with the browser.

**Comment by alloy** [comment]
Based on discussion with @katarinabatina, we’re leaving this as is, for now.

If we ever have a ‘live at X’ feed again or otherwise show instagram.com URLs, we should try to do something like the above so that it works consistent for everybody.
