### ISSUE TITLE
Armory Show Insider’s Picks has too narrow viewport

### ISSUE THREAD

**Issue by alloy** [artsy/eigen#253]
Not sure if this is on our end or if this is something that can be fixed in martsy? /cc @craigspaeth 

----

![ios simulator screen shot 04 mar 2015 14 31 08](https://cloud.githubusercontent.com/assets/2320/6484331/53d75376-c27b-11e4-97c3-126f4c0c5ac8.png)

Which leads to horrible layout for the related editorial content:

![ios simulator screen shot 04 mar 2015 14 31 28](https://cloud.githubusercontent.com/assets/2320/6484334/57358074-c27b-11e4-8d89-4bfead93faec.png)

----

Contrast with martsy:

![ios simulator screen shot 04 mar 2015 14 30 04](https://cloud.githubusercontent.com/assets/2320/6484344/720f16da-c27b-11e4-9014-f03296d4c73e.png)

![ios simulator screen shot 04 mar 2015 14 30 17](https://cloud.githubusercontent.com/assets/2320/6484347/7723c238-c27b-11e4-9db6-41e28d103c77.png)

**Comment by katarinabatina** [comment]
@orta and @craigspaeth have spoken about this in the past don't know what the conclusion was, I believed Orta said it was a microgravity issue.

**Comment by alloy** [comment]
I did some debugging and found it to be a CSS issue in the [CSS served by microgravity](https://d3df9uo7bhy7ev.cloudfront.net/assets/main_layout-6b869d44.css):

```css
.body-eigen #main-layout-container {
  margin-top: 0;
  padding: 0 55px;
}
```

![armory insider s picks](https://cloud.githubusercontent.com/assets/2320/6487010/ffdc8980-c28e-11e4-8111-1d2a0c68f14c.gif)

**Comment by alloy** [comment]
Moved to https://github.com/artsy/microgravity/issues/722
