### ISSUE TITLE
Sign-in screen issues.

### ISSUE THREAD

**Issue by alloy** [artsy/eigen#254]
Today I’ve been only able to produce this once, so probably a very low priority issue, but documenting it nonetheless.

I got the sign-in screen in a state where:
* tapping characters on the keyboard would leave the characters zoomed (see image)
* the cursor did not blink
* trying to paste a password made the application completely freeze (the paste action button would be shown, but I wasn’t able to tap it)
* I had to force quit the app in order to do anything

![photo](https://cloud.githubusercontent.com/assets/2320/6484464/84db8ec8-c27c-11e4-9ad8-2b4958338022.PNG)

**Comment by katarinabatina** [comment]
moving this out of the milestone for now

**Comment by alloy** [comment]
Let’s just close this completely. It’s documented now and if we ever come across it again we can possibly triangulate the cause then.
