### ISSUE TITLE
Articles are missing from fair overviews

### ISSUE THREAD

**Issue by katarinabatina** [artsy/eigen#256]
@orta not sure if this had anything to do with removing the Explore categories carousel story but articles are missing from fair overview pages (see martsy view for comparison). 

Somewhat time sensitive @alloy if you could dig into this and do some investigating please let me know, thank you!

**Comment by alloy** [comment]
I’ll document this as I go:

* The ‘posts’ are being omitted [here](https://github.com/artsy/eigen/blob/025e13f3f67f923bec520e637090fac479029785/Artsy/Classes/View%20Controllers/ARFairViewController.m#L180-L184). (This conditional has been there since last year, so it’s not related to a recent Eigen change.)
* If I were to remove that conditional, the app tries to make the following request: `GET 'https://api.artsy.net/api/v1/profile/(null)/posts?size=10'`
* This means that a ‘profile ID’ is missing.
* Looking at [the response](https://gist.github.com/alloy/df403e6eb9ba3eaa020b) to `GET 'https://api.artsy.net/api/v1/profile/the-armory-show'`, there doesn’t appear to be a profile ID specifically for the 2015 edition: `profile_id": null`.
* Using `default_profile_id` does return posts, but it encompasses _all_ of the Armory posts, including those from 2014.

**Comment by orta** [comment]
Perhaps there's a new API route, try load the page on martsy/force and see what endpoints are hit.

**Comment by alloy** [comment]
@orta This is the [request/response for martsy](https://gist.github.com/alloy/64089e39147d9fff3ea1). I haven’t found the corresponding call on force yet.

Can’t it be that the issue is that the 2015 edition of the Armory should simply get an explicit profile ID?

**Comment by ashfurrow** [comment]
We recently hanged how we deal with profile IDs – I can't remember the specifics, but I'll take a look in our history.

**Comment by alloy** [comment]
Ok, scratch the part about the conditional, the only issue is that `profile_id` is set to `null`. If I manually set it to be the `default_profile_id` then Eigen is apparently smart enough to filter out the 2015 posts and everything works as expected:

```

(lldb) bt
* thread #1: tid = 0x17c938, 0x001d146c Artsy`__19-[Fair updateFair:]_block_invoke(.block_descriptor=0x7b6f29b0, fair=0x7b7bd4a0) + 204 at Fair.m:105, queue = 'com.apple.main-thread', stop reason = step over

(lldb) po self
<Fair: 0x7b895770> {
    bannerURLs =     {
        "large_rectange" = "https://d32dm0rphc51dk.cloudfront.net/y0syHq4x9n8ZASGLvAoYyA/mobile-fair-cover.jpg";
        "mobile-fair-cover" = "https://d32dm0rphc51dk.cloudfront.net/y0syHq4x9n8ZASGLvAoYyA/mobile-fair-cover.jpg";
    };
    city = "New York City";
    defaultProfileID = "the-armory-show";
    endDate = "2015-03-08 23:00:00 +0000";
    fairID = "the-armory-show-2015";
    imageURLs =     {
        "large_rectangle" = "https://d32dm0rphc51dk.cloudfront.net/VdoJEo-T8fNgjd9sNF-odw/large_rectangle.jpg";
        square = "https://d32dm0rphc51dk.cloudfront.net/VdoJEo-T8fNgjd9sNF-odw/square.jpg";
        wide = "https://d32dm0rphc51dk.cloudfront.net/VdoJEo-T8fNgjd9sNF-odw/wide.jpg";
    };
    maps = "<null>";
    name = "The Armory Show 2015";
    organizer = "<FairOrganizer: 0x7b7bbe00> {\n    defaultFairID = \"the-armory-show-2015\";\n    fairOrganizerID = \"the-armory-show-2015\";\n    name = \"The Armory Show 2015\";\n    profileID = \"<null>\";\n}";
    partnersCount = 183;
    shows = "<null>";
    showsDeferred = "<null>";
    startDate = "2015-03-05 12:00:00 +0000";
    state = NY;
}

(lldb) po self.organizer
<FairOrganizer: 0x7b7bbe00> {
    defaultFairID = "the-armory-show-2015";
    fairOrganizerID = "the-armory-show-2015";
    name = "The Armory Show 2015";
    profileID = "<null>";
}

(lldb) expr (void)[self.organizer setValue:@"the-armory-show" forKey:@"_profileID"]

(lldb) po self.organizer
<FairOrganizer: 0x7b7bbe00> {
    defaultFairID = "the-armory-show-2015";
    fairOrganizerID = "the-armory-show-2015";
    name = "The Armory Show 2015";
    profileID = "the-armory-show";
}
```

**Comment by alloy** [comment]
So while we could change Eigen to default to the `default_profile_id`, this would require a new version to be available in the App Store. It would work instantaneously if the API would return the `default_profile_id` as the `profile_id` (`the-armory-show`).

I took a quick look in the admin section, but couldn’t find anything regarding the `profile_id`. Who should I ask to change that in the database?

**Comment by alloy** [comment]
Btw, unlike martsy, the posts show-up _underneath_ the Insider’s Picks, but that’s better than not at all:

![ios simulator screen shot 05 mar 2015 14 22 58](https://cloud.githubusercontent.com/assets/2320/6505511/4659a38e-c343-11e4-9376-7baebdde94aa.png)

And finally, [this issue](https://github.com/artsy/microgravity/issues/722) about the view being too narrow also applies to showing posts.

**Comment by ashfurrow** [comment]
Ask in the #core chat room. Someone should be available to do it.

**Comment by alloy** [comment]
Oh wait, no, these posts that are being shown are different posts than those that @katarinabatina was asking about in the chat.

**Comment by ashfurrow** [comment]
This is the change I was referring to: https://github.com/artsy/eigen/commit/bbcf7e5ed6b2a2b49bb8d5e9c831cafa882c9604

**Comment by ashfurrow** [comment]
I can't remember the specifics – @1aurabrown told me about them quite a while ago. Something about how the web restructured how the fairs are owned by profiles. It sounds plausible that this change could have inadvertently broke the API call conditional.

**Comment by alloy** [comment]
I found the right content. It appears that it _does_ need more code in Eigen after all, the ‘editorial’ section is completely being ignored, [only ‘primary’ and ‘curator’ content is being used](https://github.com/artsy/eigen/blob/025e13f3f67f923bec520e637090fac479029785/Artsy/Classes/View%20Controllers/ARFairViewController.m#L136-L177):

```diff
~/C/A/eigen [master] » git diff Artsy/Classes/View\ Controllers/ARFairViewController.m
diff --git a/Artsy/Classes/View Controllers/ARFairViewController.m b/Artsy/Classes/View Controllers/ARFairViewController.m
index 3b1eba2..9cdcbcf 100644
--- a/Artsy/Classes/View Controllers/ARFairViewController.m     
+++ b/Artsy/Classes/View Controllers/ARFairViewController.m     
@@ -174,6 +174,13 @@ NSString * const ARFairHighlightFavoritePartnersKey = @"ARFairHighlightFavoriteP
 
                 break;
             }
+          
+            for (OrderedSet *curatorSet in orderedSets[@"editorial"]) {
+                [curatorSet getItems:^(NSArray *items) {
+                    NSLog(@"ITEMS: %@", items);
+                }];
+            }
+
         }];
     }];
 ```

```
2015-03-05 14:41:48.703 Artsy[67190:607] ITEMS: (
    "<FeaturedLink: 0x7c1613c0> {\n    displayOnMobile = 1;\n    featuredLinkID = 54f7ef517261696ec2321900;\n    href = \"/article/editorial-at-the-armory-show-a-fresh-faced-vernissage\";\n    subtitle = \"Marina Cashdan\";\n    title = \"At The Armory Show, a Fresh-Faced Vernissage with Accessible Price Points\";\n    urlFormatString = \"https://d32dm0rphc51dk.cloudfront.net/n3qGHPWVa_I5ZcUQlZNUXA/:version.jpg\";\n}",
    "<FeaturedLink: 0x7c1612c0> {\n    displayOnMobile = 1;\n    featuredLinkID = 54f7eec77261697e67a41900;\n    href = \"/article/editorial-zero-and-gutai-reign-at-armory-shows\";\n    subtitle = \"Julie Baumgardner\";\n    title = \"Zero and Gutai Reign at Armory Show\\U2019s Modern Section\";\n    urlFormatString = \"https://d32dm0rphc51dk.cloudfront.net/VooCLefrvTGlUzHsmlTLHQ/:version.jpg\";\n}",
    "<FeaturedLink: 0x7c1611c0> {\n    displayOnMobile = 1;\n    featuredLinkID = 54f7b9397261692b66fe0e00;\n    href = \"/article/editorial-the-armory-show-wins-big-by-going\";\n    subtitle = \"Alexander Forbes\";\n    title = \"The Armory Show Wins Big by Going Small\";\n    urlFormatString = \"https://d32dm0rphc51dk.cloudfront.net/4t5-1W5v8CcxP9HKjs6HVQ/:version.jpg\";\n}",
    "<FeaturedLink: 0x7c1610c0> {\n    displayOnMobile = 1;\n    featuredLinkID = 54ee81107261697560c90600;\n    href = \"/article/editorial-hank-willis-thomas-on-race-the-media\";\n    subtitle = \"Emily Nathan\";\n    title = \"Hank Willis Thomas on Race, the Media, and His Upcoming Armory Show Takeover\";\n    urlFormatString = \"https://d32dm0rphc51dk.cloudfront.net/PdMYVOdCZejBBxrDoxvvKw/:version.jpg\";\n}"
)
```

So, alas, I see no way to make this work in a timely fashion.

**Comment by alloy** [comment]
Moving further discussion to https://github.com/artsy/eigen/issues/257.

**Comment by orta** [comment]
We _can_ make the server give us data how we expect if it's dire

**Comment by alloy** [comment]
@orta Fair enough. The only way I can see that working is if we’d re-use the currently unused ‘posts’ section for this. So:

* Make `https://api.artsy.net/api/v1/profile/the-armory-show` return a `profile_id`, e.g. `the-armory-show-2015`.
* Make `https://api.artsy.net/api/v1/profile/the-armory-show-2015/posts?size=10` return the editorial content instead of the “Insider’s Picks” that it is currently returning.

I don’t know if gravity/microgravity are using the `/posts` endpoint for something, although I doubt it as it’s returning the same data as the “Insider’s Picks”.

**Comment by katarinabatina** [comment]
About to take off on a flight but I wanted to note this is not an Armory specific problem, none of the fairs have their articles showing. 

Katarina
