### ISSUE TITLE
[Fair] Remove ‘posts’ from overview?

### ISSUE THREAD

**Issue by alloy** [artsy/eigen#258]
While investigating https://github.com/artsy/eigen/issues/256, I came across code that wasn’t working and thus wasn’t showing any of the following content on screen:

![ios simulator screen shot 05 mar 2015 14 22 58](https://cloud.githubusercontent.com/assets/2320/6505511/4659a38e-c343-11e4-9376-7baebdde94aa.png)

These posts appear to simply be the “Insider’s Picks”. I that correct and so should we simply remove all of the related ‘posts’ code?

**Comment by alloy** [comment]
Related to #432?

**Comment by mennenia** [comment]
So currently there are Fair Highlights and Insider's Picks (below the basic fair click through list). Fair highlights seem similar to posts, have they been changed to this? I can't seem to find a fair that has posts in its metadata (e.g. when I search for Art Basel 2013 up till 2015, there are no posts, same for The Armoury Show). 

This is for the api v1/profile/slug/posts - you get a 404. 

If 'Posts' are no longer a thing, should we remove that section? (as self.fairPostsVC is different to self.editorialVC).

**Comment by alloy** [comment]
Yeah, reading #432 and that that route returns a 404 seems to be a good enough indication. Let’s remove it :+1:

**Comment by mennenia** [comment]
Will do.

**Comment by katarinabatina** [comment]
@alloy @mennenia not sure if this is helpful but if you visit any fair on m.artsy, you'll see the "read highlights form the fair" section. Not sure if we can use the same "route"  to the data but that's what we should be showing in eigen as well.
