### ISSUE TITLE
Text views for the bullet points in "Sell Works From Your Collection" model are getting cut-off

### ISSUE THREAD

**Issue by bbernberg** [artsy/eigen#2596]
![fullsizeoutput_4a0e](https://user-images.githubusercontent.com/1385086/39253268-7fc0898e-4875-11e8-9b1d-964019a5201b.jpeg)

^ iPhone 8 screenshot

**Comment by ashfurrow** [comment]
Hmm interesting! I'm seeing something similar on the iPhone 8 simulator, but the text isn't wrapping (it's getting cut off horizontally, and not wrapping). I'm going to open a ticket in our Jira system to get this tracked and prioritized. Thank you so much for the bug report!

**Comment by ashfurrow** [comment]
Oh one more question: would you happen to have the "Increase Font Size" accessibility setting enabled? That might explain part of this.

**Comment by ashfurrow** [comment]
I believe that's the case, thanks for clarifying!
