### ISSUE TITLE
add padding to works by artists you follow 

### ISSUE THREAD

**Issue by 1aurabrown** [artsy/eigen#262]
the nav button in eigen covers part of the header in the "works by artists you follow" page
would be nice to add some padding and maybe move the title up a little so it could be aligned with the center of the button
![screen shot 2015-03-06 at 12 17 57 pm](https://cloud.githubusercontent.com/assets/3171662/6529984/0bba936a-c3fb-11e4-9762-6069679aa892.png)

**Comment by orta** [comment]
martsy

**Comment by 1aurabrown** [comment]
Ugh sorry i had martsy open in a different tab and put the issue in the wrong repoSent using CloudMagicOn Fri, Mar 6, 2015 at 16:57,  artsy/eigen <reply@reply.github.com> wrote:            martsy

**Comment by 1aurabrown** [comment]
closing and moving to martsy
