### ISSUE TITLE
after logging out user-specific requests and web views still succeed

### ISSUE THREAD

**Issue by 1aurabrown** [artsy/eigen#263]
I have mentioned this before --- if you log out and then somehow end up on a web view or making an api request that requires a current user (usually through stale UI) the request should, in theory, fail, but it doesn't. the fact that it doesn't fail is pretty weird, and seems problematic if we hope to introduce the ability for users to log out and log in with different usernames. I'm having trouble tracking down what reference to the user's auth isn't getting deleted, would appreciate some help.

**Comment by orta** [comment]
Log outs should kill the app after a confirmation like Folio does IMO. Given that it's not even public too.

**Comment by alloy** [comment]
Killing the app makes a lot of sense if this is indeed only about the private dev features, but I get the sense from @1aurabrown’s description that signing out (changing user) would be a future public feature?

**Comment by 1aurabrown** [comment]
I think at some point when we have a user setting menu we might also have the option to log out. Killing the app might be a good way to implement it until then though. Sent using CloudMagicOn Sun, Mar 8, 2015 at 17:44,  artsy/eigen <reply@reply.github.com> wrote:            Killing the app makes a lot of sense if this is indeed only about the private dev features, but I get the sense from @1aurabrown’s description that signing out (changing user) would be a future public feature?
