### ISSUE TITLE
Fix crash in + [ARTextView _attributedStringWithTextParams:andHTML:], line 126

### ISSUE THREAD

**Issue by artsyit** [artsy/eigen#264]
### Stacktrace (first of multiple) ###

<pre>ARTextView;_attributedStringWithTextParams:andHTML:;ARTextView.m;126
ARTextView;artsyBodyTextAttributedStringFromHTML:withFont:;ARTextView.m;95
ARTextView;setHTMLString:;ARTextView.m;56
ARTextView;setMarkdownString:;ARTextView.m;40
ARArtworkDetailView;updateWithArtwork:;ARArtworkDetailView.m;197
ARArtworkDetailView;setDelegate:;ARArtworkDetailView.m;45
ARArtworkMetadataView;setDelegate:;ARArtworkMetadataView.m;68
ARArtworkViewController;viewDidAppear:;ARArtworkViewController.m;89
-;__RACSwizzleForwardInvocation_block_invoke;NSObject+RACSelectorSignal.m;49</pre>

### Link to HockeyApp ###

* [https://rink.hockeyapp.net/manage/apps/37029/crash_reasons/29448211](https://rink.hockeyapp.net/manage/apps/37029/crash_reasons/29448211)

**Comment by alloy** [comment]
Fixed by #349.

**Comment by alloy** [comment]
Fixed by #349.
