### ISSUE TITLE
Thumbnail displays text in related artists

### ISSUE THREAD

**Issue by dblock** [artsy/eigen#265]
I often see thumbnails that display text in related artists.

![image](https://cloud.githubusercontent.com/assets/542335/6546229/77a45362-c582-11e4-9d12-13b962d29ad0.jpg)
![image](https://cloud.githubusercontent.com/assets/542335/6546228/77a45696-c582-11e4-8b7f-554a2d0e3eff.jpg)
![image](https://cloud.githubusercontent.com/assets/542335/6546227/77a2eeaa-c582-11e4-95ab-60d7c1907ada.jpg)

**Comment by orta** [comment]
Not sure there's anything we can do about this? This is the image given to us by the API

**Comment by alloy** [comment]
@jessicabackus Did you ever find out more about this mystery?

![](http://media2.giphy.com/media/EVhc1WCZnu0M0/giphy.gif)

**Comment by alloy** [comment]
@dblock In any case, this is not client side issue, so I’m gonna close this and possibly create a new one based on what/if @jessicabackus has to say about this. (I know she was wondering and looking into this issue for a while.)

**Comment by alloy** [comment]
Just found a bunch more in the related to 'Jim Krantz' section. It also has a few fully black ones btw, expected?

![ios simulator screen shot 29 jun 2015 18 36 03](https://cloud.githubusercontent.com/assets/2320/8413042/11ead22a-1e8e-11e5-92dc-6c6ffdc48b51.png)

**Comment by dblock** [comment]
I am going to bet a $ it's a client side bug in the app :)

**Comment by orta** [comment]
If it's doing different colours, I'm willing to bet a JP that it's not ;)
