### ISSUE TITLE
Markdown doesn't render correctly for Lucio Fontana

### ISSUE THREAD

**Issue by dblock** [artsy/eigen#266]
Broken markdown on eigen vs. Martsy.

![image](https://cloud.githubusercontent.com/assets/542335/6546262/ad641536-c583-11e4-9d9b-b2233976979f.jpg)
![image](https://cloud.githubusercontent.com/assets/542335/6546263/ad66aeea-c583-11e4-9895-9cd435b7e8e7.jpg)

**Comment by 1aurabrown** [comment]
From the original markdown: 
```
[performance art](/gene/performance-art), and [Arte Povera]( /gene/arte-povera).
```
The markdown parser we use in iOS must not be gobbling that whitespace between the `(` and the `/` in links.

**Comment by ashfurrow** [comment]
Hmm. Good catch. Anything we could do on the client side to fix this? Would replacing all instances of the string `]( ` with `](` pre-parsing be a good idea? Or even `]( /`?

**Comment by orta** [comment]
we should probably PR to https://github.com/mdiep/MMMarkdown - it's an active project

**Comment by ashfurrow** [comment]
Even better :)

**Comment by orta** [comment]
http://johnmacfarlane.net/babelmark2/?text=hello+%5Bworld%5D(+%2Fthing%2Fok) <- this is def a MMMarkdown bug

**Comment by 1aurabrown** [comment]
working on it

**Comment by 1aurabrown** [comment]
lol this one seems to have the same bug: `lunamark 0.2     <p>hello [world]( /thing/ok)</p>`
