### ISSUE TITLE
Add snowplow analytics to Eigen

### ISSUE THREAD

**Issue by alexanderfabry** [artsy/eigen#268]
Now that https://github.com/orta/ARAnalytics/issues/132 is in place, would be fantastic to add snowplow analytics feeding into our redshift database to Eigen so we can get all of our app analytics into the same easily accessible place.

@anipetrov and I are doing a review of our analytics events currently, and will have a number of suggestions for new things to track, and naming conventions.

**Comment by alloy** [comment]
Closed in favour of #384.
