### ISSUE TITLE
Eigen should only display fair partners/booths where "private_partner" is false

### ISSUE THREAD

**Issue by dylanfareed** [artsy/eigen#272]
Its not clear to me if the fair partners list comes from microgravity in eigen so adding dupe of https://github.com/artsy/microgravity/issues/737 here as well. Feel free to close if an upstream fix solves the issue in eigen as well.

---

As of recently, we've started having "private dealers" on CMS and Folio. They still have the ability to create shows/booths (largely for Folio) with the caveat that they'll never have those shows/booths/works published.

We should avoid listing these associated, but private, booths on Fair A-Z lists and other places - https://github.com/artsy/gravity/issues/8689

![image](https://cloud.githubusercontent.com/assets/197336/6610435/8b2713d8-c835-11e4-81a0-5609f406d78c.png)

After https://github.com/artsy/gravity/pull/8695 we now have the ability to ensure that private partners do not appear in fair booth and partner lists.

These endpoints now provide a ```private_partner``` filter. Hitting ```private_partner=false``` should be all we need here.

Fair shows endpioint
https://github.com/artsy/gravity/blob/master/app/api/v1/fairs_shows_endpoint.rb#L13

Fair partners endpoint
https://github.com/artsy/gravity/blob/master/app/api/v1/fairs_partners_endpoint.rb#L27

**Comment by orta** [comment]
Yeah, this is all done in force/martsy ATM ( I saw those PRs come though and did a quick check )

**Comment by dylanfareed** [comment]
Thanks, @orta. Much appreciated.
