### ISSUE TITLE
Bundle install error

### ISSUE THREAD

**Issue by wongzigii** [artsy/eigen#278]
I had already install ruby on Mac OSX.
But when I run `bundle install`, show `-bash: bundle: command not found`

**Comment by ashfurrow** [comment]
Looks like you don't have bundler installed. Try the following:

    gem install bundler

If that doesn't work, try:

    sudo gem install bundler

And let us know!

**Comment by orta** [comment]
bundler isn't a default gem, perhaps we should move that `bundle install` into the makefile, then we can do a check for it and offer a "run `[sudo] gem install bundler` - to continue"

**Comment by ashfurrow** [comment]
:+1: sounds good to me

**Comment by wongzigii** [comment]
You both are right! I haven't install bundler.
