### ISSUE TITLE
Create Password screen should conform to iOS 11 standards

### ISSUE THREAD

**Issue by igor-makarov** [artsy/eigen#2787]
Here's the relevant info on the subject:

https://developer.apple.com/documentation/security/password_autofill/#topics

I've just tried to register and couldn't use the built in password generator.

**Comment by ashfurrow** [comment]
Wow, thanks for the issue and link to the docs! Looks pretty easy to integrate, especially into our existing on boarding flow setup. I'll open a PR 👍

**Comment by igor-makarov** [comment]
Awesome!💪
