### ISSUE TITLE
this artwork is unpublished, this artwork is unpublished, this artwork is unpublished

### ISSUE THREAD

**Issue by orta** [artsy/eigen#279]
![slack_for_ios_upload](https://cloud.githubusercontent.com/assets/49038/6657967/b8397156-cb30-11e4-9417-cab63d1339ab.png)

This banner needs to check if one exists before adding itself to the hierarchy.

**Comment by 1aurabrown** [comment]
great issue title

**Comment by alloy** [comment]
It doesn’t match the screenshot, though.
