### ISSUE TITLE
New release does not have correct analytics keys in hockey 

### ISSUE THREAD

**Issue by orta** [artsy/eigen#281]
Let's try get a new release out this week, with browse + artworks?

**Comment by alloy** [comment]
Sounds good, but not sure yet what the ‘correct analytics keys in hockey’ is about yet, is it [this](http://hockeyapp.net/features/analytics/) for beta testers?

**Comment by orta** [comment]
https://github.com/artsy/eigen/blob/master/Podfile#L21-L24

**Comment by ashfurrow** [comment]
@orta could you fill those keys in in the 1Password secure note with our keys in it?

**Comment by orta** [comment]
Done. It is a secure note in Engineering 1p.

**Comment by katarinabatina** [comment]
Let's deploy a beta first and plan stress testing for early next week.

**Comment by orta** [comment]
closing, this is fixed, would be nice to have a way to verify keys in `make App Store` but that's an existing issue.
