### ISSUE TITLE
Fork of ARAnalytics becoming an issue

### ISSUE THREAD

**Issue by orta** [artsy/eigen#286]
We want to move to also support snowplow - https://github.com/artsy/eigen/issues/268 but because we're using a custom fork of ARAnalytics for RAC, we can't.

I plan on doing the work updating ARAnalytics to add Snowplow support, but likely @ashfurrow is going to have to bring the RAC stuff over to 3.0 when I tried I didn't get very far before having to know RAC internals

**Comment by ashfurrow** [comment]
Re-assigned to me :)

**Comment by ashfurrow** [comment]
This is [now available](https://github.com/orta/ARAnalytics/pull/140). I'll get this is ASAP.
