### ISSUE TITLE
Update to WKWebView

### ISSUE THREAD

**Issue by ashfurrow** [artsy/eigen#288]
Martsy spinners will stop spinning while you hold down your finger to scroll. We should update to [WKWebView](http://nshipster.com/wkwebkit/) (iOS 8-only) to fix.

**Comment by orta** [comment]
https://github.com/sticksen/STKWebKitViewController

**Comment by alloy** [comment]
Some work done in https://github.com/artsy/eigen/tree/alloy-WKWebView

**Comment by alloy** [comment]
Also check #500.

**Comment by alloy** [comment]
Implemented by #606.
