### ISSUE TITLE
Get background fetch back in the app

### ISSUE THREAD

**Issue by orta** [artsy/eigen#29]
_From @orta on December 15, 2014 15:25_

Extensions support means that you can grab non-private data in the background. This means that fetch networking can now work properly. 

We should grab things like:
 - [ ] Hero Units
 - [ ] First 15 items in the feed
 - [ ] 10 most recent works

_Copied from original issue: artsy/eigen-private#2065_

**Comment by alloy** [comment]
This has been done.
