### ISSUE TITLE
No Browse section when beta is installed

### ISSUE THREAD

**Issue by katarinabatina** [artsy/eigen#295]
Just downloaded the beta on iphone 6+, try without an account, go to browse, get blank screen. Restart the app, then get browse section.

**Comment by 1aurabrown** [comment]
It's possible the featured links and the set haven't been copied to staging. Have you tried in production?

**Comment by 1aurabrown** [comment]
This is a staging issue, and there's an eigen issue on top of that where after switching from staging to production we don't re-fetch data.

**Comment by katarinabatina** [comment]
I can't get it to work anywhere, staging or production. Tried re downloading the beta but that didn't help

**Comment by 1aurabrown** [comment]
this should be fixed
