### ISSUE TITLE
Fix NSInvalidArgumentException in - [ARArtworkRelatedArtworksView addRelatedArtworkRequest:], line 125

### ISSUE THREAD

**Issue by artsyit** [artsy/eigen#296]
### Stacktrace ###

<pre>ARArtworkRelatedArtworksView;addRelatedArtworkRequest:;ARArtworkRelatedArtworksView.m;125
ARArtworkRelatedArtworksView;addSectionWithArtistArtworks;ARArtworkRelatedArtworksView.m;173
ARArtworkRelatedArtworksView;addSectionsForShow:;ARArtworkRelatedArtworksView.m;148
ARArtworkRelatedArtworksView;updateWithArtwork:withCompletion:;ARArtworkRelatedArtworksView.m;96
KSPromise;resolveWithValue:;KSPromise.m;151
KSPromise;joinedPromiseFulfilled:;KSPromise.m;248
KSPromise;when:;KSPromise.m;79
KSPromise;resolveWithValue:;KSPromise.m;151
KSPromise;resolvePromise:withValue:;KSPromise.m;180
KSPromise;resolveWithValue:;KSPromise.m;156
KSDeferred;resolveWithValue:;KSDeferred.m;25
Artwork;updatePartnerShow;Artwork.m;436</pre>

### Reason ###

*** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '*** -[NSArray arrayByAddingObject:]: object cannot be nil'

### Link to HockeyApp ###

* [https://rink.hockeyapp.net/manage/apps/37020/crash_reasons/30709737](https://rink.hockeyapp.net/manage/apps/37020/crash_reasons/30709737)

**Comment by alloy** [comment]
Not seen in 1.8.0
