### ISSUE TITLE
Updated Explore (formerly browse) Section

### ISSUE THREAD

**Issue by katarinabatina** [artsy/eigen#299]
Note that these are based of moving two of the entry points to bottom nav (shows and magazine) 

iphone (spec based off iphone6)
![image](https://cloud.githubusercontent.com/assets/6482926/6786637/f9766e42-d163-11e4-8b9e-f958406f5416.png)

ipad landscape 
![image](https://cloud.githubusercontent.com/assets/6482926/6786642/00b35166-d164-11e4-89b3-6bc1c126030d.png)

ipad portrait 
![image](https://cloud.githubusercontent.com/assets/6482926/6786650/08467d2c-d164-11e4-857c-feefd4157454.png)

**Comment by katarinabatina** [comment]
@1aurabrown can you make the mobile size increases now? Before we ship?

**Comment by orta** [comment]
I'm in the codebase right now, will make the change for iPhone

**Comment by alloy** [comment]
@orta The iPad screenshot [here](https://github.com/artsy/eigen/commit/91b8ce978b2c788e52702ef35303c96199aef66c) doesn’t look like the side-by-side grid that @katarinabatina requested.

**Comment by 1aurabrown** [comment]
The grid hasn't yet been implemented but it should be a pretty qrick fixSent using CloudMagicOn Thu, Mar 26, 2015 at 09:09,  artsy/eigen <reply@reply.github.com> wrote:             @orta The iPad screenshot here doesn’t look like the side-by-side grid that @katarinabatina requested.

**Comment by orta** [comment]
Yeah @alloy that's why I didn't class it as  "fixes 299" :)

**Comment by alloy** [comment]
Gotcha.

**Comment by katarinabatina** [comment]
@1aurabrown does this grid still need to be done for ipad?

**Comment by 1aurabrown** [comment]
No, i did this. I thought i closed the issue but I guess not.

On Mon, Apr 20, 2015 at 21:37, Katarina Batina <notifications@github.com> wrote:
@1aurabrown [https://github.com/1aurabrown] does this grid still need to be done for ipad?

—
Reply to this email directly or view it on GitHub
[https://github.com/artsy/eigen/issues/299#issuecomment-94608004] .[https://github.com/notifications/beacon/ADBlTs_iQAWOsIMKXKQTgh7Nlja3npY-ks5oBaFqgaJpZM4DzQmX.gif]

**Comment by katarinabatina** [comment]
@1aurabrown yea yea the issue is closed I wanted to double check tho cause I wasn't sure if ipad got done since it was a combo issue

**Comment by 1aurabrown** [comment]
Oh yeah. I def did this, should stay closed.

On Mon, Apr 20, 2015 at 21:50, artsy/eigen
<reply@reply.github.com>
wrote:
@1aurabrown [https://github.com/1aurabrown] yea yea the issue is closed I wanted to double check tho cause I wasn't sure if
ipad got done since it was a combo issue

—
Reply to this email directly or view it on GitHub
[https://github.com/artsy/eigen/issues/299#issuecomment-94609695] .[https://github.com/notifications/beacon/ADBlTqjJZCy2w6JT-u1ySOqumhfXbXZ_ks5oBaRygaJpZM4DzQmX.gif]
