### ISSUE TITLE
Fix crash in Artsy.LiveAuctionsSalesPerson.lotViewModelRelativeToShowingIndex(Swift.Int) -> Artsy.LiveAuctionLotViewModelType, line 147

### ISSUE THREAD

**Issue by artsyit** [artsy/eigen#2990]
### Stacktrace ###

<pre>-;Artsy.LiveAuctionsSalesPerson.lotViewModelRelativeToShowingIndex(Swift.Int) -> Artsy.LiveAuctionLotViewModelType;LiveAuctionSalesPerson.swift;147
-;protocol witness for Artsy.LiveAuctionsSalesPersonType.lotViewModelRelativeToShowingIndex(Swift.Int) -> Artsy.LiveAuctionLotViewModelType in conformance Artsy.LiveAuctionsSalesPerson : Artsy.LiveAuctionsSalesPersonType in Artsy;LiveAuctionSalesPerson.swift;134
-;@objc Artsy.LiveAuctionLotCollectionViewDataSource.aspectRatioForIndex(Swift.Int) -> CoreGraphics.CGFloat;LiveAuctionLotCollectionViewDataSource.swift;58
-;Artsy.LiveAuctionFancyLotCollectionViewLayout.(applyFancyLayoutToAttributes in _9C1733ABC9DFD66F67338882E9CCE054)(inout __C.UICollectionViewLayoutAttributes, position: Artsy.(CellPosition in _9C1733ABC9DFD66F67338882E9CCE054)) -> ();LiveAuctionFancyLotCollectionViewLayout.swift;165
-;function signature specialization <Arg[0] = Owned To Guaranteed> of Artsy.LiveAuctionFancyLotCollectionViewLayout.(modifiedLayoutAttributesCopy in _9C1733ABC9DFD66F67338882E9CCE054)(__C.UICollectionViewLayoutAttributes) -> __C.UICollectionViewLayoutAttributes;LiveAuctionFancyLotCollectionViewLayout.swift;146
-;closure #1 (Swift.Int) -> __C.UICollectionViewLayoutAttributes? in Artsy.LiveAuctionFancyLotCollectionViewLayout.layoutAttributesForElementsInRect(__C_Synthesized.CGRect) -> [__C.UICollectionViewLayoutAttributes]?;LiveAuctionFancyLotCollectionViewLayout.swift;77
-;function signature specialization <Arg[0] = Owned To Guaranteed> of generic specialization <[Swift.Int] with [Swift.Int] : Swift.SequenceType in Swift, Swift.IndexingGenerator<[Swift.Int]> with Swift.IndexingGenerator<[Swift.Int]> : Swift.GeneratorType in Swift, Swift.Int, Swift.ArraySlice<Swift.Int>, __C.UICollectionViewLayoutAttributes> of (extension in Swift):Swift.SequenceType.flatMap<A>((A.Generator.Element) throws -> A1?) throws -> [A1];LiveAuctionFancyLotCollectionViewLayout.swift;0
-;function signature specialization <Arg[0] = Dead> of Artsy.LiveAuctionFancyLotCollectionViewLayout.layoutAttributesForElementsInRect(__C_Synthesized.CGRect) -> [__C.UICollectionViewLayoutAttributes]?;LiveAuctionFancyLotCollectionViewLayout.swift;73
-;@objc Artsy.LiveAuctionFancyLotCollectionViewLayout.layoutAttributesForElementsInRect(__C_Synthesized.CGRect) -> [__C.UICollectionViewLayoutAttributes]?;LiveAuctionFancyLotCollectionViewLayout.swift;0</pre>

### Link to HockeyApp ###

* [https://rink.hockeyapp.net/manage/apps/37029/crash_reasons/298058721](https://rink.hockeyapp.net/manage/apps/37029/crash_reasons/298058721)

**Comment by ds300** [comment]
@ashfurrow how was this issue created? Don't think I've seen one of these before.

**Comment by ashfurrow** [comment]
I'm trying to cast my mind way back... the app has the Hockey SDK embedded in it and reports crashes (like we do with Sentry). And then Hockey was configured to open this issue, I think is how that works.
