### ISSUE TITLE
Add shows and magazine to bottom navigation

### ISSUE THREAD

**Issue by katarinabatina** [artsy/eigen#300]
Both of these lead to web/martsy views

![image](https://cloud.githubusercontent.com/assets/6482926/6786702/528ab614-d164-11e4-8d76-2fc5dd329f07.png)

**Comment by orta** [comment]
Know the webpages they link to @katarinabatina ?

**Comment by katarinabatina** [comment]
Opps sorry yes...

shows https://www.artsy.net/shows
Magazine https://www.artsy.net/magazine
