### ISSUE TITLE
other works in show, etc. not formatting correctly on ipad

### ISSUE THREAD

**Issue by katarinabatina** [artsy/eigen#301]
second row should start on the left,

![image](https://cloud.githubusercontent.com/assets/6482926/6790547/cf5bed4c-d17e-11e4-87a0-33c04588bd8a.png)

**Comment by orta** [comment]
hrm, this is an interesting bug, I guess because we've always had 2 columns we've never seen it. 

The collection view layout would need to know if all 4 can be filled, then to do place the cells properly, otherwise to bring them in from the left.

**Comment by orta** [comment]
http://cocoapods.org/pods/ARCollectionViewMasonryLayout

**Comment by alloy** [comment]
As discussed, this requires me to better know ARCollectionViewMasonryLayout, for which I will write a unit test test-suite.

**Comment by 1aurabrown** [comment]
this is the "intended" functionality as i understand it, it just looks really weird with so few artworks. maybe the logic should be updated. as it works now, each new cell is added to the column with the shortest height. If they were assigned by cycling through the columns, you could very well end up with height discrepancies between rows if one row ends up with a bunch of cells that are tall and another ends up with a bunch that are short.

**Comment by alloy** [comment]
Yeah you’re right, I’ve been thinking for a bit whether there are any heuristics we can apply, though, e.g. “when it’s the last entry and the height difference between the shortest entry _plus the last entry’s height_ are within a certain margin of the entries to the left, always left align” ?

And mainly have been trying to think of problems that could run into. My tummy has this feeling it might be an issue when it’s a paginated list and an entry is not really the last entry, but I don’t think that’s actually a problem.

**Comment by orta** [comment]
Perhaps look at "how many items are left" if "how many items are left < columns" then "move to left most item"

**Comment by alloy** [comment]
But you don’t want this to happen:

```
+-------+  +--------------+  +--------------+
|       |  |              |  |              |
|       |  |              |  +--------------+
|       |  |              |                  
|       |  |              |                  
|       |  |              |                  
|       |  +--------------+                  
+-------+                                    
                                             
+-----------+                                 
|           |                                 
| Last Item |                                 
|           |                                 
+-----------+                                 
```

But instead this, right?

```
+-------+  +--------------+  +--------------+
|       |  |              |  |              |
|       |  |              |  +--------------+
|       |  |              |                  
|       |  |              |  +-----------+   
|       |  |              |  |           |   
|       |  +--------------+  | Last Item |   
+-------+                    |           |   
                             +-----------+   

```

**Comment by orta** [comment]
^ this is what it is in the photo

**Comment by orta** [comment]
Making it act like the top image is the point of the issue

**Comment by katarinabatina** [comment]
+1 to Orta

**Comment by 1aurabrown** [comment]
yes, #2 in @alloy's comment is the current behavior, and the behavior in the screenshot. it just looks weird because all the items are very close in height

**Comment by alloy** [comment]
My bad, I should have included this example as well, which is what is happening in the screenshot:

```
+-------+  +------------+  +-------------+
|       |  |            |  |             |
|       |  |            |  |             |
|       |  |            |  |             |
|       |  |            |  |             |
|       |  |            |  |             |
|       |  |            |  +-------------+
+-------+  +------------+                 
                           +-----------+   
                           |           |   
                           | Last Item |   
                           |           |   
                           +-----------+   

```

My idea with the heuristic was that this difference between the total height of the last item and the one above it is way too much. Whereas in my previous comment I think you do want the latter, no?

**Comment by orta** [comment]
hah, yeah, this is the core crux of the matter. Wanna hangout, this is complex?

**Comment by alloy** [comment]
Put differently, how I understand it is that you want an as equal possible distribution over total width and height and otherwise prioritise left-to-right flow.

**Comment by alloy** [comment]
**[ESTIMATE]** Another 0.5 day

**Comment by alloy** [comment]
Here’s an example of a case where previously the trailing artwork would have been added to the right-most column:

![ios simulator screen shot 23 apr 2015 17 56 37](https://cloud.githubusercontent.com/assets/2320/7301372/a11523f0-e9e2-11e4-863f-397c842b6970.png)

**Comment by alloy** [comment]
My estimate was wrong, this ended up taking ~1 day. I was very wrong about how easy it would be to figure out a layout issue (Auto Layout).
