### ISSUE TITLE
Notifications, badges, search

### ISSUE THREAD

**Issue by katarinabatina** [artsy/eigen#307]
This is obviously dependent on having fully functionally notifications but I want to get this story in the repo, don't expect we'll get to it immediately and that we should break this out into smaller stories as we see fit. Represented here is an adjustment to the navigation, removing search and adding in the "bell" which will initially be home to new works by artist you follow but could grow into a cue of other notifications. 

Notification badges, the purple dots (when we have a fully functional notification system) will be a great way for people to engage with different types of content) 

Lastly, moving search to be a global ui piece that lives behind the app, exposed on some views (such as on the home page). I know this is a big ticket item.

It would be great if you guys could help me strategize the roadmap for implementing these changes.
![image](https://cloud.githubusercontent.com/assets/6482926/6809601/c502ead6-d231-11e4-88eb-36e122c754b8.png)

![image](https://cloud.githubusercontent.com/assets/6482926/6809605/cc1c533e-d231-11e4-9dff-2887ac1ef13c.png)

**Comment by katarinabatina** [comment]
I should note this does NOT hold up release of ipad. I image this work begins to happen after we launch.

**Comment by orta** [comment]
Interesting we should probably keep track of the last seen show / mag ( for magazine this would mean doing it natively, probably. )  

Then in the background we can cache the shows and the magazine articles.

**Comment by orta** [comment]
The notifications stuff is a whole ballgame of it's own, we'd need to start making requests to Core once there's an idea of how it will work.

**Comment by katarinabatina** [comment]
What can I do to clarify what we want?

**Comment by orta** [comment]
Hrm, the clarification would be what are the things that you would expect to show in there, at a minimum. E.g:

 * New Artworks by Artists you follow
 * Recommended Artists for you
 * Recommended Shows nearby etc

That gives a sense of what to request in terms of push notifications, and can work from there.

**Comment by katarinabatina** [comment]
@alexanderfabry, please add any stories related to notifications from core team when ready

**Comment by alloy** [comment]
Closing this in favour of #482 and #483.
