### ISSUE TITLE
Bottom bar issues

### ISSUE THREAD

**Issue by ashfurrow** [artsy/eigen#309]
Open artwork, scroll to bottom, verify "contact specialist" exists. Open artwork in room view, close it, scroll back down. The scroll content size seems too small. 

Possibly iOS 7 (SDK)-only.

**Comment by ashfurrow** [comment]
![](http://cdn.memegenerator.net/instances/500x/20617396.jpg)

This is happening on iOS 8 builds, too.

**Comment by ashfurrow** [comment]
Looks like the paging view controller is resizing.

**Comment by ashfurrow** [comment]
_Probably_ has something to do with one of the constraints we're breaking. Related to #237.

**Comment by ashfurrow** [comment]
Could be related to a problem we had previously in the hero units layout. [This SO question](http://stackoverflow.com/questions/17729336/uipageviewcontroller-auto-layout-rotation-issue) helped at the time.

**Comment by katarinabatina** [comment]
Update: this is a problem on all Martsy views as well. After asking them to fix the padding on a few different views I realized the issue wasn't resolved 
![image](https://cloud.githubusercontent.com/assets/6482926/7033728/61a8e890-dd4a-11e4-9a52-54ecf4dd7346.png)

![image](https://cloud.githubusercontent.com/assets/6482926/7033743/7b2b5f8c-dd4a-11e4-99b5-8f11a194b569.png)

**Comment by orta** [comment]
I wonder if this is related to constrains on our fake status bar

**Comment by katarinabatina** [comment]
lol fake status bar?

**Comment by orta** [comment]
yeah, Apple don't really want colour block status bars on iOS7+. 
<-- So this guy had to make one.

**Comment by katarinabatina** [comment]
oh wow, that's crazy

**Comment by alloy** [comment]
@ashfurrow Could this be the same as #507?

**Comment by ashfurrow** [comment]
@alloy Looks likely.

**Comment by alloy** [comment]
Thanks! Gonna close as dupe.
