### ISSUE TITLE
missing show data on show views

### ISSUE THREAD

**Issue by katarinabatina** [artsy/eigen#311]
![image](https://cloud.githubusercontent.com/assets/6482926/6813693/ee9ac1c2-d24d-11e4-99d4-27b27ba4caad.png)

dates of show, gallery address and show blurb (if available) should all be displayed

**Comment by alloy** [comment]
I assume that the copy and layout should look exactly the same as on martsy?

![screen shot 2015-03-26 at 14 03 02](https://cloud.githubusercontent.com/assets/2320/6846753/092c39c0-d3c1-11e4-8ab2-f2343aefd698.png)

**Comment by katarinabatina** [comment]
Yup! Except for the share button (Martsys looks slightly different)

Katarina

**Comment by alloy** [comment]
Aight 👌

**Comment by katarinabatina** [comment]
more clarity for what a show in fair versus not in fair should look like 
![image](https://cloud.githubusercontent.com/assets/6482926/7034217/05d891e2-dd4e-11e4-8339-63e2a3d2dc81.png)
