### ISSUE TITLE
caret overlapping title

### ISSUE THREAD

**Issue by katarinabatina** [artsy/eigen#312]
![image](https://cloud.githubusercontent.com/assets/6482926/6814296/ca9092ce-d253-11e4-8fea-1977dd887307.png)

**Comment by orta** [comment]
*Caret
![Giphy](http://media2.giphy.com/media/M2YOchhMlJnFe/giphy.gif)

**Comment by alloy** [comment]
@katarinabatina I was able to find this on a ‘show’ overview, but not a view that resembles your example. Can you tell me which view this is exactly?

![ios simulator screen shot 26 mar 2015 18 32 17](https://cloud.githubusercontent.com/assets/2320/6852723/b5b8673e-d3e6-11e4-943d-897cd3d9672d.png)

**Comment by alloy** [comment]
Oh, I guess it doesn’t really matter, as the text and chevron are part of the same view class `ARItalicsSerifLabelWithChevron`.

**Comment by alloy** [comment]
I still need to bump the commit of Artsy-UILabels used in Eigen.
