### ISSUE TITLE
Define what's a hybrid app

### ISSUE THREAD

**Issue by dkhamsing** [artsy/eigen#313]
As used in http://artsy.github.io/blog/2015/03/23/artsy-technology-stack-2015/

> Our family of mobile applications includes Artsy for iOS, which is a hybrid app written in Objective-C..

**Comment by ashfurrow** [comment]
Hey! So here's the high-level of what happens:

When you tap a button, the `ARSwitchBoard` turns that into a URL, which it then routes. Routes are [set up at app launch](https://github.com/artsy/eigen/blob/master/Artsy/Classes/Utils/ARSwitchBoard.m#L59) and are responsible for configuring a view controller t be pushed. 

If routing fails (something our app can't handle), then we load a generic web view controller to show that content instead. We do some finicking to remove some chrome from the mobile site and make sure the user is logged in. When a user taps a link in the web view, we intercept it and run it through the switchboard again. This lets users go from Native -> Web -> Native again. 

Does that make sense? Happy to go into more detail and provide clarifications.

**Comment by orta** [comment]
Basecamp talked about how they did it here, https://signalvnoise.com/posts/3743-hybrid-sweet-spot-native-navigation-web-content

**Comment by dkhamsing** [comment]
Thanks @ashfurrow 

What is the percentage of the routes that fail?

**Comment by orta** [comment]
That is a really interesting question, that we don't really have an answer for.

**Comment by dkhamsing** [comment]
Thx guys

**Comment by orta** [comment]
I wrote a blog post about this: https://artsy.github.io/blog/2015/08/24/Cocoa-Architecture-Hybrid-Apps/
