### ISSUE TITLE
Wrong Artwork status

### ISSUE THREAD

**Issue by robertlenne** [artsy/eigen#314]
I just noticed that on the iOS app we are not specifying the artwork status (e.g. 'Not for Sale', 'Sold' etc). I receive inquiries from the app users on works that are marked 'sold' publicly, but because this info is not visible to them on an iPhone, they still inquire. 
An example is this work. 

Can we add availability status to each work on the app?

**Comment by orta** [comment]
I'm on the app, and I'm seeing the sold status. For example "Someone's texture applied on Someone Else"

Do you know of any artworks that exhibit this?

**Comment by stasya** [comment]
@orta e.g. https://www.artsy.net/artwork/bob-thompson-paris-1 does not say 'SOLD'

**Comment by orta** [comment]
perfect @stasya - looks like if we don't show a price, we don't show that section.
