### ISSUE TITLE
Browse section shows artists twice

### ISSUE THREAD

**Issue by katarinabatina** [artsy/eigen#318]
I've had this problem before where certain links from the set would show double on eigen. Any ideas about what the issue might be?

**Comment by katarinabatina** [comment]
link to link set https://admin.artsy.net/set/54fdbf14726169649fca0000

**Comment by 1aurabrown** [comment]
weird, i see it too. will look into it

**Comment by 1aurabrown** [comment]
this was an issue with admin. fixed the set, closing.
