### ISSUE TITLE
Poll auction work price, reserve, etc., during bidding

### ISSUE THREAD

**Issue by katarinabatina** [artsy/eigen#319]

**Comment by orta** [comment]
I can't find anything that implies it polls for updates at all.

**Comment by dblock** [comment]
I've renamed this to "poll auction work price, reserve, etc., during bidding". I think it's a big deal especially as we move towards live auctions. I suggest something that works in decrements, so poll continuously, start waiting for a second or two if no updates seen frequently and always poll continuously within the last few minutes of the auction,

**Comment by alloy** [comment]
@katarinabatina @anipetrov Added this to the milestone, more as a reminder that we need to discuss prioritization of this.

**Comment by devangt** [comment]
polling and live are both implemented. Closing this for now
