### ISSUE TITLE
Use iOS built-in Facebook/Twitter sharing capabilities

### ISSUE THREAD

**Issue by alloy** [artsy/eigen#321]
For instance, this martsy view has Facebook/Twitter links that would be opened in a web browser, it would be nicer to either open the share menu or even better (if possible) immediately show the appropriate sharing option.

![ios simulator screen shot 27 mar 2015 13 07 53](https://cloud.githubusercontent.com/assets/2320/6867431/95e13a16-d482-11e4-80e8-dac5d46c7de5.png)

![ios simulator screen shot 27 mar 2015 13 10 09](https://cloud.githubusercontent.com/assets/2320/6867434/9d9cea52-d482-11e4-9b1f-5d423f8c6d25.png)

**Comment by orta** [comment]
IMO this is a release blocker, only this and crash fixes should be the requirements for the next release now.

We can have it do the share-sheet with the URLs when you tap them,

**Comment by alloy** [comment]
Closed by #333.
