### ISSUE TITLE
[iPad] ARExternalWebBrowserViewController does not rotate orientation

### ISSUE THREAD

**Issue by alloy** [artsy/eigen#322]
Currently [this is set to never auto rotate](https://github.com/artsy/eigen/blob/2e814fc6216f88c61a2373a2e35db369695e6dba/Artsy/Classes/View%20Controllers/ARExternalWebBrowserViewController.m#L83), which means that martsy views will load with the expected orientation yet not rotate when already loaded.

![ios simulator screen shot 27 mar 2015 13 23 00](https://cloud.githubusercontent.com/assets/2320/6867644/6863c368-d484-11e4-9d16-570bcd5c8db1.png)

@1aurabrown Can we just change this to the following or are there other considerations to take into account?

```objc
- (BOOL)shouldAutorotate
{
    return [UIDevice isPad];
}
```

**Comment by orta** [comment]
@alloy that solution should be fine :+1:

**Comment by alloy** [comment]
Alrighty then
