### ISSUE TITLE
/Magazine isn't a public link yet on force

### ISSUE THREAD

**Issue by katarinabatina** [artsy/eigen#329]
we've moved mag into the bottom nav but we haven't shipped magazine yet (thought this was going to be done by the time we shipped). @craigspaeth we were hoping to ship this release to the app store on Monday, any insights into when we are launching Magazine? 

@alloy lets hold of shipping the release until we have a firm answer 

Thanks

**Comment by orta** [comment]
That means that it'd be _at least_ a week on monday on the app store

**Comment by katarinabatina** [comment]
a week *from Monday that it would actually be approved by Apple correct? Meaning if we were to submit on Monday we'd most likely see it in the store on April 6th.

**Comment by orta** [comment]
yes

**Comment by orta** [comment]
We can also make it developer release if needs be, so that we can choose when we want to release, but this is a great update, I want it out ASAP

**Comment by orta** [comment]
This is not a problem.
