### ISSUE TITLE
Improving speed of martsy views

### ISSUE THREAD

**Issue by katarinabatina** [artsy/eigen#330]
Now that /shows and /magazine are in the bottom nav, I was wondering if there was anything fancy we could do to pre-load the content before the user taps shows or mag? Similar to what we did with the explore tab.

**Comment by orta** [comment]
This is an interesting idea, we could grab those pages before-hand in the background to warm the cache.given their high likelihood they'll be glanced at.

**Comment by katarinabatina** [comment]
what's your guess on difficulty level d:1,2,3?

**Comment by alloy** [comment]
This should be tied together with the fair content preloading, because caching content isn’t an easy feat and I want to discuss this with e.g. @dblock as well.

**Comment by orta** [comment]
then we make it a d:3

**Comment by alloy** [comment]
:+1:

**Comment by alloy** [comment]
I think that this is sufficiently handled by #351 for now.
