### ISSUE TITLE
Sort Artists in favorites alphabetically

### ISSUE THREAD

**Issue by katarinabatina** [artsy/eigen#331]
I am not sure how they are currently sorted, maybe by most recently added? I think it's easier to understand if they are sorted alphabetically
![image](https://cloud.githubusercontent.com/assets/6482926/6882841/df81e61a-d569-11e4-9764-b781f59ab5fb.png)

**Comment by orta** [comment]
They come in in the order that we get them, which is likely to be the order in which you favourited them. In order to do this, we'd need to see if the API supports iterating through the list a-z because we get them 10 artists at a time.

**Comment by sarahscott** [comment]
@alloy  What do you think of this for @mennenia and I?

**Comment by alloy** [comment]
Yeah that could be a good one, you'll need to check if the API supports this.
