### ISSUE TITLE
Re-route any force signups to native sign up

### ISSUE THREAD

**Issue by katarinabatina** [artsy/eigen#332]
This is a screen shot from /auctions in eigen on ipad. It's a force view so when I tap signup instead of poping up our native sign up it goes through the entire force onboarding and drops by back on the force home page (which is confusing)

sign up
![image](https://cloud.githubusercontent.com/assets/6482926/6882928/ecd182f4-d56d-11e4-83cb-cc8ebd70651b.png)

onboarding
![image](https://cloud.githubusercontent.com/assets/6482926/6882931/00b89de8-d56e-11e4-8088-f6bc5f24f595.png)

Completed onboarding, get thrown back to home page
![image](https://cloud.githubusercontent.com/assets/6482926/6882936/12612380-d56e-11e4-8a4c-d5b5ef03e1b1.png)

**Comment by 1aurabrown** [comment]
requires a change to force, probably nothing for us to do as I believe the signup and login routes are already supported in our router.

**Comment by alloy** [comment]
Perfect :+1:

**Comment by alloy** [comment]
@1aurabrown This was fixed, right?

**Comment by 1aurabrown** [comment]
should be fixed by https://github.com/artsy/force/pull/2608

**Comment by 1aurabrown** [comment]
just merged damon's pr, so i'm closing. the change should existing on staging.
