### ISSUE TITLE
Swiping through tabs doesn’t work.

### ISSUE THREAD

**Issue by alloy** [artsy/eigen#339]
I just came across code in [ARTabContentView](https://github.com/artsy/eigen/blob/2e814fc6216f88c61a2373a2e35db369695e6dba/Artsy/Classes/Views/ARTabContentView.m#L24-L30) that makes it seem like swiping through tabs should be possible, however, I’m unable to trigger this at all. Is this supposed to be working?

**Comment by orta** [comment]
This is disabled in the main tabs for eigen, they are used in energy.

**Comment by alloy** [comment]
Okidoki!
