### ISSUE TITLE
Improve UI/UX for sharing magazine content.

### ISSUE THREAD

**Issue by alloy** [artsy/eigen#342]
#333 fixed #321 by showing the share panel, but this still feels a tad awkward. I think it should:

* don’t show the Facebook/Twitter icons in the web view, instead show an Eigen ‘share’ button: 
![screen shot 2015-03-31 at 18 30 03](https://cloud.githubusercontent.com/assets/2320/6923789/39c5551e-d7d4-11e4-8915-b85f90e6891c.png)

* Eigen intercepts that link and passes the href to the share panel

This way the user only gets to see the Facebook or Twitter share options once and also only those that actually have enabled in their iOS system settings.

@orta @katarinabatina Do you agree?

**Comment by orta** [comment]
we should make @craigspaeth do this instead in force IMO, us hijacking those buttons is likely to bite us later

**Comment by orta** [comment]
@craigspaeth just made share that button ^

**Comment by alloy** [comment]
@orta @craigspaeth Where’s that at?

**Comment by craigspaeth** [comment]
The share buttons on Force article pages are going to be under experiment soon. They will most likely not look like the generic share buttons on Eigen and abroad, so dunno how much we can help here. Feel free to follow up with Robert/Owen for more details.

**Comment by alloy** [comment]
Moving this to #433.
