### ISSUE TITLE
[RFC] New dependency: Easy Peasy State Management 

### ISSUE THREAD

**Issue by damassi** [artsy/eigen#3442]
#### New Dependency
Name: `easy-peasy` 
URL: https://github.com/ctrlplusb/easy-peasy

#### Focus
Easy Peasy is a popular state management solution built on battle tested redux. It provides a modern API and comes with everything one needs to quickly manage inter-component state without needing to write everything from scratch. It has first class TypeScript support, gives us access to the redux middleware system, comes with an immer-based state update patterns, and proves some excellent (and simple) abstractions around observing actions within a system and acting on them without having to write mountains of glue code.

Example from docs: 

```jsx
const store = createStore({
  todos: {
    items: ['Create store', 'Wrap application', 'Use store'],
    add: action((state, payload) => {
      state.items.push(payload)
    })
  }
});

function App() {
  return (
    <StoreProvider store={store}>
      <TodoList />
    </StoreProvider>
  );
}

function TodoList() {
  const todos = useStoreState(state => state.todos.items)
  const add = useStoreActions(actions => actions.todos.add)

  return (
    <div>
      {todos.map((todo, idx) => <div key={idx}>{todo}</div>)}
      <AddTodo onAdd={add} />
    </div>
  )
}
```

Going forward Eigen would benefit from a consistent, hooks-based batteries-included state management pattern.

#### Check List
- [x] Have read over the source code, and we can maintain it
- [x] Has had a release in the last year, or looks done and stable

#### Alternatives
There are quite a few alternatives in the react state management space. We could use redux directly, but the common complaint is that it's too verbose. We could also use react's context directly, but that would mean a lack of consistency, needing to hand-roll perf optimizations, no middleware, etc.

**Comment by pvinis** [comment]
I don't know if this was discussed or needed or whatever, but I think it's nice to keep our tools fresh. Besides easy-peasy, I've used https://redux-toolkit.js.org/api/createSlice which is a breath of fresh air after "regular" redux. It makes handling redux way easier, so I'd like to nomiate that as one of the alternatives, *but why do we need redux?*

**Comment by damassi** [comment]
> Why do we need redux?

Because we have a sophisitcated application, and rather than rewriting state managment every time we need manage state we can look at things that the team has worked with in the past, has a vibrant healthy ecosystem, and a good track record at scale.

More specifically to product needs, this came up in response to a pretty massive app we're about to undertake on consignments that has a lot of global state:

<img width="1182" alt="Screen Shot 2020-06-11 at 10 09 10 AM" src="https://user-images.githubusercontent.com/236943/84418531-3212ea80-abcc-11ea-9ef4-fabb2cc066ee.png">

**Comment by jonallured** [comment]
Something that's unclear to me is the relationship between state and routes. My feeling is that Formik can handle the state on the forms and routes can implicitly handle the state of which thing to show. I'm still struggling to see which bits of state easy-peasy will help with.

**Comment by damassi** [comment]
Formik will indeed handle form state, but we will need to coordinate things from a higher point of view; for example, locking and unlocking route navigation, saving and restoring form state, and in general thinking about things from a global top down perspective.

**Comment by pepopowitz** [comment]
> opportunity to establish some state patterns going forward for other work 

Is the idea of this proposal that we would use `easy-peasy` for _all_ state management moving forward in eigen, or just in complex cases? I still believe that the built-in react solutions for state management are suitable for 90% of cases, _especially_ react Context. 

There is complexity in redux-based solutions, and a learning curve for the team - it's a different way of thinking. The benefits it brings are not free. Having managed apps that were built entirely on redux for state management, my experience was that the amazing debugg-ability you get from redux tools was often only necessary because of the fact that state management had become so much more complex.

**Comment by damassi** [comment]
@pepopowitz - This RFC is for `easy-peasy` to be added as a dependency. There is inherent bias around Redux that I would like to avoid as mentioned above. Please see docs and an example implementation in the description of the RFC.

**Comment by ashfurrow** [comment]
Thanks for the details Chris. I think using easy-peasy makes sense in the abstract, though I do share some questions from Jon about how _specifically_ it would be helpful. Eigen doesn't really have a lot of global state _to_ manage in between most screens; while this new Sell app might be an exception, adding any dependency beyond React would increase the barrier to entry for engineers contributing to that code. As Steve said, these abstractions do have a cost, and I want to be sensitive to it in the long run.

To help me understand where easy-peasy will help us, could you give an example from the Figma designs where easy-peasy would help manage state? I know React Context isn't an ideal API, but I'm curious about comparing how it would work in that example.

**Comment by jonallured** [comment]
I guess where I'm landing on this is that I'm not convinced we have a situation where the use of easy peasy is warranted. I'm not saying that easy peasy isn't a great lib, just that while spiking and tinkering with this project I have not seen problems for which it is required.

**Comment by damassi** [comment]
> Eigen doesn't really have a lot of global state to manage in between most screens

This isn't about just managing state across screens, its about intra-component-tree communication. Doing a search in Eigen, there's twelve uses of `createContext`, and thus twelve separate API's for managing global component tree state. 

> I know React Context isn't an ideal API

It's not that its not ideal, it's that it's a primitive that provides _no API_ requiring devs to create their own each time its used, which in turn increases complexity across the app. It also requires that we manage performance on our own, versus intelligent (invisible) optimizations built in at the library level. 

> could you give an example from the Figma designs where easy-peasy would help manage state

It's about orderly control flow. Mentioned above:

> and in general thinking about things from a global top down perspective via an orderly action-based flow that genericises execution across a very wide component tree. Sophisticated user flows in particular benefit from top-down thinking.

Is the form complete? Check. Navigation is unlocked. Back button press? Are you sure? Dispatch action to show confirm? Confirm. Dispatch action to navigate. I can continue elaborating. All of these things sit centralized in one location and conform to a consistent pattern.

Additionally, `easy-peasy` allows for the ability to easily listen for events being dispatched within the system. For example: user has created a new artwork. The artwork list view then receives a notification to perform a relay refetch after our navigation system, which was also listenting for this event, transitions to the artwork list view page. All of these abstractions and patterns -- which we'll have to write from scratch -- come for free with easy-peasy, in a very good / simple API.

**Comment by ashfurrow** [comment]
Okay, thanks for elaborating. 

I'm just trying to make sure I understand the trade-offs here. We have had a conservative policy around adding new iOS dependencies for several years and it's helped us prevent what happened in the native side of the app: multiple dependencies to do the exact same thing, because the team didn't communicate&socialize the benefits/capabilities of new dependencies. 

I'm not saying easy-peasy is a bad solution – it sounds like a nice library, actually! I just want to make sure that _I_ understand its value and tradeoffs because my team will be responsible for it in the long term. Am I making sense?

**Comment by damassi** [comment]
That makes sense! 

When we write `createContext`, instantly there's a need to a) write boilerplate; and b) write correct types; and c) manage performance manually. By introducing a formal "batteries included" state management solution into Eigen we get a few wins in a few different dimensions, even for small things.

**Comment by ds300** [comment]
Aside from this new Consignments work, we'll need to implement a global app state for auth, lab options, etc, as soon as we take the plunge on Android in Q3. I think easy-peasy would be a perfect fit for that. Its 'batteries-included redux' approach seems great to me. It solves most of the problems I had with redux back in 2016-2017 and then some, and I'm confident it would provide a very robust foundation for building state-heavy features going forward.

I see no reason not to adopt it. In retrospect I kinda wish I had suggested it to @ashleyjelks back when she started working on the collection filters since she ended up having to reinvent certain patterns not provided by useReducer that easy-peasy makes... well... easy-peasy.

**Comment by pvinis** [comment]
I think it will be a good addition, and like you say Chris. My initial concern was I guess me being afraid of having it "too easy" to just use easy-peasy/redux for all kinds of state management. I think with relay, things are pretty alright. I agree the Context parts would become easier, I'm all for it. I just want to make sure or be clear that we will not start mixing these two willy-nilly until we end up with a tangled mess of data living in random places and getting fetched from all over the place, and having to manage that.

If we stick to using easy-peasy/redux for the purposes of managing state, as in flows, (navigation, notifications, consistent and common api for all our stuff, basically something more [like a state machine](https://stackoverflow.com/a/54521035/377456)) rather than state, as in data, (fetched data etc) then merge this already 😅.

**Comment by ashfurrow** [comment]
Okay, thanks for the discussion so far everyone! Here's a recap of what I have learned:

- Eigen could already benefit from a better way to manage global state than React Context, and this need will only increase over time.
- easy-peasy seems like a good solution for managing global state.
- For the immediate need, Consignments in specific could benefit from this solution.

Therefore, I think:

- We need to answer @pepopowitz's question: is easy-peasy is the go-to solution for _all_ state management in Eigen, or if it should be just for _complex_ state? I'm curious to hear what others think. We should [document our decision here](https://github.com/artsy/eigen/blob/master/docs/map_to_the_app.md).
- We can accept this RFC. I'm satisfied this makes sense, but I'm still open to hearing from those who disagree.
- To help facilitate this transition, we should convert (at least some of) the existing uses of `createContext` to use easy-peasy. Ideally in a group, maybe a Knowledge Share or a Lunch & Learn. It's really important to me that we socialize this change and make sure everyone is supported here. @ds300 do you think that the filters would be a good place to start, or should we begin smaller?

Are there any other questions/concerns anyone has? This is the exact right time to bring them up 🙌

**Comment by pvinis** [comment]
>     * To help facilitate this transition, we should convert (at least some of) the existing uses of `createContext` to use easy-peasy. Ideally in a group
+10000000 (also, I'd like to be there too)

**Comment by jonallured** [comment]
Some further comparisons of how easy-peasy vs another approach compare here:

https://github.com/artsy/eigen/pull/3451#issuecomment-643271041

**Comment by damassi** [comment]
>  @ds300 do you think that the filters would be a good place to start, or should we begin smaller?

I was thinking the same thing, that that's a great first place. I think the LOC count will nicely condense too.

**Comment by ds300** [comment]
agreed. refactoring the filters would be a great place to start since the architecture is so similar!

**Comment by sweir27** [comment]
As I was reading this I was _also_ going to suggest the filters as a place that could have benefitted from a library like easy-peasy! Happy to help out with that migration, sounds fun. 😄 

I don't have too much to add but it will certainly be nice to have a preference when the need does arise (which it certainly will) for more complex state management. Easy-peasy seems like a good choice!

**Comment by ashfurrow** [comment]
Right, I should have specified _shared_ state. That makes sense to me. Are there any circumstances that we might want to use contexts instead?

**Comment by damassi** [comment]
I would imagine a context being used in a situation that may grow into a library that can be extracted where we'd want to keep the external dependencies low. (Though even in that case, personally, I'd rather use a proper state management solution than roll my own.)

Mentioned above, every time `React.useContext` is written it means a dev is creating their own custom API for shared state. Unless there's some truly crazy unexpected thinking involved, the API created for that `useContext` call will look very, very similar to what we'd get out of the box with easy-peasy, only more complicated and requiring more lines of code. For maintainability through time, less is more.

**Comment by damassi** [comment]
@pvinis 

> I just want to make sure or be clear that we will not start mixing these two willy-nilly until we end up with a tangled mess of data living in random places and getting fetched from all over the place, and having to manage that.

Very much agree 👍 Damon mentioned at his last gig they were storing their Apollo store in Redux creating a real mess of things. That's an architectural design problem that could manifest in any number of ways, and has nothing to do with shared state management. Relay is Relay and shared state is shared state. (And in any case, Relay has its own global context.)

**Comment by damassi** [comment]
Closing with `Adopted`.

We'll be using this first in the incoming MyCollection Eigen app and then migrating collection filters over to the new setup. 

Thanks everyone for your input 👍

**Comment by damassi** [comment]
## Resolution
We decided to do it.

## Level of Support
3: Majority acceptance, with conflicting feedback.

#### Additional Context:
Some people were in favor of it, but others felt that a library that used redux might be overkill.

## Next Steps
Being implemented in the new MyCollection app in Eigen. Collection filters will be refactored.

#### Exceptions
No exceptions.
