### ISSUE TITLE
[RFC] New dependencies: Formik and Yup

### ISSUE THREAD

**Issue by jonallured** [artsy/eigen#3452]
### New Dependencies

Name: Formik

URL: https://github.com/jaredpalmer/formik

Name: Yup

URL: https://github.com/jquense/yup

### Motivation

Hot on the heels of https://github.com/artsy/eigen/issues/3442, I'd like to formally propose adding Formik and Yup to Eigen. The CSGN team plans to use these two libraries in their work on adding a form for the My Collection project. We'll use Formik to manage the state of the form and author a schema using Yup to validate user input.

### Check List

- [x] Have you read over the source code?
- [x] Has had a release in the last year, or looks done and stable?
- [ ] Could you fit this codebase in your head after reading the source?
- [x] Is this the stand-out obvious answer to a particular domain problem?
- [ ] Do you expect your team to be the only people who know about this dependency?
- [x] Is this obviously being used in production by the maintainers? Is it battle-tested?
- [ ] Does our bundle already include a (transitive) dependency that solves the problem and could we use that instead?
- [ ] Do you feel well versed in the domain of this dependency and/or could you maintain it if that needs to become an option?

### Alternatives to Formik

I confess I have not done an exhaustive audit of alternatives to Formik, but some initial findings after clicking the top search result for "formik alternatives" lead to this page:

https://stackshare.io/formik/alternatives

So there are certainly other ways to deal with forms. If people have experience with any of these and would like to chime in, that would be welcome! 🤗 

### Alternatives to Yup

The most basic alternative to Yup is not using schema-based validation at all and instead providing Formik a validation function instead. Past experience in Volt and the Artwork form there leads me to advise against that. I believe starting with schema-based validation is a best practice and better sets up the team to deal with changing requirements.

But like with Formik, there are other libs for this:

https://nodejs.libhunt.com/yup-alternatives

And if there are experiences people want to share, I'm all ears.

**Comment by damassi** [comment]
@jonallured might be worth mentioning in the "Why" how these things are already extensively battle tested in the artsy ecosystem via Force and Volt (and likely a few other spots as well).

**Comment by jonallured** [comment]
Yeah, what @damassi said! We've used the heck out of these tools in Volt and I'm super happy with them.

**Comment by pvinis** [comment]
I've used both and I was happy with them.

**Comment by ashfurrow** [comment]
Seems good – we're already using these at Artsy so expanding their use into Eigen helps bring the app closer to our existing shared tooling 👍

**Comment by damassi** [comment]
Cool! I'll be pulling this in to Eigen today.

**Comment by jonallured** [comment]
Seems like we're agreed so I'm going to close this as `adopted`. Thanks all!
