### ISSUE TITLE
ability to switch between staging and production facebook app id's

### ISSUE THREAD

**Issue by 1aurabrown** [artsy/eigen#35]
Right now, the production app id is in our info.plist. This is the id we want to ship with our app. In our cocoapods keys, I think we're using the staging app id. Ideally we should be able to switch between the two app ids at runtime, specifically when invoking the dev menu and switching between artsy's staging and production servers. 

I think @ashfurrow's auth pod will solve this but i'm putting this issue here for good measure so we don't forget that this is an issue.

**Comment by katarinabatina** [comment]
I'm going to take a wild guess and say this isn't relevant anymore but @mennenia can you confirm? If so can you close?

**Comment by mennenia** [comment]
I don't think this an issue anymore.
