### ISSUE TITLE
Loading Martsy views is all or nothing and feels very slow

### ISSUE THREAD

**Issue by dblock** [artsy/eigen#351]
been playing with beta, browse and shows feel extremely slow (LTE connection), ten seconds for every page. It snaps in once fully loaded. I think for web content it needs to work more like a web page and load progressively.

**Comment by alloy** [comment]
Good point :+1:

**Comment by orta** [comment]
Would like to see this linked to https://github.com/artsy/eigen/issues/288 too

**Comment by alloy** [comment]
Adding #288 to this.

**Comment by alloy** [comment]
**[ESTIMATE]** 1 day

**Comment by alloy** [comment]
@craigspaeth @dblock Filed the following ticket about some experience optimising https://github.com/artsy/microgravity/issues/871
