### ISSUE TITLE
[RFC] New Dependency: `relay-hooks`

### ISSUE THREAD

**Issue by pvinis** [artsy/eigen#3562]
### New Dependency

Name: `relay-hooks`

URL: https://github.com/relay-tools/relay-hooks

### Motivation

We use relay with `react-relay` already, and it works great. We use `createFragmentContainer` and `QueryRenderer` to make our components.

We already use hooks if a bunch of places and we are moving towards them more and more with new code.

`relay-hooks` is the bridge of these two "worlds". It provides hooks like `useFragment` and `useQuery` that replace the functions I mentioned earlier. This makes our components cleaner. We create a component and use hooks to connect it with relay, rather than having relay create and manage all that for us.

Look at this:
```
export const ViewingRoomQueryRenderer: React.FC<{ viewingRoomID: string }> = ({ viewingRoomID }) => {
  return (
    <QueryRenderer<ViewingRoomQuery>
      environment={defaultEnvironment}
      query={graphql`
        query ViewingRoomQuery($viewingRoomID: ID!) {
          viewingRoom(id: $viewingRoomID) {
            ...ViewingRoom_viewingRoom
          }
        }
      `}
      cacheConfig={{ force: true }}
      variables={{
        viewingRoomID,
      }}
      render={renderWithLoadProgress(ViewingRoomFragmentContainer)}
    />
  )
}
```
where our component is basically a relay component that we customize and adjust using the props.

Now look at this:
```
const query = graphql`
  query ViewingRoomQuery($viewingRoomID: ID!) {
    viewingRoom(id: $viewingRoomID) {
      ...ViewingRoom_viewingRoom
    }
  }
`

export const ViewingRoomQueryRenderer: React.FC<{ viewingRoomID: string }> = ({ viewingRoomID }) => {
  const { props, error } = useQuery(query, { viewingRoomID }, { networkCacheConfig: { force: true } })


  if (props && props.viewingRoom) {
    return <ViewingRoomFragmentContainer viewingRoom={props.viewingRoom} />
  }
  if (error) {
    throw error
  }

  return <LoadingScreen />
}
```
where our component is actually our code, and we control the flow from what we get from the hook.

The biggest changes here are that `environment={defaultEnvironment}` is not part of the component any more, it is now a Context from `RelayEnvironmentProvider` that we add when registering the screens [here](https://github.com/artsy/eigen/blob/2233fe6f91d06f8b519ee8f48b0f412efffbd798/src/lib/AppRegistry.tsx#L283), and that we don't need to use the `render` prop to have loading animations and placeholders, we can now just render the actual loading or placeholder components, so instead of `render={renderWithLoadProgress(ViewingRoomFragmentContainer)}` we can just use `return <LoadingScreen />` at the bottom of our component.

Of course, adding this dependency does not mean we will rewrite all the relay components to use hooks, but it makes it possible to start using the relay hooks.

### Check List

- [X] Have you read over the source code?
- [X] Has had a release in the last year, or looks done and stable?
- [ ] Could you fit this codebase in your head after reading the source?
- [ ] Is this the stand-out obvious answer to a particular domain problem?
- [ ] Do you expect your team to be the only people who know about this dependency?
- [ ] Is this obviously being used in production by the maintainers? Is it battle-tested?
- [ ] Does our bundle already include a (transitive) dependency that solves the problem and could we use that instead?
- [ ] Do you feel well versed in the domain of this dependency and/or could you maintain it if that needs to become an option?

### Alternatives

N/A

### Notes

This was already added in [this PR](https://github.com/artsy/eigen/pull/3457) while I was trying to make pagination work for the Viewing Room list, and it made my life easier. I added it as a test and it ended up helping. You can see it used [here for useQuery](https://github.com/artsy/eigen/blob/master/src/lib/Scenes/ViewingRoom/ViewingRoomsList.tsx) and [here for usePagination](https://github.com/artsy/eigen/blob/master/src/lib/Scenes/ViewingRoom/Components/ViewingRoomsListItem.tsx).

I'm sorry for making the RFC after the fact.

**Comment by ashfurrow** [comment]
Yeah! Looks good to me. I like the new hooks-based API; `usePagination` especially reads as a lot cleaner 👍

**Comment by ds300** [comment]
Yeah these hooks seem great. They make the code quite a bit cleaner, especially now that we won't need to create fragment containers as separate exports. :+1:

**Comment by damassi** [comment]
@dzucconi and I were just talking about getting these into Force, too, so nice and timely @pvinis 👍

**Comment by damassi** [comment]
One thing to note @pvinis is that relay [already supports hooks](https://relay.dev/docs/en/api-reference#relay-hooks) -- the thing is, hooks support was considered experimental, which led to the `relay-hooks` package. It would be worth researching if this is still the case, or if the latest version of Relay (v10) brings them out into the 🌤️.

**Comment by damassi** [comment]
Ah, yup, still experimental: https://github.com/facebook/relay/releases/tag/v10.0.0

**Comment by pvinis** [comment]
We did try it out with matt, importing from react-relay/hooks. Some were missing, some args were different, and most places seem to suggest relay-hooks is the package to go, until they are officially provided.

**Comment by pvinis** [comment]
One thing to note that came up today, is that when we mix components with hooks and components with `create*`, they might not see the relay environment. Something like that happened [here](https://github.com/artsy/eigen/pull/3572/files#diff-eff39aecfd3133de5143cce9401d6adc) and we "solved" it by just using the component before it was wrapped in the `createFragmentContainer` and not masking.

**Comment by pvinis** [comment]
## Resolution
We agree to add it. Thanks everyone for the feedback.

## Level of Support
2: Positive feedback.

## Next Steps
It's already added.
