### ISSUE TITLE
Add conditions of sale link to Artworks up for Auction, change how auctions work to how bidding works

### ISSUE THREAD

**Issue by katarinabatina** [artsy/eigen#357]
On artworks that apart of an auction...

we need to add a conditions of sale link and we need to change the current "how auctions work" to "how bidding works"
![image](https://cloud.githubusercontent.com/assets/6482926/7048520/873794ac-dde1-11e4-9bb3-f4054e7ba7a3.png)

**Comment by orta** [comment]
( could they go horizontally? )

**Comment by katarinabatina** [comment]
not enough room :/

**Comment by katarinabatina** [comment]
link for conditions of sale 
https://m.artsy.net/conditions-of-sale

**Comment by 1aurabrown** [comment]
I'm going to estimate that this will take very little time, like an hour.

**Comment by 1aurabrown** [comment]
I usually spend more time writing tests than I do making changes like these, so that may change things.

**Comment by 1aurabrown** [comment]
@katarinabatina "How bidding works" should be all lowercase like in the image?

**Comment by 1aurabrown** [comment]
Also, is conditions of sale something that should be present on all works that are for sale?

**Comment by 1aurabrown** [comment]
@katarinabatina sorry for all the questions, but do you happen to know the web url for the conditions of sale text?

**Comment by katarinabatina** [comment]
@1aurabrown 
"How Bidding Works" is fine (there are inconsistencies across the site but lets just do it this way. 

The conditions of sale only applies to auction works as far as I know 

this link https://www.artsy.net/conditions-of-sale

**Comment by alloy** [comment]
> I usually spend more time writing tests than I do making changes like these, so that may change things.

@1aurabrown How did this unfold? :)

**Comment by 1aurabrown** [comment]
It took an hour or possibly less, with me getting distracted from time to time. There was no need to write new tests, just update snapshots.

**Comment by alloy** [comment]
Nice :+1:
