### ISSUE TITLE
Verify Facebook Login on current release build

### ISSUE THREAD

**Issue by orta** [artsy/eigen#360]

**Comment by alloy** [comment]
Works with latest beta :+1:

**Comment by alloy** [comment]
In the current App Store version you are presented with an in-app modal window that only shows a spinner, this might be the issue that was reported to Carter.

![img_0668](https://cloud.githubusercontent.com/assets/2320/7089163/1f978ed2-df9a-11e4-8751-f02752e37ef7.png)

**Comment by alloy** [comment]
In the 1.8.0 beta you are simply sent to Safari, like the Twitter auth already does in the current App Store release.
