### ISSUE TITLE
[dev] Add option to sign-out

### ISSUE THREAD

**Issue by alloy** [artsy/eigen#361]
To be able to verify all authentication providers you need to be able to sign-out. Currently you can sign-out as a side-effect of switching to staging/production, but that requires 2 times switching (and restarting app) to get back to the same environment (staging/production). So it would be nice if there were an option to just sign-out.

**Comment by orta** [comment]
There should be a log out button @1aurabrown ?

**Comment by 1aurabrown** [comment]
There is also a log out button in the dev menu

On Fri, Apr 10, 2015 at 11:11 AM, Orta <notifications@github.com> wrote:

> There should be a log out button @1aurabrown
> <https://github.com/1aurabrown> ?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/artsy/eigen/issues/361#issuecomment-91588051>.
>



-- 

[A.]


Laura Brown

Artsy <http://artsy.net/>

laura@artsy.net <caroline@artsy.net>

**Comment by alloy** [comment]
I R BABOON.
