### ISSUE TITLE
bundle install --without development distribution Fails

### ISSUE THREAD

**Issue by benjamin-daniel** [artsy/eigen#3646]
Running 'bundle install --without development distribution' gives this error: 
An error occurred while installing json (1.8.6), and Bundler cannot
continue.
Make sure that `gem install json -v '1.8.6' --source 'https://rubygems.org/'`
succeeds before bundling.

In Gemfile:
  second_curtain was resolved to 0.6.0, which depends on
    aws-sdk-v1 was resolved to 1.67.0, which depends on
      json

**Comment by ashfurrow** [comment]
Thanks for the issue! Which version of Ruby are you using? You can check with `ruby -v`. If you're using system Ruby, which version of macOS are you using?

**Comment by benjamin-daniel** [comment]
Thanks for answering so fast, I use: 
ruby 2.3.7p456 (2018-03-28 revision 63024) [universal.x86_64-darwin18]

**Comment by ashfurrow** [comment]
Ahh gotcha. Can you try with Ruby 2.6.0 or higher? It's what we're using.

**Comment by benjamin-daniel** [comment]
Thanks
