### ISSUE TITLE
Rotation does not set a new height constraint on embedded model view controllers 

### ISSUE THREAD

**Issue by orta** [artsy/eigen#368]
To reproduce:

Go to an Artwork with multiple sections of related work in landscape, rotate the device once there are works in the related etc. See that the collections are cropped.

**Comment by alloy** [comment]
**[ESTIMATE]** 0.5 day

**Comment by 1aurabrown** [comment]
i've seen this before and thought it was fixed a long time ago, but it's possible things changed since then

**Comment by alloy** [comment]
Seeing as this is probably an issue related to auto-layout, I’m gonna guess that it’s not that simple a matter. So I’m adjusting the estimate:

**[ESTIMATE]** 1 day

**Comment by 1aurabrown** [comment]
1 day sounds accurate to me
