### ISSUE TITLE
Current page does not update correctly when user clicks on page control

### ISSUE THREAD

**Issue by feralbob** [artsy/eigen#369]
![eigen_page_control](https://cloud.githubusercontent.com/assets/8114/7108789/c3501152-e166-11e4-955a-d5873f8c91b2.gif)

From the docs

>When a user taps a page control to move to the next or previous page, the control sends the UIControlEventValueChanged event for handling by the delegate. The delegate can then evaluate the currentPage property to determine the page to display. The page control advances only one page in either direction.

**Comment by orta** [comment]
Thanks!

**Comment by alloy** [comment]
Fixed by #420.
