### ISSUE TITLE
Add thumbnail install image to art fair exhibitor feed

### ISSUE THREAD

**Issue by nsimmons206** [artsy/eigen#371]
When a fair booth has install shots, take the first image and put it into a thumbnail that is surfaced in the various exhibitor feeds. 
![fair_subscriberupgrade_mobile_fullspec_01](https://cloud.githubusercontent.com/assets/8950911/7145314/6729975a-e2b9-11e4-9637-59713bceea8e.jpg)
![fair_subscriberupgrade_mobile_01](https://cloud.githubusercontent.com/assets/8950911/7145317/6c0bb910-e2b9-11e4-8ac9-88bb1ee76162.jpg)

**Comment by orta** [comment]
I'm not sure these are native ATM

**Comment by katarinabatina** [comment]
@nsimmons206 this is an issue for microgravity
