### ISSUE TITLE
iOS 8 -- api deprecation warnings

### ISSUE THREAD

**Issue by 1aurabrown** [artsy/eigen#376]
I'm seeing warnings for the following deprecations (and some other issues):
- [ ] 'UIRemoteNotificationTypeBadge' is deprecated: first deprecated in iOS 8.0 - Use UIUserNotificationType for user notifications and registerForRemoteNotifications for receiving remote notifications instead. -- these are found in a few places in tests, for different types of notifications.
- [ ] /Users/laura/artsy/eigen/Artsy/Classes/ARAppDelegate.m:325:10: Comparison of address of 'UIApplicationOpenSettingsURLString' not equal to a null pointer is always true
- [ ] 'searchDisplayController' is deprecated: first deprecated in iOS 8.0 -- in several search views
- [ ] 'interfaceOrientation' is deprecated: first deprecated in iOS 8.0

**Comment by alloy** [comment]
> /Users/laura/artsy/eigen/Artsy/Classes/ARAppDelegate.m:325:10: Comparison of address of 'UIApplicationOpenSettingsURLString' not equal to a null pointer is always true

This can just be removed, because afaik it’s only used to check if the API is available, i.e. if it’s running on iOS 8.

**Comment by 1aurabrown** [comment]
cool cool







On Thu, Apr 30, 2015 at 6:48 AM, Eloy Durán <notifications@github.com>
wrote:

> /Users/laura/artsy/eigen/Artsy/Classes/ARAppDelegate.m:325:10: Comparison
> of address of 'UIApplicationOpenSettingsURLString' not equal to a null
> pointer is always true
>
> This can just be removed, because afaik it’s only used to check if the API
> is available, i.e. if it’s running on iOS 8.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/artsy/eigen/issues/376#issuecomment-97736162>.
>



-- 

[A.]


Laura Brown

Artsy <http://artsy.net/>

laura@artsy.net <caroline@artsy.net>

**Comment by alloy** [comment]
Moving this to #455, where it’s assigned to @ashfurrow.
