### ISSUE TITLE
In "All Exhibitors" list within fair experience, surface subscriber galleries above non-subscribers

### ISSUE THREAD

**Issue by nsimmons206** [artsy/eigen#379]
As part of an effort to give greater advantage to subscriber galleries we want to give them higher priority in the "All Exhibitors" feed within the fair experience. Other order determinants can remain the same but we want to be sure that subscriber's are listed first in the feed.

**Comment by katarinabatina** [comment]
@nsimmons206 this one is a microgravity story, I know it's not super obvious all ze time :-1:
