### ISSUE TITLE
Re-think how we ask for reviews

### ISSUE THREAD

**Issue by orta** [artsy/eigen#38]
_From @orta on December 5, 2014 19:23_

Currently we have the least amount of effort possible, this isn't hurting us, but it isn't helping on  a larger scale. 

This discusses a nice option: https://medium.com/circa/the-right-way-to-ask-users-to-review-your-app-9a32fd604fca

_Copied from original issue: artsy/eigen-private#2040_

**Comment by katarinabatina** [comment]
going to close this ticket for now, will reintroduce when we've prioritized

**Comment by orta** [comment]
Sidenote: there is now an official way to do this, and eventually they will disallow anything but that

**Comment by alloy** [comment]
Yeah we need to get on that.
