### ISSUE TITLE
How to prioritize snowplow analytics overhaul

### ISSUE THREAD

**Issue by katarinabatina** [artsy/eigen#380]
can someone shed light on how to best approach this incrementally? @orta ?

**Comment by orta** [comment]
The infrastructure for Snowplow is ready to go, I added it at our [framework level](https://github.com/orta/ARAnalytics/commit/d7de533509f412b820c8dbf9f01fe9487af67d69) a few weeks back. 

We need someone working on Eigen to talk with @ilyakava about what settings we need to get it working.

**Comment by ilyakava** [comment]
The only settings there should be to set are: `app_id` to `eigen` and `platform` to `mob`. Then you will report either a special "pageview" event, or a "structured" event (info on how should be in the obj-c tracker library docs).

A pageview event is simple and should take no arguments. But a structured event has 4 variable arguments that *we use* (Category (String), Action (String), Label (String), Property (String)). When you provide these 4 arguments, you will need to respect the schema described here [here](https://docs.google.com/a/artsymail.com/spreadsheets/d/1-iE1IPSDE1nsLfOwnW_kBcJtPTLtB6ZXztu_AlAS_lk/edit#gid=0).

**Comment by katarinabatina** [comment]
list:

Downloads
New Accounts Created
W1 Retention
Weekly Active User
Return WAU: (percentage of total WAU)
Total Sessions per week
Artist Follows
Weekly inquiries

**Comment by alloy** [comment]
I’m moving this into #384, @orta has done his work already.
