### ISSUE TITLE
Add event tracking for new navigation

### ISSUE THREAD

**Issue by katarinabatina** [artsy/eigen#381]
There are no events to track the main entry points of the new navigation
![image](https://cloud.githubusercontent.com/assets/6482926/7241717/9adb37aa-e789-11e4-98f0-1a9726638b61.png)

**Comment by alloy** [comment]
Moving this to #384.

**Comment by alloy** [comment]
This needs to be done anyways. Seeing as it uses ARAnalytics it can be done right now and submitted to  Mixpanel.

**Comment by ashfurrow** [comment]
Agreed. Should be fairly straightforward, barring any crazy implementation details :smile_cat:
