### ISSUE TITLE
Add test target that checks if all keys (e.g. analytics) are correctly configured for a release.

### ISSUE THREAD

**Issue by alloy** [artsy/eigen#382]
This test should be run on an app store release. The end goal is to have it use Eigen’s stack to perform the tests, but if that’s a massive undertaking then the first version may use simple `curl` calls and be invoked from a shell script.

**Comment by alloy** [comment]
This should include Snowplow analytics.

**Comment by ashfurrow** [comment]
So, (at least) Mixpanel always responds with a 200, making it impossible to determine from an HTTP response whether or not a token is valid. This is probably a feature, from their perspective, and I suspect others will do the same. 

Given that, the only alternative I can see right now is to take a one-way hash or our keys and hard-code them into the test. Then we can grab the keys at test time, hash 'em, and compare. 

Thoughts? Suggestions?

**Comment by alloy** [comment]
OMG… sad 403 cat

!()[https://farm8.staticflickr.com/7148/6508023065_8dae48a30b.jpg]

Their docs state that the API will respond with a body of `0` or `1`, so maybe that’s how you’re supposed to use their API? https://mixpanel.com/help/reference/http#tracking-events.

**Comment by orta** [comment]
there's potential that that's just around sending the required params though.

**Comment by ashfurrow** [comment]
I tried using `0` or `1`, but Orta's right – it sends `1` as long as you send _any_ token.

**Comment by alloy** [comment]
😔

**Comment by ashfurrow** [comment]
This [should be doable on Snowplow](https://twitter.com/SnowPlowData/status/596295201754329089), given that we only have a URL that's pretty easy to validate (does the server respond?). 

Still waiting on Segment.

**Comment by orta** [comment]
So, now that deploys are done by Circle, do we still need this? ( We have a linter for OSS keys )

**Comment by alloy** [comment]
I guess not, indeed.
