### ISSUE TITLE
Get all tests green

### ISSUE THREAD

**Issue by alloy** [artsy/eigen#383]
@1aurabrown can you paste an overview of the currently failing tests and, where you have the info, add why you think they’re failing?

**Comment by alloy** [comment]
For now I’m adding allotting a fair bit of time to this task, namely pretty much you and I till the end of this week. i.e. 3 days both.

**[ESTIMATE]** 6 days

**Comment by alloy** [comment]
This includes #370.

**Comment by alloy** [comment]
Can’t assign two people ¯\_(ツ)_/¯

But I’mma let you tell me what to do on this, so there you go :smile:

**Comment by 1aurabrown** [comment]
@alloy: they are all some variation on this error: https://github.com/artsy/eigen/issues/377

constraints with a multiple that is zero, which is illegal. This is legit, as I've seen the sign in screen crash with this error. I am not sure why this just started happening -- probably newest iOS does something different in layout.

There is also one snapshot diff that is failing -- I can look into this too:
![screen shot 2015-04-21 at 2 56 52 pm](https://cloud.githubusercontent.com/assets/3171662/7260799/d6f13c2e-e83a-11e4-8fc3-f90ecceb139e.png)

**Comment by orta** [comment]
Re: that ^ snapshot, I'm willing to bet the fair object needs to have its maps stubbed out so that it doesn't do async

**Comment by 1aurabrown** [comment]
can i close this? i believe everything that's left is just flakey, not consistently failing.

**Comment by alloy** [comment]
:+1:
