### ISSUE TITLE
fetchCurrentUnreadConversationCount - Error Client Not Authorized

### ISSUE THREAD

**Issue by morrys** [artsy/eigen#3847]
Hi all,
after making the changes suggested in issue https://github.com/artsy/eigen/issues/3843 I was able to start the application correctly.

There would seem to be a problem only when invoking this API https://github.com/artsy/eigen/blob/master/src/lib/Scenes/BottomTabs/BottomTabs.tsx#L16
as it returns the error `https://stagingapi.artsy.net/api/v1/me/token?client_application_id=xxxx - {" error ":" Client Not Authorized "}`

To avoid unnecessary calls to the server at the moment I have increased the interval time.

Any suggestions for this problem?

Thanks

**Comment by ashfurrow** [comment]
Hey! I've just verified that the OSS keys in `.env.example` work for me. Running `make oss` should generate this file for you, can you confirm if this file exists? It's used during the Xcode build phase so you'll need to recompile after changing it.

**Comment by morrys** [comment]
Hi @ashfurrow, 
the file exists and I ran the make oss command before running the application.
I can tell you that the services work correctly except for this highlighted in the issue.

**Comment by ashfurrow** [comment]
@morrys really? So you mean that some API requests are succeeding while others fail with this error? Hmm, that's quite odd. Is there any obvious pattern to this? I've just confirmed that the credentials are valid in our database. Can you try clearing the simulator and retrying? Maybe a failure got cached somewhere.

**Comment by morrys** [comment]
@ashfurrow, It seemed strange to me too, which is why I opened the ticket :D

At the moment I was able to try uninstalling the app and reinstalling it but the error persists.

As soon as possible I will try to provide you with more details 👍

**Comment by ashfurrow** [comment]
Hi again! Thanks for your patience on this. I've chatted with another engineer and it seems like some of our APIs require an additional level of privilege to access – including the API that you're seeing the error for. I'm going to follow up with an improvement to ignore those calls for OSS developers. In the mean time, comment out anything that's not working. Let us know what's not working, if you could, since that will help us make this more accessible for the broader OSS community 👍

**Comment by morrys** [comment]
Sure fd, thanks to you for the quick check.
In this issue I will report the queries / mutations that don't work 👍 

Another is [this query](https://github.com/artsy/eigen/blob/master/src/lib/Containers/Inbox.tsx#L151)

**Comment by gkartalis** [comment]
Closing since it is a stale issue
