### ISSUE TITLE
Remove KSPromises and replace with KVO

### ISSUE THREAD

**Issue by orta** [artsy/eigen#387]
This mainly affects the ArtworkViewController, and the ShowViewController given that the majority of the usage is inside these view controllers.

When I experimented with KVO tools, I found KVOController to be solid, but I liked the binding aspect of OS X and RACSignals. I missed that. Alternatives with it, that I didn't explore [THObserversAndBindings](https://cocoapods.org/pods/THObserversAndBinders) is kinda abandoned since the author moved to Apple, [BIND](https://cocoapods.org/pods/BIND) is definitely an interesting option.

**Comment by orta** [comment]
Expanded out of https://github.com/artsy/mobile/issues/22

**Comment by alloy** [comment]
There’s also https://vimeo.com/110932544, but I’m not sure if you can use just that part of CoconutKit and how nicely the bindings can be configured in code.
