### ISSUE TITLE
[RFC] Add button haptic feedback dependency `react-native-haptic-feedback`

### ISSUE THREAD

**Issue by pvinis** [artsy/eigen#3879]
#### Status 
Adopted

#### New Dependency
Name: react-native-haptic-feedback
URL: https://github.com/junina-de/react-native-haptic-feedback

### Focus

A React Native module that allows you to use haptic feedback, which can be added to button taps for a more ios-native feel, as well as to events for success/failure like [our Motion Guidelines](https://www.notion.so/artsy/Motion-Guidelines-11000a5ea9764bf182cc0732f5cebb17#bbd9152c131a42ce8f87153cd3f55b5f) suggest.

It uses the taptic engine on ios, and small vibrations on android.

An example of how to use it can be found [here](https://github.com/artsy/eigen/pull/3835/files#diff-d6a45a45356ecd5be818873e49cb70ccR121).

#### Check List
- [x] Have read over the source code, and we can maintain it
- [x] Has had a release in the last year, or looks done and stable

#### Alternatives
The only real alternative seems to be Expo's `Haptics` ([docs](https://docs.expo.io/versions/latest/sdk/haptics/), [code](https://github.com/expo/expo/tree/master/packages/expo-haptics)), but we would need to add Expo's unimodules support. Not too bad, but it's a whole extra thing that I'd like to avoid for now. If in the future we could use many of Expo's unimodules, we can add it then.

**Comment by admbtlr** [comment]
👍 I've used this module and it has never been problematic

**Comment by pvinis** [comment]
Resolving this RFC as accepted.

## Next steps

- Merge #3835
