### ISSUE TITLE
category descriptions do not reveal more text when pressed

### ISSUE THREAD

**Issue by katarinabatina** [artsy/eigen#390]
http://cl.ly/image/3V1h1I3j1d0f

see video

**Comment by alloy** [comment]
Definitely a bug.

**Comment by alloy** [comment]
@katarinabatina PS: Can you enable showing mouse clicks in your screen recordings?

![screen shot 2015-04-23 at 11 14 40](https://cloud.githubusercontent.com/assets/2320/7294021/0b330286-e9aa-11e4-9f9c-453be71a4274.png)

**Comment by katarinabatina** [comment]
Sure thing! 

Katarina

**Comment by alloy** [comment]
Fixed by #600.
