### ISSUE TITLE
missing show in show feed

### ISSUE THREAD

**Issue by katarinabatina** [artsy/eigen#393]
![image](https://cloud.githubusercontent.com/assets/6482926/7305642/6fc670ca-e9cd-11e4-8e85-dc1982fc83eb.png)

**Comment by 1aurabrown** [comment]
is this on staging or production? or maybe an unpublished show that came up because you're an admin?

**Comment by 1aurabrown** [comment]
@katarinabatina is this still an actual issue?

**Comment by katarinabatina** [comment]
no i dont think so
