### ISSUE TITLE
swiping between artworks feels buggy

### ISSUE THREAD

**Issue by katarinabatina** [artsy/eigen#394]
see video 

http://cl.ly/image/213W4016382L

**Comment by orta** [comment]
Hah, I had taken screenshots for this exact thing.

**Comment by 1aurabrown** [comment]
update: @broskoski is checkin this out

**Comment by 1aurabrown** [comment]
hard to estimate this, i think it's tricky. 1 day to a couple days.

**Comment by orta** [comment]
Chiming in that this is probably a lack of initial constraints at what size the work should be while we wait for the artwork. 

In older releases it would default to fit a square if there is no image aspect ratio data, but these examples should have enough information to know the aspect ratio before grabbing the image.

**Comment by 1aurabrown** [comment]
I agree that this is probably the root of the cause. You think the aspect ratio is already available? Will look for it

**Comment by orta** [comment]
yeah, should be accessible on the artwork's main image
