### ISSUE TITLE
auto layout mishaps on ipad

### ISSUE THREAD

**Issue by katarinabatina** [artsy/eigen#395]
![image](https://cloud.githubusercontent.com/assets/6482926/7305782/8f0f2e08-e9ce-11e4-8502-c5d46ad15db7.png)

![image](https://cloud.githubusercontent.com/assets/6482926/7305790/95575cea-e9ce-11e4-976a-9e7cd0e57a02.png)

**Comment by 1aurabrown** [comment]
weeiiiird!

this didn't always happen.

**Comment by 1aurabrown** [comment]
I don't see this happening, did you do anything special to get it into this state?

**Comment by katarinabatina** [comment]
Navigated to a different tab in the navigation then came back to the explore tab 

Katarina

**Comment by 1aurabrown** [comment]
Interesting. Will check it out.

On Thu, Apr 23, 2015 at 20:17, artsy/eigen
<reply@reply.github.com>
wrote:
Navigated to a different tab in the navigation then came back to the explore tab

Katarina

> On Apr 23, 2015, at 7:17 PM, Laura Brown <notifications@github.com> wrote:
>
> I don't see this happening, did you do anything special to get it into this
state?
>
> —
> Reply to this email directly or view it on GitHub.
>
—
Reply to this email directly or view it on GitHub
[https://github.com/artsy/eigen/issues/395#issuecomment-95760318] .[https://github.com/notifications/beacon/ADBlTvmXAt6s-b1CjHkvz5P5NFegbWRRks5oCYMdgaJpZM4EHO8L.gif]

**Comment by alloy** [comment]
1. Load ‘explore’ tab in portrait orientation
2. Change to other tab
3. Change to landscape orientation
4. Change back to ‘explore’ tab

![ipad explore rotation bug](https://cloud.githubusercontent.com/assets/2320/7325886/aeddba76-eac1-11e4-81ec-f823765b3fab.gif)

**Comment by alloy** [comment]
I realise you had already fixed this, I just had not clicked the ‘comment’ button so doing that now for completeness sake :)
