### ISSUE TITLE
turn off spelling suggestions in search field on fairs

### ISSUE THREAD

**Issue by katarinabatina** [artsy/eigen#396]
![image](https://cloud.githubusercontent.com/assets/6482926/7306260/e89e21ba-e9d1-11e4-9693-db992a5b15b2.png)

**Comment by alloy** [comment]
I think it’s unlikely that you would want this anywhere. I used the Safari developer console to add the `autocomplete="off"` and `autocorrect="off"` attributes to the input, which finally disabled it in Safari.

I think it was specifically `autocorrect`, but it's probably best to just disable all options: http://davidwalsh.name/disable-autocorrect

So, this should be moved to force.

**Comment by 1aurabrown** [comment]
@katarinabatina do we want this disabled on non-embedded force as well? when it's viewed in iPad safari, or on a computer?

**Comment by katarinabatina** [comment]
yeah I would think so

[A.] Katarina Batina

Artsy <http://artsy.net/>


katarina@artsymail.com

                @katarinabatina <https://twitter.com/katarinabatina>

253 225 5812

**Comment by 1aurabrown** [comment]
ok, can you make a force issue?

**Comment by 1aurabrown** [comment]
I'm going to close since the force issue is closed.
