### ISSUE TITLE
Map point preview missing 

### ISSUE THREAD

**Issue by orta** [artsy/eigen#40]
_From @katarinabatina on December 1, 2014 21:26_

press point on map, black bar preview does not appear 

_Copied from original issue: artsy/eigen-private#2030_

**Comment by orta** [comment]
_From @ashfurrow on January 9, 2015 16:5_

Hmm. Not seeing this on my end – any idea on how to reproduce? Seeing this. 

![ios simulator screen shot jan 9 2015 5 04 19 pm](https://cloud.githubusercontent.com/assets/498212/5682618/a0917324-9821-11e4-9620-41ed90e27066.png)

**Comment by orta** [comment]
_From @katarinabatina on January 9, 2015 17:46_

launch app>armroy show>map>zoom>tap point>preview flickers...It might be an iPhone 6 compatibility issue.

**Comment by orta** [comment]
_From @ashfurrow on January 12, 2015 17:9_

OK, I'll be sure to try it on an iPhone 6. Thanks for the info!

**Comment by orta** [comment]
Confirmed, pretty sure I've seen this.

**Comment by alloy** [comment]
To clarify, the originally reported issue by @katarinabatina is about the black callout immediately disappearing after showing.

* This bug only occurs when running the application on a device that runs iOS 8.x
* I have verified that the bug does *not* occur on a device running iOS 7 (7.1.1).
