### ISSUE TITLE
Fix crash in WebCore::StyleResolver::loadPendingImages()

### ISSUE THREAD

**Issue by artsyit** [artsy/eigen#402]
### Reason ###

No reason found. Full stack trace includes WebCore, WebKitLegacy, DataDetectorsUI, CoreFoundation, libsystem_pthread.dylib.

### Link to HockeyApp ###

* [https://rink.hockeyapp.net/manage/apps/37029/crash_reasons/32448235](https://rink.hockeyapp.net/manage/apps/37029/crash_reasons/32448235)

**Comment by alloy** [comment]
Closing this in anticipation of #606.
