### ISSUE TITLE
Add breadcrumb logging to crash reports around - [ARTiledImageView drawRect:]

### ISSUE THREAD

**Issue by alloy** [artsy/eigen#408]
We need to figure out some things to log so we can try to hone in on how to reproduce these segfaults:

* https://rink.hockeyapp.net/manage/apps/37029/app_versions/33/crash_reasons/33140567
* https://rink.hockeyapp.net/manage/apps/37029/app_versions/33/crash_reasons/32348962
* https://rink.hockeyapp.net/manage/apps/37029/app_versions/33/crash_reasons/32627729

I’m thinking:

* Log (time) when showing a view controller that displays a `ARTiledImageView`
* Log (time) when leaving a view controller that displays a `ARTiledImageView`
* Log (time) when drawing a `ARTiledImageView`
* Log the exact image being displayed

Any other suggestions?

----

Attaching logs should be done like so: http://support.hockeyapp.net/kb/client-integration-ios-mac-os-x/how-to-add-application-specific-log-data-on-ios

**Comment by alloy** [comment]
**[ESTIMATE]** 0.5 day

**Comment by orta** [comment]
You could add support at ARAnalytics level? ( `ARLog()` I think )

**Comment by alloy** [comment]
@orta Interesting. So that won’t spam other providers with useless logging and potentially slow down the app?

**Comment by alloy** [comment]
Off-topic, doesn’t it make sense to perform this on a background thread in any case? https://github.com/orta/ARAnalytics/blob/1c1fc997c9a0aa7e27271eeade02ba426d92300b/ARAnalytics.m#L613-L615

**Comment by orta** [comment]
probably, yeah, no guarantee how well the libs would respond to that. You could say the same about the entire thing: https://github.com/orta/ARAnalytics/blob/1c1fc997c9a0aa7e27271eeade02ba426d92300b/ARAnalytics.m#L476-L481

**Comment by alloy** [comment]
Hah, good point.

So, I’m slightly ambivalent about doing this through `ARLog`. I don’t have a problem with adding logging support to ARAnalytics+HockeyApp, but these breadcrumbs are _specifically_ for Hockey crash logs, not for any other analytics.

**Comment by orta** [comment]
Fair, from my perspective, I think `ARAnalytics + Hockey` could do better in this respect, I thought hockey completely disabled logging, so was surprised to see this. The [hockey](https://github.com/orta/ARAnalytics/blob/1c1fc997c9a0aa7e27271eeade02ba426d92300b/Providers/HockeyAppProvider.m#L4) provider can log all ARLogs and if it notices a crash, send those off

**Comment by orta** [comment]
Happy to not though, to get it done

**Comment by alloy** [comment]
We’re already doing file logging with CocoaLumberjack, so I’d like to just use that.

However, I’m unsure how to get that data into the Hockey manager. Should I expose a ‘log file collection’ block parameter on the Hockey provider in ARAnalytics and call that when the HockeyManager delegate method extra logs is called?

**Comment by alloy** [comment]
Hrmm, I guess not, because ARAnalytics’ API basically only takes identifiers (token etc).

**Comment by orta** [comment]
someone built a pod for this I think, ARAnalytics+CocoaLumberjack

**Comment by alloy** [comment]
Alas, [ARAnalyticsLogger](https://github.com/sgtsquiggs/ARAnalyticsLogger) only sends `DDLog()` to `ARLog()`.

**Comment by alloy** [comment]
Ok, I guess I’ll have to make this work through `ARLog` after all.

**Comment by alloy** [comment]
https://github.com/orta/ARAnalytics/pull/155

![screen shot 2015-05-08 at 20 23 02](https://cloud.githubusercontent.com/assets/2320/7542797/15d83180-f5c0-11e4-8751-16a7575faaf0.png)

**Comment by alloy** [comment]
This took a whole day longer, because a polished abstracted version (for the ARAnalytics library) takes a whole lot longer than just what we need for our app. So I definitely need to take that into account in the future.
