### ISSUE TITLE
Fix crash in - [ISO8601DateFormatter dateComponentsFromString:timeZone:range:fractionOfSecond:], line 623

### ISSUE THREAD

**Issue by artsyit** [artsy/eigen#410]
### Stacktrace (first of multiple) ###

<pre>ISO8601DateFormatter;dateComponentsFromString:timeZone:range:fractionOfSecond:;ISO8601DateFormatter.m;623
ISO8601DateFormatter;dateFromString:timeZone:range:;ISO8601DateFormatter.m;692
MTLValueTransformer;transformedValue:;MTLValueTransformer.m;64
MTLJSONAdapter;initWithJSONDictionary:modelClass:error:;MTLJSONAdapter.m;190
MTLJSONAdapter;modelOfClass:fromJSONDictionary:error:;MTLJSONAdapter.m;47
MTLModel(JSON);modelWithJSON:error:;MTLModel+JSON.m;23
ArtsyAPI;getRequest:parseIntoAnArrayOfClass:withKey:success:failure:;ArtsyAPI.m;85
AFJSONRequestOperation;JSONRequestOperationWithRequest:success:failure:;AFJSONRequestOperation.m;54</pre>

### Link to HockeyApp ###

* [https://rink.hockeyapp.net/manage/apps/37029/crash_reasons/27869523](https://rink.hockeyapp.net/manage/apps/37029/crash_reasons/27869523)

**Comment by alloy** [comment]
This was fixed in 1.8.0.
