### ISSUE TITLE
banners go stale if app has been open a while

### ISSUE THREAD

**Issue by katarinabatina** [artsy/eigen#411]
banner content does not update automatically. have to restart the app to get new banners anyone else having this problem? Is it a beta thing?

**Comment by orta** [comment]
Do they change often enough that its worth looking?

**Comment by katarinabatina** [comment]
Well today we launched an auction, no other way of getting there besides
the banner, we shouldn't depend on the user to have to restart the app to
get that new content.

[A.] Katarina Batina

Artsy <http://artsy.net/>


katarina@artsymail.com

                @katarinabatina <https://twitter.com/katarinabatina>

253 225 5812

**Comment by alloy** [comment]
We could ‘solve’ this in the same way we deal with stale shows and magazine content. i.e. reload on selecting the tab after N amount of time.

**Comment by 1aurabrown** [comment]
Yeah, we could totally re-fetch when the tab is selected and refresh the UI if the data is different

**Comment by alloy** [comment]
Fixed by #444.
