### ISSUE TITLE
Show page design updates

### ISSUE THREAD

**Issue by nsimmons206** [artsy/eigen#415]
These updates include layout changes, changes to the installs carousel, a new "follow artist" section,  and the addition of new data like full gallery hours, map location, opening reception, additional info and press releases.
![showpage_eigenmartsy_finalspec_02](https://cloud.githubusercontent.com/assets/8950911/7523026/e3060e16-f4c6-11e4-8057-883df73359b5.jpg)

![showpage_eigenmartsy_finaldesign_02](https://cloud.githubusercontent.com/assets/8950911/7523027/e306f0ce-f4c6-11e4-8bad-eac31e06ccf2.jpg)

![showpage_ipad_finalspec_02](https://cloud.githubusercontent.com/assets/8950911/7523028/e307bd92-f4c6-11e4-9610-661a492d4a05.jpg)

![showpage_ipad_finaldesign_02](https://cloud.githubusercontent.com/assets/8950911/7523025/e3049662-f4c6-11e4-8f42-3ba8086ddad6.jpg)

**Comment by nsimmons206** [comment]
Is there a way to copy this issue into microgravity as well? Or should i just make it twice?

**Comment by alloy** [comment]
@nsimmons206 You’ll just have to create it twice.

I assume this is meant for the next sprint?

/cc @katarinabatina

**Comment by katarinabatina** [comment]
@alloy I'm unsure at this point whether or not it will make it into the next sprint we'll have to see how it stacks up against other priorities.
