### ISSUE TITLE
Analytics Events Cleanup

### ISSUE THREAD

**Issue by ashfurrow** [artsy/eigen#422]
Originally captured in #384. 

- [ ] ~~Rename some events to sign up with the other teams. See https://github.com/artsy/eigen/issues/380#issuecomment-94608099.~~
- [x] New navigation (tab bar) entry switching (shows / magazine) See #381.
- [ ] Natural-language event names
- [ ] Downloads
- [ ] New Accounts Created
- [ ] W1 Retention
- [ ] Weekly Active User
- [ ] Return WAU: (percentage of total WAU)
- [ ] Total Sessions per week
- [ ] Artist Follows
- [ ] Weekly inquiries

**Comment by alloy** [comment]
@alexanderfabry will get us an events overview before Monday and in a format that’s tailored to Segment. This should then only be matter of ‘typing them in’.

**Comment by alloy** [comment]
The list https://docs.google.com/spreadsheets/d/1bLbeOgVFaWzLSjxLOBDNOKs757-zBGoLSM1lIz3OPiI/edit#gid=497747862

**Comment by katarinabatina** [comment]
@ashfurrow progress update, I know you mentioned you wanted this done yesterday

**Comment by ashfurrow** [comment]
Nearly done; there is an open pr with the work.
