### ISSUE TITLE
relay-hooks 4.0.0

### ISSUE THREAD

**Issue by morrys** [artsy/eigen#4225]
Hi guys,
as I am close to the release of relay-hooks 4.0.0 I would like your feedback on the changes that will be made.

Here https://github.com/relay-tools/relay-hooks/issues/126 you can find the issue in which to discuss any changes 

Here https://github.com/relay-tools/relay-hooks/pull/128 the PR where the biggest changes are made and from which I will release the beta version.

Thanks

**Comment by pvinis** [comment]
Oh I totally missed this issue. Thanks for making it!

We kinda tried relay-hooks in a couple of places but the team prefers the hoc way for now for most places.

Also, we saw that relay will soon add hooks officially. What are your thoughts about this?

**Comment by gkartalis** [comment]
closing this since we are using react-relay 14 that supports hooks
