### ISSUE TITLE
[RFC] Add react-native-localize

### ISSUE THREAD

**Issue by ds300** [artsy/eigen#4244]
#### Status 
Open

#### New Dependency
Name: react-native-localize
URL
- https://github.com/zoontek/react-native-localize
- https://www.npmjs.com/package/react-native-localize

### Focus

`react-native-localize` lets us access information about the user's locale and other preferences, e.g. calendar type. It's a small, actively-maintained lib, with loads of downloads per week.

We need it, or something like it, for this PR: #4241 

#### Check List
- [x] Have read over the source code, and we can maintain it
- [x] Has had a release in the last year, or looks done and stable

#### Alternatives
No noteworth alternatives on npm.

We could always roll our own with just the data we need (current locale). I think this library is lightweight enough and generally useful enough that it makes sense to adopt, though.

**Comment by MounirDhahri** [comment]
I used this in the past and it's stable and lightweight
👍

**Comment by ds300** [comment]
[Resolved]

**Comment by Isabel-creator** [comment]
Come si installa? Grazie
