### ISSUE TITLE
other works in auction not appearing in choice works auction

### ISSUE THREAD

**Issue by katarinabatina** [artsy/eigen#425]
on some of the lots in choice works auction, the artwork view is missing the "other works in auction" module" in some cases it is "related artworks" and in others it is missing that data all together

**Comment by katarinabatina** [comment]
not working in beta or production

**Comment by katarinabatina** [comment]
looks like it's a larger issue then just auctions

**Comment by alloy** [comment]
A [recent change in gravity](https://github.com/artsy/gravity/commit/e54068dea4fad84d81e692652bf1b5d9d28a0079#diff-1dde0f2c52115f6820b2f6fa84852714L183) changed the API without providing backwards compatibility, which is causing a network call, that’s necessary for us to decide what to show, to fail.

**Comment by alloy** [comment]
@mzikherman Is going to make the API accept our usage again, so this should be back to work in a day.

**Comment by alloy** [comment]
Should be fixed by https://github.com/artsy/gravity/pull/8870

**Comment by mzikherman** [comment]
Sorry guys, I updated the web side, totally forgot/didnt realize you were using this too :(

My bad, should be fixed in the next grav deploy (will post here when that's done).

**Comment by mzikherman** [comment]
Gravity has been deployed, can u verify this issue is fixed? @katarinabatina

**Comment by katarinabatina** [comment]
yup we're good!

**Comment by mzikherman** [comment]
Whew, sorry again!

**Comment by mzikherman** [comment]
I'd close this issue but I dont have access or something.

**Comment by katarinabatina** [comment]
thanks for hoppin' on this @mzikherman!

**Comment by alloy** [comment]
Thanks for the quick turn around time, @mzikherman 👌🏿
