### ISSUE TITLE
Magazine section is cramped at the top

### ISSUE THREAD

**Issue by alexanderfabry** [artsy/eigen#426]
See below. Would be nice to have some padding

![img_5557](https://cloud.githubusercontent.com/assets/598684/7542866/4810cbe4-f58e-11e4-9207-5f0cfe0611ed.PNG)

Compare to microgravity:

![img_5569](https://cloud.githubusercontent.com/assets/598684/7542879/63b7be2a-f58e-11e4-985e-a2dc5be2aac7.PNG)

**Comment by alloy** [comment]
This appears to have been fixed since then:

![ios simulator screen shot 29 jun 2015 15 19 00](https://cloud.githubusercontent.com/assets/2320/8408675/3eb1eabc-1e72-11e5-92f0-6173bf4aa406.png)
