### ISSUE TITLE
intermittent crash when rotating gene view

### ISSUE THREAD

**Issue by orta** [artsy/eigen#43]
_From @1aurabrown on August 27, 2014 21:50_

one of those errors about calling [super LayoutSubviews], which is pretty unhelpful.

_Copied from original issue: artsy/eigen-private#1954_

**Comment by alloy** [comment]
@1aurabrown @orta Are there crash reports for these?

**Comment by alloy** [comment]
bump

**Comment by alloy** [comment]
Seeing as I cannot find any seemingly related crash reports in HockeyApp, I’m gonna close this one.

@1aurabrown if you do have crash reports saved somewhere, please attach them and re-open.
