### ISSUE TITLE
Are related posts being used?

### ISSUE THREAD

**Issue by mzikherman** [artsy/eigen#430]
Force/martsy have been completely migrated to use the new Articles/Positron infrastructure, over gravity's posts.

I am in the process of removing all post code and associated API's from Gravity, and noticed in Papertrail that something is still requesting 'related posts'.

The API call is something like `/api/v1/related/posts?artist[]=vito-acconci` . Is that happening from Eigen? I can't tell from the logs, somehow the UserAgent isn't listed.

**Comment by dblock** [comment]
Yes it is, https://github.com/artsy/eigen/blob/828a695838b2a536d27e068ae5589b4ba529620c/Artsy/Classes/View%20Controllers/ARArtworkViewController.m#L129 and https://github.com/artsy/eigen/blob/95b4473388dead96a6d48e02b88a53a3f94a1f19/Artsy/Classes/View%20Controllers/ARArtistViewController.m#L200.

**Comment by mzikherman** [comment]
Oy vey.

@orta @craigspaeth - how/can/who should update Eigen?

**Comment by alloy** [comment]
Removing it completely means that Eigen 1.8 will no longer function for 100%, which is the last version to target iOS 7 (and thus some devices). It shouldn’t stop working, but finding related work is a central feature, so that needs to be given some thought as to whether or not we find this ‘legacy’ support important.

**Comment by mzikherman** [comment]
Hmm, to just keep that API around for you, it might suffice to rip out everything we were intending, and do a redirect to the related Positron url? That definitely seems really hacky, and Eigen would have to be able to follow redirects.

Would returning a 404 (or worse, some sort empty array/response) be alright? Effectively removing the functionality but not in a 'breaking' way.

I haven't been too involed in posts/articles, but just in case this endpoint/issue was overlooked I opened https://github.com/artsy/eigen/issues/432 to switch to articles, since I think that's the new standard.

**Comment by alloy** [comment]
After thinking it over for a bit, reading through the source, and testing the app out _without_ related posts, I think this is fine. There's very little impact in discovering artworks, which is the more important part, so :+1: 

The only current issue is sprint planning. Is there need to remove it _now_ or is another ~8 weeks a possibility?

**Comment by mzikherman** [comment]
We can definitely wait to remove server-side `Post` stuff, as it's part of a more general clean up effort, but if it's ok to return either a 404 or en empty response (whichever), we'd probably do that and remove stuff sooner.

**Comment by alloy** [comment]
@mzikherman Ok that sounds good. So to summarise, it will keep working for a bit more and then to conclude the general cleanup the endpoint will 404. :+1:

**Comment by alloy** [comment]
moving any further discussion to #432.
