### ISSUE TITLE
Replace related posts with related articles

### ISSUE THREAD

**Issue by mzikherman** [artsy/eigen#432]
@craigspaeth probably has the best insight in terms of what's needed, but I think it's just swapping one API for another!

Then we can totally remove all this post related cruft from Gravity, plus I think articles are the new standard over posts, which is now deprecated.

**Comment by craigspaeth** [comment]
:+1: If you start implementing articles in native please let me know so I can make sure API design decisions are frozen.

**Comment by katarinabatina** [comment]
not sure if this is relevant anymore @alloy your call to close or keep open
