### ISSUE TITLE
Native sharing on martsy views

### ISSUE THREAD

**Issue by ashfurrow** [artsy/eigen#433]
Taken from comments in #367. 

**[Estimate]** 2 Days

**Comment by alloy** [comment]
@craigspaeth Would it be possible for martsy to render pages that show the Facebook/twitter share icons differently when Eigen is the client? I.e. only show the iOS share icon and have it link to e.g. `artsy://favorite/?text=6%20Contemporary%20African%20Artists%20You%20Should%20Know&url=https%3A%2F%2Fwww.artsy.net%2Farticle%2Fstas-chyzhykova-6-contemporary-african-artists-you-should-know`?

The iOS share icon we use looks like: 
![screen shot 2015-05-12 at 13 00 31](https://cloud.githubusercontent.com/assets/2320/7585971/34e4753a-f8a8-11e4-92c1-8ea7140d1ea3.png)

**Comment by alloy** [comment]
@craigspaeth Actually, I’d be interested in making that PR myself, so if you have any suggestions for how to do this better and/or pointers to where I should be doing this, then I’ll be on my merry way :)

**Comment by craigspaeth** [comment]
@alloy Happy to have web implement this, but if you are interested I highly encourage diving into it!

You should be able to follow the Set-Up in the README [here](https://github.com/artsy/microgravity#set-up) to get started launching the app. Basically it's a combination of Node/JS tools [explained here](http://ezeljs.com/) written in [coffeescript](http://coffeescript.org/). Chunks of UI are grouped into ["components"](https://github.com/artsy/ezel#components) and in the case of this share button it's the [share](https://github.com/artsy/microgravity/tree/master/components/share) component. You might want to check against `sd.USER_AGENT.match('Artsy-Mobile')` and render something different [in the template](https://github.com/artsy/microgravity/blob/master/components/share/index.jade#L1) then [style it](https://github.com/artsy/microgravity/blob/master/components/share/index.styl) to look like Eigen.

**Comment by alloy** [comment]
I have some local changes to martsy to start supporting this, but it’s got a lot more edges, so it’s on ice atm until, probably, the next sprint.

**Comment by katarinabatina** [comment]
@alexanderfabry pointed out how clumsy this feels to me today, agree we should move forward with hijacking the view and putting in the more general share button to work more smoothly in-app
