### ISSUE TITLE
[RFC] Add react-native-multi-slider

### ISSUE THREAD

**Issue by MounirDhahri** [artsy/eigen#4333]
**Status**
Open

**New Dependency**
Name: react-native-multi-slider

URLs:
- Github: https://github.com/ptomasroos/react-native-multi-slider
- Npm: https://www.npmjs.com/package/@ptomasroos/react-native-multi-slider

**Description**
Highly customizable JS-based multi-slider. It's small, actively-maintained lib, with loads of downloads per week.

We need it, or something like it, for this PR: #4332

**Check List**
- [x] Have read over the source code, and we can maintain it
- [x] Has had a release in the last year, or looks done and stable

**Alternatives**
No noteworthy alternatives on npm.

**Comment by ds300** [comment]
Doing some cleanup and it looks like we have adopted this! Gonna close 🙏🏼
