### ISSUE TITLE
map blinks through scroll view when scrolling

### ISSUE THREAD

**Issue by orta** [artsy/eigen#44]
_From @1aurabrown on July 9, 2014 22:30_

not sure what causes this flash of the map through the scroll view -- pay attention at the very beginning of the gif:
![blinking](https://cloud.githubusercontent.com/assets/3171662/3532226/72910088-07b8-11e4-872a-29c45d050eb0.gif)

(also the scroll view shouldn't be so long given its content.)

_Copied from original issue: artsy/eigen-private#1853_

**Comment by orta** [comment]
This is easily reproducible, you need enough content to be able to hit a 0 height maps, then scrolling past that flickers to something big, maybe when it's size first hits 0 something happens?

**Comment by orta** [comment]
My guess, is that at 0 height it's using the intrinsic content size, then we go back to 1 and minus 1

**Comment by ashfurrow** [comment]
Almost – precisely `-0.5`.
