### ISSUE TITLE
Facebook/Twitter sharing popover issues

### ISSUE THREAD

**Issue by alloy** [artsy/eigen#441]
After playing with #367 #435 for a bit, I ran into 2 issues:
- Because the popover is shown from the touch point, _not_ the view frame, the popover is always in a different place:
  
  ![ios simulator screen shot 15 may 2015 12 49 24](https://cloud.githubusercontent.com/assets/2320/7651464/0579c466-fb01-11e4-83c1-284f73b7a467.png)
  ![ios simulator screen shot 15 may 2015 12 49 30](https://cloud.githubusercontent.com/assets/2320/7651466/085d91bc-fb01-11e4-86f4-2f1b39646aa5.png)
- Changing orientation moves the popover to the wrong location, which without information about how the page will be laid out is going to be hard to get right:
  
  ![ios simulator screen shot 15 may 2015 12 45 59](https://cloud.githubusercontent.com/assets/2320/7651487/4453756a-fb01-11e4-86ea-f1d30beeda37.png)

---

All in all, I think that this isn’t the right solution. To get this right we really need to query the web view for the exact frame of the element, in a way like described [here](https://github.com/artsy/eigen/pull/435#issuecomment-102021582).

So after giving it some more thought, I think that maybe we need to do this completely different, design wise.
- All the articles on the [overview page](https://www.artsy.net/articles) have share links, but does that really make sense, as you haven’t even really read the article yet by that time?
- It makes more sense to me to share from a specific article’s page, which means that there will only be 1 thing to share per page.
- This also brings it much more in line with native iOS views, where you’d typically share what you’re currently looking at.
- Finally, this means that we can just omit the button on martsy completely when shown in Eigen (see #433) and instead have some `meta` link in the HTML document that Eigen uses to determine it should show a ‘share’ button, which we can then just overlay over the web view. This, being a native button, takes away _all_ of these layout problems.

@katarinabatina What do you think?

**Comment by ashfurrow** [comment]
Really great points @alloy – I like the idea of a `meta` tag.

**Comment by katarinabatina** [comment]
can we omit the buttons on the force view when embedded in eigen as well (like you are suggesting for martsy)?

**Comment by katarinabatina** [comment]
can we deploy the current state of it like this? I feel like we might be able to live with it like this for the time being

**Comment by alloy** [comment]
> can we omit the buttons on the force view when embedded in eigen as well (like you are suggesting for martsy)?

Yep.

> can we deploy the current state of it like this? I feel like we might be able to live with it like this for the time being

Aye, will do.

**Comment by alloy** [comment]
After confirming with @katarinabatina, we’re going to keep it as-is for this release.

**Comment by katarinabatina** [comment]
as we de-prioritize articles in the app I don't think this view will be as easily accessible
