### ISSUE TITLE
Analytics framework

### ISSUE THREAD

**Issue by alexanderfabry** [artsy/eigen#443]
A great resource on implementing iOS analytics with Segment: https://segment.com/docs/libraries/ios/

We want to make three types of tracking calls:
- **Identify**, to record a user's unique identifiers and any associated traits
```objc
[[SEGAnalytics sharedAnalytics] identify:@"a user's id"
                                traits:@{ @"email": @"a user's email address" }];
```
- **Screen**, to record screen views and associated properties

```objc
[[SEGAnalytics sharedAnalytics] screen:@"Photo Feed"
                            properties:@{ @"Feed Type": @"private" }];
```
- **Track**, to record actions the user takes in the app
```objc
[[SEGAnalytics sharedAnalytics] track:@"Bought an Item"
                           properties:@{ @"item": @"Sword of Heracles", @"revenue": @2.95 }}];
```

Right now the only integration we're using is Mixpanel, but we may want to turn on other integrations in the future.

See https://docs.google.com/a/artsymail.com/spreadsheets/d/1bLbeOgVFaWzLSjxLOBDNOKs757-zBGoLSM1lIz3OPiI/edit#gid=497747862 for a tracking plan that includes the screens we want to track, event names, and describes the properties we want to record for these tracking calls.

**Comment by orta** [comment]
This is almost in: https://github.com/artsy/eigen/pull/442 closing as dupe

**Comment by alexanderfabry** [comment]
There's a lot of additional info here, but feel free to pull into the the other issue if you like!

cc @ashfurrow @alloy
