### ISSUE TITLE
Fix NSInvalidArgumentException in - [ARModernPartnerShowTableViewCell initWithStyle:reuseIdentifier:], line 46

### ISSUE THREAD

**Issue by artsyit** [artsy/eigen#445]
### Stacktrace ###

<pre>ARModernPartnerShowTableViewCell;initWithStyle:reuseIdentifier:;ARModernPartnerShowTableViewCell.m;46
ARFeedViewController;tableView:cellForRowAtIndexPath:;ARFeedViewController.m;186</pre>

### Reason ###

*** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[ARModernPartnerShowTableViewCell setScrollEnabled:]: unrecognized selector sent to instance 0x1698a0b0'

### Link to HockeyApp ###

* [https://rink.hockeyapp.net/manage/apps/37029/crash_reasons/22644806](https://rink.hockeyapp.net/manage/apps/37029/crash_reasons/22644806)

**Comment by alloy** [comment]
Old app version, haven’t seen this crash on newer versions.
