### ISSUE TITLE
Spinner of first page of embedded models shows underneath heading.

### ISSUE THREAD

**Issue by alloy** [artsy/eigen#447]
I also saw this happen on another view, I think it was an artist’s page (on iPad), so maybe it’s triggered in conjunction with a switch view?

![slack_for_ios_upload-2](https://cloud.githubusercontent.com/assets/2320/7679260/63878762-fd5b-11e4-83f0-9cbec21f4ee8.png)

**Comment by alloy** [comment]
Scratch that ‘switch’ part, it’s just embedded models:

![ios simulator screen shot 18 may 2015 13 20 35](https://cloud.githubusercontent.com/assets/2320/7679835/cafc11d8-fd60-11e4-97c5-c930cf39f73b.png)

**Comment by 1aurabrown** [comment]
This should be fixed by https://github.com/ashfurrow/ARCollectionViewMasonryLayout/pull/25. I'll keep this issue open even though it's really a masonry layout issue, as a reminder to update eigen's podfile once the masonry pr is merged.

**Comment by 1aurabrown** [comment]
closing
