### ISSUE TITLE
Incorrect state for orientation

### ISSUE THREAD

**Issue by alloy** [artsy/eigen#448]
Yesterday I was able to get the iPad into this state once, alas I was not able to reproduce it yet.

![img_0046](https://cloud.githubusercontent.com/assets/2320/7680149/ff63f046-fd63-11e4-8f08-3eca2e9c4ccf.PNG)

**Comment by 1aurabrown** [comment]
may be my fault from recent change, but i did check this and i thought it was working in all views.

**Comment by 1aurabrown** [comment]
I haven't been able to reproduce this

**Comment by alloy** [comment]
Have still not been able to reproduce this, so gonna close it.
