### ISSUE TITLE
Fair navigation menu is confusing on iPad

### ISSUE THREAD

**Issue by alloy** [artsy/eigen#449]
I understand that we're just showing a force view, but the menu is confusing in the context of Eigen’s own tab bar.

Specifically, the `HOME` entry makes it seem as if it could be the same as Eigen’s `HOME` tab, when it is in fact the fair’s home page. It doesn’t help that the other entries also seem to reflect those in Eigen’s tab bar (`BROWSE` -> `EXPLORE`, `FOR YOU` -> `YOU`, `ARTICLES` -> `MAG`).

I’m thinking that if `HOME` were renamed to `FAIR`, the other entries might also be more in context.

@katarinabatina What are your thoughts on this?

![ios simulator screen shot 18 may 2015 13 49 52](https://cloud.githubusercontent.com/assets/2320/7680241/dc25bc1c-fd64-11e4-8d71-949f8eeade0b.png)

**Comment by katarinabatina** [comment]
it's a force story getting worked on here https://github.com/artsy/force/issues/2853 

I'm gonna go ahead and close this one.
