### ISSUE TITLE
logged out fair guide scroll view weirdness

### ISSUE THREAD

**Issue by orta** [artsy/eigen#45]
_From @1aurabrown on July 9, 2014 22:5_

Looking through the fair changes, some things i noticed:

![personal_2](https://cloud.githubusercontent.com/assets/3171662/3531804/c0591ca6-07b3-11e4-961a-6890bd5512c1.gif)
![personanl_1](https://cloud.githubusercontent.com/assets/3171662/3531805/c05b319e-07b3-11e4-9980-4bbe16f77656.gif)
- ~~on first scroll after entering the personalized guide, scroll view jumps at first (this is visible in both gifs)~~
- ~~dragging up results in the scroll indicator jiggling around (see gif 1)~~
- scroll view has a much bigger height than the actual content, all the content fits well within the bounds of the screen but there is a ton of white space under the content. (see gif 2)
- ~~dragging down, the scroll indicator looks pretty weird as a floating bar midway between the top and bottom of the screen -- i propose we just turn off scroll indicators for this view. (see gif 2)~~

subjective things i noticed but that are not urgent for this release:
- when i drag down, my expectation is to enter the expanded map view, but this expectation is not met
- i expect to be able to pan the map without entering the expanded map view
  i think both these last two things things used to be possible, i'm assuming we changed them for a reason.

_Copied from original issue: artsy/eigen-private#1850_

**Comment by orta** [comment]
The big weird one here IMO is that you can contact the map when you're logged out, doesn't make sense.

**Comment by katarinabatina** [comment]
no longer relevant
