### ISSUE TITLE
missing show images in the carousel on home view

### ISSUE THREAD

**Issue by katarinabatina** [artsy/eigen#450]
http://cl.ly/image/2p2G3f142H0y

**Comment by alloy** [comment]
I have not been able to reproduce this. Can you reliably do so? If so, are there certain steps to take?

**Comment by 1aurabrown** [comment]
This should be fixed by https://github.com/ashfurrow/ARCollectionViewMasonryLayout/pull/25. I'll keep this issue open even though it's really a masonry layout issue, as a reminder to update eigen's podfile once the masonry pr is merged.

**Comment by 1aurabrown** [comment]
sorry commented on the wrong issue

**Comment by katarinabatina** [comment]
Cannot reproduce, it has happened before, perhaps it's related to admin functionality I have no idea. Let's shelf it for now

**Comment by alloy** [comment]
Gonna close this for now, so that we have a better idea of what’s actually actionable. This can always be re-opened anyways.
