### ISSUE TITLE
Contact Gallery button fade animation feels slow when it comes in the first time

### ISSUE THREAD

**Issue by katarinabatina** [artsy/eigen#451]
![image](https://cloud.githubusercontent.com/assets/6482926/7691541/496c7120-fd89-11e4-9270-d3cc32f7c16d.png)

**Comment by alloy** [comment]
To be clear, this is the first time _after a cold start of the application_. Once the application is running, the button shows up a lot sooner.

**Comment by 1aurabrown** [comment]
wait, what? why would the animation be slower on the first start?

**Comment by 1aurabrown** [comment]
is there any reason not to remove the animation all together? i don't think it adds much.

**Comment by orta** [comment]
Think removing the animation is fine IMO

**Comment by orta** [comment]
fixed by #479
