### ISSUE TITLE
Works in show not laid out correctly 

### ISSUE THREAD

**Issue by katarinabatina** [artsy/eigen#452]
![image](https://cloud.githubusercontent.com/assets/6482926/7691571/9552b234-fd89-11e4-82d5-910d2c08c88c.png)
 
horizontal should be three column

![image](https://cloud.githubusercontent.com/assets/6482926/7691578/a14ec88e-fd89-11e4-8d76-cecabdcf4fe7.png)

vertical should be two column

**Comment by 1aurabrown** [comment]
On it. This was a bug i introduced last week.




On Mon, May 18, 2015 at 18:13, Katarina Batina <notifications@github.com> wrote:
image
[https://cloud.githubusercontent.com/assets/6482926/7691571/9552b234-fd89-11e4-82d5-910d2c08c88c.png]
[https://cloud.githubusercontent.com/assets/6482926/7691571/9552b234-fd89-11e4-82d5-910d2c08c88c.png]

horizontal should be three column

image
[https://cloud.githubusercontent.com/assets/6482926/7691578/a14ec88e-fd89-11e4-8d76-cecabdcf4fe7.png]
[https://cloud.githubusercontent.com/assets/6482926/7691578/a14ec88e-fd89-11e4-8d76-cecabdcf4fe7.png]

vertical should be two column

**Comment by 1aurabrown** [comment]
This should be fixed by https://github.com/artsy/eigen/pull/456
