### ISSUE TITLE
show details text too small

### ISSUE THREAD

**Issue by katarinabatina** [artsy/eigen#453]
![image](https://cloud.githubusercontent.com/assets/6482926/7691628/0107aa2a-fd8a-11e4-8037-227f820b0027.png)

on both iphone and ipad these should be 32 px (retina) (also increase line spacing)

![image](https://cloud.githubusercontent.com/assets/6482926/7691670/5923d260-fd8a-11e4-8b5c-c52e37bf794d.png)

**Comment by orta** [comment]
@sarahscott wanna take this?

**Comment by orta** [comment]
Estimate ( for sarah): 2-3 hours

**Comment by katarinabatina** [comment]
@sarahscott if you could ping me when you've got snapshots ready let me know! thanks!

**Comment by sarahscott** [comment]
I'll start on it today and likely finish tomorrow - will send snapshots asap!

**Comment by sarahscott** [comment]
@katarinabatina how's this?

![ios simulator screen shot may 27 2015 2 21 37 pm](https://cloud.githubusercontent.com/assets/2712962/7844219/c7b91bb0-047c-11e5-97f9-57f8ee58b2d6.png)
