### ISSUE TITLE
Dev question: why eigen merged with Emissions

### ISSUE THREAD

**Issue by jacksbox** [artsy/eigen#4561]
Hello, this is no real issue, more a question for the artsy dev team (found no suitable mail address, so I thought github would be the next best place for this):
I'm working on project where we have a native iOS app (with more iOS and android apps in development) and we would like to develop some features as react native modules so we can share it between apps. 
Researching this I stumbled upon your dev blog, which I really like 😄 , and explored how you tackled basically the same approach. So far so good, but now I see you merged the react native code in the iOS repo - what was the reason for this? Are there big benefits (or disadvantages the other way)?

So far, thanks a lot for your highly informative blog and your open source projects - they give great support on my quest 👍

**Comment by ds300** [comment]
Hi! 👋🏼  Sorry for the delay in getting back to you.

We merged emission with eigen to reduce development friction while paving the way for supporting Android devices. Basically our goal was to make the eigen repo look like a normal react-native app repo.

In terms of reducing development friction it was an enormous success. It allowed us to incrementally refactor the app to be compatible with Android without blocking work on new features.

Also android support is done and we're just polishing the app in preparation for a public android release.

I very much recommend keeping everything in one repo!
