### ISSUE TITLE
after singing up with twitter, full name and email form formatting is off

### ISSUE THREAD

**Issue by katarinabatina** [artsy/eigen#457]
![image](https://cloud.githubusercontent.com/assets/6482926/7735497/92eea178-ff0b-11e4-9fd7-345726036191.png)

![image](https://cloud.githubusercontent.com/assets/6482926/7735503/9e9a85f0-ff0b-11e4-9670-5fa958141e38.png)

**Comment by katarinabatina** [comment]
update, same thing happens when using facebook to sign up

**Comment by orta** [comment]
closed by #480
