### ISSUE TITLE
Inquiries popover says "yo" at the bottom 

### ISSUE THREAD

**Issue by orta** [artsy/eigen#461]
![img_0070](https://cloud.githubusercontent.com/assets/49038/7742047/04d433d2-ff81-11e4-97e1-9ae3d29975a6.PNG)

I'm a logged out user, tested on a few artworks and it shows every time.

**Comment by 1aurabrown** [comment]
I think you were in fact logged in as a user names Yo

If you were logged out, there would be a name and email field on the top of the form

**Comment by orta** [comment]
:+1:
