### ISSUE TITLE
from /auctions, tapping register to bid for a logged out should pop sign up

### ISSUE THREAD

**Issue by katarinabatina** [artsy/eigen#464]
Right now, when I tap register to bid on /auctions from the explore page, I am shot into the registration flow where I am asked for a CC and other info, we need to have the user sign up first, then throw them into this screen. 

http://cl.ly/image/3S3s1A0o3k2F

**Comment by orta** [comment]
Estimate: 2-4 hours

**Comment by orta** [comment]
Hrm this might be related to #470

**Comment by 1aurabrown** [comment]
I thought this was closed because they took this button out of the /auctions page?

**Comment by alloy** [comment]
![auction-register](https://cloud.githubusercontent.com/assets/2320/8408465/a6feb1ec-1e70-11e5-9803-570d49fcf7fa.gif)

Seems fixed.
