### ISSUE TITLE
animation of artwork details is messy

### ISSUE THREAD

**Issue by katarinabatina** [artsy/eigen#465]
on artwork details page when the ipad is rotated the righthand column details float across the artwork in a white box, looks buggy 

![image](https://cloud.githubusercontent.com/assets/6482926/7751661/21d2ee92-ffa9-11e4-8eb5-605b0238336a.png)

**Comment by orta** [comment]
Pretty sure this has come up before, but searching issues came up empty. 
Estimate: 1/2 day.
