### ISSUE TITLE
back navigation disabled

### ISSUE THREAD

**Issue by katarinabatina** [artsy/eigen#466]
went to artist page, picked an artwork, back button went gray, cannot navigate back, have to restart app 

![image](https://cloud.githubusercontent.com/assets/6482926/7751819/e9103a8c-ffa9-11e4-8f4b-b86eb7741b7b.png)

**Comment by ashfurrow** [comment]
Reproduced by starting an interactive pop (start slide from the left hand side of the screen), then returning the view to normal.
