### ISSUE TITLE
logged out user contact gallery flow has weird dummy type in the email and name fields

### ISSUE THREAD

**Issue by katarinabatina** [artsy/eigen#467]
![image](https://cloud.githubusercontent.com/assets/6482926/7751888/6a142120-ffaa-11e4-8bb8-33efeb3c6de6.png)

**Comment by orta** [comment]
This really does feel like you're logged in with a generic account

**Comment by orta** [comment]
Nah, this is very likely from another test run of yours, it saves it between sessions ( so you don't have to put it in multiple times. )

Just happened to me :D
