### ISSUE TITLE
force views appear to think I am logged in

### ISSUE THREAD

**Issue by katarinabatina** [artsy/eigen#470]
on the fair overview page, I get this unit "works by artists I follow" which shouldn't be surfaced if I am logged out (which I am) 

![image](https://cloud.githubusercontent.com/assets/6482926/7752289/a1854a2e-ffac-11e4-8a92-4a5d619425ec.png)

might be related to #467 #464

**Comment by orta** [comment]
Same, this is likely a force bug.

**Comment by orta** [comment]
This may be by design though, but I see the exact same works /cc @craigspaeth

**Comment by 1aurabrown** [comment]
apparently this isn't a force ~bug~ it's the way that made the most sense for them, and it's kind of a pain for them to change just for us to not push a new page. i really thinkt here should be some way that they communicate to us the rare cases where a page reload should not be treated as a new page on our end.

**Comment by 1aurabrown** [comment]
There's also the opposite issue, which comes up more often -- force push state should really be a new page on our end, rather than an update to the existing page. not sure if there is a great solution to that.

**Comment by orta** [comment]
we should make a convention on url params around these kind of things. One for ignoring the push, and another for forcing a push.

**Comment by 1aurabrown** [comment]
somehow commented on the wrong issue again - i was referring to https://github.com/artsy/eigen/issues/471

**Comment by katarinabatina** [comment]
@1aurabrown where is the force issue for this?

**Comment by broskoski** [comment]
@katarinabatina these are artists you are following right?

**Comment by katarinabatina** [comment]
@broskoski this is the "artists you follow at fair X" however these are not artists I follow, additionally, I'm not logged in.

**Comment by 1aurabrown** [comment]
whoops, here https://github.com/artsy/force/issues/2901

**Comment by alloy** [comment]
> @broskoski: Talked offline with @katarinabatina and @orta, closing this until we can be sure it's not just a problem with Eigen Beta.

@katarinabatina @orta What’s the status on this?

**Comment by katarinabatina** [comment]
Close 

Katarina

**Comment by alloy** [comment]
:+1:
