### ISSUE TITLE
other works in show do not show all the other works in a show

### ISSUE THREAD

**Issue by katarinabatina** [artsy/eigen#472]
there seems to be a cap of how many works are show on an artwork page underneath other works in the show header 

see this show from Trevor Bell http://cl.ly/image/30073u0u3p0Y

Compared to how many works are in the show here https://www.artsy.net/artwork/trevor-bell-bernina

**Comment by orta** [comment]
This could be that we have an artworks limit and have to paginate.

Estimate: 1 day.

**Comment by alloy** [comment]
How would pagination work when there’s also a section underneath it? Like in @katarinabatina’s example there is the “Other Works by Author” section.
