### ISSUE TITLE
tapping close on search does not close keyboard

### ISSUE THREAD

**Issue by katarinabatina** [artsy/eigen#473]
close tap area could probably be increased as well 

![https://s3.amazonaws.com/f.cl.ly/items/3C2f2z2a0o30280k0u3l/Screen%20Recording%202015-05-21%20at%2011.52%20AM.gif](https://s3.amazonaws.com/f.cl.ly/items/3C2f2z2a0o30280k0u3l/Screen%20Recording%202015-05-21%20at%2011.52%20AM.gif)

**Comment by orta** [comment]
I have no clue here, feels like an apple bug.
Estimate: ? ( may not even be addressable )

The close button should be resized though :dancers: 
Estimate: 30m

**Comment by 1aurabrown** [comment]
the keyboard thing is our fault -- the search view never resigns first responder.
maybe this wasn't an issue before, when we were removing inactive tabs from the hierarchy. anyway, fix ~10 minutes
