### ISSUE TITLE
artwork buttons do not work

### ISSUE THREAD

**Issue by katarinabatina** [artsy/eigen#474]
go to artwork page, try to tap contact button, nothing happens, tapping heart, share, auction results, nothing happens. Go to different artwork try all the same buttons again, nothing. 

http://cl.ly/image/0q210b0z1j0N

**Comment by 1aurabrown** [comment]
I don't see this happening for me

**Comment by 1aurabrown** [comment]
i got this to happen in the simulator, but i can't figure out how

**Comment by 1aurabrown** [comment]
i can not for the life of me figure out how to make this bug happen but it is real
