### ISSUE TITLE
Add new works for you "bell" in global navigation

### ISSUE THREAD

**Issue by katarinabatina** [artsy/eigen#483]

**Comment by katarinabatina** [comment]
![image](https://cloud.githubusercontent.com/assets/6482926/8084380/b542774c-0f58-11e5-878b-e4332ba513a4.png)

**Comment by katarinabatina** [comment]
http://cl.ly/image/2F0i131f2e0i

Will prepare bell asset soon.

**Comment by alloy** [comment]
@katarinabatina Can you get me that asset today?

**Comment by alloy** [comment]
Depends on https://github.com/artsy/gravity/pull/9058 for polling status to work, not for push notifications.

**Comment by alloy** [comment]
@katarinabatina I know we discussed this somewhere, but clearly not here; what happens when the user is trial user (not signed-in)? The same as with ‘YOU’?

**Comment by alloy** [comment]
@katarinabatina What do you think of the font?

![ios simulator screen shot 04 jul 2015 00 55 52](https://cloud.githubusercontent.com/assets/2320/8505501/aa034220-21e7-11e5-8b45-3d14c57069fb.png)

**Comment by alloy** [comment]
Next week I still need to do:

- [ ] Update badge when a push notification comes in.
- [ ] Update badge after sign-in during on boarding (currently you need to launch the app _signed-in_ for the number to populate)
- [ ] Look into when notifications are considered ‘seen’ and implement that.

**Comment by katarinabatina** [comment]
Are we also moving search? 

Katarina

**Comment by katarinabatina** [comment]
Looks great

Katarina

**Comment by katarinabatina** [comment]
Yup, pop sign up

Katarina

**Comment by alloy** [comment]
I used the same on boarding message as fair guides show:

> Sign up for a free account to get personal recommendations.

![ios simulator screen shot 04 jul 2015 10 39 08](https://cloud.githubusercontent.com/assets/2320/8507223/3cbb3b94-2239-11e5-8679-7885d0c96681.png)

**Comment by alloy** [comment]
> Are we also moving search?

I want to, yes.

**Comment by alloy** [comment]
This has been implemented by #581.
