### ISSUE TITLE
Fix crash in - [ARArtworkViewController viewWillTransitionToSize:withTransitionCoordinator:], line 194

### ISSUE THREAD

**Issue by artsyit** [artsy/eigen#496]
### Stacktrace ###

<pre>ARArtworkViewController;viewWillTransitionToSize:withTransitionCoordinator:;ARArtworkViewController.m;194</pre>

### Reason ###

objc_msgSend() selector name: _duration

### Link to HockeyApp ###

* [https://rink.hockeyapp.net/manage/apps/37020/crash_reasons/36333941](https://rink.hockeyapp.net/manage/apps/37020/crash_reasons/36333941)

**Comment by ashfurrow** [comment]
Fixed by https://github.com/artsy/eigen/pull/495
