### ISSUE TITLE
Certificates Setup

### ISSUE THREAD

**Issue by esttorhe** [artsy/eigen#5]
Maybe I'm missing something but this line right here looks «impossible» for non-artsy employees
>Login as it@artsymail.com to Certificates, Identities and Profiles.

Which then takes us to the next issue:
>Have the admin approve your certificate.

Unless the project doesn't actually required this and perhaps it could be removed from the setup steps for the OSS version?

**Comment by esttorhe** [comment]
I just noticed that perhaps that kind of a "regular how to user a development device" instruction set but doesn't look like its required for this codebase.

**Comment by orta** [comment]
I think in general this is reasonable, I'd like to hope that OSS people aren't submitting our app to the store. I kept it in as it can act as a linkable guide for others doing certificate setup. Know it's a pain.

**Comment by esttorhe** [comment]
I guess it makes more sense for future Artsy devs coming to the project but the `it@artsymail.com` part won't make much sense for developers outside the organization.

No biggie; just wanted to brought it to light in case you did not notice it.

Feel free to close it anytime :) :lock:

**Comment by orta** [comment]
:heart:

**Comment by pcompassion** [comment]
how do I login?

`Login as it@artsymail.com to Certificates, Identities and Profiles.`

I don't know the password?

**Comment by orta** [comment]
@pcompassion we don't give out our password for iTunes Connect etc.

I'll make a note about changing the bundle id to be something that you own in order to run it on a device.
