### ISSUE TITLE
Webviews get incorrect extra top margin

### ISSUE THREAD

**Issue by alloy** [artsy/eigen#500]
Reproduction:
1. Load a webview, e.g. a fair on iPad or the museums overview on iPhone
2. Hide Artsy app, e.g. press home button
3. Launch Artsy app again
4. Observe extra margin being applied
### iPad

![ios simulator screen shot 03 jun 2015 12 46 15](https://cloud.githubusercontent.com/assets/2320/7958708/289fc1ac-09f2-11e5-974e-ffcc26a3c6f8.png)
### iPhone

![ios simulator screen shot 03 jun 2015 13 13 27](https://cloud.githubusercontent.com/assets/2320/7958734/636dddf0-09f2-11e5-91c4-aafb560a6c55.png)

**Comment by orta** [comment]
interesting, you should validate that this is not on purpose in martsy to deal with our occasional "remove 20px from the top" bug

**Comment by alloy** [comment]
@orta Do you have (links to) information on that issue for me?

**Comment by alloy** [comment]
It’s weird to add the margin after the app becomes active again, though.

**Comment by katarinabatina** [comment]
think we're good to close this
