### ISSUE TITLE
[iPad - fullscreen artwork] Incorrect content mode

### ISSUE THREAD

**Issue by alloy** [artsy/eigen#503]
Reproduction:

1. Load [a portrait artwork](http://www.artsy.net/artwork/amber-cowan-peach-bloom-after-the-morgan-vase) and show it fullscreen in landscape orientation
2. Observe artwork being stretched horizontally

![ios simulator screen shot 03 jun 2015 13 20 23](https://cloud.githubusercontent.com/assets/2320/7958958/c292c334-09f4-11e5-9079-59251c4f0e91.png)

**Comment by alloy** [comment]
Ok, the problem is, of course, harder than anticipated. What’s happening is that `ARTiledImageView` is [expecting all tiles to be equally sized](https://github.com/dblock/ARTiledImageView/blob/cd3cd38828535ed8b48bcd7b1f12835d8214a112/Classes/ARTiledImageView.m#L98) and `ARTile` is [rendering into that size](https://github.com/dblock/ARTiledImageView/blob/796fc58e4e05e36bba9290f694d7ddf79b96163f/Classes/ARTile.m#L26) regardless of the tile image’s _atcual_ size.

The docs of `-[UIImage drawInRect:blendMode:alpha:]` states:

> This method scales the image as needed to make it fit in the specified rectangle.

For the image shown in the original report, this means that it is rendering the following tile at 512x512, which is clearly gonna stretch it horizontally (it’s 245x512):

![](https://d32dm0rphc51dk.cloudfront.net/qP8pgtyaDvukIPQmZ-ok1w/dztiles/11/1_1.jpg)

**Comment by alloy** [comment]
This means it’s probably gonna be more involved to fix than just a few hours, so I’m gonna defer this till later.

**Comment by 1aurabrown** [comment]
how often does this happen, and why aren't our image tiles being sliced into squares? is it expected that the client lays out the tiles properly regarless of their format, or is it a mistake on the image processing end that they aren't square?

**Comment by alloy** [comment]
Good questions, @joeyAghion do you have an answer to whether or not this should be happening at all?

**Comment by joeyAghion** [comment]
I don't know much about our tiling (@mzikherman want to chime in?), but I expect that those at the periphery can be non-square. I.e., if a full-size image can't be sliced evenly into 512x512 squares, the tiles at the edges will have a dimension <512. What's the alternative... fill that space with black?

**Comment by alloy** [comment]
@joeyAghion No I think it makes total sense that those aren’t 512, it’s just that seeing as @dblock wrote this code for Eigen I wanted to know for sure that I wasn’t missing anything. Which I’m clearly not :+1:

**Comment by mzikherman** [comment]
yes that's exactly right, they may not be square around the periphery. Here's a spec from our image processing service showing that: https://github.com/artsy/gemini/blob/master/spec/util/entry_version_image_processor_spec.rb#L149-L166

**Comment by alloy** [comment]
@mzikherman Ace, thanks.

**Comment by orta** [comment]
Pretty sure this is not new though, the image tiling engine Leonard & I wrote is now 4+ years old with very little core changes. Feels more like a CGContext being stretched though iPad rotation rather than us not handling it correctly at the framework level ( I've not seen this problem in Folio for example )

**Comment by alloy** [comment]
@orta No it’s definitely not that, you don’t need to rotate to trigger this. If you look at the code I link to in my first comment than you can see it doesn’t take tiles of other sizes into account.

**Comment by alloy** [comment]
@1aurabrown This one doesn’t have the highest priority btw, it’s been there for a good while now, so it’s fine if we’re to move this to the next sprint.
