### ISSUE TITLE
[iPhone] ArtworkVC rotation removes the insets for the related information under the artwork

### ISSUE THREAD

**Issue by orta** [artsy/eigen#505]
Easily reproducible by rotating into a VIR on an artwork, e.g. https://www.artsy.net/artwork/jacqueline-fowler-amari-vase-and-white-japonica

### Before

![screen_shot_2015-06-04_at_9 11 34_am](https://cloud.githubusercontent.com/assets/2320/7985253/c9e99a28-0acf-11e5-98ca-03b27afee381.png)

### After

![screen_shot_2015-06-04_at_9 11 39_am](https://cloud.githubusercontent.com/assets/2320/7985255/cbbd130c-0acf-11e5-9505-7522568d09bb.png)

**Comment by alloy** [comment]
Do you mean the following?

![ios simulator screen shot 03 jun 2015 15 59 42](https://cloud.githubusercontent.com/assets/2320/7961744/a182058c-0a09-11e5-80fc-a290efcf7540.png)

VS

![ios simulator screen shot 03 jun 2015 15 59 57](https://cloud.githubusercontent.com/assets/2320/7961745/a65e6f28-0a09-11e5-8dee-20b88c36810b.png)

**Comment by alloy** [comment]
It also removes the side insets around the artwork btw:

![ios simulator screen shot 03 jun 2015 16 05 12](https://cloud.githubusercontent.com/assets/2320/7961866/63f6b7e8-0a0a-11e5-8ba2-6b414cc34454.png)

VS

![ios simulator screen shot 03 jun 2015 16 05 18](https://cloud.githubusercontent.com/assets/2320/7961869/69dc2c42-0a0a-11e5-8b33-e7f7b9b9e830.png)

**Comment by orta** [comment]
The thing I noticed was related works, but same same. Very likely the same problem.

**Comment by alloy** [comment]
Hmm, the current App Store version (1.8.0) doesn’t ever show see insets around the artwork, so what is the expected behaviour?

**Comment by orta** [comment]
Full bleed for iPhone, insets for iPad

**Comment by alloy** [comment]
[This] is the constraint that is making the artwork not showing from side to side initially. The image view is actually being shown from side to side, but the height is being constraint, which leads the image to being centered in the too wide image view.

![screen shot 2015-06-03 at 18 12 52](https://cloud.githubusercontent.com/assets/2320/7965206/4f2ce532-0a1c-11e5-9c4d-fe8c0aa557fd.png)

**Comment by ashfurrow** [comment]
I'm able to reproduce the problem with the bottom inset of the scroll view easily.

The problem with the image side insets seems to be trickier. I can't reproduce it anymore, on a phone or simulator.

**Comment by ashfurrow** [comment]
Concentrating on the problem with the bottom insets now; very strange. Could be something to do with using `UIPageViewController`. Investigating.

**Comment by ashfurrow** [comment]
I think it may have to do with the constraints on the tab content view in the top menu view controller, since rotating, then rotating back to portrait to produce the bug, then pushing an artist VC, then popping, fixes the problem.

**Comment by alloy** [comment]
I disabled that constraint that makes the artwork have incorrect side insets and then grabbed the view hierarchy description before and after triggering the incorrect bottom inset. Here’s the diff:

```diff
@@ -5,11 +5,11 @@
    |    |    | ARNavigationController:0x7d0bd200 2c.[ARShowFeedViewController 0x7b19d470: ARArtworkSetViewController 0x7c091800: ] <UILayoutContainerView: 0x7b19e550; frame = (0 0; 320 434); autoresize = W+H; gestureRecognizers = <NSArray: 0x7b059dc0>; layer = <CALayer: 0x7b19e220>>
    |    |    |    | <UINavigationTransitionView: 0x7b058090; frame = (0 0; 320 434); clipsToBounds = YES; autoresize = W+H; layer = <CALayer: 0x7b04ab40>>
    |    |    |    |    | <UIViewControllerWrapperView: 0x7af50dd0; frame = (0 0; 320 434); autoresize = W+H; layer = <CALayer: 0x7af50830>>
-   |    |    |    |    |    | ARArtworkSetViewController:0x7c091800 1c.[ARArtworkViewController 0x7aebf0c0: ] <_UIPageViewControllerContentView: 0x7aebca10; frame = (0 0; 320 434); clipsToBounds = YES; opaque = NO; autoresize = W+H; layer = <CALayer: 0x7aeb6b20>>
-   |    |    |    |    |    |    | <_UIQueuingScrollView: 0x7c0ad200; frame = (0 0; 320 434); clipsToBounds = YES; gestureRecognizers = <NSArray: 0x7aec1000>; layer = <CALayer: 0x7aeb2da0>; contentOffset: {320, 0}; contentSize: {960, 434}>
-   |    |    |    |    |    |    |    | <UIView: 0x7aebfa10; frame = (0 0; 320 434); layer = <CALayer: 0x7aebfaa0>>
-   |    |    |    |    |    |    |    | <UIView: 0x7aebfaf0; frame = (320 0; 320 434); layer = <CALayer: 0x7aebfb80>>
-   |    |    |    |    |    |    |    |    | ARArtworkViewController:0x7aebf0c0 1c.[ARPostsViewController 0x7b0e0760: ] <ARArtworkView: 0x7c111000; baseClass = UIScrollView; frame = (0 0; 320 434); clipsToBounds = YES; autoresize = W+H; gestureRecognizers = <NSArray: 0x7aec5630>; layer = <CALayer: 0x7aec5b60>; contentOffset: {0, 402}; contentSize: {320, 836}>
+   |    |    |    |    |    | * OVERLAP! ARArtworkSetViewController:0x7c091800 1c.[ARArtworkViewController 0x7aebf0c0: ] <_UIPageViewControllerContentView: 0x7aebca10; frame = (0 0; 320 480); clipsToBounds = YES; opaque = NO; autoresize = W+H; layer = <CALayer: 0x7aeb6b20>>
+   |    |    |    |    |    |    | <_UIQueuingScrollView: 0x7c0ad200; frame = (0 0; 320 480); clipsToBounds = YES; gestureRecognizers = <NSArray: 0x7aec1000>; layer = <CALayer: 0x7aeb2da0>; contentOffset: {320, 0}; contentSize: {960, 480}>
+   |    |    |    |    |    |    |    | <UIView: 0x7aebfa10; frame = (0 0; 320 480); layer = <CALayer: 0x7aebfaa0>>
+   |    |    |    |    |    |    |    | <UIView: 0x7aebfaf0; frame = (320 0; 320 480); layer = <CALayer: 0x7aebfb80>>
+   |    |    |    |    |    |    |    |    | ARArtworkViewController:0x7aebf0c0 1c.[ARPostsViewController 0x7b0e0760: ] <ARArtworkView: 0x7c111000; baseClass = UIScrollView; frame = (0 0; 320 480); clipsToBounds = YES; autoresize = W+H; gestureRecognizers = <NSArray: 0x7aec5630>; layer = <CALayer: 0x7aec5b60>; contentOffset: {0, 356}; contentSize: {320, 836}>
    |    |    |    |    |    |    |    |    |    | <ORTagBasedAutoStackView: 0x7aec5ff0; frame = (0 0; 320 836); layer = <CALayer: 0x7aec6160>>
    |    |    |    |    |    |    |    |    |    |    | <ARArtworkMetadataView: 0x7aec9560; frame = (0 0; 320 816); tag = 3; layer = <CALayer: 0x7aec9740>>
    |    |    |    |    |    |    |    |    |    |    |    | <UIView: 0x7aed4690; frame = (0 0; 320 419); layer = <CALayer: 0x7aed4720>>
@@ -50,13 +50,13 @@
    |    |    |    |    |    |    |    |    |    |    | XX (<ARAuctionBannerView: 0x7b045a50; frame = (0 0; 320 0); tag = 1; layer = <CALayer: 0x7b074910>>)
    |    |    |    |    |    |    |    |    |    |    |    | XX (<UILabel: 0x7b0bdd90; frame = (20 0; 280 0); userInteractionEnabled = NO; layer = <_UILabelLayer: 0x7b07b360>>)
    |    |    |    |    |    |    |    |    |    |    | XX (<ARWhitespaceGobbler: 0x7b022d90; frame = (-320 816; 0 0); tag = 9; layer = <CALayer: 0x7b045f90>>)
-   |    |    |    |    |    |    |    |    |    | XX (<UIImageView: 0x7aeda240; frame = (313 411.5; 7 2.5); alpha = 0; opaque = NO; autoresize = TM; userInteractionEnabled = NO; layer = <CALayer: 0x7aeda340>>)
+   |    |    |    |    |    |    |    |    |    | XX (<UIImageView: 0x7aeda240; frame = (313 457.5; 7 2.5); alpha = 0; opaque = NO; autoresize = TM; userInteractionEnabled = NO; layer = <CALayer: 0x7aeda340>>)
    |    |    |    |    |    |    |    |    |    | XX (<UIImageView: 0x7aeda830; frame = (314.5 626; 2.5 207); alpha = 0; opaque = NO; autoresize = LM; userInteractionEnabled = NO; layer = <CALayer: 0x7aeda930>>)
-   |    |    |    |    |    |    |    | <UIView: 0x7aebfbb0; frame = (640 0; 320 434); layer = <CALayer: 0x7aebfc40>>
+   |    |    |    |    |    |    |    | <UIView: 0x7aebfbb0; frame = (640 0; 320 480); layer = <CALayer: 0x7aebfc40>>
    |    |    |    | <UIView: 0x7b059eb0; frame = (0 0; 320 20); layer = <CALayer: 0x7b059e10>>
-   |    |    |    | XX (<ARMenuButton: 0x7b05b0c0; baseClass = UIButton; frame = (12 32; 40 40); clipsToBounds = YES; alpha = 0; opaque = NO; layer = <CALayer: 0x7b05ae80>>)
+   |    |    |    | <ARMenuButton: 0x7b05b0c0; baseClass = UIButton; frame = (12 32; 40 40); clipsToBounds = YES; opaque = NO; layer = <CALayer: 0x7b05ae80>>
    |    |    |    |    | <CALayer: 0x7b05be40> (layer)
-   |    |    |    |    | XX (<UIImageView: 0x7af33a40; frame = (9.5 10.5; 21 19); clipsToBounds = YES; opaque = NO; userInteractionEnabled = NO; layer = <CALayer: 0x7af314d0>>)
+   |    |    |    |    | <UIImageView: 0x7af33a40; frame = (9.5 10.5; 21 19); clipsToBounds = YES; opaque = NO; userInteractionEnabled = NO; layer = <CALayer: 0x7af314d0>>
    |    |    |    |    | XX (<UIButtonLabel: 0x7b05b250; frame = (20 11.5; 0 17); hidden = YES; opaque = NO; userInteractionEnabled = NO; layer = <_UILabelLayer: 0x7b05b340>>)
    |    | <UIView: 0x7b073380; frame = (0 434; 320 46); layer = <CALayer: 0x7b064ee0>>
    |    |    | <ARNavigationTabButton: 0x7b0734f0; baseClass = UIButton; frame = (0 0.5; 46 45.5); alpha = 0.7; opaque = NO; layer = <CALayer: 0x7b073730>>
```

The difference in height of the overall views is 46 (480 - 434) and the other difference is that a `ARMenuButton` instance with a height of 40 has an alpha of 0 before and an alpha of 1 after. I don’t know if a view with an alpha of 0 can influence the view layout, though.

**Comment by alloy** [comment]
Ok, that button is the navigation controller’s back button. Removing it from the view hierarchy indeed fixes the layout problem:

```
(lldb) expr (void)[0x7b05b0c0 removeFromSuperview]

(lldb) po [[[UIApplication sharedApplication] keyWindow] recursiveDescription]
[SNIP]
   |    |    |    |    |    | ARArtworkSetViewController:0x7c091800 1c.[ARArtworkViewController 0x7aebf0c0: ] <_UIPageViewControllerContentView: 0x7aebca10; frame = (0 0; 320 434); clipsToBounds = YES; opaque = NO; autoresize = W+H; layer = <CALayer: 0x7aeb6b20>>
   |    |    |    |    |    |    | <_UIQueuingScrollView: 0x7c0ad200; frame = (0 0; 320 434); clipsToBounds = YES; gestureRecognizers = <NSArray: 0x7aec1000>; layer = <CALayer: 0x7aeb2da0>; contentOffset: {320, 0}; contentSize: {960, 434}>
   |    |    |    |    |    |    |    | <UIView: 0x7aebfa10; frame = (0 0; 320 434); layer = <CALayer: 0x7aebfaa0>>
   |    |    |    |    |    |    |    | <UIView: 0x7aebfaf0; frame = (320 0; 320 434); layer = <CALayer: 0x7aebfb80>>
   |    |    |    |    |    |    |    |    | ARArtworkViewController:0x7aebf0c0 1c.[ARPostsViewController 0x7b0e0760: ] <ARArtworkView: 0x7c111000; baseClass = UIScrollView; frame = (0 0; 320 434); clipsToBounds = YES; autoresize = W+H; gestureRecognizers = <NSArray: 0x7aec5630>; layer = <CALayer: 0x7aec5b60>; contentOffset: {0, 402}; contentSize: {320, 836}>
[SNIP]
```

**Comment by alloy** [comment]
And here are screenshots that show the screen before and after the problem occurs. As you can see, the back button is present in the later case, where it’s not in the former. So somehow that button gets shown when transitioning back from the room view and somehow breaks the layout (still not sure why that is).

### Before

![ios simulator screen shot 04 jun 2015 13 08 19](https://cloud.githubusercontent.com/assets/2320/7982932/b06d597c-0abb-11e5-9a20-04842ed5f455.png)

### After

![ios simulator screen shot 04 jun 2015 13 08 07](https://cloud.githubusercontent.com/assets/2320/7982933/b91d3e84-0abb-11e5-9fab-e2c00dcd82c2.png)

**Comment by alloy** [comment]
Ok, so, it’s not the button per se, but removing it from the hierarchy triggers a re-layout of its superview which then gets played out correct, so the following fixes it too:

```
(lldb) po [0x7b05b0c0 superview]
ARNavigationController:0x7d0bd200 2c.[ARShowFeedViewController 0x7b19d470: ARArtworkSetViewController 0x7c091800: ] <UILayoutContainerView: 0x7b19e550; frame = (0 0; 320 434); autoresize = W+H; gestureRecognizers = <NSArray: 0x7b059dc0>; layer = <CALayer: 0x7b19e220>>

(lldb) expr (void)[0x7b19e550 setNeedsLayout]
(lldb) expr (void)[0x7b19e550 layoutIfNeeded]
```

So maybe that needs to be done after the transition finishes? (I don’t know anything about those transitions and or if that’s something that should be working as-is.)

**Comment by orta** [comment]
Shouldn't this affect other VCs then if it sits further up the VC chain?

**Comment by alloy** [comment]
My naive (about transitions) thought is that it might be something specifically about this room-view transition?

But possibly there’s another auto layout issue on the artwork view that influences this, but I haven’t been able to determine what that would be.

**Comment by ashfurrow** [comment]
I don't think other VCs allow landscape orientations, which would make the VIR transition unique.

**Comment by alloy** [comment]
This hack fixes it, but it reeks of not fully understanding the issue and it also doesn’t maintain the scroll position before and after showing the VIR view.

```diff
diff --git a/Artsy/Classes/Utils/Navigation Animations/ARViewInRoomTransition.m b/Artsy/Classes/Utils/Navigation Animations/ARViewInRoomTransition.m
index d276d5f..28f665e 100644
--- a/Artsy/Classes/Utils/Navigation Animations/ARViewInRoomTransition.m        
+++ b/Artsy/Classes/Utils/Navigation Animations/ARViewInRoomTransition.m        
@@ -162,6 +162,11 @@
         originalArtworkImageView.hidden = NO;
         [artworkImageView removeFromSuperview];
 
+        dispatch_async(dispatch_get_main_queue(), ^{
+            [artworkController.navigationController.view setNeedsLayout];
+            [artworkController.navigationController.view layoutIfNeeded];
+        });
+
         [transitionContext completeTransition:YES];
     }];
```

**Comment by alloy** [comment]
Ok, this thread went awry, as @orta and @ashfurrow & I were talking about different issues. I’ve updated the original issue with screenshots that show the problem that @orta meant and have splitted the other issues discussed in this thread out into:

* https://github.com/artsy/eigen/issues/506
* https://github.com/artsy/eigen/issues/507

**Comment by orta** [comment]
The crux that I've found is that [here](https://github.com/artsy/eigen/blob/cff8130b399688722a3cf1c365e75be9101cbefc/Artsy/Classes/View%20Controllers/ARArtworkMasonryModule.m#L87-87) we are setting the width of the collection view's internal state to be based on the "width"  that is the height:

![screen shot 2015-06-04 at 10 05 01 am](https://cloud.githubusercontent.com/assets/49038/7985766/36311348-0aa1-11e5-9a5a-9d7aa3d17bf6.png)

I'd guess that this could be that we're doing some layout invalidation before we can rely on the height to be correct

**Comment by orta** [comment]
Looks like doing this fixes it:
``` diff
diff --git a/Artsy/Classes/View Controllers/ARArtworkMasonryModule.m b/Artsy/Classes/View Controllers/ARArtworkMasonryModule.m
index e2e850a..5f32412 100644
--- a/Artsy/Classes/View Controllers/ARArtworkMasonryModule.m
+++ b/Artsy/Classes/View Controllers/ARArtworkMasonryModule.m
@@ -76,7 +76,7 @@
 + (CGFloat)dimensionForlayout:(ARArtworkMasonryLayout)layout useLandscapeValues:(BOOL)useLandscapeValues
 {
     CGRect screenRect = [[UIScreen mainScreen] bounds];
-    CGFloat width = CGRectGetWidth(screenRect);
+    CGFloat width = MIN(CGRectGetWidth(screenRect), CGRectGetHeight(screenRect));
```

**Comment by alloy** [comment]
👏🏿

**Comment by ashfurrow** [comment]
Coooool
