### ISSUE TITLE
[iPhone] Artwork image may not show from left to right.

### ISSUE THREAD

**Issue by alloy** [artsy/eigen#506]
In some cases, depending on the device screen size, an artwork image might not be shown from side to side. Going into VIR mode and back changes the layout and fixes it.

Reproduction:

1. Load app on a small screen device (e.g. 4S)
2. Load an artwork (with presumably an aspect ratio that doesn’t jibe well with the device screen size) such as https://www.artsy.net/artwork/donald-baechler-the-edible-daydream
3. Notice that there are seemingly margins on both sides. Mind you, these are not margins around the image view, rather the image is centered in the image view while maintaining the aspect ration and thus showing white borders.
    ![screen shot 2015-06-03 at 18 12 52](https://cloud.githubusercontent.com/assets/2320/7965206/4f2ce532-0a1c-11e5-9c4d-fe8c0aa557fd.png)
4. Enter VIR mode and leave it again
5. Notice that the image now shows from side to side. (In fact, the height of the image view is now larger than before.)

**Comment by alloy** [comment]
The issues seems related to [this](https://github.com/artsy/eigen/blob/1f388d2f668a2d98399982a6520af5028882c743/Artsy/Classes/Views/ARArtworkView.m#L139) constraint.

**Comment by 1aurabrown** [comment]
This is intended. We want to always fit the artwork in the screen and make it
apparent that there is content below, so there is a constraint to limit the
height (and therefore width, depending on the ratio) of the artwork

On Mon, Jun 8, 2015 at 08:35, artsy/eigen
<reply@reply.github.com>
wrote:
Assigned #506 [https://github.com/artsy/eigen/issues/506] to @1aurabrown [https://github.com/1aurabrown] .

**Comment by alloy** [comment]
@1aurabrown That’s fair and a good point, but shouldn’t that be maintained after entering VIR mode?

**Comment by 1aurabrown** [comment]
The return from VIR seems weird. I will check this out, something isn't right

On Mon, Jun 8, 2015 at 08:38, laura@artsymail.com <laura@artsymail.com> wrote:
This is intended. We want to always fit the artwork in the screen and make it
apparent that there is content below, so there is a constraint to limit the
height (and therefore width, depending on the ratio) of the artwork

On Mon, Jun 8, 2015 at 08:35, artsy/eigen
<reply@reply.github.com>
wrote:
Assigned #506 [https://github.com/artsy/eigen/issues/506] to @1aurabrown [https://github.com/1aurabrown] .

**Comment by 1aurabrown** [comment]
Yes, something in this sequence is broken. Will check it out.

On Mon, Jun 8, 2015 at 08:40, Eloy Durán <notifications@github.com> wrote:
@1aurabrown [https://github.com/1aurabrown] That’s fair and a good point, but shouldn’t that be maintained after entering
VIR mode?

—
Reply to this email directly or view it on GitHub
[https://github.com/artsy/eigen/issues/506#issuecomment-109979474] .[https://github.com/notifications/beacon/ADBlTi6TM92sWIgG2WPCFfSQlxsKEx8cks5oRYSsgaJpZM4E4Njg.gif]

**Comment by alloy** [comment]
@1aurabrown Well, testing with current master I can indeed no longer reproduce the originally described inconsistency. Feel free to close this one and create a new one about the animation.
