### ISSUE TITLE
FLKAutoLayout breaks with a layout guide object

### ISSUE THREAD

**Issue by alloy** [artsy/eigen#514]
It tries to call `superview` on it. On iOS 9 these guides are no longer `UIView` objects.

```
2015-07-03 15:52:09.007 Artsy[15521:73932] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[_UILayoutSpacer superview]: unrecognized selector sent to instance 0x7fc7be15fd00’
```

**Comment by alloy** [comment]
Work on-going in https://github.com/artsy/eigen/compare/eloy-iOS9, not sure yet if I like that stab at updating FLKAutoLayout, though.

**Comment by alloy** [comment]
https://github.com/alloy/FLKAutoLayout/tree/add-support-for-layout-guides

**Comment by alloy** [comment]
@floriankugler Have you run into this yet and/or what do you think of the way my changes are going?

**Comment by floriankugler** [comment]
@alloy None of my current projects are using this code, so I'm a bit out of the loop here... sorry!

**Comment by alloy** [comment]
I took a different route, instead I now wrap a VCs layout guides in a special FLKAutoLayout object that stores the VC’s view and the layout guide and use that to construct the NSLayoutConstraint: https://github.com/floriankugler/FLKAutoLayout/compare/master...alloy:add-support-for-layout-guides-take-2?expand=1

Which is used in Eigen here: https://github.com/artsy/eigen/commit/4a32a404bfd042935c074fdc5ad9c6442d42441b

It’s a much simpler and clear approach and works for all of the FLKAutoLayout API.
