### ISSUE TITLE
Stop using SiteFeatures

### ISSUE THREAD

**Issue by dblock** [artsy/eigen#516]
Eigen shipped with server-side support for a number of site-wide features.

From https://github.com/artsy/gravity/blob/master/lib/tasks/db_site_features.rake

```ruby
SiteFeature.find_or_create_by!(
        name: 'Eigen Onboard Skip Personalize',
        description: 'Skip personalize in Eigen onboarding'
      )
      SiteFeature.find_or_create_by!(
        name: 'Eigen Onboard Skip Collector Level',
        description: 'Skip collector level step in Eigen onboarding'
      )
      SiteFeature.find_or_create_by!(
        name: 'Eigen Onboard Skip Price Range',
        description: 'Skip prince range step in Eigen onboarding'
      )
      SiteFeature.find_or_create_by!(
        name: 'Eigen Onboard Prompt Threshold',
        description: 'Set number of actions allowed between sign-up prompts in Eigen onboarding'
      )
      SiteFeature.find_or_create_by!(
        name: 'Eigen Auction Results Button',
        description: 'Show auction results button in Eigen artwork view'
      )
      SiteFeature.find_or_create_by!(
        name: 'Auction Results',
        description: 'Enable auction results for artworks.'
      )
``` 

Are those still used? Should some be nuked? I did a bit of aggressive deleting in https://github.com/artsy/gravity/pull/8976 but the actual site feature instances in the database have not been deleted.

**Comment by alloy** [comment]
Based on [the code in Eigen](https://github.com/artsy/eigen/blob/b8f1dcb67c7f341faa0a0308eefc3ba273da427b/Artsy/Classes/Constants/ARDefaults%2BSiteFeatures.m), the only one I don’t see is the last one: `Enable auction results for artworks.`.

I am, however, not sure yet how this is used, if at all. @orta / @1uarabrown can you enlighten me on this topic?

PS: Hihi, “Skip prince” ;)

**Comment by orta** [comment]
Yeah, these existed but have never changed since during our initial pre-launch betas, I don't know if we set defaults that these then overwrite with server values, if that's the case IMO we can remove them form both sides.

**Comment by dblock** [comment]
I opened https://trello.com/c/wW0UBCNH/920-remove-eigen-s-sitefeatures to remove Eigen's site features from Gravity and the database. That won't break anything, right? I mean if the list of site features returned from Gravity is empty.

**Comment by joeyAghion** [comment]
I still like the idea of these, but I'm not sure that clients respect them consistently (e.g., so we could disable e-commerce during a payments transition).

**Comment by orta** [comment]
I've taken a quick look and we set [defaults](https://github.com/artsy/eigen/blob/c917934864d180592509f8d8f21de65536815427/Artsy/Classes/Constants/ARDefaults.m#L34-42) for all the values in there, if the api route is removed, or the db emptied then older builds will handle it fine.

**Comment by alloy** [comment]
Ok, I’ll turn this into a ticket to remove the code from Eigen when/if this does get removed from the API.

**Comment by dblock** [comment]
I have deleted Eigen's SiteFeature instances from the Gravity database, but the API will remain since we will/want to use it with other applications.

```
gravity:production> SiteFeature.all.select { |f| f.name =~ /Eigen.*/ }.map(&:name)
=> ["Eigen Onboard Skip Personalize", "Eigen Onboard Prompt Threshold", "Eigen Onboard Skip Collector Level", "Eigen Onboard Skip Price Range", "Eigen Auction Results Button"]
```

**Comment by alloy** [comment]
Moving to #556.
