### ISSUE TITLE
[Push Notifications] Device token submitted to Artsy API at wrong time.

### ISSUE THREAD

**Issue by alloy** [artsy/eigen#518]
Currently we try to submit the device token to the Artsy API as soon as possible, but it’s very possible that by then the user has not yet signed-in.

* Will we ever want to spam all users that have the app installed, even if they are not registered users? (e.g. to do more general announcements) Keep in mind that this is not just a matter of a decision, it will require eigen and gravity side work which may or may not be trivial.
* if not, then we can just defer registering for push notifications until the user has signed-in, or if they’re signed-in perform it at startup as is currently the case

@katarinabatina @orta

**Comment by katarinabatina** [comment]
I could see us wanting to push people in the fair context who aren't signed in

**Comment by alloy** [comment]
Ok, I’m gonna do some work on Gravity’s end to support push notifications for trial users.
