### ISSUE TITLE
Art world in your pocket

### ISSUE THREAD

**Issue by dblock** [artsy/eigen#524]
Given the iPad [release](https://twitter.com/artsy/status/611643456914522113), Is it time to change _Art world in your pocket_? Unless of course you have very big pockets :)

![screen shot 2015-06-18 at 6 10 45 pm](https://cloud.githubusercontent.com/assets/542335/8243497/7132e53a-15e5-11e5-99db-ca7f9a5286f6.png)

**Comment by orta** [comment]
![screen shot 2015-06-19 at 10 43 11 am](https://cloud.githubusercontent.com/assets/49038/8255714/ffed05a0-166f-11e5-9ce7-f144125079f9.png)

**Comment by orta** [comment]
![Giphy](http://media4.giphy.com/media/pJllps8fJQFoY/giphy.gif)

**Comment by alloy** [comment]
Hah, furry well done.
