### ISSUE TITLE
Fix crash in WebCore::StyleResolver::applyMatchedProperties(WebCore::StyleResolver::MatchResult const&, WebCore::Element const*, WebCore::StyleResolver::ShouldUseMatchedPropertiesCache)

### ISSUE THREAD

**Issue by artsyit** [artsy/eigen#528]
### Reason ###

No reason found. Full stack trace includes WebCore, WebKitLegacy, DataDetectorsUI, CoreFoundation, libsystem_pthread.dylib.

### Link to HockeyApp ###

* [https://rink.hockeyapp.net/manage/apps/37029/crash_reasons/37715695](https://rink.hockeyapp.net/manage/apps/37029/crash_reasons/37715695)

**Comment by alloy** [comment]
This one comes from deep inside a web view, but which one is impossible to know. So I’m just gonna look at fixing my breadcrumb code in ARAnalytics instead, which should have provided us with more context on where this happens.
