### ISSUE TITLE
Bidding is not working

### ISSUE THREAD

**Issue by katarinabatina** [artsy/eigen#529]
Tap bid button on artwork view, tries to fetch martsy bid page and gets "page does not exist" error. There is currently an auction running, amfar, easy to replicate. No corresponding problems on microgravity.

**Comment by orta** [comment]
iPad / iPhone?

**Comment by katarinabatina** [comment]
both @orta it would be great if someone could probe into this today

**Comment by orta** [comment]
Looks like we didn't know about a change in URL structures on Force, we're still presuming all auctions have URLs like `feature/amfar-generationcure-solstice-auction/bid/robert-beck-untitled-daly-over-slash-under-at-close-range-with-12-punkin-ball-slug` but now they can go to `https://artsy.net/auction/amfar-generationcure-solstice-auction/bid/robert-beck-untitled-daly-over-slash-under-at-close-range-with-12-punkin-ball-slug`

**Comment by orta** [comment]
This was fixed for iPhones, https://github.com/artsy/microgravity/pull/917 but not for iPad

**Comment by katarinabatina** [comment]
@orta is there a force change that could be made now to get these to work?

**Comment by orta** [comment]
It is done :+1:

**Comment by orta** [comment]
but we're also going to support the new route via #534

**Comment by alloy** [comment]
This has been merged.
