### ISSUE TITLE
user has to login every time app is refreshed

### ISSUE THREAD

**Issue by katarinabatina** [artsy/eigen#530]
start app, log in, browse, close app (completely close app by swiping up to refresh), come back to app, get full splash experience, asked to login in again, when I tap trial user and hit you, I don't get the sign up cta just a blank zero state.

**Comment by katarinabatina** [comment]
have to delete the app to log back in

**Comment by orta** [comment]
I'm not seeing this on my App Store build (iPad)

**Comment by katarinabatina** [comment]
here's a video of the repo. http://cl.ly/image/0S253v2j262L

I login, go to you, see my favorites, refresh app, get splash and 1st time load splash, bypass sign up, hit you, get no sign up CTA

**Comment by orta** [comment]
Yep, verified on my end, can't stay logged in as a logged in user

**Comment by orta** [comment]
This isn't happening to me on the sim

**Comment by orta** [comment]
```
Jun 22 11:03:44 Ortas-iPad securityd[87] <Error>:  securityd_xpc_dictionary_handler Artsy[297] add The operation couldn’t be completed. (OSStatus error -25243 - NoAccessForItem)
Jun 22 11:03:44 Ortas-iPad Artsy[297] <Error>:  SecOSStatusWith error:[-25243] The operation couldn’t be completed. (OSStatus error -25243 - Remote error : The operation couldn‚Äôt be completed. (OSStatus error -25243 - NoAccessForItem))
zzz

**Comment by orta** [comment]
http://stackoverflow.com/questions/28173565/keychain-secosstatuswith-error-34018

Likely that the app was signed with an invalid distribution cert:

![screen shot 2015-06-22 at 11 06 20 am](https://cloud.githubusercontent.com/assets/49038/8285041/d4e58862-18ce-11e5-9892-65563219ed21.png)

Not actually sure why it's classed as invalid. Probably will need to re-submit to be sure alas.

**Comment by orta** [comment]
I've successful got this replicated on my local iPad :+1:

**Comment by orta** [comment]
OK, I got this fixed, PR incoming if I can ever get our entire test suite to pass before I make changes

**Comment by alloy** [comment]
@orta The fix does not actually seem to work in the beta version I just released. I’ll look into this myself tomorrow as well.
