### ISSUE TITLE
Support dynamic routing

### ISSUE THREAD

**Issue by orta** [artsy/eigen#531]
Right now our routes can break if Artsy makes changes and we can't make updates to the routing without a full app + review update. Would be nice to expand upon JLRoutes with something that allows us to edit the routing information from a website where we can have defaults with the app that get updated from the server.

re: https://github.com/artsy/eigen/issues/529 and more from before

**Comment by alloy** [comment]
Yeah I think this is a good idea and a good backup anyways :+1:

I do have a gut feeling that it’s less good that we’re able to have clear communication about what is being used where and routes being broken, though :-/

**Comment by orta** [comment]
Work has been done towards this, but for a different reason

**Comment by orta** [comment]
We did this.
