### ISSUE TITLE
Sharing on Facebook causes a persistent Keyboard?

### ISSUE THREAD

**Issue by orta** [artsy/eigen#532]
> Your app is great. It's simple and beautiful. But seem that the app has got a issue relates to Sharing. I open Sharing and want to share it on my Facebook, then I close Sharing, now I can't close the keyboard. It's a minor thing and just restart. In general, still highly recommended.

Probably Apple's fault IMO. Worth a quick explore though.

**Comment by alloy** [comment]
I have been unable to reproduce on either iPhone or iPad, either in native views or an iPad Force view such as the magazine.

**Comment by alloy** [comment]
Still unable to reproduce this. I’m gonna close it for now and we’ll see if more helpful reports come in.
