### ISSUE TITLE
disable downloads for old iOS 7 or earlier

### ISSUE THREAD

**Issue by katarinabatina** [artsy/eigen#537]
Not sure we can even do this but Nick was able to download the last version of eigen that supported iOS7 on his not up to date ipad. Resulted in him downloading a BIG phone app haha. Is there anyway to disable this or "hide" it from the store for ipad.

**Comment by ashfurrow** [comment]
As far as I know, this is not possible. For users with older iPads that don't run iOS 8, they'll be able to download the old pre-iPad eigen version. The only way to prevent them would be to disable iPhone users on iOS 7 from downloading it, too.

**Comment by orta** [comment]
Yeah, we have no ability to do this, they get an old build on an iOS7 iPad full stop. As though they had tapped it on iPad ( you have to say "I want an iPhone app" normally. )

The only thing we can do it totally kill iOS7 support alas, which doesn't feel reasonable.

**Comment by alloy** [comment]
> The only thing we can do it totally kill iOS7 support alas, which doesn't feel reasonable.

I agree.

**Comment by alloy** [comment]
Here’s a user asking if we could re-instate iOS 7 support: https://groups.google.com/a/artsymail.com/forum/#!topic/mobile/Jz3yet9lFaY

Seeing as the consensus seems to be to let the version work, I’m gonna close this.
