### ISSUE TITLE
[search] Keyboard appears to have a black accessory view, which hides results

### ISSUE THREAD

**Issue by alloy** [artsy/eigen#538]
There’s an extra black view above the keyboard, which makes it look like there are no more search results behind the keyboard. E.g.

![ios simulator screen shot 24 jun 2015 13 09 51](https://cloud.githubusercontent.com/assets/2320/8328614/807a8e94-1a72-11e5-87a7-adfe90de32f3.png)

When in fact, these are all the results when the keyboard is dismissed:

![ios simulator screen shot 24 jun 2015 13 09 19](https://cloud.githubusercontent.com/assets/2320/8328616/8b458a72-1a72-11e5-980d-952f1d5bf4be.png)

Need to check if this is still a problem when implementing the new search UI.

**Comment by orta** [comment]
Could be that it's got a constraint that was made for small phones that was never updated

**Comment by 1aurabrown** [comment]
What device is this on? just tested on 6 and 6 plus and it looks fine
![screen shot 2015-07-01 at 3 32 25 pm](https://cloud.githubusercontent.com/assets/3171662/8463175/7e8f60b6-2006-11e5-97c0-2128edf5b6a9.png)
![screen shot 2015-07-01 at 3 27 02 pm](https://cloud.githubusercontent.com/assets/3171662/8463174/7e8bd018-2006-11e5-8b02-c77339263987.png)

**Comment by 1aurabrown** [comment]
The accessory view is constrained to reach 20px above they keyboard, which is more obvious in the first image. in the second image, that 20px just happens to fall between two search results. Neither looks like the image in the original issue though.

**Comment by alloy** [comment]
A 4S, where the accessory view is much bigger. Nonetheless, that accessory view in your first screenshot doesn’t look nice either. Why is there an accessory view at all?

**Comment by alloy** [comment]
Fixed by #569.
