### ISSUE TITLE
Redesign of artist header

### ISSUE THREAD

**Issue by celinenguyen** [artsy/eigen#544]
**Redesign for the artist page header**. Important components:

* artist name / nationality, dates / follower count *(like on the web; image attached below)*
* follow button with a following state
* a tab-y view switcher *(already exists on the 'You' view in switching between favorite artworks, artists, categories)*

***

**Header overview**:

![screen shot 2015-06-25 at 10 24 21 am](https://cloud.githubusercontent.com/assets/1417844/8356714/f04e48b6-1b24-11e5-8ba0-9f6aa099e8d2.png)

**Spec for the iPhone artist header**:

![screen shot 2015-06-25 at 10 35 02 am](https://cloud.githubusercontent.com/assets/1417844/8356874/dd88063a-1b25-11e5-9b86-02fec3982abb.png)

**Spec for the iPad portrait and landscape header** (only changes from the iPhone header are marked):

![screen shot 2015-06-25 at 10 34 52 am](https://cloud.githubusercontent.com/assets/1417844/8356876/e2dfc8ca-1b25-11e5-84dc-cb913ec24f35.png)

***

For reference, here's the web version:

![screen shot 2015-06-25 at 10 26 04 am](https://cloud.githubusercontent.com/assets/1417844/8356723/ffd665f2-1b24-11e5-86e6-1490f68aaf01.png)

**Comment by orta** [comment]
10/10 points for a great issue. 
:star2:

**Comment by briansw** [comment]
Closing in favor of https://github.com/artsy/eigen/issues/1131
