### ISSUE TITLE
Redesign of artist works view

### ISSUE THREAD

**Issue by celinenguyen** [artsy/eigen#545]
**Redesign for the works view for an artist**.  Components:

* an "All Works" header *(on the iPad)* 
* a 'For Sale' checkbox with a count, includes a checkbox asset *(please let me know what's the best way to provide this)*
* a works count that changes if the 'For Sale' checkbox is pressed
* the full list of all the artist's works *(2-up on the iPhone, 3-up on iPad portrait, 4-up on iPad landscape—use the existing component on the 'You' page that lists favorite artworks)*

For each artwork, the metadata below should be:

* artist name (semibold)
* work name (italicized regular) + , + the work date
* gallery/institution/location/whatever (regular)
* the price, or price range, or text saying 'For Sale' if that information is available (regular)

***

**Works view overview**:

![screen shot 2015-06-25 at 11 18 52 am](https://cloud.githubusercontent.com/assets/1417844/8358024/ffa35a5c-1b2b-11e5-9e9e-717d5d7c1519.png)

**Spec for the iPhone works view**:

![screen shot 2015-06-25 at 11 13 38 am](https://cloud.githubusercontent.com/assets/1417844/8357945/8c5439a4-1b2b-11e5-8bfc-26e0ca9d740a.png)

**Spec for the iPad (portrait) works view** (only changes from the iPhone version are marked):

![screen shot 2015-06-25 at 11 16 33 am](https://cloud.githubusercontent.com/assets/1417844/8357982/be169360-1b2b-11e5-85d8-0660bff39c9d.png)

**Spec for the iPad (landscape) works view** (only changes from the portrait version are marked):

![screen shot 2015-06-25 at 11 16 53 am](https://cloud.githubusercontent.com/assets/1417844/8357987/c437de52-1b2b-11e5-94b0-08b3baf5489a.png)

***

For reference, here's the 'You' (favorite artworks) view on the iPad:

![ipad-example](https://cloud.githubusercontent.com/assets/1417844/8357936/84034f60-1b2b-11e5-9d23-d76abfffbed5.png)

Also (this is applicable to all of the [Artist Page Update](https://github.com/artsy/eigen/labels/Artist%20Page%20Update)) here are the type sizes I've been using:

![screen shot 2015-06-25 at 11 35 11 am](https://cloud.githubusercontent.com/assets/1417844/8364043/2f1ed94e-1b51-11e5-9b9c-9bfc84acde1c.png)

In red: everything where the iPad is different from the iPhone type size hierarchy.

**Comment by briansw** [comment]
Closing in favor of https://github.com/artsy/eigen/issues/1131
