### ISSUE TITLE
Redesign of artist shows view

### ISSUE THREAD

**Issue by celinenguyen** [artsy/eigen#548]
**Redesign for the shows view for an artist**. Components:

* a "Solo Shows" section
* a "Group Shows" section
* a "Fair Booths" section

This is how the shows are sorted on the [web artist pages](https://www.artsy.net/artist/sol-lewitt/shows) (but they aren't explicitly divided into solo/group/fair booth chunks). 

Each section lists shows by most recent first. Each show has the following metadata:

* the gallery name (2 lines max, truncate if longer)
* the show name (1 line max, truncate if longer)
* city (if available) + , + dates (1 line max; put this in green if the show is currently running)

***

**Shows view overview**:

![screen shot 2015-06-25 at 3 43 36 pm](https://cloud.githubusercontent.com/assets/1417844/8364027/0b7b0bac-1b51-11e5-9032-96564dbb3aa0.png)

**Spec for the iPhone works view**:

![screen shot 2015-06-25 at 3 35 23 pm](https://cloud.githubusercontent.com/assets/1417844/8363947/8fa9c658-1b50-11e5-80a3-6e8e364ac3b5.png)

**Spec for the iPad (portrait) works view** (only changes from the iPhone version are marked):

![screen shot 2015-06-25 at 3 35 52 pm](https://cloud.githubusercontent.com/assets/1417844/8363949/93650bea-1b50-11e5-822e-bd3a32a8f00b.png)

**Spec for the iPad (landscape) works view** (only changes from the portrait version are marked):

![screen shot 2015-06-25 at 3 43 52 pm](https://cloud.githubusercontent.com/assets/1417844/8364021/05435604-1b51-11e5-82fb-71828cc9110e.png)

***

For reference (this is applicable to all of the [Artist Page Update](https://github.com/artsy/eigen/labels/Artist%20Page%20Update)) these are the type sizes I've been using:

![screen shot 2015-06-25 at 11 35 11 am](https://cloud.githubusercontent.com/assets/1417844/8364043/2f1ed94e-1b51-11e5-9b9c-9bfc84acde1c.png)

In red: everything where the iPad is different from the iPhone type size hierarchy.

**Comment by briansw** [comment]
Closing in favor of https://github.com/artsy/eigen/issues/1131
