### ISSUE TITLE
Redesign of artist about view

### ISSUE THREAD

**Issue by celinenguyen** [artsy/eigen#549]
**Redesign for the about view for an artist**. Components:

* full biography of the artist (with links to genes and other artists inside it)
* a list of articles (1-up on iPhone and iPad portrait, 2-up on iPad landscape)

***

**About view overview**:

![screen shot 2015-06-25 at 4 35 47 pm](https://cloud.githubusercontent.com/assets/1417844/8365274/0b24a98e-1b5a-11e5-9f5c-a427b0385a11.png)

**Spec for the iPhone about view**:

![screen shot 2015-06-25 at 4 34 50 pm](https://cloud.githubusercontent.com/assets/1417844/8365281/1160ecea-1b5a-11e5-95c8-f5443808be33.png)

**Spec for the iPad (portrait) about view** (only changes from the iPhone version are marked):

![screen shot 2015-06-25 at 4 35 02 pm](https://cloud.githubusercontent.com/assets/1417844/8365286/1a5d7052-1b5a-11e5-9582-3715a97435c8.png)

**Spec for the iPad (landscape) works view** (only changes from the portrait version are marked):

![screen shot 2015-06-25 at 4 35 08 pm](https://cloud.githubusercontent.com/assets/1417844/8365292/20183e28-1b5a-11e5-8303-40476fe0ff7d.png)

***

For reference (this is applicable to all of the [Artist Page Update](https://github.com/artsy/eigen/labels/Artist%20Page%20Update) issues) these are the type sizes I've been using:

![screen shot 2015-06-25 at 11 35 11 am](https://cloud.githubusercontent.com/assets/1417844/8364043/2f1ed94e-1b51-11e5-9b9c-9bfc84acde1c.png)

In red: everything where the iPad is different from the iPhone type size hierarchy.

**Comment by briansw** [comment]
Closing in favor of https://github.com/artsy/eigen/issues/1131
