### ISSUE TITLE
Redesign of artist related view

### ISSUE THREAD

**Issue by celinenguyen** [artsy/eigen#554]
**Redesign for the related view for an artist**. Components:

* a "Related Artists" section
* a "Related Categories" section

Both displays should have the same layout and use the existing display for related artists/categories on Eigen—2-up for iPhone, 3-up for iPad portrait, 4-up for iPad landscape. *However*, I'd like to have that display modified a bit (margins, type size). This is what it currently is (iPhone example):

![screen shot 2015-06-26 at 2 34 15 pm](https://cloud.githubusercontent.com/assets/1417844/8384643/6fe4485a-1c10-11e5-9f3d-a2e3bbffcc53.png)

***

**Related view overview**:

![screen shot 2015-06-26 at 2 28 19 pm](https://cloud.githubusercontent.com/assets/1417844/8384611/2a2d68c8-1c10-11e5-9a38-5608dad912a8.png)

**Spec for the iPhone related view**:

![screen shot 2015-06-26 at 2 27 18 pm](https://cloud.githubusercontent.com/assets/1417844/8384618/2ded9d02-1c10-11e5-8da3-92854582e214.png)

**Spec for the iPad (portrait) related view** (only changes from the iPhone version are marked):

![screen shot 2015-06-26 at 2 27 41 pm](https://cloud.githubusercontent.com/assets/1417844/8384620/332d2044-1c10-11e5-84bf-5a5b657e6c43.png)

**Spec for the iPad (landscape) related view** (only changes from the portrait version are marked):

![screen shot 2015-06-26 at 2 27 49 pm](https://cloud.githubusercontent.com/assets/1417844/8384623/35ae4190-1c10-11e5-8bf8-850c6c257f6c.png)

***

For reference (this is applicable to all of the [Artist Page Update](https://github.com/artsy/eigen/labels/Artist%20Page%20Update) issues) these are the type sizes I've been using:

![screen shot 2015-06-25 at 11 35 11 am](https://cloud.githubusercontent.com/assets/1417844/8364043/2f1ed94e-1b51-11e5-9b9c-9bfc84acde1c.png)

**Comment by briansw** [comment]
Closing in favor of https://github.com/artsy/eigen/issues/1131
