### ISSUE TITLE
Fix NSInternalInconsistencyException in - [ARArtworkPreviewImageView setAspectRatioConstraintWithImage:], line 115

### ISSUE THREAD

**Issue by artsyit** [artsy/eigen#555]
### Stacktrace ###

<pre>ARArtworkPreviewImageView;setAspectRatioConstraintWithImage:;ARArtworkPreviewImageView.m;115
ARArtworkPreviewImageView;setImage:;ARArtworkPreviewImageView.m;108
UIImageView(WebCache);sd_setImageWithURL:placeholderImage:options:progress:completed:;UIImageView+WebCache.m;53
UIImageView(WebCache);sd_setImageWithURL:placeholderImage:options:progress:completed:;UIImageView+WebCache.m;53
SDWebImageManager;downloadImageWithURL:options:progress:completed:;SDWebImageManager.m;252
SDImageCache;queryDiskCacheForKey:done:;SDImageCache.m;292
SDWebImageManager;downloadImageWithURL:options:progress:completed:;SDWebImageManager.m;149
UIImageView(WebCache);sd_setImageWithURL:placeholderImage:options:progress:completed:;UIImageView+WebCache.m;51
UIImageView(WebCache);sd_setImageWithURL:placeholderImage:completed:;UIImageView+WebCache.m;34
UIImageView(AsyncImageLoading);ar_setImageWithURL:placeholderImage:completed:;UIImageView+AsyncImageLoading.m;29
UIImageView(AsyncImageLoading);ar_setImageWithURL:placeholderImage:;UIImageView+AsyncImageLoading.m;69
ARArtworkPreviewImageView;updateWithArtwork:;ARArtworkPreviewImageView.m;85
ARArtworkPreviewImageView;setArtwork:;ARArtworkPreviewImageView.m;40
Artwork;onArtworkUpdate:failure:;Artwork.m;296
KSPromise;resolveWithValue:;KSPromise.m;151
KSDeferred;resolveWithValue:;KSDeferred.m;25
Artwork;updateArtwork;Artwork.m;268</pre>

### Reason ###

*** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: '<NSISEngine: 0x17013b3a0>{ Rows:
	0x1742a9000.posErrorMarker{id: 105558} == 60 + 1*0x174487440.marker{id: 105465} + -1*0x174283c00.marker{id: 105481} + 0.00277778*ARArtworkBlurbView:0x14f249330.Width{id: 105482} + 1*0x174684ab0.marker{id: 105495} + 1*0x1742a9000.negError{id: 105559}
	0x1742afea0.posErrorMarker{id: 105578} == 0 + -1*0x174280050.marker{id: 105537} + 1*0x174688020.marker{id: 105542} + 1*0x1742afea0.negError{id: 105579} + 1*0x1742ba760.posErrorMarker{id: 105582} + -1*0x1742ba760.negError{id: 105583}
	0x1742b0020.posErrorMarker{id: 105586} == 0 + 0.00277778*ARWhitespaceGobbler:0x14ddd33e0.Height{id: 105573} + 1*0x1742b0020.negError{id: 105587}
	0x1742b3c80.posErrorMarker{id: 105584} == 0 + 1*0x1742b3c80.negError{id: 105585} + 0.00277778*ARWhitespaceGobbler:0x14ddd33e0.Width{id: 105588}
	0x1742b6aa0.posErrorMarker{id: 105639} == 23 + 1*0x170881f40.marker{id: 105600} + 1*0x1742b6aa0.negError{id: 105640}
	0x1744a3900.posErrorMarker{id: 105630} == 28 + 1*0x17428d750.marker{id: 105598} + 1*0x1744a3900.negError{id: 105631}
	0x1744a3960.posErrorMarker{id: 105520} == 0 + 1*0x1744a3960.negError{id: 105521} + 0.00277778*ARWhitespaceGobbler:0x14ddc3940.Width{id: 105524}
	0x1744a7f20.posErrorMarker{id: 105632} == 17.5 + -1*0x17049b1c0.marker{id: 105602} + 1*0x17088e150.marker{id: 105606} + 1*0x1744a7500.posErrorMarker{id: 105628} + -1*0x1744a7500.negError{id: 105629} + 1*0x1744a7f20.negError{id: 105633}
	0x1744a8ee0.posErrorMarker{id: 105548} == 280 + 1*0x174287cb0.marker{id: 105433} + -1*0x174689740.marker{id: 105435} + -1*0x17429ea50.marker{id: 105442} + 1*0x174886090.marker{id: 105448} + 1*0x1744a4620.posErrorMarker{id: 105546} + -1*0x1744a4620.negError{id: 105547} + 1*0x1744a8ee0.negError{id: 105549}
	0x1744ab8e0.posErrorMarker{id: 105552} == 0 + 1*0x1744ab8e0.negError{id: 105553} + 0.00277778*ARArtworkBlurbView:0x14f249330.Height{id: 105554}
	0x1744ac600.posErrorMarker{id: 105555} == 0 + 1*0x1744ac600.negError{id: 105556} + 0.00277778*ARArtworkRelatedArtworksView:0x14dd8c070.Height{id: 105557}
	0x1744ac720.posErrorMarker{id: 105637} == 114 + -1*0x17049b1c0.marker{id: 105602} + 1*0x17029be40.marker{id: 105610} + 1*0x1744a7500.posErrorMarker{id: 105628} + -1*0x1744a7500.negError{id: 105629} + 1*0x1744ac720.negError{id: 105638}
	0x1744ae040.posErrorMarker{id: 105522} == 0 + 0.00277778*ARWhitespaceGobbler:0x14ddc3940.Height{id: 105429} + 1*0x1744ae040.negError{id: 105523}
	0x1744af120.posErrorMarker{id: 105550} == 0 + 0.00277778*ARWhitespaceGobbler:0x14ddfabf0.Height{id: 105445} + 1*0x1744af120.negError{id: 105551}
	0x1744b4c40.posErrorMarker{id: 105560} == 0 + 0.00277778*UILabel:0x14f1004a0.Height{id: 105470} + 1*0x1744b4c40.negError{id: 105561}
	0x174693ec0.posErrorMarker{id: 105468} == 40 + -0.00277778*ARAuctionBannerView:0x14ddaa970.Height{id: 105464} + 1*0x174693ec0.negError{id: 105469} + 0.00277778*UILabel:0x14f1004a0.Height{id: 105470}
	0x174880b90.posErrorMarker{id: 105462} == 0 + 1*0x174880b90.negError{id: 105463} + 0.00277778*ARAuctionBannerView:0x14ddaa970.Height{id: 105464}
	ARArtworkActionsView:0x14dd531f0.Width{id: 105436} == 100800 + 360*0x1744a4620.posErrorMarker{id: 105546} + -360*0x1744a4620.negError{id: 105547}
	ARArtworkActionsView:0x14dd531f0.minX{id: 105434} == 0 + -360*0x174889b50.marker{id: 105430} + 360*0x174287cb0.marker{id: 105433} + 180*0x17049b1c0.marker{id: 105602} + -360*0x17049db00.marker{id: 105604} + 1*ARSansSerifLabelWithChevron:0x14dd780f0'LÉON WILMA LOÏS RADEGONDE'.minX{id: 105605}
	ARArtworkActionsView:0x14dd531f0.minY{id: 105440} == 0 + -360*0x17469ce30.marker{id: 105438} + -1*ARArtworkActionsView:0x14dd531f0.Height{id: 105441} + 360*0x1742940a0.marker{id: 105444} + -1*ARWhitespaceGobbler:0x14ddfabf0.Height{id: 105445} + 1*UIView:0x14f1803a0.Height{id: 105447} + -360*0x17088a410.marker{id: 105450} + -360*0x174099c80.marker{id: 105641} + 1*ARSansSerifLabelWithChevron:0x14dd780f0'LÉON WILMA LOÏS RADEGONDE'.minY{id: 105642}
	ARArtworkBlurbView:0x14f249330.minX{id: 105486} == 100800 + -360*0x174889b50.marker{id: 105430} + 360*0x174287cb0.marker{id: 105433} + -360*0x174689740.marker{id: 105435} + -360*0x170885e10.marker{id: 105456} + -180*0x17488a4b0.marker{id: 105477} + -360*0x1748806e0.marker{id: 105479} + 180*0x174283c00.marker{id: 105481} + -1*ARArtworkBlurbView:0x14f249330.Width{id: 105482} + 360*0x174886e50.marker{id: 105485} + 360*0x1744a4620.posErrorMarker{id: 105546} + -360*0x1744a4620.negError{id: 105547} + 180*0x17049b1c0.marker{id: 105602} + -360*0x17049db00.marker{id: 105604} + 1*ARSansSerifLabelWithChevron:0x14dd780f0'LÉON WILMA LOÏS RADEGONDE'.minX{id: 105605}
	ARArtworkBlurbView:0x14f249330.minY{id: 105565} == 0 + 1*UIView:0x14f1803a0.Height{id: 105447} + -360*0x17088a410.marker{id: 105450} + 360*0x17088a550.marker{id: 105458} + 360*0x174491760.marker{id: 105564} + -360*0x174099c80.marker{id: 105641} + 1*ARSansSerifLabelWithChevron:0x14dd780f0'LÉON WILMA LOÏS RADEGONDE…

### Link to HockeyApp ###

* [https://rink.hockeyapp.net/manage/apps/37029/crash_reasons/38393374](https://rink.hockeyapp.net/manage/apps/37029/crash_reasons/38393374)

**Comment by alloy** [comment]
See #526 for history about this and something I tried to see if that was related, alas it’s clearly not.

**Comment by alloy** [comment]
Be sure to check the breadcrumbs in HockeyApp, in case it’s related to specific artworks or details thereof.

**Comment by alloy** [comment]
@1aurabrown This is the change I mentioned #539, be sure to revert that.

**Comment by alloy** [comment]
Hopefully fixed by #526.
