### ISSUE TITLE
Remove Superfluous Changelogs

### ISSUE THREAD

**Issue by ashfurrow** [artsy/eigen#564]
We have two/three-ish changelogs. Let's remove them all and opt for one in the [One True Format](https://github.com/artsy/energy/blob/master/Docs/CHANGELOG.yml).

**Comment by alloy** [comment]
:+1:

**Comment by orta** [comment]
@alloy if you're good with converting it to yml, I can do this
https://github.com/artsy/eidolon/blob/master/CHANGELOG.yml

**Comment by alloy** [comment]
Go for it :+1:
