### ISSUE TITLE
How to run yarn setup:oss on Windows?

### ISSUE THREAD

**Issue by zhbzhbzhbz** [artsy/eigen#5728]
When run it in cmd, it said '.\scripts\setup-env-for-oss' not recognized as an internal or external command

**Comment by brainbicycle** [comment]
Hey there, right now our setup instructions assume a macOS machine with Xcode installed. You may be able to try working around with a docker image or virtual machine with macOS and Xcode but none of us have tried before. If you do have success would love to hear about it!
