### ISSUE TITLE
Consider enforcing testing on device

### ISSUE THREAD

**Issue by ashfurrow** [artsy/eigen#578]
What do y'all think about having CI fail a PR if it doesn’t end with ':iphone:'? That way ones with  :no_entry_sign::iphone: or :iphone: would be OK, forcing the submitter to specify one way or the other?

**Comment by orta** [comment]
I had something similar in mind with this https://github.com/artsy/mobile/issues/31 - might work on Circle, Travis didn't provide enough metadata to get back to the PR to make a call

**Comment by orta** [comment]
We got this #1013
