### ISSUE TITLE
Fix crash in - [ARArtworkView setUpCallbacks], line 113

### ISSUE THREAD

**Issue by artsyit** [artsy/eigen#58]
### Stacktrace ###

<pre>ARArtworkView;setUpCallbacks;ARArtworkView.m;113
Artwork;onFairUpdate:failure:;Artwork.m;398
KSPromise;resolveWithValue:;KSPromise.m;151
KSDeferred;resolveWithValue:;KSDeferred.m;25
Artwork;updateFair;Artwork.m;384
ArtsyAPI(Artworks);getFairsForArtwork:success:failure:;ArtsyAPI+Artworks.m;114</pre>

### Link to HockeyApp ###

* [https://rink.hockeyapp.net/manage/apps/37029/crash_reasons/26509340](https://rink.hockeyapp.net/manage/apps/37029/crash_reasons/26509340)

**Comment by alloy** [comment]
Attempt at fix in https://github.com/artsy/eigen/pull/203.
