### ISSUE TITLE
ARExpandingTextView doesn't expand

### ISSUE THREAD

**Issue by orta** [artsy/eigen#583]
Before
![img_2806](https://cloud.githubusercontent.com/assets/49038/8508858/c4dd6740-227a-11e5-874c-165555882f62.jpg)

After
![img_2807](https://cloud.githubusercontent.com/assets/49038/8508857/c4bcbdf6-227a-11e5-9a05-6ee2de16863d.jpg)

**Comment by alloy** [comment]
Duplicate of #390, I imagine? Not sure if it's that class or another one.

**Comment by orta** [comment]
ah yeah
