### ISSUE TITLE
Partner Articles link white screen

### ISSUE THREAD

**Issue by orta** [artsy/eigen#584]
Likely a martsy issue, on prod, clicked through to a partner in search, tapping their articles showed a white screen: 
![img_2804](https://cloud.githubusercontent.com/assets/49038/8508865/f97c2e46-227a-11e5-8c5d-218cdf79e377.jpg)

**Comment by alloy** [comment]
Is this what you mean by blank?

https://m.artsy.net/ybca/articles

<img width="616" alt="screen shot 2015-07-14 at 14 07 04" src="https://cloud.githubusercontent.com/assets/2320/8672753/a2c10d10-2a31-11e5-9338-748c7569dcdf.png">

**Comment by alloy** [comment]
Moved to https://github.com/artsy/microgravity/issues/956.

**Comment by alloy** [comment]
Fixed.
