### ISSUE TITLE
Cleanup headers/imports

### ISSUE THREAD

**Issue by alloy** [artsy/eigen#585]
```
#import "Interface.h"

#import "LocalHeaderA.h"
#import "LocalHeaderB.h"

@import ModuleA;
@import ModuleB;
```

And I’d also like to look into slimming down the prefix header so changes to headers don’t require it to be recompiled and, more importantly, to make it clear what dependencies a file has.

**Comment by orta** [comment]
Note, if/when this happens, can you make any reference to 
```
#import <Artsy+UIFonts/UIFont+ArtsyFonts.h>
```
to
```
#if __has_include(<Artsy+UIFonts/UIFont+ArtsyFonts.h>)
#import <Artsy+UIFonts/UIFont+ArtsyFonts.h>
#endif

#if __has_include(<Artsy+OSSUIFonts/UIFont+OSSArtsyFonts.h>)
#import <Artsy+OSSUIFonts/UIFont+OSSArtsyFonts.h>
#endif
```
would recommend making an `AR_INCLUDE_FONTS` define that does it.
