### ISSUE TITLE
wrong font in current beta, helvetica showing up intermittently 

### ISSUE THREAD

**Issue by katarinabatina** [artsy/eigen#588]
![image](https://cloud.githubusercontent.com/assets/6482926/8524230/e70fce54-23c7-11e5-82ae-7ebcd79b1ccb.png)

**Comment by katarinabatina** [comment]
also happening on iPad for force view but same page on desktop looks fine
![image](https://cloud.githubusercontent.com/assets/6482926/8525752/b941e6f2-23d0-11e5-97a0-c8c0cb38018a.png)

**Comment by katarinabatina** [comment]
![image](https://cloud.githubusercontent.com/assets/6482926/8525855/32327fb8-23d1-11e5-9ca6-6591b9418b00.png)

**Comment by orta** [comment]
OK, that is _super_ weird.

**Comment by orta** [comment]
Re-opening, these Force screenshots are not running on the frameworks Eigen I think. So #603 gets the ones in-app, but maybe, not in energy.

**Comment by orta** [comment]
Fixed in force - (sorry non-Artsy ) https://github.com/artsy/force/pull/3115
