### ISSUE TITLE
Current production version still does not retain logged in state

### ISSUE THREAD

**Issue by katarinabatina** [artsy/eigen#589]
revised the app after an hour, got full relaunch, tried with test account, thinks i am logged in but not under my normal account. Have to delete app and re-download to get back in.

**Comment by ashfurrow** [comment]
Probably a result of using frameworks. Updating the font and label pods should be sufficient. Might need screenshot updates too.

**Comment by alloy** [comment]
@ashfurrow Probably meant for #588?

**Comment by katarinabatina** [comment]
for this issue???

[A.] Katarina Batina

Artsy <http://artsy.net/>


katarina@artsymail.com

                @katarinabatina <https://twitter.com/katarinabatina>

253 225 5812

**Comment by ashfurrow** [comment]
Ah yes, apologies. 

--
Ash Furrow
iOS Developer, Author
http://ashfurrow.com

**Comment by orta** [comment]
I've never seen this, can anyone confirm seeing in the last 6 months?

**Comment by alloy** [comment]
At least I haven’t heard about it.

**Comment by orta** [comment]
Closing it, re-creating issues is cheap.
