### ISSUE TITLE
new works by artists I follow not updating

### ISSUE THREAD

**Issue by katarinabatina** [artsy/eigen#592]
last updated on Jun 26th but I have new works on desktop from Jul 7th

**Comment by alloy** [comment]
Is this ‘works for you’?

Can you test this on martsy and make screenshots comparing martsy to force? There have been a few issues on martsy, but I thought we got them all sorted.

**Comment by katarinabatina** [comment]
Microgravity this morning 


Eigen this morning

**Comment by alloy** [comment]
@katarinabatina Was that message supposed to have screenshots?

**Comment by katarinabatina** [comment]
@alloy yes updated my apologies

**Comment by alloy** [comment]
I believe this is fixed by #581 now.
