### ISSUE TITLE
Launch Image shows too large logo on iPhone 4S

### ISSUE THREAD

**Issue by alloy** [artsy/eigen#607]
Related to #593.

![ios simulator screen shot 10 jul 2015 16 42 03](https://cloud.githubusercontent.com/assets/2320/8621737/854f6324-2727-11e5-8372-a212c15fb329.png)

**Comment by 1aurabrown** [comment]
is the non-retina version missing?

**Comment by 1aurabrown** [comment]
OH right, we moved to using a xib.

**Comment by 1aurabrown** [comment]
The logo is set up to be a fixed size no matter what the device. What _shoud_ it look like?

Here are the 4 phones:
![screen shot 2015-07-13 at 4 41 02 pm](https://cloud.githubusercontent.com/assets/3171662/8660319/45ce21c8-297e-11e5-8cf2-536c5f9e8326.png)
![screen shot 2015-07-13 at 4 35 50 pm](https://cloud.githubusercontent.com/assets/3171662/8660322/45d34ce8-297e-11e5-8b1f-5839f85c6ad0.png)
![screen shot 2015-07-13 at 4 42 48 pm](https://cloud.githubusercontent.com/assets/3171662/8660320/45d2c7b4-297e-11e5-8b5b-8cb58260be41.png)
![screen shot 2015-07-13 at 4 28 49 pm](https://cloud.githubusercontent.com/assets/3171662/8660321/45d319da-297e-11e5-84ca-15cc9f6afc7c.png)

**Comment by alloy** [comment]
@1aurabrown I think it’s still too large. Shouldn’t it be just as big as the logo in the onboarding view that’s shown immediately afterwards (in case you’re onboarding) ?

/cc @katarinabatina 

![ios simulator screen shot 14 jul 2015 12 28 47](https://cloud.githubusercontent.com/assets/2320/8671298/44b8b004-2a24-11e5-92d0-1d462257eaaa.png)

![ios simulator screen shot 14 jul 2015 12 29 03](https://cloud.githubusercontent.com/assets/2320/8671301/49f377c0-2a24-11e5-882e-875e927f60a5.png)

**Comment by katarinabatina** [comment]
@1aurabrown agreed, should be the same size

**Comment by 1aurabrown** [comment]
Ah yes, will fix.

**Comment by orta** [comment]
closed by https://github.com/artsy/eigen/pull/651
