### ISSUE TITLE
Update iOS notification permission request

### ISSUE THREAD

**Issue by katarinabatina** [artsy/eigen#610]
![image](https://cloud.githubusercontent.com/assets/6482926/8624968/b1cc0c5e-2709-11e5-9ed9-49c0aedfca07.png)

Move towards a manually triggered request for new users in on boarding. If the user says no, I think it makes most sense to resurface the request after the user has followed a few artists (lets say perhaps two or three) and once they've visited works by artists you follow.

I could also see us asking permission for users who register for an auction.

**Comment by orta** [comment]
:+1: - we can do a check when you tap the auctions tab too, incase you've ran through on boarding already ( or have an existing account etc )

**Comment by katarinabatina** [comment]
I think the tab might feel a bit weird would rather tie it to an explicit action, like registration, following, or saving.

**Comment by orta** [comment]
I'm happy with any/all of these, as long as it's tied to something ;)

( Following something is a _really_ good one. )

**Comment by alloy** [comment]
What happens when you decide to not create an account during on boarding and use it as a trial user? Just ask for notifications after dismissing it, like is currently the case?

**Comment by alloy** [comment]
> If the user says no, I think it makes most sense to resurface the request after the user has followed a few artists (lets say perhaps two or three) and once they've visited works by artists you follow.

Alas, we cannot show the same alert again once the user has previously said ‘No’. So this would have to be a custom alert that reminds the user to allow notifications by going to `Settings -> Notifications -> Artsy`.

We can re-use most of the copy of the standard alert, though. E.g.:

```
  “Artsy” Would Like to Send You Notifications
           Notifications may include alerts,
      sounds and icon badges. These can be
                   turned on in Settings.
                   [ Don’t Allow ]   [ OK ]
```

Where tapping `OK` would open the Settings app? (I think we can do that.)

**Comment by alloy** [comment]
Hmm, I see what you’re saying now, we wouldn’t even be showing the alert if they answered ‘NO’ on our own on boarding view. The above is still a possibility, as people can still tap “Don’t Allow” in the real alert.

**Comment by alloy** [comment]
> What happens when you decide to not create an account during on boarding and use it as a trial user? Just ask for notifications after dismissing on boarding, like is currently the case?

Bump, also still waiting for that.

**Comment by katarinabatina** [comment]
@alloy even a trial user will be thrown into on boarding eventually. However in the case of forcing them to skip onboarding (like I am suggesting when someone taps bid or register to bid) we should ask after they finish account creation.

**Comment by alloy** [comment]
@katarinabatina Yeah, but right now we also ask trial users to accept push notifications, so something will have to give. Either we ask them when they’ve decided to not sign up/in yet, like we do now, or we don’t ask them anymore and we won’t be able to send them any push notifications while they are trial users.

**Comment by alloy** [comment]
@katarinabatina bump

**Comment by katarinabatina** [comment]
@alloy I think it's fine if we aren't able to push to people who are trial users, unsure what we would push to them if they were trial only.

**Comment by katarinabatina** [comment]
@alloy sorry that this has fallen to the bottom of the stack, let's attack it this sprint. I think we can still bug trial users after they've entered the app, it sucks to do it right as they start their trial but not sure when it makes sense to ask them again. Perhaps we could ask them after they've been shown the sign up splash page once?

**Comment by alloy** [comment]
@katarinabatina Or maybe we can have a similar on-boarding view, as in your new design, except for trial users? So it would go like:

```
  1.  ┌────────────────────────────────┐
      │                                │
      │                                │
      │                                │
      │                                │
      │                                │
      │                                │
      │                                │
      │                                │
      │ ┌────────────────────────────┐ │
      │ │          SIGN UP           │ │
      │ └────────────────────────────┘ │
      │ ┌────────────────────────────┐ │
      │ │   TRY WITHOUT AN ACCOUNT   │ │
      │ └────────────────────────────┘ │
      │                                │
      │                                │
      │                                │
      │                                │
      │                                │
      │                                │
      │                                │
      │                                │
      └────────────────────────────────┘

  2.  ┌────────────────────────────────┐
      │Would you like to receive       │
      │updates about shows and         │
      │auctions?                       │
      │                                │
      │                                │
      │                                │
      │                                │
      │                                │
      │                                │
      │                                │
      │                                │
      │                                │
      │                                │
      │                                │
      │                                │
      │ ┌────────────────────────────┐ │
      │ │            YES             │ │
      │ └────────────────────────────┘ │
      │ ┌────────────────────────────┐ │
      │ │       NOT RIGHT NOW        │ │
      │ └────────────────────────────┘ │
      │                                │
      └────────────────────────────────┘
```

(Based on the types listed in #851.)

**Comment by katarinabatina** [comment]
I think this could work @alloy

**Comment by katarinabatina** [comment]
@orta did you get a chance to check this out?

**Comment by orta** [comment]
nope

**Comment by katarinabatina** [comment]
@alloy maybe an incremental step is just shipping a fake modal and still ask when we ask now so we're not spending our one real request 
![image](https://cloud.githubusercontent.com/assets/6482926/13509583/47722b34-e15a-11e5-9f1b-7b1bc7e95dcc.png)

**Comment by alloy** [comment]
@katarinabatina What would that do when you press OK? Show the _real_ modal?

**Comment by katarinabatina** [comment]
yea

**Comment by katarinabatina** [comment]
@alloy I know @mennenia was looking for more one off issues to pick up in more isolation would this be a good one for her?

**Comment by katarinabatina** [comment]
closing in favor of a new issue since the desired ux/form factor is different
