### ISSUE TITLE
search should not be considered in navigation stack when moving back

### ISSUE THREAD

**Issue by katarinabatina** [artsy/eigen#617]
go to a work, tap artist name, land on artist page A, use search for different artist, land on artist page B, hit back button, see search again....

i should actually go back to artist page A, not see search again

**Comment by orta** [comment]
We did this before with search and this ^ ended up feeling a bit off. So what we went with was if you pushed through two things then the search would go away. Otherwise you could easily get back and revise search, or try other results (say if there were multiple artists with similar sounding names). 

So, `Artwork -> Artist -> Search -> Artist` tapping back would show search. Whereas `Artwork -> Artist -> Search -> Artist -> Artwork` Would remove the Search from the history.

**Comment by katarinabatina** [comment]
![image](https://cloud.githubusercontent.com/assets/6482926/8634529/6abb21e4-27ca-11e5-8715-97af8bd6720c.png)

**Comment by katarinabatina** [comment]
@orta why not retain search results instead? so that when the user enacts the button again their old search is still there (lets say for a period of time)

**Comment by alloy** [comment]
I like the simplicity of retaining the search results.

**Comment by alloy** [comment]
There is only one issue, namely that a single view controller can only be shown in one place at a time. Thus, if you open search in one tab, then move to another tab and also open search there, they cannot show the same single search view controller. Things we can do:

* only maintain search results per tab (simple to implement)
* persist search results to disk and load those for each search view controller we show, thus always showing the last search results, regardless of tab (harder to implement)

**Comment by orta** [comment]
> only maintain search results per tab (simple to implement)

I think this is acceptable, there is a context change in switching between tabs. It's very unlikely you're going to want to go back to same results after switching from `home` to `notifications` for example

**Comment by alloy** [comment]
> remove presented search view controller from other tabs when it’s shown (simple to implement)

I added this one after the fact.

@orta While what you say makes sense, I’d just like to be sure that you wouldn’t prefer this one instead.

**Comment by orta** [comment]
I do prefer 

> remove presented search view controller from other tabs when it’s shown (simple to implement)

**Comment by alloy** [comment]
Okidoki :+1:

**Comment by alloy** [comment]
![single-search-outside-of-stack](https://cloud.githubusercontent.com/assets/2320/8680690/49f6b806-2a63-11e5-9d4f-a1a818d2ec4e.gif)

**Comment by orta** [comment]
:+1:
