### ISSUE TITLE
No recognition of regaining network connection 

### ISSUE THREAD

**Issue by katarinabatina** [artsy/eigen#620]

**Comment by katarinabatina** [comment]
Went on subway, opened app, got the network disconnected screen, closed app, reopened at home with network connection and wifi, the same disconnected screen stayed. Had to refresh app.

**Comment by alloy** [comment]
I think this is pretty much the same issue as #624, no?

**Comment by alloy** [comment]
@katarinabatina I’m gonna assume this is indeed the same as #624.
