### ISSUE TITLE
open app after just closing it, get wrong orientation

### ISSUE THREAD

**Issue by katarinabatina** [artsy/eigen#621]
![image](https://cloud.githubusercontent.com/assets/6482926/8640057/f20fdace-28b8-11e5-96a5-20eb1cac0c3c.png)

after closing ios system message 
![image](https://cloud.githubusercontent.com/assets/6482926/8640058/fabb0112-28b8-11e5-85fc-ba8a51448329.png)

after hitting back button 
![image](https://cloud.githubusercontent.com/assets/6482926/8640060/0ca5b232-28b9-11e5-91bb-86129c938ebd.png)

trying to repo...

**Comment by alloy** [comment]
It appears that the dev view is allowed to rotate, which shouldn’t be allowed, but it’s also not a larger user facing problem.

Steps to reproduce:

1. Open an artwork.
2. Rotate to landscape to enter VIR mode
3. Shake device to open dev menu

![ios simulator screen shot 13 jul 2015 15 58 04](https://cloud.githubusercontent.com/assets/2320/8651263/20f4b23c-2978-11e5-97f8-b01c552284ac.png)
