### ISSUE TITLE
Web view user session error

### ISSUE THREAD

**Issue by katarinabatina** [artsy/eigen#622]
home won't load, tap shows get this message 
![image](https://cloud.githubusercontent.com/assets/6482926/8640080/99bc3268-28b9-11e5-84b4-4e092ffb12be.png)

**Comment by alloy** [comment]
I’m not sure if this is an Eigen problem or a microgravity one.

@craigspaeth Any insight as to what causes these problems?

**Comment by alloy** [comment]
This error is shown by Force/Martsy when they query Gravity for the user details and that query times-out. Thus it is definitely not something that Eigen is doing wrong.

It would be helpful for Force/Martsy if we keep track of exactly when we see these errors happening. So let’s keep track of that till the end of the next sprint or so.

**Comment by alloy** [comment]
Gonna close this for now, as I’ve not heard of it happening since then.
