### ISSUE TITLE
After fresh download, notification gems are enacted 

### ISSUE THREAD

**Issue by katarinabatina** [artsy/eigen#625]
![](http://i.imgur.com/df1Y9w0.jpg) Just downloaded new beta and red notifications gem is lit up but I'm not signed in

**Comment by alloy** [comment]
Normally this data would only be fetched when you’re signed in, so I think this is simply an issue with iOS still showing data of the previous installation of the app, which it still has cached. I think all notification related data is cached for 24 hours, as the official docs from Apple say that if you want to re-test the ‘Allow Notifications’ alert to show up, you have to:

* restart device
* set date a minimum of 24 hours into the future
* restart device again

In any case, however iOS caches this data, this will not be an issue for a normal user that does not re-install the app all the time.
