### ISSUE TITLE
File google-services.json is missing

### ISSUE THREAD

**Issue by heylee-svg** [artsy/eigen#6277]
I build the project it show missing google-service.json file
did it miss upload?

Execution failed for task ':app:processDebugGoogleServices'.
> File google-services.json is missing. The Google Services Plugin cannot function without it. 
   Searched Location: 
  /Users/dhg/reactnative/eigen/android/app/src/debug/google-services.json
  /Users/dhg/reactnative/eigen/android/app/src/google-services.json
  /Users/dhg/reactnative/eigen/android/app/src/Debug/google-services.json
  /Users/dhg/reactnative/eigen/android/app/google-services.json

**Comment by ahmamedhat** [comment]
Yeah, Me too

**Comment by abhishek-netizen** [comment]
@ahmamedhat hey just add  google-service.json file to project/android folder,
create that g-service.json file by creating a project in firebase, & dont forget to edit the "package_name" inside g-s.json file to 
"package_name": "net.artsy.app"

**Comment by ahmamedhat** [comment]
@abhishek-netizen Thank you

**Comment by abhishek-netizen** [comment]
same here, i am facing this error too, is there any example to get to know what to send in env file

**Comment by brainbicycle** [comment]
Hey we merged a PR recently that we believe should fix this: https://github.com/artsy/eigen/pull/7024, there are instructions in https://github.com/artsy/eigen/blob/main/docs/getting_started.md for independent contributors, let us know if you still have trouble!

**Comment by AAverin** [comment]
@brainbicycle #7024 seems to fixes Google Services for iOS, but not for Android

**Comment by AAverin** [comment]
I have used this mock version to workaround:
```
{
  "project_info": {
    "project_id": "PRODJECT-ID",
    "project_number": "PROJECT-NUMBER",
    "name": "APPLICATION-NAME"
  },
  "client": [
    {
      "client_info": {
        "mobilesdk_app_id": "1:PROJECT-NUMBER:android:HASH-FOR-FLAVOR1",
        "client_id": "android:net.artsy.app",
        "client_type": 1,
        "android_client_info": {
          "package_name": "net.artsy.app"
        }
      },
      "oauth_client": [
        {
          "client_id": ""
        }
      ],
      "api_key": [
        {
          "current_key": ""
        }
      ],
      "services": {
        "analytics_service": {
          "status": 1
        },
        "cloud_messaging_service": {
          "status": 2,
          "apns_config": []
        },
        "appinvite_service": {
          "status": 1,
          "other_platform_oauth_client": []
        },
        "google_signin_service": {
          "status": 1
        },
        "ads_service": {
          "status": 1
        }
      }
    }
  ],
  "client_info": [],
  "ARTIFACT_VERSION": "1"
}

```
