### ISSUE TITLE
bell/works by artist you follow not connecting to native artwork views

### ISSUE THREAD

**Issue by katarinabatina** [artsy/eigen#629]
tap bell
![image](https://cloud.githubusercontent.com/assets/6482926/8654362/c3cd5818-2957-11e5-8a2e-0f0328bc35b0.png)

tap first artwork, get force view instead of artwork view...also no way of getting back to previous view 
![image](https://cloud.githubusercontent.com/assets/6482926/8654372/d68020d0-2957-11e5-8463-36ed876d8ffe.png)

**Comment by alloy** [comment]
It looks like Force is using something like PJAX to load the link instead of actually opening the link.

**Comment by alloy** [comment]
It’s not PJAX, but the outcome is the same. Filed a Force ticket: https://github.com/artsy/force/issues/3145

**Comment by alloy** [comment]
This has been fixed, tested on staging, but not yet deployed to production.
