### ISSUE TITLE
force dropdown picker hard to deal with in eigen

### ISSUE THREAD

**Issue by katarinabatina** [artsy/eigen#631]
example on shows page, the all cities dropdown feels broken, making a selection is very difficult 
http://cl.ly/image/213N3U3h3N2D

**Comment by katarinabatina** [comment]
force story https://github.com/artsy/force/issues/3128

**Comment by alloy** [comment]
@anipetrov In addition to #687, can you keep tabs on this one as well?

**Comment by anipetrov** [comment]
Yes, got it! @alloy

**Comment by alloy** [comment]
Fixed in https://github.com/artsy/force/pull/3391
