### ISSUE TITLE
Onboarding keyboard has odd gradient behind it, should be removed

### ISSUE THREAD

**Issue by katarinabatina** [artsy/eigen#633]
@owendodd do you have a screen shot you can add here?

**Comment by owendodd** [comment]
Yeah sorry, been waiting for my photos to sync in the cloud. :/

**Comment by owendodd** [comment]
![img_2951](https://cloud.githubusercontent.com/assets/3196536/8658128/f7de651c-296f-11e5-863a-05e335546126.PNG)

**Comment by owendodd** [comment]
Sorta hard to see here. I think it is caused by the button bellow.

**Comment by alloy** [comment]
Can you elaborate on “the button below” ?

**Comment by katarinabatina** [comment]
@alloy the screen prior looks like this

![image](https://cloud.githubusercontent.com/assets/6482926/8850739/7dce96d8-3118-11e5-8d8c-3157cab5ef06.png)

when the keyboard comes up I think it blurs the white button below causing that effect

**Comment by alloy** [comment]
@katarinabatina Aha, thanks! :+1:
