### ISSUE TITLE
zero state for works by artist you follow needs work 

### ISSUE THREAD

**Issue by katarinabatina** [artsy/eigen#635]
screen shot coming but it does not look great. 

also spacing for 1024px is pretty packed

**Comment by alloy** [comment]
Why was this closed?

**Comment by katarinabatina** [comment]
It's a force issue

Katarina

**Comment by alloy** [comment]
Ok, there was also this in Martsy https://github.com/artsy/microgravity/issues/930, which probably also needs better design and should be re-opened?
