### ISSUE TITLE
iPad bottom menu bar has incorrect padding/positioning for menu elements

### ISSUE THREAD

**Issue by celinenguyen** [artsy/eigen#636]
The Artsy logo on the bottom left corner is (nearly) flush against the left edge of the screen. Happens in landscape and portrait mode. See menu bar of the screenshot below:

![img_0012](https://cloud.githubusercontent.com/assets/1417844/8655875/fecfc932-2961-11e5-9f84-35e24baf5634.PNG)

**Comment by alloy** [comment]
Note: You need to rotate a couple of times to get it into this state.
