### ISSUE TITLE
iPad has a flashing rectangle when touching at sidebar on 'Works by Artist You Follow'

### ISSUE THREAD

**Issue by celinenguyen** [artsy/eigen#637]
Touching the whitespace on the left sidebar of the WAYF page creates this brief flashing black rectangle around the sidebar area (hard to screenshot, sorry!). Doesn't appear when viewing the page in iPad Safari.

**Comment by alloy** [comment]
![force-works-for-you-selection](https://cloud.githubusercontent.com/assets/2320/8672070/f7b7dd00-2a2a-11e5-8a91-60e9bc01b4f3.gif)

This is a Force issue, I can also reproduce it in Safari on the iPad.

**Comment by alloy** [comment]
Moved to https://github.com/artsy/force/issues/3139

**Comment by alloy** [comment]
This has been fixed upstream.
