### ISSUE TITLE
artist section in eigen (iphone) is linking to the wrong place

### ISSUE THREAD

**Issue by katarinabatina** [artsy/eigen#638]
correct order:

https://m.artsy.net/artists  to https://m.artsy.net/gene/emerging-art

right now we go to native gene pages which are not organized by artist and therefore are confusing to arrive at. We should instead link to the microgravity view instead 

![image](https://cloud.githubusercontent.com/assets/6482926/8657457/ab52da56-296b-11e5-9f4a-5dbd6de41cdb.png)

----

Required fixes:
- [x] Martsy: https://github.com/artsy/microgravity/issues/960
- [ ] Force: https://github.com/artsy/force/issues/3209

**Comment by katarinabatina** [comment]
correct order:

https://m.artsy.net/artists  to https://m.artsy.net/gene/emerging-art

right now we go to native gene pages which are not organized by artist and therefore are confusing to arrive at. We should instead link to the microgravity view instead 

![image](https://cloud.githubusercontent.com/assets/6482926/8657457/ab52da56-296b-11e5-9f4a-5dbd6de41cdb.png)

**Comment by alloy** [comment]
@katarinabatina This is only easily and fast done if we decide that there’s no place that should link directly to the overview of a gene, because then we can decide to not route that URL, but if there are places where such a URL _should_ route then it’s going to get hard.

I don’t know from the top of my head if there are any other places. Seeing as our ‘all genes’ overview is native as well, it won’t be a problem there.

**Comment by katarinabatina** [comment]
@alloy As in, from the category pages?

**Comment by alloy** [comment]
> @alloy As in, from the category pages?

Yeah, because our category pages are native, it won’t be a problem there if we’d re-route the `https://artsy.net/gene/NAME` URLs. So I think re-routing will be fine.

**Comment by katarinabatina** [comment]
yeah I think desired end result would be to only have this affect coming through the artist section if possible and leave the category entry points as is

**Comment by alloy** [comment]
The alternative is to ask Force/Martsy to show these ‘artists by gene’ under `/gene/:name/artists` so that when we do ever need to route to just our native gene view it can be done with `/gene/:name`.

@craigspaeth Does that sound feasible to you?

**Comment by alloy** [comment]
Filed a Martsy ticket https://github.com/artsy/microgravity/issues/960

**Comment by alloy** [comment]
Filed a Force ticket https://github.com/artsy/force/issues/3209

**Comment by alloy** [comment]
This is fixed in Martsy, just needs deploying.

**Comment by alloy** [comment]
Gonna move to the next sprint to keep an eye on, but at least we’ll be able to close this milestone.

**Comment by alloy** [comment]
@anipetrov Assigning this to you to keep an eye on, as it is a cross-team dependency.

**Comment by alloy** [comment]
This should all be fixed upstream by now.
