### ISSUE TITLE
museums page won't load coming from explore

### ISSUE THREAD

**Issue by katarinabatina** [artsy/eigen#639]
tap on museum page from explore and nothing ever loads, works fine in safari

**Comment by alloy** [comment]
It seems to work fine for me. Are you still experiencing this issue?

**Comment by katarinabatina** [comment]
@alloy seems to be working fine. I think we have some issues related to first-install or first-session and getting force views. Just a hypothesis but I think it might explain some of the issues I've been seeing. Let's close this for now
