### ISSUE TITLE
iPad favorites page transition when you touch to go to a favorite artwork/artist is buggy

### ISSUE THREAD

**Issue by celinenguyen** [artsy/eigen#640]
(@katarinabatina need to shoot video of this issue)

iPad landscape view only—when you're on the Favorites tab and pressing an artwork/artist to get to the artwork/artist-specific page, there's an awkward black rectangle that appears in the space where the new page is sliding into view. The previous/background page during the transition is not properly dimmed.

Not an issue on portrait view or on iPhone, where the background page is dimmed and there's no awkward black rectangle.

**Comment by katarinabatina** [comment]
@celinenguyen having trouble reproducing this on my ipad. You may need to record the video yourself it's working ok for me

**Comment by celinenguyen** [comment]
[Video here](https://www.icloud.com/sharedalbum/#B06JtdOXmJR4ck3;05453B5B-4061-454A-9AF6-3322EF664ACD). I was able to replicate it by:

* going to favorites area
* touching an artwork
* rotating while I was on the artwork page
* going back (page transition showed the bug)

After doing that rotate, all subsequent actions of touching an artwork from the favorites page would produce the transition bug too (when going from favorites view to artwork view).
