### ISSUE TITLE
how to fill sparse matrix fastly?

### ISSUE THREAD

**Issue by wujilingfeng** [artsy/eigen#6409]
I was filling a sparse matrix, but it's so slowly. 
I was wondering how to fill sparse matrix fastly?
My code is like :
```
 SparseMatrix<double> A(16777216,16777216);
    A.reserve(VectorXi::Constant(16777216,140));
for(..)
{
    for(...)
   A.coeffRef()
}

```

**Comment by brainbicycle** [comment]
👋 hi there! I think perhaps this issues was meant for the linear algebra library Eigen? https://github.com/PX4/eigen
