### ISSUE TITLE
When searching, "No results found." text is hard to notice/see

### ISSUE THREAD

**Issue by celinenguyen** [artsy/eigen#641]
The "No Results found." text on iPad is far away from where the user expects the results to appear—so it may be hard to notice. Not quite as bad on the iPhone but it could be repositioned/made larger too.

On iPad:

![img_0014](https://cloud.githubusercontent.com/assets/1417844/8656248/631193a6-2964-11e5-9a35-8757db33eec2.PNG)

On iPhone:

![img_2123](https://cloud.githubusercontent.com/assets/1417844/8656262/723e0012-2964-11e5-887a-f6ca80d92c50.PNG)

**Comment by katarinabatina** [comment]
increase type size to 24px make text full opacity instead of 50% white
