### ISSUE TITLE
Add 50px to "Do you buy art?" in onboarding

### ISSUE THREAD

**Issue by celinenguyen** [artsy/eigen#642]
The "Do you buy art?" text initially looks like it's another selectable option on the screen (just like "Yes, I buy art" &c). Maybe should be bolded/given more bottom margin from the text?

![img_2122](https://cloud.githubusercontent.com/assets/1417844/8656305/c8fa400a-2964-11e5-940a-e5fc9e4d20a8.PNG)

**Comment by katarinabatina** [comment]
add 50px of space 
![image](https://cloud.githubusercontent.com/assets/6482926/8660793/16b47876-2981-11e5-96af-c1c9cb0abe90.png)
