### ISSUE TITLE
Works that have a 'More Info' option on the artwork page have blank 'More Info' pages when you tap through

### ISSUE THREAD

**Issue by celinenguyen** [artsy/eigen#643]
For examples, see the Tara Donavan show at the Parrish Art Museum (currently the third item in the featured carousel on the home screen), where 2/3 show items don't have any content when you tap through to the 'More Info' page.

Also, Carsten Höller's *Upside-Down Googles*, 2015 piece (and others from the Höller show at Hayward Gallery at Southbank Centre).

**Comment by alloy** [comment]
Duplicate of #130.
