### ISSUE TITLE
new network connection error state

### ISSUE THREAD

**Issue by katarinabatina** [artsy/eigen#644]
![image](https://cloud.githubusercontent.com/assets/6482926/8705422/8ac84770-2af7-11e5-9274-8bac2e03482c.png)

@alloy updated mock

**Comment by alloy** [comment]
To be clear, the ‘tap to try reloading’ subtitle is only an instruction for the implementation, right?

**Comment by alloy** [comment]
These are the locations from where we currently present the gradient network issue alert:

* When [failing to get an X-App token](https://github.com/artsy/eigen/blob/1723ee6dfd824842e2548faff89d4b6fcc23677e/Artsy/Networking/ArtsyAPI.m#L193-L201): “Couldn't reach Artsy”
* When [failing to save an artwork](https://github.com/artsy/eigen/blob/1723ee6dfd824842e2548faff89d4b6fcc23677e/Artsy/View_Controllers/Artwork/ARArtworkViewController+ButtonActions.m#L45-L47): No current specific message.
* When [following an artist](https://github.com/artsy/eigen/blob/1723ee6dfd824842e2548faff89d4b6fcc23677e/Artsy/View_Controllers/Core/ARArtistViewController.m#L326-L330): No current specific message.
* When [signing-in with user credentials](https://github.com/artsy/eigen/blob/1723ee6dfd824842e2548faff89d4b6fcc23677e/Artsy/View_Controllers/Login_and_Onboarding/Onboarding_stages/3_-_Sign_Up_+_Log_In/ARCreateAccountViewController.m#L236-L240): No current specific message.
* When [signing-in with Twitter credentials](https://github.com/artsy/eigen/blob/1723ee6dfd824842e2548faff89d4b6fcc23677e/Artsy/View_Controllers/Login_and_Onboarding/Onboarding_stages/3_-_Sign_Up_+_Log_In/AROnboardingMoreInfoViewController.m#L321-L325): No current specific message.
* When [signing-in with Facebook credentials](https://github.com/artsy/eigen/blob/1723ee6dfd824842e2548faff89d4b6fcc23677e/Artsy/View_Controllers/Login_and_Onboarding/Onboarding_stages/3_-_Sign_Up_+_Log_In/AROnboardingMoreInfoViewController.m#L345-L349): No current specific message.
* When [following a gene](https://github.com/artsy/eigen/blob/1723ee6dfd824842e2548faff89d4b6fcc23677e/Artsy/Views/Collection_Views/ARGeneViewController.m#L195-L197): No current specific message.

So none of them have really useful error messages at the moment.

**Comment by alloy** [comment]
What I really like in the design of Echofon for iPhone is that the alert has a question mark button which, when pressed, shows a regular iOS alert that shows the raw error. This way people can provide us with more helpful feedback, whereas most other users won’t even tap that button. (It could even be a very dim button imo.)

![slack_for_ios_upload-3](https://cloud.githubusercontent.com/assets/2320/8673416/9bedd130-2a36-11e5-8d06-5b470b80edb7.png)

![slack_for_ios_upload-4](https://cloud.githubusercontent.com/assets/2320/8673429/a7b0a3e4-2a36-11e5-85cb-bf52368018d1.png)

**Comment by katarinabatina** [comment]
To be clear, the ‘tap to try reloading’ subtitle is only an instruction for the implementation, right?

— correct!

**Comment by katarinabatina** [comment]
@alloy when do we know there is no connection for these

When signing-in with user credentials: No current specific message.
When signing-in with Twitter credentials: No current specific message.
When signing-in with Facebook credentials: No current specific message.

when they first tap the [connect with facebook] button?

or after they come back to the app?

same thing with singing in w/ email, is it after they tap [sign up with email] or after they tap [enter] after filling out their details?

**Comment by alloy** [comment]
> when do we know there is no connection for these

All of these errors are for _after_ we’ve (tried to) send the credentials to the Artsy servers.

In the case of Twitter/Facebook that’s after they’ve come back to the app and in the case of email that’s after they tap enter.

**Comment by alloy** [comment]
@katarinabatina Thanks for the updated mocks!

* Can you get me the warning sign asset?
* I notice you used ‘Sign up failed.’ for the sign in case as well. Is there a reason for that over ‘Sign in failed.’ ?

**Comment by katarinabatina** [comment]
warning sign asset

1. http://cl.ly/image/45013b0M2O0g
2. yes lets change
3. nope that was an oversight!

**Comment by alloy** [comment]
On it! 💂👋

**Comment by alloy** [comment]
@katarinabatina Can you get me the refresh button asset? Including border.

**Comment by katarinabatina** [comment]
here it is http://cl.ly/image/33052t2y1f1D

**Comment by alloy** [comment]
When you have no connection at all, failing actually goes real fast, but I let the button spin a bit more, so people feel like we did our best.

![network-refresh](https://cloud.githubusercontent.com/assets/2320/8752572/1b0b591c-2cb5-11e5-902a-babc2ebf9dcd.gif)

**Comment by katarinabatina** [comment]
that's nice of you to think of ;)

**Comment by katarinabatina** [comment]
do you have a screen cap of the other kind of error?

**Comment by alloy** [comment]
I'm polishing that one now, I'll definitely add one once it's done.

**Comment by alloy** [comment]
![ios simulator screen shot 17 jul 2015 21 49 12](https://cloud.githubusercontent.com/assets/2320/8757190/91eea0ac-2cd8-11e5-90bb-a4190455d564.png)
![ios simulator screen shot 17 jul 2015 21 51 41](https://cloud.githubusercontent.com/assets/2320/8757198/9248ff5c-2cd8-11e5-82c4-9af62c184277.png)
![ios simulator screen shot 17 jul 2015 21 53 08](https://cloud.githubusercontent.com/assets/2320/8757195/9246c37c-2cd8-11e5-97d0-80c6de046071.png)
![ios simulator screen shot 17 jul 2015 21 55 28](https://cloud.githubusercontent.com/assets/2320/8757199/92492766-2cd8-11e5-8ab4-eb1c0bd91e6a.png)
![ios simulator screen shot 17 jul 2015 21 55 38](https://cloud.githubusercontent.com/assets/2320/8757197/92472fc4-2cd8-11e5-8fe4-db51efab0643.png)
![ios simulator screen shot 17 jul 2015 22 25 14](https://cloud.githubusercontent.com/assets/2320/8757196/9247150c-2cd8-11e5-8ee9-3523c5fb33e7.png)
![ios simulator screen shot 17 jul 2015 22 26 00](https://cloud.githubusercontent.com/assets/2320/8757191/920836f2-2cd8-11e5-9208-829e9c828998.png)
![ios simulator screen shot 17 jul 2015 22 26 27](https://cloud.githubusercontent.com/assets/2320/8757192/921f2470-2cd8-11e5-8058-4ce9c265e2fb.png)
![ios simulator screen shot 17 jul 2015 22 27 27](https://cloud.githubusercontent.com/assets/2320/8757194/9237890c-2cd8-11e5-9ad8-b28b649c9182.png)

**Comment by alloy** [comment]
Triggering the 'sign up' ones is a bit harder, hence no screenshots.
