### ISSUE TITLE
test issue trying to tag people

### ISSUE THREAD

**Issue by 1aurabrown** [artsy/eigen#645]
@owendodd @nsimmons206 @lucaderosso

**Comment by owendodd** [comment]
:wave:

**Comment by 1aurabrown** [comment]
![screen shot 2015-07-13 at 2 46 01 pm](https://cloud.githubusercontent.com/assets/3171662/8657823/ed39fc68-296d-11e5-9ef5-f88a5538f284.png)

fixed the mention autocomplete for design team members :)
