### ISSUE TITLE
No padding top on certain onboarding views

### ISSUE THREAD

**Issue by owendodd** [artsy/eigen#647]
![img_2956](https://cloud.githubusercontent.com/assets/3196536/8658329/21a4c9f8-2971-11e5-9b38-b2aecd1e67e4.PNG)
![img_2951](https://cloud.githubusercontent.com/assets/3196536/8658337/26d9380a-2971-11e5-9121-16026e1233d9.PNG)

**Comment by orta** [comment]
So, it's expected that there wouldn't be a status bar throughout the onboarding,

![screen shot 2015-07-15 at 09 51 58](https://cloud.githubusercontent.com/assets/49038/8694468/2e265f90-2ad7-11e5-9b2b-d02d62779da3.png)

so I need to figure out where it's getting turn on from, cause I can't get it

**Comment by orta** [comment]
I tried going through onboarding via creating a user right away, and via signing up inside the app and couldn't find a way to replicate. 

@owendodd - any ideas what you did? Or what phone OS you're using ( iOS9? )

**Comment by owendodd** [comment]
Ahh yes, I am in iOS9, didn't think about that...

**Comment by orta** [comment]
:+1:

**Comment by alloy** [comment]
I have no clue, but I expect this to be not too simple.

**Comment by alloy** [comment]
@1aurabrown Can you look into this one on iOS 9?

**Comment by alloy** [comment]
This only occurs with the initial on-boarding, the status bar is hidden as expected when on-boarding within the app.
