### ISSUE TITLE
categories show up in wrong orientation 

### ISSUE THREAD

**Issue by katarinabatina** [artsy/eigen#650]
holding ipad landscape, tap explore, tap categories get-->

![image](https://cloud.githubusercontent.com/assets/6482926/8675443/fd51203c-2a11-11e5-98f0-940284f5261c.png)

**Comment by orta** [comment]
I've struggled to replicate this in the sim, moving to device.

**Comment by ashfurrow** [comment]
Could be related: https://github.com/artsy/eigen/issues/448

**Comment by 1aurabrown** [comment]
Im looking at it


On Tue, Jul 21, 2015 at 13:53, artsy/eigen
<reply@reply.github.com>
wrote:
Could be related: #448 [https://github.com/artsy/eigen/issues/448]

—
Reply to this email directly or view it on GitHub
[https://github.com/artsy/eigen/issues/650#issuecomment-123414932] .[https://github.com/notifications/beacon/ADBlTjMXFIB9w9wzht0Dk2cr4rNcm2kWks5ofn6LgaJpZM4FYRt-.gif]

**Comment by orta** [comment]
Repro'd on my beta on an iPad iOS 8.4.
Go into categories, tap through to anything, rotate, go back.

**Comment by alloy** [comment]
Closed by #694
