### ISSUE TITLE
Create unified way to define whether to perform work synchronously or not.

### ISSUE THREAD

**Issue by alloy** [artsy/eigen#658]
We currently have `-[ARDispatchManager useSyncronousDispatches]` and `-[UIViewController shouldAnimate]` which both are basically to allow async work during normal app operations but restrict to sync work during testing.

Replace both of them with a global variable like `ARPerformWorkSynchronously` and define it like I previously did here https://github.com/artsy/eigen/commit/5ad9a3b8003c6f444d94b60d82b5e194d29893ac.

For previous discussion see https://github.com/artsy/eigen/pull/654#discussion-diff-34613124.

**Comment by jorystiefel** [comment]
Note to self: fix spelling of synchronous
