### ISSUE TITLE
Collapsible text view on gene view freezes app

### ISSUE THREAD

**Issue by alloy** [artsy/eigen#672]
I haven't run any stack dump yet, but it appears the app deadlocks. After enough time and moving the ap into the background, the app just seems to restart.

**Comment by 1aurabrown** [comment]
Yikes; will look at it.

**Comment by ashfurrow** [comment]
What build was this seen on? I couldn't even expand the text – the app got stuck in an infinite recursion loop introduced by this commit: https://github.com/artsy/eigen/commit/44ec4057e9b9b0131a2893be57620b91ae77568d#diff-3b2cfb2303245110984718f08dcb603d

@orta should that be calling `[self openToFullHeightAnimated:YES]` or something?

**Comment by 1aurabrown** [comment]
yup




On Mon, Jul 20, 2015 at 3:19 PM, Ash Furrow <notifications@github.com>
wrote:

> What build was this seen on? I couldn't even expand the text – the app got
> stuck in an infinite recursion loop introduced by this commit: 44ec405
> #diff-3b2cfb2303245110984718f08dcb603d
> <https://github.com/artsy/eigen/commit/44ec4057e9b9b0131a2893be57620b91ae77568d#diff-3b2cfb2303245110984718f08dcb603d>
>
> @orta <https://github.com/orta> should that be calling [self
> openToFullHeightAnimated:YES] or something?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/artsy/eigen/issues/672#issuecomment-122995575>.
>



-- 

[A.]


Laura Brown

Artsy <http://artsy.net/>

laura@artsy.net <caroline@artsy.net>

**Comment by orta** [comment]
![When I send my friend for drinks and he comes back with girls](http://i.imgur.com/c3D1iad.gif)
