### ISSUE TITLE
Notifications are inaccurate 

### ISSUE THREAD

**Issue by katarinabatina** [artsy/eigen#673]
Notification number never reflects try update, keeps saying I have 56 new works even though there are only three new based on the last time I checked

**Comment by alloy** [comment]
This is an issue of martsy/force not yet having implemented the feature to consider notifications as read when the page is loaded. This is what they are planning, I’ll lookup what the respective ticket are later.

**Comment by alloy** [comment]
It’s mentioned as part of [this Force ticket](https://github.com/artsy/force/issues/2383), I’ve added a [comment](https://github.com/artsy/force/issues/2383#issuecomment-122855316) to make it clear that this is important for Eigen.

**Comment by wrgoldstein** [comment]
Are you guys using the flat event feed under `api/v1/me/notifications`?  You can [see in the implementation](https://github.com/artsy/gravity/blob/master/app/models/util/notification_service.rb#L29) that that endpoint wasn't designed to respect any "mark as read" markers.  In fact, a better name for it might be "recently added works".

**Comment by alloy** [comment]
@wrgoldstein Yup, that's the one. So which should we be using? `api/v1/me/notifications/feed`?

**Comment by wrgoldstein** [comment]
Cool.  `api/v1/me/notifications/feed` is the aggregated feed for artsy.net.  It doesn't yet support the x-total-count header, or any kind of total notifications count.

Do you want the counts to be aggregated?  E.g. if 5 works by Andy Warhol are published at the same time, should the count increment by 1 or 5?

There isn't currently an endpoint that does what you're asking.  We could support that next with a relatively small update to the endpoint:   https://trello.com/c/3RlHaOzE/734-support-push-notifications-for-ios

**Comment by alloy** [comment]
> E.g. if 5 works by Andy Warhol are published at the same time, should the count increment by 1 or 5?

5, as it does now.

> There isn't currently an endpoint that does what you're asking. We could support that next with a relatively small update to the endpoint.

That would be perfect. So to be clear, when the ‘works for you’ page is visited on either Martsy or Force, this feed would no longer return the works shown there?

**Comment by wrgoldstein** [comment]
Yes with
1. a new method on NotificationService that respects flushed markers but only returns certain events
  * and paginates/uses a `x-total-count` header
2. extending the PUT notifications endpoint to also flush NotificationService events
3. making sure the Works For You page hits this endpoint

doable after the PR you reference above gets merged

**Comment by wrgoldstein** [comment]
when https://github.com/artsy/gravity/pull/9098 is merged, the endpoint you're currently using will respect a `?unread=true` param, solving this problem.

**Comment by wrgoldstein** [comment]
oh, sorry, also need to make a small change to force/microgravity as well after this is deployed

**Comment by alloy** [comment]
Yikes! I was not under the impression that we would still have to make a change, so I’m pulling the build I submitted to the App Store immediately and will update the request to include that param and re-submit.

Thanks for making the changes 🙏🏽 💯💫

**Comment by wrgoldstein** [comment]
Ay, sorry to hear that!  Artsy.net uses that endpoint currently, so we couldn't just change it wholesale :(

**Comment by alloy** [comment]
@wrgoldstein Can you please review/merge this one asap? https://github.com/artsy/eigen/pull/698

**Comment by alloy** [comment]
This has all been merged and should be done.
