### ISSUE TITLE
Investigate dependency build cache

### ISSUE THREAD

**Issue by ashfurrow** [artsy/eigen#678]
CircleCI lets us cache gems and pods, but only the pods' source. It would be killer to also cache their build artefacts to avoid recompiling every time. 

Shouldn't be too hard. Tricky part involves Xcode – how does it determine whether or not an object needs to be recompiled? Is it by its modification date? What does it compare that date to? Can we modify it? 

These are questions I don't know the answers to off the top of my head. Could be worth looking into. @circlrci might even consider adding it as a first-party caching mechanism some day.

**Comment by orta** [comment]
This could be done by using a pre-determined builds directory in CI, and making sure that's inside Circles folder caching
