### ISSUE TITLE
[iPhone] Possible to get app in incorrect orientation

### ISSUE THREAD

**Issue by alloy** [artsy/eigen#681]
1. Open VIR mode in landscape
2. Navigate back
3. App is in incorrect orientation (landscape)

Basically like #621.

Tested on device.

**Comment by orta** [comment]
cool, this is a break from previous behaviour (back should show only in vertical), can we get some tests on this pleassseee.

**Comment by ashfurrow** [comment]
Confirmed! 

![screen shot 2015-07-21 at 11 53 49 am](https://cloud.githubusercontent.com/assets/498212/8805422/2db73a1c-2f9f-11e5-8617-fe6716b7c2cc.png)
