### ISSUE TITLE
Skip onboarding when user registers for an auction 

### ISSUE THREAD

**Issue by katarinabatina** [artsy/eigen#687]
right now when a logged out user taps the bid or register, we pop the general signup/login CTA. After the user signs up with email or FB/Twitter, we should skip onboarding. On the phone this means bypassing the native onboarding flow and for ipad it means bypassing the embedded force onboarding. Instead, we should shoot them directly to the registration screen shown here 
![image](https://cloud.githubusercontent.com/assets/6482926/8804792/dfa5afa0-2f9b-11e5-9de0-bfd900693823.png)

@alloy or @1aurabrown can you give a brief estimate on the difficulty level of this?

**Comment by alloy** [comment]
Is this a native screen we already have or is the question about creating the view?

>  After the user signs up with email or FB/Twitter, we should skip onboarding.

I’m not sure I follow this. Should this have been like so?

> right now when a logged out user taps the ~~sign up~~ **bid** button

**Comment by katarinabatina** [comment]
we dont need to create a new view, we just need to skip anything that happens after initial account creation and dump them into this form https://staging.artsy.net/auction-registration/watermill-summer-benefit-and-live-auction-2015

**Comment by alloy** [comment]
To summarise private discussion, this behaviour is only triggered when the user taps the bid or register to bid buttons.

**Comment by alloy** [comment]
I don’t foresee any complications, this should probably take 3-4 hours.

**Comment by alloy** [comment]
@katarinabatina Just to be sure, I assume this one is high-ish priority, right?

**Comment by katarinabatina** [comment]
@alloy yes

**Comment by jorystiefel** [comment]
I put in a switch to skip the onboarding flow when the users hits "Bid" or "Register to Bid." I was not able to dump the user directly into the "Register to Bid" form after signing up. The logic to achieve happens on Martsy.

If we'd like to make this flow directly into the Register To Bid form, Martsy would have to handle this.

What it does show you is this, and from there you tap Register To Bid to see the form

![ios simulator screen shot jul 28 2015 4 09 20 pm](https://cloud.githubusercontent.com/assets/1065248/8942378/0a4486a8-3543-11e5-856e-d86093610c42.png)

----

I tried to look at the flow on Martsy, but the flow appears to be broken as it shows you the Register To Bid form before asking you to signup/login, for which I filed this ticket: https://github.com/artsy/microgravity/issues/984

**Comment by jorystiefel** [comment]
We currently cannot skip the onboarding on the iPad, we do have a way to tell if the signup request is coming from a Register To Bid link in a Force view. To be able to do this, I've filed the following request with Force: https://github.com/artsy/force/issues/3211

**Comment by alloy** [comment]
@anipetrov Can you keep track of https://github.com/artsy/microgravity/issues/984 & https://github.com/artsy/force/issues/3211 with regards to the upcoming auction season (if they’re deemed important enough)?

**Comment by anipetrov** [comment]
I got it @alloy

**Comment by alloy** [comment]
![](http://media0.giphy.com/media/2lB4XWVJLOTh6/giphy.gif)
