### ISSUE TITLE
Allow viewing of artwork image without the back arrow

### ISSUE THREAD

**Issue by bhoggard** [artsy/eigen#701]
I should be able to look at an artwork without anything on the screen.

![artwork-view](https://cloud.githubusercontent.com/assets/19369/8908816/2725c068-344c-11e5-8fc7-915e869665e8.jpeg)

**Comment by jorystiefel** [comment]
@orta @alloy this is a pretty simple change. Am I okay to PR this, or does this need a design/ui approval?

```objc
#pragma mark - ARMenuAwareViewController

- (BOOL)hidesBackButton
{
    return NO;
}
```

**Comment by orta** [comment]
there probably should be more nuance to it than just that. 
E.g. a tap to hide, and a tap to return, like Folio/Photos.app. 
Or hiding on any scroll and then returning when idle.

**Comment by jorystiefel** [comment]
Well, that back arrow actually doesn't perform any different action than just tapping the image - so it's only there as a signifier. Without it, our behavior matches Tumblr's, so not sure the back arrow is really necessary there.

**Comment by alloy** [comment]
I agree with @jorystiefel. Because the fullscreen view is entered by tapping as well it makes intuitive sense to close it that way as well.

**Comment by katarinabatina** [comment]
Once we prioritize a re-write of the artwork VC the updated designs will address this problem
