### ISSUE TITLE
Art title collides with status bar

### ISSUE THREAD

**Issue by hichemfantar** [artsy/eigen#7040]
![Screenshot_20220706-133516.jpg](https://user-images.githubusercontent.com/34947993/177551405-25ec81a6-2265-468a-bd2e-d4a495b1a9c9.jpg)

**Comment by Sudhanva-Nadiger** [comment]
Can I work on this ?

**Comment by hichemfantar** [comment]
> Can I work on this ?

This issue is very old, I'm not sure if it was fixed.
Try reproducing the issue and if you can't reproduce it then I'll close this issue.
