### ISSUE TITLE
[RFC] New dependency: react-native-vision-camera

### ISSUE THREAD

**Issue by dimatretyak** [artsy/eigen#7159]
**Status:** Open

**Type:** New Dependency

**Name:** react-native-vision-camera

**Github URL:** https://github.com/mrousavy/react-native-vision-camera

**NPM URL:** https://www.npmjs.com/package/react-native-vision-camera

### Description
In the new version of [reverse image](https://www.figma.com/file/d5BqaCzrAPKF78K1WWluM9/Reverse-Image?node-id=3%3A5758), we need to provide more options for users when working with the camera. We should also be able to implement custom design for the camera page. For these purposes, the `react-native-vision-camera` library is perfect for us, which offers great APIs, better performance, improved stability, actively maintained and more features from the box.

### Things to pay attention to
- We need to set `targetSdkVersion` and `compileSdkVersion` to 31, otherwise the project will not be built for Android
- We need to specify `android:exported` value for every activities, services, or broadcast receivers in `AndroidManifest.xml` (you can find [more context here](https://developer.android.com/about/versions/12/behavior-changes-12#exported))

### Alternatives

There is an alternative `react-native-camera` library for React Native. But due to the lack of maintainers and increased code complexity, `react-native-camera` is now deprecated in favor of `react-native-vision-camera`.

**Comment by MounirDhahri** [comment]
such a nice package 👍

**Comment by dimatretyak** [comment]
We will adopt this
[Resolved]
