### ISSUE TITLE
Zero state for "Works For You" section

### ISSUE THREAD

**Issue by nsimmons206** [artsy/eigen#720]
@alloy This is the zero state for when a user has not followed any artists. If the user has followed artists but no works have been added recently then the message shown on the far right should appear on the screen until a work populates the feed. 

![worksforyou_zerostate_nospec_01](https://cloud.githubusercontent.com/assets/8950911/8941277/a42f24be-353c-11e5-97b6-dd141d12514d.png)
![worksforyou_zerostate_spec_01](https://cloud.githubusercontent.com/assets/8950911/8941278/a42f9444-353c-11e5-9d18-8be7d8ead9e1.png)

**Comment by alloy** [comment]
https://github.com/artsy/microgravity/issues/930
