### ISSUE TITLE
Fix crash in WebCore::StyleResolver::applyMatchedProperties(WebCore::StyleResolver::MatchResult const&, WebCore::Element const*, WebCore::StyleResolver::ShouldUseMatchedPropertiesCache)

### ISSUE THREAD

**Issue by artsyit** [artsy/eigen#723]
### Reason ###

No reason found. Full stack trace includes WebCore, WebKitLegacy, DataDetectorsUI, CoreFoundation, libsystem_pthread.dylib.

### Link to HockeyApp ###

* [https://rink.hockeyapp.net/manage/apps/37029/crash_reasons/40912132](https://rink.hockeyapp.net/manage/apps/37029/crash_reasons/40912132)

**Comment by alloy** [comment]
Closing this in anticipation of #606.
