### ISSUE TITLE
[Notifications] Badge remains when count is 0

### ISSUE THREAD

**Issue by alloy** [artsy/eigen#724]
Maybe this has to do with reading notifications on the web and then coming back to the app? Not sure yet.

**Comment by alloy** [comment]
From @robertlenne:

> I saw "15" on my badge icon a few days ago. After checking my works-for-you feed I still see "15" on the badge icons. (Would expect it to clear). 
>
> A few days later it's still 15 on the badge icon.
>
> I enter the app and now see "13" (Not 15) on the bell in the menu. (When I go back to iOS the badge icon has now updated to "13")
>
> I go into the app, tap the bell to enter the works for you feed, I see that there are 3 new works (by two different artists, so 2 feed items). I don't know why it went from 15 to 13. 
>
> Now, after exiting the app, the count on the badge icon and bell is gone. However, if I quit the app (by swiping it off my app switcher) and open it again the number goes back to 13.

**Comment by alloy** [comment]
> I go into the app, tap the bell to enter the works for you feed, I see that there are 3 new works (by two different artists, so 2 feed items). I don't know why it went from 15 to 13.

This part is not something that Eigen controls.

@craigspaeth @kanaabe @wrgoldstein Any insights into how this would have happened?

**Comment by alloy** [comment]
So, what I think happens in Eigen is the following:

1. The notification count on both the tab and the app icon gets properly set to e.g. 42.
2. The bell tab is tapped and the page starts loading
3. The API marks the notifications as read, but the actual page is not yet done loading
4. The user moves away from the tab before the ‘works for you’ page is done loading or maybe hides the app, but at least some action that makes it so that the ‘reset notification count’ action is never triggered once the ‘works for you page’ is sufficiently loaded
5. The app icon badge never gets removed when the notification count is fetched on app activation

I tested this by marking all my notifications as read and then simply setting the app icon badge to 42. The badge never gets removed no app activation.

**Comment by kanaabe** [comment]
Notifications get marked as 'read' on the server side in Force but I realized that I hadn't updated it to match MG as well. It is still on client side in MG. Updating this should help the situation, do you agree? I'm going to submit that Github issue now.

**Comment by alloy** [comment]
@kanaabe That woud definitely throw things off, so yeah please do. Thanks :+1:

I’m unsure how that would have gotten Robert’s notification count from 15 to 13, but let’s see if it crops up once MG is at least doing the right thing.
