### ISSUE TITLE
[Search] Make keyboard appear more quickly

### ISSUE THREAD

**Issue by jorystiefel** [artsy/eigen#739]
From @robertlenne:

> Search: Seem to be delay before keyboard pop ups up. Would feel snappier if the keyboard started moving as soon as user hits search icon

I definitely have experienced this to, it seems to happen on the first load of the Search view controller after launch, there is a slight delay (enough to be noticeable) between the Search field displaying and the keyboard rising up. Subsequent "Search" loads seem to happen faster.

Maybe there is an earlier place we can call -becomeFirstResponder?

``` objc
- (void)viewDidAppear:(BOOL)animated
{
    [self.view layoutSubviews];
    [super viewDidAppear:animated];

    [self.textField becomeFirstResponder];
}
```

**Comment by katarinabatina** [comment]
This, even today is still an issue for search. @sarahscott I'm not sure if we should write up a new ticket for this but it would be great to have you take a look at this after works for you deeplinking work.
