### ISSUE TITLE
[Artwork] "Contact For Price" not shown

### ISSUE THREAD

**Issue by jorystiefel** [artsy/eigen#740]
Example piece: https://www.artsy.net/artwork/keith-haring-pop-shop-d

On artsy.net, we see the "Contact for price" message. On Eigen, it is absent:

![ios simulator screen shot aug 21 2015 1 25 17 pm](https://cloud.githubusercontent.com/assets/1065248/9414635/157e1aac-4808-11e5-857d-4e9c4cfc3a72.png)

**Comment by anipetrov** [comment]
Could be intentional, so that the `Contact Gallery` button is above the fold?

**Comment by orta** [comment]
We don't have this feature at all @anipetrov

**Comment by orta** [comment]
Nope, I'm wrong, here it is: https://github.com/artsy/eigen/blob/master/Artsy/Views/Artwork/ARArtworkPriceView.m#L47

**Comment by anipetrov** [comment]
whooop yeah i also thought we didn't have the feature @orta
