### ISSUE TITLE
Configure App Transport Security

### ISSUE THREAD

**Issue by alloy** [artsy/eigen#741]
Currently we simply disable it completely, but once we’ve had time to see if opening arbitrary URLs with WKWebView is allowed with this enabled, then we can start scoping the domains etc.

Depends on #606.

**Comment by orta** [comment]
For FB Auth: https://developers.facebook.com/docs/ios/ios9

**Comment by alloy** [comment]
It's interesting to see them state to disable it for them, which means they don't meet the criteria. Alas they don't mention what criteria that is and when they would fix it.
