### ISSUE TITLE
Sign up for account CTA screen is jumpy

### ISSUE THREAD

**Issue by anipetrov** [artsy/eigen#742]
Browsing the app without account, press *YOU* which will trigger the sign up CTA screen. As the CTA screen appears, the background scrolls up and then scrolls back down when the CTA is dismissed. Replicated on iPhone 6 iOS 9 and iOS 8.4.1

http://cl.ly/37370L3Z0W2z

**Comment by alloy** [comment]
This will no longer be an issue now that we’ll require sign-in.
