### ISSUE TITLE
Search freezes loading screen

### ISSUE THREAD

**Issue by anipetrov** [artsy/eigen#743]
If you tap search while a screen is loading, when you close the search bar, the loader continues for a bit and then freezes. If you browse through other sections and then go back to the same screen, it is still frozen with the spinner. Replicated on iPhone 6, iOS 9 and iOS 8.4.1

http://cl.ly/0V1k263G3Y0n

**Comment by alloy** [comment]
Not sure yet what the best approach is here, either:

* make it not get stuck, which means the VC should keep on loading or needs a re-load when getting back from search
* not show the search button over a VC while it is still loading
