### ISSUE TITLE
Search bar is too narrow

### ISSUE THREAD

**Issue by anipetrov** [artsy/eigen#744]
Search bar that shows up when you tap search icon while browsing the app seems too narrow (definitely narrower than the search bar you are shown during onboarding). Also, the font of the keyboard input is smaller size than the font of the results that come up (in both cases). iPhone 6 iOS 9 and iOS 8.4.1
in app search:
![image](https://cloud.githubusercontent.com/assets/8701687/9418865/22342936-4825-11e5-8d25-971e240a7ef2.png)
vs onboarding artists & categories search: 
![image](https://cloud.githubusercontent.com/assets/8701687/9418926/9c234984-4825-11e5-9c0b-d607cd92e341.png)

**Comment by orta** [comment]
It also doesn't fit well in iOS9

**Comment by alloy** [comment]
@orta What exactly doesn’t “fit well” ? E.g. the font size or style-wise?

**Comment by orta** [comment]
On my iOS9 iPhone the status bar bleeds into the search field

**Comment by katarinabatina** [comment]
intended look: 
![image](https://cloud.githubusercontent.com/assets/6482926/10144833/b84b42ca-65ed-11e5-9008-b922adc6d5ec.png)

what it looks like now on ios9:
![image](https://cloud.githubusercontent.com/assets/6482926/10144863/f2f3d798-65ed-11e5-92ef-840b19f1a0cb.png)
