### ISSUE TITLE
Overscrolling brings up black background

### ISSUE THREAD

**Issue by anipetrov** [artsy/eigen#745]
Overscrolling up or down on artwork or partner profile screens brings up black background:
![image](https://cloud.githubusercontent.com/assets/8701687/9419156/4c29c3c0-4827-11e5-9669-94c635a5de02.png)
![image](https://cloud.githubusercontent.com/assets/8701687/9419161/53859e6e-4827-11e5-8bc3-c6a98644e5ea.png)

The overscroll background should be white instead, as for articles:
![image](https://cloud.githubusercontent.com/assets/8701687/9419135/2917326e-4827-11e5-8143-d7689ec5b326.png)

**Comment by orta** [comment]
Afraid not, articles have it wrong, it should be black. But it's a website, and we can't hack it without repercussions.

**Comment by anipetrov** [comment]
Ahh my bad, thanks @orta!
