### ISSUE TITLE
[Search] Selecting search result opens new view with strange top/left reveal transition

### ISSUE THREAD

**Issue by jorystiefel** [artsy/eigen#747]
From @robertlenne:

> When entering an view from search all the content expands from the upper left corner in a weird way

To replicate: go to search, search for anything, tap a result, and see a top/left reveal transition.

**Comment by jorystiefel** [comment]
Interesting note: this transition seems to only happen on iPhone and not in the simulator. Haven't checked iPad.

**Comment by alloy** [comment]
Maybe turning on ‘slow animations’ in the simulator would show it?

**Comment by jorystiefel** [comment]
Not in this case, they are actually different transitions. The transition in the simulator is a fade, whereas the transition on device is a top-left reveal.

**Comment by alloy** [comment]
@jorystiefel My gut feeling is that it’s all the views’ initial frames that are getting assigned in an animated fashion, which would animate them all from their 0 rect to their eventual frame.
