### ISSUE TITLE
API client secret and key for OSS users are swapped?

### ISSUE THREAD

**Issue by vlas-voloshin** [artsy/eigen#76]
I've tried going through the **OSS Quick Start** process of installation, but app ended up failing to connect to the staging API server with 401 errors. After some digging around and trying different things, I realized there's a web client on the staging server. I've extracted the key and secret from its JS and tried using them in the app, and they worked. I noticed that the length of key and secret from the web client are different from those currently in the app Makefile for OSS, so I've switched around the key and secret there, but unfortunately they didn't work either. I had to resort to using web client keys...
Could you check that keys in the Makefile are still valid? I've noticed they've been updated recently.

**Comment by ashfurrow** [comment]
Great catch!

**Comment by orta** [comment]
Hah, thanks @vlas-voloshin
