### ISSUE TITLE
[iOS 9] Add Handoff support

### ISSUE THREAD

**Issue by alloy** [artsy/eigen#768]
This makes it so that you can continue your session from another device (e.g. Safari on Mac) to Eigen and vice-versa.

See https://developer.apple.com/library/ios/documentation/UserExperience/Conceptual/Handoff/AdoptingHandoff/AdoptingHandoff.html#//apple_ref/doc/uid/TP40014338-CH2-SW10

Like with #767, this requires a JSON file to be served from the domain. It’s the same file, though, it just needs additional details.

**Comment by katarinabatina** [comment]
I would rank this one as a "nice to have" based on other priorities in the sprint.

**Comment by orta** [comment]
This is the way in which we support iOS9 searching WRT letting Apple parse our website and use that for finding data. It's important.

**Comment by katarinabatina** [comment]
+1 @orta thanks for clarifying. Suppose few of our users use this feature. Does this mean Apple will have trouble finding data? I feel like usage will be very low.

**Comment by alloy** [comment]
> This is the way in which we support iOS9 searching WRT letting Apple parse our website and use that for finding data. It's important.

I don’t understand this. What do you mean by “letting Apple parse our website”?

Based on what I understand this feature being helpful for, I think #767 would be more important as it allows people to open content in the app that they see in e.g. their personalized emails (improve engagement with the app and all).

**Comment by orta** [comment]
The handoff-specific part is not important, it's the relationship between the app & the website that is important. A few things this does:

* We can make it so that clicking an artsy link in Mail would open the app 
* We connect the app to the website so that apple know that it can [index the website](https://developer.apple.com/library/prerelease/ios/releasenotes/General/WhatsNewIniOS/Articles/iOS9.html) and connect that to the app:

> #Search 
> Privacy is an essential feature of search in iOS 9. To give users the best search experience while protecting their private data, iOS 9 makes the following indexes available:

> * A private on-device index. Each device contains a private index whose information is never shared with Apple or synced between devices. When you make an item available in a user’s on-device index, only that user can view the item in search results.
> * Apple’s server-side index. The server-side index stores only publicly available data that you’ve marked appropriately on your website.

**Comment by orta** [comment]
Ah, this is also covered by #767 - I think the two are basically the same thing.

**Comment by alloy** [comment]
> The handoff-specific part is not important, it's the relationship between the app & the website that is important

Ok, fair, but then let’s keep those things clearly defined and separated. We, @katarinabatina and me included, can’t talk prioritisation if it’s not clear/concise what issues are about.

> We can make it so that clicking an artsy link in Mail would open the app

That’s Universal Links, not Handoff. Which is what #767 is about.

> Search

Ok, so that’s something tangential, I’ve created #777 for that.

**Comment by alloy** [comment]
> Ah, this is also covered by #767 - I think the two are basically the same thing.

I can see how conceptually they overlap, but I think they both require different implementation work in Eigen, so it’s probably better to keep them separate and clear what they’re solving.

**Comment by orta** [comment]
:+1:

**Comment by alloy** [comment]
This is working for Native (Eigen) to web (desktop browser) but not yet the other way around.

**Comment by alloy** [comment]
So, it appears that this does actually work, but only with iOS 8 devices. This means we’re being hit with the same issue as described [here](https://www.cocoanetics.com/2015/08/radar-web-to-native-handoff-broken/).

![img_0001](https://cloud.githubusercontent.com/assets/2320/10133757/4b7363ce-65e0-11e5-8a94-5c8c6fdf1628.PNG)

It’s pretty sweet when it works :tada:

**Comment by alloy** [comment]
This is reported to be fixed in 9.1: http://twitter.com/Cocoanetics/status/648491619583426560
