### ISSUE TITLE
npm run setup:artsy  failed

### ISSUE THREAD

**Issue by zhengzebiao** [artsy/eigen#7747]
> eigen@1.21.52 setup:artsy
> ./scripts/setup-env-for-artsy

+ aws s3 cp s3://artsy-citadel/dev/.env.eigen .env.shared
fatal error: An error occurred (403) when calling the HeadObject operation: Forbidden

how can i get the file?

**Comment by pvinis** [comment]
you don't get that file. we have setup:oss for non-artsy people, but that might faol too. we need to make sure this works, and we will get back to you when we do.

**Comment by brainbicycle** [comment]
Hey we merged a PR recently that we believe should fix this: https://github.com/artsy/eigen/pull/7024, there are instructions in https://github.com/artsy/eigen/blob/main/docs/getting_started.md for independent contributors, let us know if you still have trouble!

**Comment by brainbicycle** [comment]
hmm in theory no, the bucket where these fonts live should be public, I know @pvinis saw a similar issue and then maybe logged out and in again to the cli and it started working? If you continue to have issues let me know.
