### ISSUE TITLE
[Makefile] Fix bundle name and icon alpha/beta/release tasks

### ISSUE THREAD

**Issue by alloy** [artsy/eigen#785]
- [ ] Re-enable the icon date stamping in `beta` builds. iirc the asset catalog would not validate during app build time.
- [ ] We have an `alpha` task, but I’m not sure what that’s meant for. I would like us to have the `alpha` bundle display name (`Artsy α`) during regular development so that it’s easily distinguishable from an App Store release. It does not need the date stamped on the icon, as that means we’d need to run that task during each dev build, which is tiresome.

**Comment by orta** [comment]
We used to do daily builds, that was what the alpha was for

**Comment by alloy** [comment]
Gotcha! What about re-using it for normal dev builds?

**Comment by orta** [comment]
happy for it :+1:

**Comment by jorystiefel** [comment]
It appears the "stamp" plugin is broken. It hasn't been updated in several years. Exploring an alternate solution.

**Comment by jorystiefel** [comment]
And by broken, I mean it is changing the size of the AppIcons which is causing the asset catalog not to build.
