### ISSUE TITLE
Completing a bid on an artwork does not take you back to a native artwork view

### ISSUE THREAD

**Issue by katarinabatina** [artsy/eigen#804]
On staging:

I enter an auction, find an artwork (native view), press the bid button, get confirmation screen (microgravity view), press confirm bid, land on artwork view (microgravity)<-- this last view should be back to native, not microgravity.

This is a bit of a timely fix for Sotheby's if anyone could set aside some time today to take a look at this please let me know!

**Comment by alloy** [comment]
I’ll take a look in about an hour.

**Comment by katarinabatina** [comment]
thanks @alloy I suspect it may be a microgravity bug, if so let me know.

**Comment by orta** [comment]
Perhaps something like:

``` objective-c
- (WKNavigationActionPolicy)shouldLoadNavigationAction:(WKNavigationAction *)navigationAction;
{
    NSURL *URL = navigationAction.request.URL;
    NSLog(@"Martsy URL %@ - %@", URL, @(navigationAction.navigationType));

    // If we really have to hijack regardless do it first.
    // This is to take into account AJAX requests which are not
    // strictly classed as a WKNavigationTypeLinkActivated
    // as the user may not have _directly_ loaded it

    BOOL urlIsLoginOrSignUp = [URL.path isEqual:@"/log_in"] || [URL.path isEqual:@"/sign_up"];
    if ([ARRouter isInternalURL:URL]) {
        if (urlIsLoginOrSignUp && [User isTrialUser]) {
            [ARTrialController presentTrialWithContext:ARTrialContextNotTrial success:^(BOOL newUser) {
                [self userDidSignUp];
            }];
        } else {
            UIViewController *viewController = [ARSwitchBoard.sharedInstance loadURL:URL fair:self.fair];
            if (viewController && ![self.navigationController.viewControllers containsObject:viewController]) {
                [self.navigationController pushViewController:viewController animated:YES];
            }
        }
        
        return WKNavigationActionPolicyCancel;
    }

    if (navigationAction.navigationType == WKNavigationTypeLinkActivated) {
        if ([self.shareValidator isSocialSharingURL:URL]) {
            ARWindow *window = ARAppDelegate.sharedInstance.window;
            CGPoint lastTouchPointInView = [window convertPoint:window.lastTouchPoint toView:self.view];
            CGRect position = (CGRect){.origin = lastTouchPointInView, .size = CGSizeZero};
            [self.shareValidator shareURL:URL inView:self.view frame:position];

            return WKNavigationActionPolicyCancel;

        }
    return WKNavigationActionPolicyAllow;
}
```

**Comment by alloy** [comment]
@katarinabatina This is not a microgravity issue per se. We are not catching the link because this is a page change initiated by the page’s JavaScript instead of the user tapping a link.

Fixing that might be simple enough –I see that by now @orta has pasted the code :smile:–, but we would have to test that it doesn’t cause breakage on any other pages that have forms of any kind.

**Comment by alloy** [comment]
@katarinabatina In addition, I’d like to point out that after fixing it, this would mean the view stack would get an additional artwork view on top of the existing stack. Thus when the user navigates back from that artwork, they would get to see the ‘confirm bid’ page again, and when navigating further back the artwork once again.

**Comment by katarinabatina** [comment]
@alloy the biggest issue is solved for which is that the martsy view shows the correct, updated bid amount, however we sill have the issue where two artwork views are stacked on top of one another see here http://cl.ly/3S3k05382u2l

and the native artwork view doesn't represent the new bid amount

**Comment by alloy** [comment]
Ok, so I think this means we have to do the following:

- [ ] Pop the second artwork view from the stack after confirming a bid
- [ ] Reload all views (in the stack only?) related to the auction/artwork.
  - [ ] So auction related web views should probably get their own InternalWebBrowserVC subclass, which listens for notifications.
