### ISSUE TITLE
Fonts are not being loaded in web views

### ISSUE THREAD

**Issue by alloy** [artsy/eigen#815]
This is the case since we’ve switched to WKWebView. I filed the following tickets

- [ ] Martsy https://github.com/artsy/microgravity/issues/1078
- [ ] Force https://github.com/artsy/force/issues/3506

**Comment by jorystiefel** [comment]
This is the error from the inspector:
```
TypeError: undefined is not an object (evaluating 'window['mti_element_cache'].length')
```

I found two sites discussion this problem. The [first suggestion](https://github.com/bernerdschaefer/akephalos/issues/22) is to add this call before the fonts.net javascript is loaded:
```js
<script type="text/javascript">
window['mti_element_cache'] = []
</script>
```
The [second suggestion](https://techblog.willshouse.com/2014/01/04/window-mti_element_cache-fonts-com/) is to replace the fonts.net javascript call with something that calls the CSS directly, something like this:
```html
<link type="text/css" rel="stylesheet" rel="nofollow" href="//fast.fonts.net/cssapi/ff111ab-123-456-789.css"/>
```

**Comment by orta** [comment]
There's the potential that the webpages had always been using our app's font cache, which is now not available to them as the web rendered is out of process. 

http://stackoverflow.com/questions/25785179/using-custom-fonts-in-wkwebview

**Comment by alloy** [comment]
@orta Yeah that’s very possible.

**Comment by alloy** [comment]
Same with iPad/Force btw:

![simulator screen shot 29 sep 2015 13 27 59](https://cloud.githubusercontent.com/assets/2320/10162790/fc5c840e-66ad-11e5-92e1-be533fd96bd7.png)

**Comment by alloy** [comment]
![simulator screen shot 25 sep 2015 19 46 19](https://cloud.githubusercontent.com/assets/2320/10107888/37d328c8-63be-11e5-8b83-4d926f1b6676.png)

**Comment by orta** [comment]
So, this is likely our side, running a vanilla WKWebView app:

![screen shot 2015-09-29 at 20 17 05](https://cloud.githubusercontent.com/assets/49038/10186600/30432646-674a-11e5-9947-c3a7accc3b65.png)

**Comment by orta** [comment]
I have tried:
1, remove the avante garde font from the app
2, make the wkwebkit action delegate always return YES
3, I tried removing all font references in the info.plist

**Comment by orta** [comment]
A guess, the avant garde font is not the same filename as the rtf - it is also a TTF where everything else is an OTF - https://github.com/artsy/Artsy-UIFonts/blob/old_fonts_new_lib/Pod/Classes/UIFont+ArtsyFonts.m#L90-L100

**Comment by orta** [comment]
So the font martsy is using has completely different names etc from our Avant Garde, I doubt they're conflicting. I also tried adding our fonts into the example project I made, and got nowhere.


`{'fontfamily' : "ITC Avant Garde Gothic W04" ,'fontWeight' : "400" ,'fontStyle' : "Bold" ,contentIds :{EOT: '521186fb-1032-4a81-bff4-a67d052d6e5e',WOFF: '5f1f53ca-f786-466b-979b-2dc11d2d05e9',WOFF2: 'cd6106cf-c21e-4d0b-953e-3905a1b9dece',TTF: 'ac3dc0aa-6281-4d8f-aadb-67c67099ff9c',SVG: '0f98417d-ca43-4d3e-b392-21a473e4917a'}` from https://fast.fonts.net/jsapi/f7f47a40-b25b-44ee-9f9c-cfdfc8bb2741.js

vs

![screen shot 2015-09-30 at 08 44 38](https://cloud.githubusercontent.com/assets/49038/10187314/83f0bdc6-674f-11e5-903f-5f6a857e03a9.png)

**Comment by orta** [comment]
Injecting the `mti_element_cache` beforehand removes the error, but doesn't fix the font issue:

``` objc
    NSString *jScript = @"window['mti_element_cache'] = []";
    WKUserScript *wkUScript = [[WKUserScript alloc] initWithSource:jScript injectionTime:WKUserScriptInjectionTimeAtDocumentStart forMainFrameOnly:YES];
    WKUserContentController *wkUController = [[WKUserContentController alloc] init];
    [wkUController addUserScript:wkUScript];

    WKWebViewConfiguration *wkWebConfig = [[WKWebViewConfiguration alloc] init];
    wkWebConfig.userContentController = wkUController;

    WKWebView *web = [[WKWebView alloc] initWithFrame:self.view.bounds configuration:wkWebConfig];
    [self.view addSubview:web];

    NSURLRequest *request = [NSURLRequest requestWithURL:[NSURL URLWithString:@"http://m.artsy.net"]];
    [web loadRequest:request];
```

![screen shot 2015-09-30 at 08 56 49](https://cloud.githubusercontent.com/assets/49038/10187545/36e6dd38-6751-11e5-97f4-4a8bb78bec25.png)

**Comment by orta** [comment]
hah, so I stopped almost all code being ran in the app delegate, then almost gave up and noticed 

```
    [ARDefaults setup];
    [ARRouter setup];
```

were still being ran. Removing those brings back the fonts.

![screen shot 2015-09-30 at 09 49 37](https://cloud.githubusercontent.com/assets/49038/10188623/9c9ab2b0-6758-11e5-8ae1-872c1f13ef44.png)

**Comment by orta** [comment]
I'm leaving it at that, I need to work on Emergence. 

I gave enough info for someone to finish up. The problem lies in either the defaults or the router. If I had to guess, it might be around our custom browser id.
