### ISSUE TITLE
Fix crash in - [AFNetworkActivityLogger networkRequestDidFinish:], line 153

### ISSUE THREAD

**Issue by artsyit** [artsy/eigen#816]
### Stacktrace ###

<pre>AFNetworkActivityLogger;networkRequestDidFinish:;AFNetworkActivityLogger.m;153
AFURLConnectionOperation;finish;AFURLConnectionOperation.m;482</pre>

### Link to HockeyApp ###

* [https://rink.hockeyapp.net/manage/apps/37029/crash_reasons/46656553](https://rink.hockeyapp.net/manage/apps/37029/crash_reasons/46656553)

**Comment by orta** [comment]
closed by https://github.com/artsy/eigen/pull/826
