### ISSUE TITLE
Add Buyer's Premium Functionality 

### ISSUE THREAD

**Issue by katarinabatina** [artsy/eigen#82]
Some artworks in an auction will have a "buyer's premium" this will be noted underneath the BID button 
![image](https://cloud.githubusercontent.com/assets/6482926/5983089/e809b398-a897-11e4-80c3-45e073fc245f.png)

It will lead to a modal (martsy view) containing the relevant information explaining what a buyer's premium is and what that is for this particular sale (premiums change from sale to sale)

**Comment by orta** [comment]
How do you feel on the design @katarinabatina ( given that there's been some emails about this today? )

Aside from this, the martsy URL: https://m.artsy.net/auction/[auction_id]/buyers-premium
