### ISSUE TITLE
Artwork details jump on landscape artworks after full details are grabbed

### ISSUE THREAD

**Issue by orta** [artsy/eigen#822]
This is way more obvious on iPad portrait, but steps to repro:
- Click any landscape artwork
- Initial aspect ratio is used
- Artwork details are loaded, view layout happens syncronously. (I think the Artwork image's aspect ratio is set to 1:1?)
- Details animate back into place

![2015-09-28 11_22_53](https://cloud.githubusercontent.com/assets/49038/10133182/46466b24-65d3-11e5-9b28-df215645828a.gif)

**Comment by orta** [comment]
From `ARArtworkMetadataView`
![screen shot 2015-09-28 at 11 49 50](https://cloud.githubusercontent.com/assets/49038/10133678/175e453a-65d7-11e5-9b14-e8c483fd9bb2.png)

Looks like it's the left view section in the `ARArtworkMetadataView`. I wonderded if it was the ARWhitespaceGlobber - but no hints so far.

**Comment by orta** [comment]
this only happens on portrait iPad, tested last night

**Comment by katarinabatina** [comment]
haven't seen in a while, @orta are you still seeing this if not will you close?

**Comment by orta** [comment]
This is still happening, yep!
