### ISSUE TITLE
No way for users to pick from multiple edition_sets of an artwork

### ISSUE THREAD

**Issue by 1aurabrown** [artsy/eigen#83]
If the artwork doesn't belong to an edition or has only one edition, that's pretty straight-forward, but artworks like https://www.artsy.net/artwork/zaria-forman-greenland-number-54-1 which have multiple editions can't be purchased through the app. We instead send the user to the inquiry form for these works. It would be nice to add some method of selecting from multiple editions.

See https://github.com/artsy/eigen/pull/80

**Comment by alloy** [comment]
Related https://artsy.wake.io/937 /cc @katarinabatina

**Comment by alloy** [comment]
Closing in favour of #909.
