### ISSUE TITLE
[Shared Web Credentials] Better handle case when a user has outdated credentials.

### ISSUE THREAD

**Issue by alloy** [artsy/eigen#833]
Currently, when trying to sign in with invalid credentials, the user doesn’t get any feedback and is just shown the normal sign-in/trial view. We should probably alert the user about the credentials being invalid and also offer to remove them.

See [video](https://artsy.slack.com/archives/eigen/p1443641223000465) and [message](https://artsy.slack.com/archives/eigen/p1443642497000483) in Slack

**Comment by katarinabatina** [comment]
After we learn that their credentials are out of date, can we land them in the login view showing the error  "invalid credentials"

**Comment by alloy** [comment]
@katarinabatina Agreed and could probably be combined with #935 really well.
