### ISSUE TITLE
[RFC] Add Moti, a more declarative animation API built on top of Reanimated

### ISSUE THREAD

**Issue by damassi** [artsy/eigen#8378]
**Status**: Accepted

**Type**: New Dependency

**Name**: moti

**Website** URL: https://moti.fyi/

**Github URL**: https://github.com/nandorojo/moti

**NPM URL**: https://www.npmjs.com/package/moti

**Description**

Reanimated is the primary animation library in the React Native world. It's great, but its also highly imperative. To write animations, one needs to build them from scratch using a combination of API methods that are often times confusing to understand, with docs that are at times vague. From this foundation, however, a lot of cool stuff can be built, and that's where Moti comes in. It's a **declarative** wrapper on top of Reanimated, with an absolutely simple API. You just describe what you want, and it will do it:

**Examples:**

```tsx
<MotiView from={{ opacity: 0 }} animate={{ opacity: 1 }} />
```
```tsx
<MotiView
  from={{ opacity: 0, scale: 0.5 }}
  animate={{ opacity: 1, scale: 1 }}
  transition={{
    type: 'timing',
    duration: 350,
  }}
/>
```
```tsx
<MotiView
  from={{ opacity: 0, scale: 0.5 }}
  animate={{ opacity: 1, scale: 1 }}
  transition={{
    // default settings for all style values
    type: 'timing',
    duration: 350,
    // set a custom transition for scale
    scale: {
      type: 'spring',
      delay: 100,
    },
  }}
/>
```
And the coolest of all, an easy way to animate things out, even though they're unmounted. This has been historically very hard to do in React:
```tsx
const [visible, setVisible] = useState(false)

<AnimatePresence>
  {visible && (
    <MotiView
      from={{ opacity: 1 }}
      animate={{ opacity: 1 }}
      exit={{
        opacity: 0,
      }}
    />
  )}
</AnimatePresence>
```

Check out an example of how much simpler the code became when we swapped it in this Folio PR: https://github.com/artsy/energy/pull/565. 

It's also worth calling out how few issues and PRs are present. That is a great indicator of a successful design: 

<img width="400" alt="Screenshot 2023-03-16 at 9 28 04 AM" src="https://user-images.githubusercontent.com/236943/225737680-d553733f-93af-4ed9-b110-4f9f32dbacd1.png">

Lastly, thank you @pvinis 🙏  for paving the way here by doing the difficult work upgrading Reanimated to v2 in Eigen; without that we wouldn't be able to add this.

**Comment by pvinis** [comment]
I like moti. looking forward to feedback after using it :)

**Comment by olerichter00** [comment]
Looks great! Looking forward to it 👍

**Comment by rajsam003** [comment]
Love it ❤️

**Comment by MounirDhahri** [comment]
Looking forward to having this 💯

**Comment by gkartalis** [comment]
🥇 Lets try it out!

**Comment by damassi** [comment]
Cool, that looks like a majority so gonna 🚀

**Comment by damassi** [comment]
Marked as accepted! 

Next steps will be to get the dep in Eigen, and update an existing piece of code using it. @gkartalis has volunteered to look at the PopoverMessage component (tyy george 👍)
