### ISSUE TITLE
Artsy+UIFonts/UIFont+ArtsyFonts.h file not found when initially setting up the project

### ISSUE THREAD

**Issue by nbfuhao** [artsy/eigen#845]
I followed the instructions and run the following in the terminal
`git clone https://github.com/artsy/eigen.git`
`cd eigen`
`bundle install`
`make oss`
`bundle exec pod install`
`open Artsy.xcworkspace`
However, when compiling, XCode said `'Artsy+UIFonts/UIFont+ArtsyFonts.h' file not found`
Anyone experiencing the same error message?

**Comment by orta** [comment]
This is from https://github.com/artsy/eigen/pull/832 - we'd need to do a `#if __include` t detect which fonts to use.

**Comment by nbfuhao** [comment]
Thanks for the reference. 
It's the `Categories.h` file that is missing the `#if __include` command

I replaced the `#import <Artsy+UIFonts/UIFont+ArtsyFonts.h>` with
`#if __has_include(<Artsy+UIFonts/UIFont+ArtsyFonts.h>)`
`#import <Artsy+UIFonts/UIFont+ArtsyFonts.h>`
`#endif`

`#if __has_include(<Artsy+OSSUIFonts/UIFont+OSSArtsyFonts.h>)`
`#import <Artsy+OSSUIFonts/UIFont+OSSArtsyFonts.h>`
`#endif'`

XCode should compile again.

**Comment by orta** [comment]
@nbfuhao - any chance of a PR with that? :D
