### ISSUE TITLE
Log in button doesn't work

### ISSUE THREAD

**Issue by ashfurrow** [artsy/eigen#85]
Logging in (at least with a `.eigen` file) doesn't work when I tapped "Log In" button, but did when I hit the Done key on the keyboard. 

![screen shot 2015-02-02 at 12 45 56 pm 1](https://cloud.githubusercontent.com/assets/498212/6000066/735af630-aad9-11e4-8e95-18f8d6db5f24.png)

From the network request that fails, it looks like it is sending the following (decoded) variable: 

```
password=••••••••••••••••••
```

(Those are actual bullets.)

**Comment by 1aurabrown** [comment]
I'm going to take a look at this. probably has something to do with dB's custom font faux secure textfield thing
