### ISSUE TITLE
Notification types and proposed schedule 

### ISSUE THREAD

**Issue by katarinabatina** [artsy/eigen#851]
All users, trial or not
1. Fair Preview now open--> 12pm local time
suggested copy:"Fair X Preview is now open, "x" works now on view
2. Auction now open--> 9pm local time
suggested copy: "Auction X is now open, bid on works from Artist Name 1, Artist Name 2, and more"
3. Auction closing soon--> 1 hr before auction closes
suggested copy: "Last chance to bid in "Auction X" 

Per User, logged in user
1. Outbid at auction--> immediately
suggested copy: "You've been outbid in "Auction X" Increase max bid now"
2. New Works by artist you follow--> 10am local time
suggested copy: "X" new works by Artist Name 1, Artist Name 2, and more"

**Comment by katarinabatina** [comment]
@alexanderfabry @robertlenne I wanted to outline this as a starting point but I'd appreciate your input as well.

**Comment by jessekedy** [comment]
hey @katarinabatina would be great to include Sara here, as she's coordinating the manual push for Sotheby's (and moving forward), as well as all Email comms, which should ideally be in harmony with push. Let me know if you have other thoughts.

**Comment by alexanderfabry** [comment]
Would we want to segment the fair notifications by location? We have a lot of fairs, and one that's near you is much more relevant.

We did a bunch of blue-sky thinking around the best way to do new for you notifications -- I think a set daily one will get annoying pretty quickly, and people will just ignore it. The more nuanced version would have a quality metric for the "new for you" content, and would have a per-user threshold. This threshold could depend on lots of things: user's past engagement with notifications, users collector level, users time zone. Once the sum of the quality metrics exceeds the threshold, then the push gets delivered. This could then learn: if a user doesn't interact with their notifications, we increase the threshold which means they get fewer of them. If they interact a lot, we lower it and they get them more frequently.

**Comment by katarinabatina** [comment]
cc: @sperle

**Comment by katarinabatina** [comment]
@alloy I met with @alexanderfabry and @sperle today to discuss initial push notifications we would like to implement. Obviously part of this process will be to decide how these notifications will be implemented. Obviously we'll want most of these to be automated but for fairs I think relying on a service like mixpanel or another that @sperle could schedule notifications would be great. 

Fairs:
Fair Preview Now Open--> 12pm local time
This notification would be limited to Tier 1 Fairs 
User Segment: all users
Suggested Copy: :"Fair X sneak preview is now open, explore the fair"

Personalized:
New Works by artist you follow--> Thursdays, 10am (user's local time)
User Segment: all users
Suggested copy: we'd like to test different messaging:
1. "#" new works by Artist Name 1, Artist Name 2, and more"
2. "#" new works for available by artists you follow"
3. "x event such as a fair" # new works for you"


Auctions:
Auction now open--> Day the auction opens, 12pm (or whenever the auction opens) user's local time
User Segment: all users who have ever bid on artsy or registered to bid on artsy before
suggested copy: "Auction X is now open, bid on works from Artist Name 1, Artist Name 2, and more"

Auction closing soon--> 1 hr before auction closes
User Segment: all users who have ever bid on artsy or registered to bid on artsy before
suggested copy: "Last chance to bid in "Auction X" bid now"

Auction closing soon--> 10 min before auction closes
User Segment: all users registered for THIS particular auction
suggested copy: "Bidding closing in 10 minutes, bid now!" 

Outbid at auction--> immediately
suggested copy: "You've been outbid in "Auction X" Increase max bid now"

**Comment by orta** [comment]
The other service would allow better notification targeting, e.g. with mix panel we could do: "message only people in NYC who have favourited a work by `artist_id``

**Comment by alloy** [comment]
I get that, but the mention about an external service is regarding fairs and the description mentions that those should be sent to all users, so it’s not clear to me why in that case an external service would be preferred. The only reason I see is about timing, but that’s something we already need to build in our system anyways.

**Comment by orta** [comment]
Given that there's many [fairs in a week](https://www.artsy.net/art-fairs) - I imagine that's so we can target  just people in the local area

**Comment by katarinabatina** [comment]
@alloy what I meant by external service is exactly what @orta is implying. Outside of automated notifications we'll want to provide @sperle with a tool to coordinate specific campaigns to a small subset of users.

**Comment by alloy** [comment]
Got it :+1:

**Comment by alloy** [comment]
@katarinabatina Regarding auction opening, I’m not sure how to interpret this: “12pm (or whenever the auction opens) user's local time”. Can you elaborate on it?

**Comment by alloy** [comment]
@katarinabatina Please correct me if I’m wrong, this is what I understand the plan for scheduling around e.g. an auction opening.

1. Consider an auction in Kiribati to open on October the 31st at 13:00.
   People in this timezone will receive the notification at the real time.
2. That’s October the 30th in New York at 19:00.
   People in this timezone will receive the notification at the real time.
3. That’s October the 30th in Niue at 12:00.
   People in this timezone will receive the notification one hour later.
4. That’s October the 31st in Moscow at 02:00.
   People in this timezone will receive the notification 11 hours later (November 1st at 13:00).

* 1 and 2 are clear-cut, these are fine times to disturb a user and real time is always preferable?
* 3 seems overdoing it, so would it be an idea to define an ‘after X hour’ threshold? E.g. if it is later than 09:00 in the user’s local time, then just deliver the notification at the real time.
* 4 for this to work (not disturb users at night time) there will have to be a ‘before X hour’ threshold. Any idea as to what time that would be?

**Comment by alloy** [comment]
For now we’re going with 10:00 - 20:00 for allowed local times.

**Comment by alloy** [comment]
We can have custom sounds inside the app for notifications, for now we're going with the system ones ( which you can see in System Preferences -> Sounds )

![screen shot 2015-11-03 at 17 56 51](https://cloud.githubusercontent.com/assets/2320/10924388/5d6c6c98-8254-11e5-87b1-9e9bb7090600.png)

but there's definitely time to change that

**Comment by robertlenne** [comment]
I'm a bit late to the game but it seems like your outline @katarinabatina would lead to a lot of fair notifications. Worry that it won't be that compelling content for the vast majority of users (it would be different if it was let's day "See recommended works for you at Frieze London").

And I wonder if we should send the Works for you notification more often than each Thursday. Some treshold system here would be good – could see some users wanting to know immidately when new works are added.

**Comment by orta** [comment]
@robertlenne even with this?

> This notification would be limited to Tier 1 Fairs

**Comment by robertlenne** [comment]
I saw that. Yes, maybe. 

Generally we should be testing the "swipe-through rates" of our initial set of notifications right and quickly adapt? Fine running with notification for all Tier 1 Fairs initially if we are tracking the results carefully.

**Comment by alloy** [comment]
The first major part of the backend work has been done in this PR: https://github.com/artsy/gravity/pull/9395

**Comment by katarinabatina** [comment]
@alloy to Robert's point, will we be able to track the "engagement" rate with notifications on a per user basis? cc @anipetrov If we knew each users engagement we could start to tailor how often we push.

**Comment by alloy** [comment]
@katarinabatina If it’s about the fair related discussion, then I won’t be able to answer that right now, as the idea is to send it through an external system like mixpanel, right? If it’s about notifications in general, then yes, I have some ideas on how to get more reliable numbers.

**Comment by katarinabatina** [comment]
@alloy sorry for not specifying. Yes the fair related ones would be administered through mixpanel. This refers to the personalized "Works for you" notification in particular.

**Comment by sperle** [comment]
Throwing into the mix here that I'm talking to some potential vendors to
handle our email program that have integrated push capabilities (e.g.
Sailthru which uses Appboy, and Strongview which has some proprietary
system). It's not really what I'm focused on in my evaluation of them, but
if the functionality is there anyway might be worth looping some of you in?

On Tue, Nov 10, 2015 at 10:18 AM, Eloy Durán <notifications@github.com>
wrote:

> @katarinabatina <https://github.com/katarinabatina> If it’s about the
> fair related discussion, then I won’t be able to answer that right now, as
> the idea is to send it through an external system like mixpanel, right? If
> it’s about notifications in general, then yes, I have some ideas on how to
> get more reliable numbers.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/artsy/eigen/issues/851#issuecomment-155448968>.
>



-- 

[A.] Sara Perle

                Email Marketing Manager

Artsy <http://artsy.net/> | 401 Broadway, 25th Floor
                New York, NY 10013


sara@artsy.net

                @saperle <http://twitter.com/saperle>

+1 541-255-5509

**Comment by katarinabatina** [comment]
@sperle Mixpanel has all the valuable data about our users we can segment by, do other services allow for this?

**Comment by sperle** [comment]
The ones I'm talking to would let us pull that in, I believe, but I can
find out more.

On Tue, Nov 10, 2015 at 10:54 AM, Katarina Batina <notifications@github.com>
wrote:

> @sperle <https://github.com/sperle> Mixpanel has all the valuable data
> about our users we can segment by, do other services allow for this?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/artsy/eigen/issues/851#issuecomment-155461407>.
>



-- 

[A.] Sara Perle

                Email Marketing Manager

Artsy <http://artsy.net/> | 401 Broadway, 25th Floor
                New York, NY 10013


sara@artsy.net

                @saperle <http://twitter.com/saperle>

+1 541-255-5509

**Comment by alloy** [comment]
@katarinabatina As @mzikherman points out [here](https://github.com/artsy/gravity/pull/9395#discussion_r45331621), when a bidder is outbid they already receive an email and a text message. Might an additional push notification not be a bit much?

**Comment by katarinabatina** [comment]
@alloy @mzikherman, a push notification is a direct entry point into the app and precise lot which you were outbid on, far more direct than the text message. While it may seem like a lot it's a pretty critical point in time (even more so when we get into live integration) the push notification seems really important. I think it's more than ok to bombard the user in this instance.

**Comment by alloy** [comment]
@katarinabatina @mzikherman Good point. If the text message includes the URL to the artwork then, through Universal Links, iOS would still open the work in Eigen, but I agree that in the case of an outbid ‘more’ is probably better.

**Comment by katarinabatina** [comment]
It also guarantees total coverage. Those who don't have the app at all or have opted out of push will still get the text. 

Sent with thumbs,
Katarina Batina 
Product Designer
Artsy.net

**Comment by alloy** [comment]
FYI For future copy design, to be sure that you don’t always get to see the same name (And is presumably Warhol):

> trending could also be a cool sort (regardless of number of artworks, that way its not always Andy...), though I don't think trending calculations are working atm

From @mzikherman: https://github.com/artsy/gravity/pull/9395#discussion_r45330774

**Comment by katarinabatina** [comment]
Talked a bit more to @robertlenne today and came to the conclusion that we may want to be more aggressive with personalized notification (works by artist you follow) by figuring out how engaged a user is and sending them more or less of these notifications. For example, if we find that a person is consistently engaging with their notifications, we would send them a daily push of "works for you" versus only on Thursday. We obviously need to have a starting point and it may be worth increasing the starting point to two days a week instead of 1. @alloy will our current implementation allow us to do something like this? cc @orta who I chatted with a bit today.

**Comment by robertlenne** [comment]
@katarinabatina – Alexander did a fair amount of thinking how the notification system could work to enable things like this. Might be worth syncing up with him.

**Comment by alloy** [comment]
@katarinabatina There’s nothing in the current implementation that would stand that in the way. It just requires more work done, specifically pulling in analytics data that would provide the input necessary to determine how often a notification should be sent.

For the sake of completeness, in case you might think otherwise, I’ll add that sending a notification on each new work (added by an artist you follow) is probably significantly easier to implement, as it doesn’t require such analytics data and further heuristics.

**Comment by robertlenne** [comment]
Perhaps it's the engagement is too sophisticated for a V1....

Maybe just settle on more frequent delivery, eg. three times/week, for V1? Is that much more effort than notification about each work?

**Comment by alloy** [comment]
@robertlenne I agree that that’s probably a good idea for v1, a fixed number of times per week for all users (when there actually is new content available for them) is definitely the simplest solution.

On what days shall we send them out? (And I assume at 10AM in all cases?)

**Comment by robertlenne** [comment]
Cool. How big step up would it be to do split testing for frequency and timing? eg. three time per week vs. once per week OR 10AM vs. evening.

I'll leave V1 timing question to Katarina as she has more context (but FWIW 10AM makes sense to me)

**Comment by katarinabatina** [comment]
@alloy I think we should still stick with 10, ultimately testing for comparison to other times would be ideal

**Comment by alloy** [comment]
@robertlenne I’d propose this timeline:

1. Get V1 ready, with limited delivery stats: only get back a list of devices, **not** users, that no longer have the app
2. Get more delivery stats: has a notification been sent for sure, possible, or definitely not
3. Introduce split-testing for frequency and timing
4. Introduce more variable frequency or whatnot

**Comment by alloy** [comment]
@katarinabatina Ok, and which 3 days?

**Comment by alloy** [comment]
I’m going to close this, please file new tickets where necessary. For now there’s this one about increasing the frequency of personalised notifications: https://github.com/artsy/gravity/issues/9753
