### ISSUE TITLE
Fix crash in - [AFNetworkActivityLogger networkRequestDidFinish:], line 153

### ISSUE THREAD

**Issue by artsyit** [artsy/eigen#852]
### Stacktrace ###

<pre>AFNetworkActivityLogger;networkRequestDidFinish:;AFNetworkActivityLogger.m;153
AFURLConnectionOperation;finish;AFURLConnectionOperation.m;482</pre>

### Link to HockeyApp ###

* [https://rink.hockeyapp.net/manage/apps/37029/crash_reasons/46683987](https://rink.hockeyapp.net/manage/apps/37029/crash_reasons/46683987)

**Comment by alloy** [comment]
Same as #824
