### ISSUE TITLE
keyboard freezes after sign-in

### ISSUE THREAD

**Issue by katarinabatina** [artsy/eigen#861]
in staging, open app, tap sign in w/ email, enter credentials, keyboard gets stuck

**Comment by alloy** [comment]
I wasn’t able to reproduce this, are you still able to? Maybe staging was slow/down at the time?

**Comment by katarinabatina** [comment]
yes in production as well I realize now that this was specific to the ipad

**Comment by alloy** [comment]
I just tested on a physical iPad and was still unable to reproduce it :/ Can I bug you for a video?

**Comment by jorystiefel** [comment]
Also unable to reproduce on iPad Air 2
