### ISSUE TITLE
3D Touch can sometimes use models from view controllers that are deeper in the nav hierarchy

### ISSUE THREAD

**Issue by orta** [artsy/eigen#863]
I have a video of this, but my WIFI is terrible. Reliable steps to repro:

* Open Artsy, take note of the positions of the current artworks
* Press the home button
* Use a quick navigation thing to jump into favourites
* Switch to artists
* Do a hard push and it will give you an overlay for the positions of the original page you were on before you opened the app

Likely can be fixed by adding a check that the view the `AREmbeddedModelsPreviewDelegate` would show the preview in is still attached to the window. Don't check the view controller hierarchy, I'm not certain that this is always hooked up correctly ( at least I know for sure it isn't on the ShowFeedVC )

**Comment by orta** [comment]
Video should is here: http://cl.ly/0U3R3n1Y002l
I've just got online, can take a quick look here

**Comment by alloy** [comment]
Fixed by #864.
