### ISSUE TITLE
Fix NSInvalidArgumentException in - [ARTopMenuInternalMobileWebViewController webView:didFailNavigation:withError:], line 122

### ISSUE THREAD

**Issue by artsyit** [artsy/eigen#870]
### Stacktrace ###

<pre>ARTopMenuInternalMobileWebViewController;webView:didFailNavigation:withError:;ARTopMenuInternalMobileWebViewController.m;122</pre>

### Reason ###

*** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[ARTopMenuInternalMobileWebViewController webView:didFailNavigation:withError:]: unrecognized selector sent to instance 0x1756e340'

### Link to HockeyApp ###

* [https://rink.hockeyapp.net/manage/apps/37020/crash_reasons/47308718](https://rink.hockeyapp.net/manage/apps/37020/crash_reasons/47308718)

**Comment by alloy** [comment]
Fixed by #819.
