### ISSUE TITLE
[Gene] Expandable description label UX improvements

### ISSUE THREAD

**Issue by alloy** [artsy/eigen#876]
Feedback from @YogaZenter:
- [ ] The little arrow underneath it makes it appear as if you can expand by dragging down on it, which isn’t really the case. Make that work.
- [ ] Figure out some heuristics to determine if the label really needs to be collapsed at all. Some descriptions are who short, that expanding only reveals a few more lines.

**Comment by katarinabatina** [comment]
view has been redesigned since this issue was created
