### ISSUE TITLE
Price on artwork favorites is removed when switching between fav types

### ISSUE THREAD

**Issue by orta** [artsy/eigen#878]
To replicate: 

load favourites, observe price on works
Switch to artists then back and the layout will have skipped them

**Comment by alloy** [comment]
I wasn’t able to reproduce the prices fully disappearing, but I think this might actually also be fixed by #879. I’ll put out a GM beta today, can you please verify this issue when I’ve done that?

**Comment by orta** [comment]
Yeah, that does look like it might do it

**Comment by orta** [comment]
Confirmed, cannot reproduce.

**Comment by alloy** [comment]
:+1:
