### ISSUE TITLE
[Fair] Load a map image once, cache that, and that there’s a fair map at all.

### ISSUE THREAD

**Issue by alloy** [artsy/eigen#88]
Right now, when a map is going to be shown on any view:
- The map view is added only if a map for the fair is available, which you really only need to determine for a fair once.
- The image appears to be loaded from scratch, thus leading to a short progressive image loading phase. It would be smoother if the image was shown immediately (from a cache).

**Comment by orta** [comment]
This is difficult, as the map is a collection of tiles. We do cache the shows, so far ( if there's a map ) we could switch to doing something like what Folio does: https://github.com/artsy/energy/blob/master/Classes/Artwork/Artwork%20%20Detail%20View/Zoom%20View/ARTiledImageDataSourceWithImage.m#L28-L44

```
- (void)tiledImageView:(ARTiledImageView *)imageView didDownloadTiledImage:(UIImage *)image atURL:(NSURL *)url
{
    NSCharacterSet *charactersToRemove = [[NSCharacterSet alphanumericCharacterSet] invertedSet];
    NSArray *urlParts = [url.absoluteString componentsSeparatedByCharactersInSet:charactersToRemove];

    if (urlParts.count != 16) {
        [super tiledImageView:imageView didDownloadTiledImage:image atURL:url];
        return;
    }

    NSInteger x = [urlParts[urlParts.count - 1] integerValue];
    NSInteger y = [urlParts[urlParts.count - 2] integerValue];
    NSInteger level = [urlParts[urlParts.count - 3] integerValue];

    NSString *filepath = [self.image imagePathForTileForLevel:level atX:x andY:y];
    [UIImageJPEGRepresentation(image, 1.0) writeToFile:filepath atomically:YES];
}
```

**Comment by alloy** [comment]
@orta Yeah that seems good. I guess the most important point, which I did not clarify enough in the original description, is that we don’t need the layout of the view to suddenly expand with the map, because we already know there will be one once we’ve established that once, which might be a nicer experience.

**Comment by ashfurrow** [comment]
Definitely. Just storing a `BOOL` indicating that there *is* a map will help us construct the stack view accurately before getting the actual map data.

**Comment by orta** [comment]
Given that we nearly always pass the fairs around, it should aalready have its 'has map' cached I imagine?

**Comment by ashfurrow** [comment]
Makes sense – now all we need to do is infer the presence of a map from it.
