### ISSUE TITLE
[Auction] ‘Register to bid’ form is impossible to submit after validation errors 

### ISSUE THREAD

**Issue by alloy** [artsy/eigen#881]
Martsy ticket: https://github.com/artsy/microgravity/issues/1104

**Comment by orta** [comment]
_maybe_ the new force version fixes this?

**Comment by ashfurrow** [comment]
This ought to have been addressed on our side by https://github.com/artsy/eigen/pull/1645

**Comment by devangt** [comment]
done for now. Individual updates will be tackled with new issues/epics
