### ISSUE TITLE
update how to bid link on artwork pages

### ISSUE THREAD

**Issue by katarinabatina** [artsy/eigen#893]
update with this link https://m.artsy.net/how-auctions-work

![image](https://cloud.githubusercontent.com/assets/6482926/10491603/6c63f110-7275-11e5-9704-0fc20bb2c985.png)

currently goes here
![image](https://cloud.githubusercontent.com/assets/6482926/10491620/85517e72-7275-11e5-9332-06f5423d6fd8.png)

should go here
![image](https://cloud.githubusercontent.com/assets/6482926/10491631/8cd8033c-7275-11e5-8fe4-3b9e1e8e60c7.png)

**Comment by orta** [comment]
@katarinabatina any idea what the new URL behind the scenes would be?

**Comment by orta** [comment]
ah it's on there, disregard :+1:

**Comment by katarinabatina** [comment]
@orta I should clarify though that we'd wanna use this link for the ipad https://www.artsy.net/how-auctions-work
