### ISSUE TITLE
Consider replacing flatlist with Shopify/flash-list ?

### ISSUE THREAD

**Issue by ducdh-dev** [artsy/eigen#8950]
I use production app. When I load other works (about 4 pages), it will be very lag, and the app will be crashed after that.

**Comment by brainbicycle** [comment]
hey @ducdh-dev thanks for calling out, we are aware and working on this issue, on Android it is especially bad. We will keep you posted if/when we get a fix.

**Comment by gkartalis** [comment]
Linking here the first part of a series of PRs that will swap out the old implementation with the MasonryFlashList
