### ISSUE TITLE
[Auction] Bid view should have more top margin on iPad

### ISSUE THREAD

**Issue by alloy** [artsy/eigen#896]
Force issue: https://github.com/artsy/force/issues/3599

**Comment by katarinabatina** [comment]
The force view has sufficient padding on desktop. Is the padding problem present while viewing this page on safari on iPad? 

Katarina

**Comment by alloy** [comment]
Nope, plenty of margin there as well. Might be related to the top bar that’s not present on Eigen?

![simulator screen shot 15 oct 2015 14 51 39](https://cloud.githubusercontent.com/assets/2320/10514149/586263c2-734c-11e5-9117-3812ed55c794.png)

**Comment by alloy** [comment]
Oops, thought this was the Force ticket. Moving there.

**Comment by katarinabatina** [comment]
Yeah I guess it might be a force ticket but I can't think of any changes we can ask for on their end of its working ok in safari. 

Katarina

**Comment by katarinabatina** [comment]
@alloy are we confident that there are chances that could be made on force that would help?

**Comment by alloy** [comment]
@katarinabatina Nope. But to answer whether or not my suggestion on the Force ticket could be the reason is much faster for the people that have worked on that page to judge than for me (I’d have to go through all the CSS). I can spend more time on figuring it out, if that’s the preference?

**Comment by katarinabatina** [comment]
@alloy ah I see thanks for explaining, I will get someone on web to take a look first, thanks
