### ISSUE TITLE
[Search] Hide tab bar

### ISSUE THREAD

**Issue by alloy** [artsy/eigen#897]
It’s not an immediate issue, as pretty much everybody will have the keyboard shown on top of the tab bar, but for the few that use an external keyboard, this could be a slight UI issue.

![simulator screen shot 15 oct 2015 14 10 38](https://cloud.githubusercontent.com/assets/2320/10513242/9e3a09aa-7346-11e5-82a4-3f24b1ef24b1.png)

**Comment by katarinabatina** [comment]
@sarahscott this is also still an issue for our current version of the app, maybe something you can look into post works for you work?

**Comment by sarahscott** [comment]
@katarinabatina it does still exist in the current app version, but only for users who use external keyboards. I can take a look after WFU stuff.
