### ISSUE TITLE
sign in ends in endless spinner after tapping bid on auction sale overview

### ISSUE THREAD

**Issue by katarinabatina** [artsy/eigen#898]

**Comment by alloy** [comment]
This on iPad, yeah? And when signed-in as a trial user?

**Comment by katarinabatina** [comment]
yup, however after navigating away from the auction and coming back it looks like i am signed in. Will try repo now

**Comment by katarinabatina** [comment]
Just reproduced. As trial user, navigate to auction, tap bid, login, get stuck keyboard and an endless spinner. However, it looks like login works. If I navigate away from this screen and go to you, I see my favorites.
