### ISSUE TITLE
Link in Readme 404s

### ISSUE THREAD

**Issue by getaaron** [artsy/eigen#9]
From the Readme:

> Want API documentation, go through this [guide in gravity](https://github.com/artsy/gravity/blob/master/doc/Api.md#playing-with-the-api) replacing `localhost:4000` with `artsy.net`.

This link doesn't work, presumably because *artsy/gravity* is private. Also, the sentence contains a comma splice.

**Comment by dblock** [comment]
These instructions should be updated to run against Artsy staging, and we can include a test app id / secret for that.

**Comment by ashfurrow** [comment]
This should be fixed by the [setup instructions](https://github.com/artsy/eigen/blob/master/docs/getting_started.md) combined with the sample key/secret we include in the Makefile.
