### ISSUE TITLE
purge app tabs on low memory?

### ISSUE THREAD

**Issue by orta** [artsy/eigen#902]
![screen shot 2015-10-15 at 17 08 55](https://cloud.githubusercontent.com/assets/49038/10522125/661c7272-736b-11e5-970e-16a0d91f4e47.png)

I wonder if this is accounting for the memory issues ?

**Comment by katarinabatina** [comment]
any chance it has to do with this? https://github.com/artsy/eigen/issues/903

**Comment by orta** [comment]
nope, it's a pretty standalone concept

**Comment by alloy** [comment]
Yeah that would definitely be worth looking into :+1:
