### ISSUE TITLE
Change ‘BUY’ to ‘INQUIRE’ button when an artwork has multiple editions.

### ISSUE THREAD

**Issue by alloy** [artsy/eigen#909]
E.g. https://www.artsy.net/artwork/josh-soskin-lone-surfer

Currently we show a ‘BUY’ button for these works, but when tapped the user gets shown an inquire form: https://github.com/artsy/eigen/blob/4f2ba8040b2f188c00dec4c703d1b180f2838b25/Artsy/View_Controllers/Artwork/ARArtworkViewController%2BButtonActions.m#L174-L179

We should reflect this by changing the button’s caption to e.g. ‘INQUIRE’. @katarinabatina do you agree?

**Comment by alloy** [comment]
Ideally we would have UI to select the multiple editions and simply purchase it, of course.

**Comment by orta** [comment]
worth checking if that's supported in martsy

**Comment by erinekim** [comment]
@orta @alloy in Martsy, it works perfectly. It just take me to the actual order form and I can enter my shipping details and then click "continue to checkout."

**Comment by orta** [comment]
What does it look like? Is there a way to choose which edition on the page?

**Comment by erinekim** [comment]
I've attached screenshots; yes, you can choose the edition on the page and it will take you to the checkout page, similar to how it looks like on a web browser. 

![martsy2](https://cloud.githubusercontent.com/assets/8950354/10644481/ecbe7912-77f6-11e5-9e8a-0be73ed6a649.PNG)
![martsy](https://cloud.githubusercontent.com/assets/8950354/10644480/ecbcce32-77f6-11e5-9796-ef6e5b76a027.PNG)

**Comment by orta** [comment]
@katarinabatina - to do this right, we'd want to do a more native-y feeling version of that ^

**Comment by katarinabatina** [comment]
@orta I think the checkout flow can be supported by microgravity but I agree that a native view for the page needs to be devised.

**Comment by orta** [comment]
I can add a edition selector to the artwork page? 

I don't want to replace the full checkout process, but the artwork page we can probably still do, I'll see what they do on microgravity.

FWIW, I'd rather it be something you tap that expands, I'm not sure I'm that into the idea of scrolling through all the editions on every artwork with them.

**Comment by katarinabatina** [comment]
@orta I will take a look. I don't think the editions lists are ever very long and it's nice to see what your options are before you tap buy or have to expose additional information.

**Comment by orta** [comment]
adding to the milestone cause I can look after this

**Comment by katarinabatina** [comment]
![image](https://cloud.githubusercontent.com/assets/6482926/10737810/abe776ee-7bea-11e5-889f-8eadc459a303.png)

**Comment by katarinabatina** [comment]
@alloy this story is what Amy mentioned yesterday.
