### ISSUE TITLE
Run Synx on Project Directory

### ISSUE THREAD

**Issue by ashfurrow** [artsy/eigen#91]
For developers who don't use Xcode as their primary text editor, navigating our folder structure is currently quite difficult. We should use [Synx](https://github.com/venmo/synx/) to restructure the existing files to match our Xcode groups. 

Which raises a question: are we OK with the way our Xcode groups are currently organized? Don't want to go down a rabbit whole. but worth asking.

**Comment by orta** [comment]
I did this on Energy a few months back, happy with results. There were some issues with jobs but I saw the issue get closed a month or so ago. Might be a good one to sit down with @alloy on, I'm happy with whatever you two come up with. :+1: 

Think running synx is a good idea, whatever you come up with please add the command to the Makefile.

**Comment by ashfurrow** [comment]
Still waiting on the big merge from Orta for this, right?

**Comment by orta** [comment]
yes

**Comment by orta** [comment]
I did this.
