### ISSUE TITLE
Universal links/deep links

### ISSUE THREAD

**Issue by hffmnn** [artsy/eigen#916]
Hi,

I have one question.

I found this [question](https://m.artsy.net/artwork/akiakane-razikaruyi-nu-falselian-ai-shi-qing-slash-love-situation-of-radical-young-girl) of @alloy in the dev forums. My question is: does this already work in the current app store version? So does `eigen` support spotlight search for e.g. `AKIAKANE` in Spotlight and Spotlight opens up the app? I am asking, because I can not make it work, also it seems like it should work (I see the associated domains in Xcode, the applebot seems to have [searched for the site](https://search.developer.apple.com/appsearch-validation-tool/)...) and still Spotlight does not suggest to open `eigen`. Can you give an insights on this?

Thanks and regards,
hffmnn

**Comment by orta** [comment]
@alloy ^

**Comment by katarinabatina** [comment]
@alloy I'll let you answer and close?
