### ISSUE TITLE
After resetting my password app is unusable

### ISSUE THREAD

**Issue by dblock** [artsy/eigen#918]
- login with eigen
- reset your password on web

Eigen shows a cant connect to artsy error (not true), and there's no way to recover since you can't logout either (I only guess that logging out would help). Reinstalling the app is the only workaround.

**Comment by dblock** [comment]
![image](https://cloud.githubusercontent.com/assets/542335/10870783/1e5ccb06-80a1-11e5-9fed-8fb27a3fd135.png)

**Comment by alloy** [comment]
Good point!

I guess that at least in this case we can detect the credentials being wrong by the HTTP status code and ask for a new sign-in.

**Comment by alloy** [comment]
Fixed by #978.
