### ISSUE TITLE
Include location (timezone) information during sign-up

### ISSUE THREAD

**Issue by alloy** [artsy/eigen#921]
For more effective push notification support, we should be including this information in the sign-up API call.

I wonder if we can retroactively update it for those users that have not yet supplied this information manually.

**Comment by orta** [comment]
We could use something like:

```
NSTimeZone *timeZone = [NSTimeZone localTimeZone];
NSString *name = [timeZone name];
```

Then do a User model update, I think we can do partial updates on a model so could just send up that

**Comment by alloy** [comment]
Yup, that seems good :+1:

**Comment by alloy** [comment]
What do you think about retroactively updating the user with the timezone info if a `USER_UPDATED_WITH_TZ_INFO` user default is **not** set? Better ideas?

**Comment by orta** [comment]
I'm cool with this

**Comment by alloy** [comment]
Should we also try to gather the coordinates? Seems like fragile data to collect from a mobile device, which could be located anywhere for short periods of time.

```
gravity:staging> u.location
=> #<Location _id: 568e6da18b3b810305000004, created_at: nil, updated_at: 2016-01-07 13:52:38 UTC, coordinates: [4.90252639999994, 52.3667499], raw: nil, address: "", address_2: "", city: "Amsterdam", state: "Noord-Holland", state_code: "NH", postal_code: "1011 PL", country: "Netherlands", timezone: "Europe/Amsterdam", summary: nil>
gravity:staging> User.new.location
=> #<Location _id: 568e6f92ebad645abe000000, created_at: nil, updated_at: nil, coordinates: nil, raw: nil, address: "", address_2: "", city: "", state: "", state_code: "", postal_code: "", country: "", timezone: nil, summary: nil>
```

**Comment by orta** [comment]
I think to get raw coords we'd need to ask for location permissions, which this isn't really a good enough use case for the intrusion.

**Comment by alloy** [comment]
Yah, agreed :+1:

**Comment by alloy** [comment]
Well, it appears that Gravity does record timezone location based on IP nowadays, so no need for us to spend more time on that.

**Comment by orta** [comment]
Does it do it on every API call? When is that grabbed

**Comment by alloy** [comment]
After each save (and thus create): https://github.com/artsy/gravity/blob/e0c9b02755481b651d7c6c36bceae3b323919f7a/app/models/domain/user.rb#L1027-L1045

**Comment by orta** [comment]
ace, thanks
