### ISSUE TITLE
Fix crash in - [ARFeedViewController loadNextFeedPage], line 193

### ISSUE THREAD

**Issue by artsyit** [artsy/eigen#928]
### Stacktrace ###

<pre>ARFeedViewController;loadNextFeedPage;ARFeedViewController.m;193
ARFeedTimeline;getNextPage:failure:completion:;ARFeedTimeline.m;71</pre>

### Link to HockeyApp ###

* [https://rink.hockeyapp.net/manage/apps/37029/crash_reasons/51571365](https://rink.hockeyapp.net/manage/apps/37029/crash_reasons/51571365)

**Comment by orta** [comment]
Should be fixed by #936

**Comment by orta** [comment]
Class doesn't exist any more.
