### ISSUE TITLE
slow image load time

### ISSUE THREAD

**Issue by katarinabatina** [artsy/eigen#930]
Alexander reported this today but it happens pretty consistently for me. Wondering how we can optimize the way we grab images
![image](https://cloud.githubusercontent.com/assets/6482926/11067094/e3c8a6dc-8798-11e5-9b13-740e720be82a.png)

**Comment by orta** [comment]
this is a _really_ hard problem, that would probably take one person 2-3 weeks to get solid

**Comment by orta** [comment]
A discussion about this is in https://github.com/rs/SDWebImage/issues/1351

**Comment by alloy** [comment]
Might _also_ be related to us fetching too large images?

**Comment by orta** [comment]
I spotted this in my logs - we do a _lot_ of networking for the favourites stuff on launch for the spotlight stuff, we could do some work there on timeouts and gaps to allow other networking to finish at a higher priority.

**Comment by alloy** [comment]
Sounds like a good idea.
