### ISSUE TITLE
wrong type showing up in search

### ISSUE THREAD

**Issue by katarinabatina** [artsy/eigen#937]
ipad pro only bug, but this is in production 
![image](https://cloud.githubusercontent.com/assets/6482926/11133546/5972e240-8964-11e5-9ef1-566299685fc2.png)

**Comment by orta** [comment]
Just tested on mine, not seeing it on App Store build, might be intermittent

**Comment by katarinabatina** [comment]
yeah just refreshed the app, all is well now
