### ISSUE TITLE
Handle XApp timeouts more gracefully

### ISSUE THREAD

**Issue by orta** [artsy/eigen#939]
We've occasionally got reports of users saying that they cannot see or do anything. @katarinabatina just brought me a reproducible case of this and the errors from her console were:

```
Nov 13 10:10:54 Batinas-iPhone Artsy[3802] <Critical>: 2015-11-13 10:10:54.122 [ERROR] | Couldn't get an Xapp token.
Nov 13 10:10:54 Batinas-iPhone Artsy[3802] <Debug>: [Can’t reach Artsy.] {
	    description = "Can\U2019t reach Artsy.";
	    failureReason = "(empty)";
	    recoveryOptions = "(empty)";
	    recoverySuggestion = "(empty)";
	}
Nov 13 10:10:54 Batinas-iPhone Artsy[3802] <Critical>: 2015-11-13 10:10:54.142 [ERROR] | Couldn't get an Xapp token.
Nov 13 10:10:54 Batinas-iPhone Artsy[3802] <Debug>: [Can’t reach Artsy.] {
	    description = "Can\U2019t reach Artsy.";
	    failureReason = "(empty)";
	    recoveryOptions = "(empty)";
	    recoverySuggestion = "(empty)";
	}
Nov 13 10:10:54 Batinas-iPhone Artsy[3802] <Debug>: [Can’t reach Artsy.] {
	    description = "Can\U2019t reach Artsy.";
	    failureReason = "(empty)";
	    recoveryOptions = "(empty)";
	    recoverySuggestion = "(empty)";
	}
```

Which come from https://github.com/artsy/eigen/blob/master/Artsy/Networking/ArtsyAPI.m#L170

So my guess is that we are not deleting, or taking into account the expiry date for xapp tokens. This isn't fixed on an app restart either, so pretty high priority.

**Comment by orta** [comment]
Got it - [hasValidXAppToken ](https://github.com/artsy/eigen/blob/master/Artsy/Networking/API_Modules/ARUserManager.m#L122-L129) checks from the defaults whereas [ArtsyAPI](https://github.com/artsy/eigen/blob/master/Artsy/Networking/ArtsyAPI.m#L158) sets it in Keychain.

**Comment by alloy** [comment]
Nice one :+1:
