### ISSUE TITLE
Fix crash in - [ARArtworkView setUpCallbacks], line 106

### ISSUE THREAD

**Issue by artsyit** [artsy/eigen#94]
### Stacktrace ###

<pre>ARArtworkView;setUpCallbacks;ARArtworkView.m;106
Artwork;onFairUpdate:failure:;Artwork.m;388
KSPromise;resolveWithValue:;KSPromise.m;151
KSDeferred;resolveWithValue:;KSDeferred.m;25
Artwork;updateFair;Artwork.m;374
ArtsyAPI(Artworks);getFairsForArtwork:success:failure:;ArtsyAPI+Artworks.m;106</pre>

### Link to HockeyApp ###

* [https://rink.hockeyapp.net/manage/apps/37029/crash_reasons/27568094](https://rink.hockeyapp.net/manage/apps/37029/crash_reasons/27568094)

**Comment by alloy** [comment]
Attempt at fix in https://github.com/artsy/eigen/pull/203.
