### ISSUE TITLE
no image data available on first load for favorites

### ISSUE THREAD

**Issue by katarinabatina** [artsy/eigen#954]
Across artworks, artists, and categories no image data available. When I go between tabs it doesn't refetch the content. I left the app and came back and now the images are there.

![image](https://cloud.githubusercontent.com/assets/6482926/11319296/74fe9036-9026-11e5-96f9-e322e68688fd.png)

**Comment by alloy** [comment]
I haven’t been able to reproduce this yet. Have you seen it once of constantly?

**Comment by orta** [comment]
I wonder if this is to do with downloading favourites in the background, the requests could coalesce and not call both callbacks

**Comment by alloy** [comment]
Not sure what you mean by “both callbacks”. In any case, I think you already commented on a similar ticket recently (and thus is a dupe) ?

**Comment by katarinabatina** [comment]
haven't run into this for some time going to close
