### ISSUE TITLE
[Home] Hero units don't show

### ISSUE THREAD

**Issue by alloy** [artsy/eigen#955]
I think they did show the first time that I launched the beta, but today they haven't been showing for me at all.

I do see at least 1 on staging, so might be a production web issue?

**Comment by alloy** [comment]
I’m unable to reproduce this with a dev build. After re-installing the beta it also works fine, so I’m not sure what the cause of this was. I’ll keep an eye on it for now.

**Comment by orta** [comment]
FWIW, I've not seen this with the betas

**Comment by alloy** [comment]
:+1:
