### ISSUE TITLE
Cleanup use of user IDs for both authenticated and anonymous users.

### ISSUE THREAD

**Issue by alloy** [artsy/eigen#962]
We settled on using the ‘User ID’ and ‘Anonymous ID’ fields of Segment, dropping ours in our custom `properties` dictionary. These are:

* `user_id`: Gravity user ID of an authenticated user.
* `anonymous_id`: The trial user’s UUID generated by `ARUserManager`. 

----

- [x] Update Segment iOS SDK to specify our own anonymous ID: https://github.com/segmentio/analytics-ios/pull/485.
- [x] Update ARAnalytics to add a Segment specific setup method that also takes an anonymous ID.
- [x] Use new ARAnalytics and Segment iOS SDK in Eigen.

**Comment by orta** [comment]
This is in, and we also expose our trial user UUID to martsy web-views
