### ISSUE TITLE
[Shows Feed] Does not gobble whitespace when there are no featured links

### ISSUE THREAD

**Issue by alloy** [artsy/eigen#965]
There are apparently currently no featured links. Rather than adjusting the whitespace that’s normally reserved for the featured links, a gap is left:

![slack_for_ios_upload png](https://cloud.githubusercontent.com/assets/2320/11531342/65a6559a-98fc-11e5-9c2f-39e720d721df.jpeg)

**Comment by alloy** [comment]
It does gobble the whitespace as soon as there is _at least_ 1 featured link.

**Comment by orta** [comment]
interesting, making the feed links not do anything does not cause this to happen

**Comment by orta** [comment]
I take it back, I was on a different branch
