### ISSUE TITLE
Refine Tool

### ISSUE THREAD

**Issue by katarinabatina** [artsy/eigen#971]
The refine tool will act as a catch all for both filtering and sorting that we can hopefully use wherever a large collection of works is displayed in the app. For now though, let's limit the scope to the auction sale page. It will act as a modal on top of the sale page. By default the works will show up in the "default" sort order (either lot order or artist a-z) displayed in a masonry layout. When a particular sort item is selected from the refine modal, this will switch the view to display the works in a list. We use this same logic in Eidolon and on the web. I'm going to assume we don't have the backend to support price filtering at the moment but I plan on putting a request into the auctions team to support it. I imagine for a V1 we can plan on excluding the price filter altogether. 

![image](https://cloud.githubusercontent.com/assets/6482926/11725329/38748e2e-9f47-11e5-88d9-c19ca499633b.png)

![image](https://cloud.githubusercontent.com/assets/6482926/11726713/f879e308-9f4d-11e5-9b18-4f5ba900ff05.png)

**Comment by orta** [comment]
@katarinabatina - does the "28 lots" float? or would it scroll off-screen?

**Comment by orta** [comment]
Likely connected, https://github.com/ashfurrow/ARCollectionViewMasonryLayout/issues/26

**Comment by ashfurrow** [comment]
Based on https://github.com/artsy/eigen/issues/973 I think it sticks to the top.

**Comment by katarinabatina** [comment]
correct @ashfurrow!

**Comment by ashfurrow** [comment]
*Estimate*: 2 days

**Comment by ashfurrow** [comment]
@katarinabatina The two different, orientation-specific iPad designs are going to take a lot of time to make:

https://cloud.githubusercontent.com/assets/6482926/11726713/f879e308-9f4d-11e5-9b18-4f5ba900ff05.png

_Especially_ when rotating the device. Ideally I'd like to just use one, and ideally it would be the modal view (the one on the left) since it's mostly standard and we can use existing components. Thoughts?

**Comment by katarinabatina** [comment]
@ashfurrow sounds good, I'm ok with the modal view working for both.

**Comment by ashfurrow** [comment]
@katarinabatina I don't see the font sizes for labels specified for iPad, are they just the same as iPhone?

**Comment by katarinabatina** [comment]
yup!

**Comment by katarinabatina** [comment]
@ashfurrow adjustments to the button behavior and copy (reset instead of clear) http://cl.ly/2w2v401o2l18

**Comment by ashfurrow** [comment]
Estimated 2 days, gonna say this took shy of 3.
