### ISSUE TITLE
Auction sale page banner behavior and components 

### ISSUE THREAD

**Issue by katarinabatina** [artsy/eigen#974]
Banner for auction sale page, banner image should be sourced from 
https://auctions.artsy.net/sales/art-for-life-benefit-and-live-auction-2015/edit

![image](https://cloud.githubusercontent.com/assets/6482926/11717962/9257b4aa-9f21-11e5-8c27-dcac9cd7a003.png)

endpoint for auction logo does not exist currently, trying to get that prioritized on the auctions end will get back to you on a timeline for that.

Pulling down on the view should create a slight zoom effect into the content (similar what we used? to have on fairs but with much higher tension)

**Comment by ashfurrow** [comment]
Gonna tackle this.

**Comment by ashfurrow** [comment]
Note that the zoom effect on the background is captured in https://github.com/artsy/eigen/issues/973 so the #1023 doesn't include that.

**Comment by alloy** [comment]
@ashfurrow Is this component implemented yet?

<img width="377" alt="screen shot 2016-02-10 at 14 23 37" src="https://cloud.githubusercontent.com/assets/2320/12948382/0132be68-d002-11e5-81ff-f3e06b5ebda7.png">

**Comment by ashfurrow** [comment]
Yes, in my most recent PR.

**Comment by katarinabatina** [comment]
@ashfurrow @alloy it does needs some design QA

**Comment by ashfurrow** [comment]
Agreed, I think _all_ of the auctions views will need some design QA :wink:
