### ISSUE TITLE
Registration status of user

### ISSUE THREAD

**Issue by katarinabatina** [artsy/eigen#975]
We are moving away from requiring a user to register on a per sale basis. Instead we want to move to a simpler model where an artsy user can bid if they are qualified. 

That means, for users who have bid with us before will automatically be Approve to Bid, those who haven't will be required to register if they want to bid. When an auction places more strict vetting i.e. asks users to opt in to separate terms and conditions, asks user to send along a bank statement, etc. the user will be again asked to register. We don't anticipate more strict vetting in the short term but we know this will be a feature that partners will want so I figure it's good to build for the case now. 

Cases outlined:

1. Reg required
2. Reg pending (we shouldn't see this for some time, this would only be seen in the scenario that the user has given additional info during registration that needs to be reviewed)
3. Approved to bid
4. Outdated payment info (expired cc) on file

![image](https://cloud.githubusercontent.com/assets/6482926/11718739/782a3874-9f25-11e5-85b4-26f3d03e345b.png)

Measurements for Information Area

![image](https://cloud.githubusercontent.com/assets/6482926/11718751/86965884-9f25-11e5-8c99-83758c3f9b44.png)

**Comment by ashfurrow** [comment]
It should be easy to figure out the case involved, and as long as we leave the native flow in #997 and just push to martsy, an estimate would be:

*Estimate*: 1 day

**Comment by ashfurrow** [comment]
Based on discussions on Slack, we don't currently have a way to check for outdated payment info. That may require some backend changes, but we should move forward on this for now with registered/please register states.

**Comment by ashfurrow** [comment]
@katarinabatina Are there two different display names, one or iPad and one for iPhone?

**Comment by katarinabatina** [comment]
@ashfurrow no my apologies for the inconsistency in the comp, same display name

**Comment by ashfurrow** [comment]
Awesome, makes life easier for me :)
