### ISSUE TITLE
App has no data??

### ISSUE THREAD

**Issue by katarinabatina** [artsy/eigen#979]
Don't have a lot of context to provide here besides opening the app. 

![image](https://cloud.githubusercontent.com/assets/6482926/11699043/23b9ecd4-9e90-11e5-95ed-7ee13cab0346.png)

![image](https://cloud.githubusercontent.com/assets/6482926/11699050/30c88494-9e90-11e5-9fec-624b13e3aeb2.png)

![image](https://cloud.githubusercontent.com/assets/6482926/11699046/27a0441a-9e90-11e5-94b7-5f7f017bb083.png)

![image](https://cloud.githubusercontent.com/assets/6482926/11699049/2c1ae07c-9e90-11e5-8a95-483425946346.png)

![image](https://cloud.githubusercontent.com/assets/6482926/11699053/35b42d28-9e90-11e5-9da7-023ef6243b23.png)

![image](https://cloud.githubusercontent.com/assets/6482926/11699055/39ac4a14-9e90-11e5-9e49-2dba3c05cdc1.png)

**Comment by katarinabatina** [comment]
When I open it I do get a "can't reach network" error briefly

**Comment by orta** [comment]
So this is an authentication thing, lots of:

```
Dec  9 17:10:10 Artsy[4316] <Debug>: [We're having trouble accessing the show feed.] {
	    description = "Request failed: unauthorized (401)";
	    failureReason = "(empty)";
	    recoveryOptions = "(empty)";
	    recoverySuggestion = "(empty)";
	}
```

Killing the app fixes it. Wonder if there's something to do with the app token stuff I spotted in #978

**Comment by orta** [comment]
I've not seen this in betas in the last month.
