### ISSUE TITLE
Adjust-Google Analytics integration

### ISSUE THREAD

**Issue by alloy** [artsy/eigen#988]
From @jessekedy:

> Would it be possible to turn on the Adjust-Google Analytics integration?
> 
> Now that GA tracks Eigen sessions, this would let us view “install source” in GA against other analytics that’s already in GA.
> 
> https://docs.adjust.com/en/special-partners/google-analytics/
> 
> Another small benefit is that it:
> - would funnel install source to GA, which we could then feed into the KPI google sheet
> - should make it possible to see install source within Looker (?)

**Comment by orta** [comment]
This might not be feasible, google analytics support comes in via segment, eigen has no knowledge about google's user ids. Unless its the user id we send up from #966 - in which case I can take a look at this.
