### ISSUE TITLE
live preview, close to full spec

### ISSUE THREAD

**Issue by katarinabatina** [artsy/eigen#996]
phone 
![image](https://cloud.githubusercontent.com/assets/6482926/11942401/19c47834-a7eb-11e5-8523-8660c678c64e.png)

ipad

![image](https://cloud.githubusercontent.com/assets/6482926/11942455/8b3a8b34-a7eb-11e5-9761-d43d3eb83668.png)

major differences...

1. no swipe navigation in ipad, instead use left hand column to navigate between lots
2. no jump to live lot unit on upcoming lots in ipad. Instead the live lot will remain always highlighted in the list. When a user scrolls that purple live lot will be a sticky element in the list, sticking to the bottom or top of the list depending on scroll direction. 

think of this as the "lay of the land" more thorough stories will be written based on this spec but if any major red flags are presenting themselves please let me know.

**Comment by orta** [comment]
Is support a two way conversation done in app?

**Comment by katarinabatina** [comment]
@orta yes, will double check that intercom can support this in real time. If not, do you know of any out of the box messaging services that we could build on top of?
