### ISSUE TITLE
Auction Registration Flow

### ISSUE THREAD

**Issue by katarinabatina** [artsy/eigen#997]
- [ ] Card entry #1091 
- [ ] Form abstraction #1120
- [ ] Applying form abstraction + tying it all together #1092 

Flow logic
![image](https://cloud.githubusercontent.com/assets/6482926/12704400/3a6e27f8-c828-11e5-9bad-eb1e2a1b28fb.png)

Measurements
![image](https://cloud.githubusercontent.com/assets/6482926/12704401/447701ac-c828-11e5-9dca-87035ae45549.png)

ipad specific measurements
![image](https://cloud.githubusercontent.com/assets/6482926/11944124/835df0ba-a7f8-11e5-9f5a-6e7fecb2a66b.png)

**Comment by ashfurrow** [comment]
I'm going to remote the "Auction Update" label from this, since it's strictly now a Live Integration issue.

**Comment by ashfurrow** [comment]
Estimate: 4 Days (fuzzy) needs to be split out.

**Comment by ashfurrow** [comment]
Issue moved to [artsy/auctions #197](https://github.com/artsy/auctions/issues/197) via [**ZenHub**](https://www.zenhub.com/)
